### PR TITLE
[GSSoC'23]: [NEW GAME] - Color Matcher (PR for issue #363)

### LINKED ISSUE #363: [New Game]: Color Matcher
### 🎮 Game Request

Description:
I would like to request the addition of a new game called "Color Matcher" to the Games collection. This game is designed to be unique and simple, providing an engaging matching experience for players.

### Point down the features

Game Logic and Basic Description:

- The Color Matching Game was created using HTML, CSS, and JavaScript.
- This is a user-friendly kind of application that can be easily modified to be used in your on working projects.
- The application is a simple Matching type game that can be played by a single-player.
- The player can play the game using the Mouse, you only just need to use the Left Mouse Button to interact the game.
- The gameplay is very simple all you have to do is to match the same color you will see within 30 seconds.
- Each color you matched will disappear and you to need to proceed to other colors.
- Try to match all the colors before the time runs out.

Features:

- Timer: Display a countdown timer to indicate the remaining time for the player to make matches.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by PoulasthaMukherjee**
## PR Description 📜

I have added a new HTML, CSS and JS based game called 'Color Matcher' which is a single player game where the player needs to click on tiles using their Left mouse Button and match all colors before the time runs out.

Fixes #363

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Color_Matcher

--- 

<br>

## Thank you so much for giving me an opportunity to contribute to your repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @PoulasthaMukherjee ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hey please add your entries in main README file

**Comment by PoulasthaMukherjee** [comment]
@kunjgit Can you please tell me what changes I need to make somewhat specifically to my PR?

**Comment by PoulasthaMukherjee** [comment]
@kunjgit I have added the entry in the main README. Could you take a look?

**Comment by PoulasthaMukherjee** [comment]
@kunjgit Are you there

**Comment by kunjgit** [comment]
rename your folder name by following convention all other things are done just make PR with updated code

**Comment by kunjgit** [comment]
Thank you  @PoulasthaMukherjee , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
