### PR TITLE
Added Subway Surfers game

### LINKED ISSUE #4936: [New game]: Subway Surfers
### 🎮 Game Request

Subway Surfers is an endless runner game where the player takes on the role of a graffiti artist who is caught in the act of tagging a metro railway site and must run down railroad tracks to escape the Inspector and his dog. As the player runs, they must dodge oncoming trains and obstacles by swiping left or right to change lanes, swiping up to jump, and swiping down to roll. The game increases in speed and difficulty as the player progresses, requiring quick reflexes and strategic decision-making to survive longer.

### Point down the features

Endless Running: The game features a continuous, never-ending chase where the player aims to achieve the highest possible score by running as far as they can without being caught.
Power-Ups and Boosters: Players can collect various power-ups like jetpacks, super sneakers, coin magnets, and score multipliers to aid their run and increase their score.
Daily Challenges and Missions: The game includes daily challenges and missions that offer additional rewards and objectives to keep the gameplay engaging.
Character and Board Upgrades: Players can unlock and upgrade different characters and hoverboards, each offering unique abilities and boosts.
Vibrant Graphics and Locations: The game features colorful and vibrant graphics, with regular updates introducing new locations and seasonal themes.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by arunimaChintu**
## PR Description 📜
Subway Surfers is an endless runner game where the player takes on the role of a graffiti artist who is caught in the act of tagging a metro railway site and must run down railroad tracks to escape the Inspector and his dog. As the player runs, they must dodge oncoming trains and obstacles by swiping left or right to change lanes, swiping up to jump, and swiping down to roll. The game increases in speed and difficulty as the player progresses, requiring quick reflexes and strategic decision-making to survive longer.

Fixes #4936 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @arunimaChintu ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by arunimaChintu** [comment]
@ishita-43 Please review this...

**Review by ishita-43 — APPROVED** [review]
Ready to merge

**Comment by arunimaChintu** [comment]
@kunjgit Please merge this

**Comment by ishita-43** [comment]
> @kunjgit Please merge this

Please resolve the arising merge conflicts after it will be merged by the admin

**Comment by arunimaChintu** [comment]
@kunjgit Please merge it now... All conflicts resolved

**Comment by arunimaChintu** [comment]
@kunjgit Please merge this now

**Comment by mohitgedar** [comment]
hey , do add this game to gamesData.json so that it is visible on the website also .Details about how to add is provided in contributors guideline

**Comment by arunimaChintu** [comment]
Done! @kunjgit Please merge this now...

**Comment by kunjgit** [comment]
Thank you  @arunimaChintu , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
