### PR TITLE
Added Mario Game

### PR DESCRIPTION
**Pull request by ananyag309**
Added Mario Game - #4430 
Please add gssoc and level label

Mark the task you have completed ✅
- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅] My changes generates no new warnings.
- [✅] I have added screenshot for website preview in assets/images 
- [✅] I have added README.md in my folder 
- [✅] I have specified the respective issue number for which I have requested the new game.

Please excuse for low quality video, the quality has been low because I have compressed it to much!!!

https://github.com/kunjgit/GameZone/assets/145869907/25bde2da-ecff-41d1-8a73-c64fd9537114

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @ananyag309 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — CHANGES_REQUESTED** [review]
ADD your game in main README.MD file of the GameZone
Place your images in asset folder and follow contribution guidelines while naming the image .
Hoping you will make desired changes soon!!

**Comment by ananyag309** [comment]
@ishita-43 ma'am added game in read.me and added images accordingly.
please check.
also ma'am please add gssoc and level label

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by kunjgit** [comment]
Thank you  @ananyag309 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
