### PR TITLE
Bottle Flip Game

### LINKED ISSUE #3485: [New game]: Bottle Flip Game
### 🎮 Game Request

Game logic and basic description
So basically the logic behind this game is that when the user click on the bottle the bottle will flip on its respective position. If it lands correctly then the user will get one point and if it doesn't lands correctly then there will be an option of restart.

### Point down the features

Game points
1. Animated Bottle Flip:
   Enhance the flip animation to include rotation and smooth transition effects.

2. Landing Check:
    Implement a more realistic physics-based check to determine if the bottle lands correctly.

3. Scoreboard:
   Display the current score and the highest score achieved in the session.

4. Sound Effects:
   Add sound effects for successful flips and failed attempts.

5. Background Music:
    Play background music that can be toggled on or off.

6. Responsive Design:
    Ensure the game works well on different screen sizes, including mobile devices.

7. Flip Count and Timer:
   Track the number of flips and display a timer for timed challenges.

8. Difficulty Levels:
   Add different difficulty levels that change the success probability or flip dynamics.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by VaibhavS0710**
## PR Description 📜

I developed a new game Bottle Flip using HTML, CSS, and JS.
Fixes #3485 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
"C:\Users\VAIBHAV SRIVASTAVA\OneDrive - vitbhopal.ac.in\Desktop\Game_ss.png"

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @VaibhavS0710 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VaibhavS0710,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VaibhavS0710,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Comment by VaibhavS0710** [comment]
@kunjgit Please merge this PR.

**Comment by kunjgit** [comment]
Thank you  @VaibhavS0710 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by VaibhavS0710** [comment]
@kunjgit Thanks a lot for merging my PR. I loved working on your project. There is one request please remove 'under review' label.
Thank You once again!!

**Comment by VaibhavS0710** [comment]
@kunjgit please remove this under review label.
Thank you

**Pull request merged**
