### PR TITLE
PR updated. Main index file unchanged.

### LINKED ISSUE #231: [New game]: Valorous Rabbit
### 🎮 Game Request

Game logic and basic description
Valorous Rabbit is an adventurous game created using HTML, CSS, and JavaScript, where players take control of a brave rabbit on a mission to save its woodland friends from peril. Here's a description of how the game works:

HTML Structure:
The game interface is built using HTML elements. It typically includes a container div to hold the game elements, a canvas element for rendering the game graphics, score and life counters, and buttons for player interactions.

CSS Styling:
The game elements are styled using CSS to create an appealing visual design. The container div and canvas can be styled with appropriate dimensions and positioning to fit the game screen. The buttons, score, and life counters are styled to be easily readable and visually distinct.

JavaScript Functionality:

Initialization: When the game starts, JavaScript initializes the player's score and life counter to a default value and sets up event listeners to track player input.
Player Movement: JavaScript listens for keyboard inputs or button clicks to control the rabbit's movement. It updates the rabbit's position on the canvas accordingly.
Enemy Generation: JavaScript randomly generates enemies, obstacles, or challenges on the canvas to hinder the rabbit's progress. These may include predators, traps, or obstacles that the player must avoid.
Collision Detection: JavaScript detects collisions between the rabbit and enemies or obstacles. If a collision occurs, the player's life counter decreases, and appropriate feedback is provided.
Scoring: JavaScript tracks the player's score based on their progress and achievements within the game. For example, collecting power-ups or saving friends can increase the score.
Game Over: When the player's life counter reaches zero or the game objective is not achieved within a specified time limit, the game ends. The player's final score is displayed, and they may have the option to restart or quit the game.

### Point down the features

Game points
The player controls the rabbit using keyboard inputs or button clicks. The objective is to navigate the rabbit through various levels or stages, overcoming obstacles and enemies, and rescuing woodland friends along the way. The player must avoid colliding with enemies or traps to prevent their life counter from depleting. Collecting power-ups or bonuses can enhance the rabbit's abilities or provide extra points. The player's goal is to achieve the highest score and complete the game with the maximum number of rescued friends.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by uzmaansari23**
I undo all the changes that I made in main index file and is now generating a new PR.

Fixes #231 
 

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @uzmaansari23 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by uzmaansari23** [comment]
@Arun9739 done sir!

**Comment by Arun9739** [comment]
@uzmaansari23 Plz add the entry of your game into the main README file.

**Comment by uzmaansari23** [comment]
@Arun9739 I've to add the entry in the main readme file or create a readme file for my game in its folder?

**Comment by Arun9739** [comment]
@uzmaansari23 Remove the .vscode folder and resolve branch conflicts.

**Comment by uzmaansari23** [comment]
@Arun9739 done sir

**Comment by kunjgit** [comment]
we are already having the game and you are having same UI also we can't have exact same games !!!!

**Comment by kunjgit** [comment]
Thank you  @uzmaansari23 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
