### PR TITLE
[New game]: Ghost Busting Added

### LINKED ISSUE #4548: [New game]: Ghost Busting
### 🎮 Game Request

Game logic and basic description

A 15 second game, where we need to click on a ghost, that pops up from grave
each click = 1 point

### Point down the features

Game points
- fun game
- quick game
- HTML CSS game

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by sau-mili**
## PR Description 📜

Added a new game Ghost Busting

Fixes #4548 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

https://github.com/kunjgit/GameZone/assets/146661411/1bafa207-0aec-4f6f-af06-4c6918a518b7

--- 
<br>

## Thank you soo much for contributing to our repository 💗
game window
ghost_busting
score

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @sau-mili ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by sau-mili** [comment]
@ishita-43 please check

**Review by ishita-43 — APPROVED** [review]
Good to go!! :>

**Comment by kunjgit** [comment]
Thank you  @sau-mili , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
