### PR TITLE
[GSSoC'23] Number Sliding Game Completed

### LINKED ISSUE #1944: [New game]: Number Sliding Puzzle Game [GSSoC'23]
### 🎮 Game Request

Game logic and basic description

- This game is a single player game.
- The Number Sliding Puzzle Game is a classic puzzle where players rearrange numbered tiles on a square grid.
- The objective is to arrange the tiles in ascending order, starting from a randomized initial configuration.
- Players can slide tiles into the empty space, strategically planning their moves to achieve the desired order.
- The challenge lies in the limited moves available, requiring logical thinking and problem-solving skills.

### Point down the features

Game points

- Complete the game and win the game.
- Congrats with a grand celebration look of the website on completion of the game

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
- This game is single player game and created using HTML, CSS and JS.
- Set the size of the board according to yourself.
- Start the game and try to solve it.
- Arrange all the numbers in the non-decreasing order.
- The player has to complete the game within the bounded number of moves.
- Player can also check how much time, player takes to solve the game.
- If unable to solve, loose the game.
- Otherwise wins the game.

Fixes #1944 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Number_Sliding_Puzzle_Game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Avdhesh-Varshney ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Avdhesh-Varshney** [comment]
@kunjgit please review this pull request and requested to merge this pr for a valuable contribution under GSSoC'23 program

**Comment by Avdhesh-Varshney** [comment]
@kunjgit I have created this pr 2 days ago. Please review this pr and requested to merge into main branch for a successful contribution under GSSoC'23 program

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Avdhesh-Varshney , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
