### PR TITLE
add Plankman game

### LINKED ISSUE #828: [New game]: Plankman
### 🎮 Game Request

Plankman is an engaging pirate-themed hangman game, crafted using HTML and CSS. Challenge your movie knowledge as you attempt to guess the hidden film titles before running out of guesses. Prepare to walk the plank if your movie expertise falls short in this thrilling, word-guessing adventure!

## **How to play? 🕹️**
- Open the Plankman game in your web browser.
- The game will present you with a blank space representing a movie title.
- Guess a letter from the movie title by clicking on the corresponding letter on the virtual keyboard or by typing it on your physical keyboard.
- If the letter you guessed is present in the movie title, it will be revealed in its correct position(s) in the blank space.
- If the letter you guessed is not in the movie title, a part of the hangman's plank will be added to the visual display.
- Keep guessing letters one by one, trying to fill in the blanks and complete the movie title before the hangman's plank is complete.
- Be careful! You have a limited number of incorrect guesses before the hangman's plank is fully built, leading to the end of the game.
- Guess the movie title correctly before the hangman's plank is complete to win the game.
- If you run out of guesses and the hangman's plank is fully built, the game is over, and you lose.
- Challenge yourself to improve your score by guessing more movie titles correctly and with fewer incorrect guesses.

## **Functionalities 🎮** 

- Engaging pirate theme with captivating visuals and design.
- Developed using HTML and CSS for a seamless web experience.
- Guess movie titles within a limited number of attempts.
- Test your movie knowledge and trivia skills.
- Enjoy a thrilling and immersive word-guessing adventure.
- Progressively challenging levels to keep you engaged.
- Interactive and user-friendly interface for easy gameplay.
- Track your score and attempt to beat your own records.
- Educational and entertaining, perfect for movie enthusiasts.
- Suitable for all ages, providing hours of fun and entertainment.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by MisterMickey**
## PR Description 📜

Add Plankman Game

Fixes #828 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @MisterMickey ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by MisterMickey** [comment]
@kunjgit Kindly merge, I have made the changes and resolved conflict issues.

**Comment by MisterMickey** [comment]
@kunjgit every time you merge any PR I've to solve the merge conflict in my PR, Is there any solution for this?

**Comment by kunjgit** [comment]
Thank you  @MisterMickey , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @MisterMickey,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by MisterMickey** [comment]
@kunjgit @daccdacc  Kindly put label of gssoc23 and level-3

**Pull request merged**
