### PR TITLE
Navbar Enhanced to be responsive and new working links

### LINKED ISSUE #4801: [Enhancement]: Enhanced the navbar of the main website
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

- The navbar of the main website don't respond well to different screen sizes .

- The links in the navbar don't work .

- The theme-toggle button is placed incorrectly .

- Navbar hides when we scroll down the page.

### Describe the solution you'd like

- I would like the navbar to be responsive to different screen sizes and with smooth transitions .

- The links of the navbar should work 

- **#A new link *contact* should be added**

- The Theme-toggle button should be a part of navbar

- Navbar should be fixed at the top as that the links of the navbar can be used to move through the website.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by mohitgedar**
## PR Description 📜

Fixes #4801

I have made changes to make the main websites navbar responsive and working .
- I have added media queries so that the navbar responds well to different screen sizes
- I have added a new Link **Contact** in the navbar to go to contact section at the end of website
- I have updated html file so that the links already present works now , before they were just sitting there
- I have fixed the navbar to the top , so that it can be used to navigate through the website.
- I have removed unnecessary CSS rule from both style.css and navbar.css, that were not used anywhere so that maintaining the website becomes easy , right now it's very hard to navigate through
- I have place the theme-toggle button in the navbar , perfectly aligned with other items so that now it don't look like a alien on the page but a part of the website.
- Now GameZone logo also works as a clickable element in the navbar.
<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added youtube link for preview before and after changes.  
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Preview videos are of large size so uploaded on youtube. Links below.
- [before changes](https://youtu.be/LU4EfyrQytA?feature=shared)
- [after changes](https://youtu.be/5AdKy41FcVY?feature=shared)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @mohitgedar ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by mohitgedar** [comment]
@ishita-43  what's the update ?

**Review by ishita-43 — APPROVED** [review]
You did  good work !!  👍

**Comment by kunjgit** [comment]
Thank you  @mohitgedar , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
