### PR TITLE
New game: Black_jackk

### LINKED ISSUE #3447: [New game]: Add New Game BlackJack
### 🎮 Game Request

Game Logic:
Objective: The primary goal in Blackjack is to have a hand value closer to 21 than the dealer's hand without exceeding 21.

Card Values:

Number cards (2-10) are worth their face value.
Face cards (Jack, Queen, King) are each worth 10 points.
Aces can be worth either 1 or 11 points, depending on which value benefits the hand most.
Gameplay:

.Initial Deal: Each player and the dealer are dealt two cards. Players’ cards are usually dealt face up, while the dealer has one card face up (the "Up Card") and one card face down (the "hole card").

.Player Decisions:
Hit: Take another card from the dealer.
Stand: Keep the current hand and end the turn.

Double Down: Double the initial bet and take exactly one more card.

Split: If the first two cards are of the same value, the player can split them into two separate hands, each with its own bet. Players then play each hand individually.

Surrender: Forfeit half the bet and end the hand immediately (only available as the first decision of the hand).
Dealer Rules: After all players have finished their turns, the dealer reveals the hole card. The dealer must hit until their cards total 17 or higher (some casinos require the dealer to hit on a "soft 17," which is a hand containing an Ace counted as 11).
Winning:

A player wins if their hand total is higher than the dealer's hand total without exceeding 21.
A player wins with a "Blackjack" (an Ace and a 10-value card) if the dealer does not also have a Blackjack.
If the dealer busts (exceeds 21), all remaining players win.
If a player busts, they lose regardless of the dealer’s outcome.

### Point down the features

Game Points:
Points Calculation:

The total value of a player's hand is the sum of the individual card values.
If a player's hand includes an Ace, it can be counted as 1 or 11, depending on which value keeps the hand total under or equal to 21.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by codewithishu**
## PR Description 📜

fixes #3447 

 

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

## Add your screenshots(Optional) 📸
Screenshot 2024-05-21 165650

---

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @codewithishu ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @codewithishu,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by codewithishu** [comment]
merge it

**Comment by kunjgit** [comment]
@codewithishu solve merge conflicts !

**Comment by kunjgit** [comment]
@codewithishu you are still having merge conflicts !

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @codewithishu,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @codewithishu,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @codewithishu,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by codewithishu** [comment]
@kunjgit I have resolve all the conflict

**Comment by kunjgit** [comment]
Thank you  @codewithishu , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Thank you  @codewithishu , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Thank you  @codewithishu , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
