### PR TITLE
Enhancement of Ludo Game Completed [GSSoC'23]

### LINKED ISSUE #938: [Enhancement]: Ludo Game [GSSoC'23]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

- Adding background music
- Adding sound of dice rolling
- Adding game over sound
- Adding a new game sound on clicked
- Adding a demo video in the read me file
- Improving a the folder layout

### Describe the solution you'd like

Solution steps

Using JavaScript, 
- Adding background music in the game
- Roll dice sound
- Game over sound on clicked
- New game sound on clicked

Record a video and creating a github link and adding it to the readme file
Arranging the images into a folder

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## PR Description 📜

- Adding sound of dice rolling
- Adding game over sound
- Adding a new game sound on clicked
- Adding a demo video in the read me file
- Improving a the folder layout

Fixes #938 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2023-06-08 141118

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Avdhesh-Varshney ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Avdhesh-Varshney** [comment]
@kunjgit @Arun9739 @raju-kumar21 please review my pull request and merge this enhancement into the main branch for successful contribution under GSSoC'23.

**Comment by Avdhesh-Varshney** [comment]
@kunjgit @Arun9739 @raju-kumar21 please review my enhancement of ludo game and merge it into the main branch for successful contribution under GSSoC'23.

**Comment by kunjgit** [comment]
we already have this game on GameZone !!!

**Comment by kunjgit** [comment]
Thank you  @Avdhesh-Varshney , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Avdhesh-Varshney** [comment]
@kunjgit I am not removing the game or adding the new game
But this is an enhancement of Ludo Game.
I am adding more features in it by adding background music, rolling sounds, winning sound to give a congratulation, more attractive interface, add more responsiveness, etc.

So, please again review the pull request and i requested to merge it into the main branch. Thanks !

**Pull request closed without merging**
