### PR TITLE
fixed game data and image links

### LINKED ISSUE #2502: [Bug]: Images not loading and some missing games not visible on website
### Give a brief about the bug ✍️

Some games are not visible on the website and some images are not loading 

### What is the expected behavior? 🤔

Correct Image loads and games present

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Swapnil-Singh-99**
## PR Description 📜

I have fixed GameData file and Readme File with some changes and fixing image url

Fixes #2502 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Swapnil-Singh-99 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Swapnil-Singh-99** [comment]
@kunjgit Please review and merge

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Conflicts are still there @Swapnil-Singh-99

**Comment by Swapnil-Singh-99** [comment]
@gurjeetsinghvirdee I have resolved conflicts

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM

**Comment by kunjgit** [comment]
Thank you  @Swapnil-Singh-99 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
