### PR TITLE
Added Enduro retro game ( A classic retro game )

### LINKED ISSUE #1990: [New game]: Enduro ( Retro car game )
### 🎮 Game Request

we all have played this game in our childhood, this is a simple game that uses a bit of js 
player get to control through his keyboard up, left and right. On colliding with other cars player's card get decreased.
This game doesn't need any description, because this was played by us.

### Point down the features

We have controls to move forward, left and right. Player has to avoid getting collided to other cars.

image

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Bhuvanchand26**
## PR Description 📜

we all have played this game in our childhood, this is a simple game that uses a bit of js
player get to control through his keyboard up, left and right. On colliding with other cars player's card get decreased.
This game doesn't need any description, because this was played by us.
Fixes #1990

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Bhuvanchand26 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Bhuvanchand26,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by Bhuvanchand26** [comment]
hey @kunjgit , Enduro which is a classic retro game, this is different from other racing games, Please do consider this.
THANK YOU

**Comment by kunjgit** [comment]
we already have racing game on GameZone and it is having much better UI !!

**Comment by kunjgit** [comment]
Thank you  @Bhuvanchand26 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Bhuvanchand26** [comment]
Hey @kunjgit , this is not about we having a racing game. The game which i've raised was released in 1980s.
thats the reason why I've raised issue even with the bad UI.

**Comment by gurjeetsinghvirdee** [comment]
**Copied from codepen: https://codepen.io/rafaelcastrocouto/pen/obQJwb**

**Pull request closed without merging**
