### PR TITLE
[Fixes #2294] Enhanced Number guessing game

### LINKED ISSUE #2294: [Enhancement]: Number Guessing Game Enhancement
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

Currently when the user make a right guess , then the gamne do not reset. It get stuck unless we refresh.

### Describe the solution you'd like

Solution steps

I would like to add reset functionality to the game and also some popups to inform user if the guess was right or wrong and then move to the next game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by ritik48**
## PR Description 📜

After making the right or wrong guess there was no way to replay the game unless user refreshed the site. So, I added reset button to overcome this problem.
Fixes #2294 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

nnnnnn

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @ritik48 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by ritik48** [comment]
@kunjgit please review this pr

**Comment by ritik48** [comment]
@kunjgit please review this pr

**Comment by ritik48** [comment]
@kunjgit please review this pr

**Comment by ritik48** [comment]
@kunjgit please review this pr

**Comment by kunjgit** [comment]
Thank you  @ritik48 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
