### PR TITLE
[ADD]: PACIFIC AIR BATTLE GAME (3D)

### LINKED ISSUE #710: [New game]: PACIFIC AIR BATTLE
### 🎮 Game Request

Game logic and basic description
- In this game, you will take control of a fighter jet and engage in aerial combat against enemy jets.
- You will need to use your skills and experience to dodge enemy fire and take down your targets.
- This game has good graphics 

### Point down the features

Game points
- The objective of the game is to destroy all of the enemy jets. You can do this by using your weapons to shoot them down or by ramming them.
- This game is challenging and will require you to use all of your skills and experience to succeed.
- You will get points for Attacking the enemies, you can get mediboxes to boost your health and much more!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## PR Description 📜
- This PR is about adding the "Pacific Air Battle" Game, it's an action phased attacking game
- In this game, you will take control of a fighter jet and engage in aerial combat against enemy jets.
- You will need to use your skills and experience to dodge enemy fire and take down your targets.

Fixes #710 

## Fixes/Closes: 
- #710 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
preview1
preview2
preview3

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @0xabdulkhalid ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
add your game entry in main README games section

**Comment by 0xabdulkhalid** [comment]
Done @kunjgit !

**Comment by 0xabdulkhalid** [comment]
Conflicts also resolved!

**Pull request closed without merging**
