### PR TITLE
Added Foosball Game

### LINKED ISSUE #2083: [New game]: Foosball Multiplayer Game
### 🎮 Game Request

I want to add a foosball game using HTML, CSS, and JavaScript. The foosball game will allow users to play a virtual version of the popular table game directly on our website.

### Point down the features

1. A visually appealing and intuitive game interface that resembles a foosball table, complete with players, goalposts, and a scoring system.
2. Realistic physics and gameplay mechanics to simulate the movement of the foosball and the interaction between players and the ball.
3. Optionally, there is a multiplayer functionality to enable users to play against each other online, adding a competitive element to the game.
4. A scoring system to keep track of goals scored by each player or team and display the scores on the screen during gameplay.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by abhinav-m22**
## PR Description 📜

This foosball game is developed using HTML, CSS, and JavaScript. 
The game will allow users to play a virtual version of the popular table game directly on our website.

Fixes #2083 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

[screen-capture (10).webm](https://github.com/kunjgit/GameZone/assets/113239388/be16f4bc-3575-4e69-bacf-d3bc7a6fe6bb)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @abhinav-m22 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Resolve Conflicts @abhinav-m22

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @abhinav-m22,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @abhinav-m22,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @abhinav-m22,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Comment by abhinav-m22** [comment]
@gurjeetsinghvirdee please check now

**Comment by kunjgit** [comment]
Thank you  @abhinav-m22 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
