### PR TITLE
[New Game]: Catch the fruit

### LINKED ISSUE #450: [New game]: Catch the fruit
### 🎮 Game Request

**Game Logic:**

1. The game is a simple catch-the-falling-fruit game where the player controls a character to catch falling fruits.
2. The player can move horizontally within the game container using the mouse.
3. Fruits fall from the top of the game container and the player needs to position themselves to catch the falling fruits.
4. When a fruit is caught, the player's score increases.
5. If a fruit reaches the bottom without being caught, it resets to the top, and the game continues.
6. The game continues indefinitely, allowing the player to try to achieve the highest score possible.

### Point down the features

 **Features of the Game:**

1. **Player Control:** The player can move horizontally within the game container by moving the mouse.
2. **Falling Fruits:** Fruits fall from the top of the game container and the player needs to catch them.
3. **Score Tracking:** The player's score is displayed at the top of the game container and increases each time a fruit is caught.
4. **Continuous Gameplay:** The game continues indefinitely, allowing the player to catch as many fruits as possible and try to achieve a high score.
5. **Dynamic Difficulty:** The speed at which the fruits fall can be adjusted to increase the difficulty as the game progresses.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by sudarshan-hub**
## PR Description 📜

Added a new game, Catch the fruit. 
Fixes #450 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @sudarshan-hub ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@sudarshan-hub Make the entry of your game into the main README file.

**Comment by sudarshan-hub** [comment]
@Arun9739 Updated the main README.md by adding the entry of my game. Could you please verify and merge the PR?

**Comment by Arun9739** [comment]
@sudarshan-hub Plz add a * in place of number in main REDAME, not the number

**Comment by sudarshan-hub** [comment]
@Arun9739 Replaced * in the place of number in main README file, kindly verify the same

**Comment by Arun9739** [comment]
@sudarshan-hub Plz check your README structure, there have been some duplicate entries.

**Comment by sudarshan-hub** [comment]
Could you tell me which README file whether the main README or in the games folder README?
I have checked the main README, and it does not have any duplicate entries. Only one entry for my game is there and that too with * in the place of the number. May be some other game names are there with duplicate number entries. Kindly verify the same.

**Comment by kunjgit** [comment]
Hey please add your image as mentioned in documentation and create PR again

**Comment by kunjgit** [comment]
Thank you  @sudarshan-hub , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
