### PR TITLE
Added Navigation Bar

### LINKED ISSUE #311: [Bug]:  Navigation Bar Missing
### Give a brief about the bug ✍️

Navigation bar is missing on the site.

### What is the expected behavior? 🤔

After adding the Navigation bar to the site it will make website look more attractive and make easy to use by the users as it will help in the direct navigation of the different section of the website.

### Provide step by step information reproduce the bug 📄

I firstly saw the website and I got that the first of all a navigation bar should be present in the website which will give convinience to the user for navigating within the website.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by adarsh-1262**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #311 <your_issue_number>

As earlier the navigation bar is missing in the website, I have added Navigation Bar to the Website. 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)

<hr>

## Add your screenshots(Optional) 📸

Screenshot (16)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Arun9739** [comment]
@adarsh-1262 plz resolve the branch conflicts

**Comment by adarsh-1262** [comment]
> @adarsh-1262 plz resolve the branch conflicts

Sir could you explain me some more what i have to do.... plz sir?

**Comment by adarsh-1262** [comment]
> @adarsh-1262 plz resolve the branch conflicts

done sir...

**Comment by Arun9739** [comment]
@adarsh-1262 LGTM

**Comment by kunjgit** [comment]
Hey @adarsh-1262  as per now we are not having any changes in website as we don't want changes in UI for now !!

**Comment by kunjgit** [comment]
Thank you  @adarsh-1262 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
