### PR TITLE
Tower of blocks Game added #2521

### LINKED ISSUE #2521: [New game]: Tower of Blocks
### 🎮 Game Request

Game logic and basic description:
Tower of Blocks is a casual stacking game where the objective is to build a tower by precisely placing blocks on top of each other. The player's goal is to achieve the highest possible score by aligning the blocks perfectly.
It will look something like this:
image

### Point down the features

Features:

Block Stacking: The game involves stacking blocks on top of each other. Each block is placed directly above the previous block, and the player must ensure a stable tower structure.

Block Sliding: Blocks slide horizontally across the screen from one side to another, making the gameplay dynamic and challenging.

User Input: The player can interact with the game using either the spacebar or the mouse click to place the sliding block on top of the previous block.

Precision Placement: To maximize their score, the player must align the sliding block accurately with the previous block. If the new block partially extends beyond the previous one, the excess portion is cut off, and the remaining portion becomes the foundation for the next block.

Scoring System: The score increases with each successful block placement. Perfectly aligned blocks yield higher scores.

Game Over Condition: If the sliding block is not placed correctly, causing the tower to become unstable and collapse, the game ends. The player can then view their final score and attempt to beat their high score.

Visual Feedback: The game provides visual cues to help players align the blocks, such as highlighting the correct alignment position or indicating when a block is precisely aligned.

Progressive Difficulty: As the game progresses, the sliding blocks may become smaller, making the stacking process more challenging and engaging.

High Score: The game keeps track of the player's highest score achieved, motivating them to beat their own records.

Restart Option: After a game over, the player has the option to restart the game to try again.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Yashika-Agrawal**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #2521 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Yashika-Agrawal ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Yashika-Agrawal,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Yashika-Agrawal,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Review by gurjeetsinghvirdee — COMMENTED** [review]
JS copied from here: **https://github.com/Siddhant-K-code/Block-Tower**
Design copied from here: **https://codepen.io/ste-vg/pen/ppLQNW**

**Comment by kunjgit** [comment]
Thank you  @Yashika-Agrawal , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
