### PR TITLE
Added falling words game

### LINKED ISSUE #4587: [New game]: Falling Words
### 🎮 Game Request

A game where players need to type falling words before they reach the bottom of the screen.

### Point down the features

It will have difficulty level
Points will be scored based on how many words correctly typed.
If the words reach bottom of the screen then the game will be over

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by somilyadav7**
## Added new game: Falling Words
A game where players need to type falling words before they reach the bottom of the screen.
Type the word, as fast as you can !!, before it reaches the bottom of the blurred square. If it touches the bottom line you lose
Fixes #4587  

## Features:
* It will have difficulty level
* Points will be scored based on how many words correctly typed.
* If the words reach bottom of the screen then the game will be over.
* How to play option
* Palying music option 

## Game difficulties

It has 3 difficulties

* Easy = 1 word per 3seg
* Medium = 1 word per 2seg
* Hard = 1 word per 1seg
* Impossible = 1 word per 0.4seg

## Tech used

* HTML
* CSS
* Javascript
* [Bootstrap](https://getbootstrap.com/)
<hr>

 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add screenshots📸

Screenshot 2024-06-17 200544
Screenshot 2024-06-17 200557
Screenshot 2024-06-17 200621
Screenshot 2024-06-17 200703

--- 
<br>

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @somilyadav7 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by somilyadav7** [comment]
@ishita-43  @kunjgit  Review the PR please.

**Comment by somilyadav7** [comment]
@ishita-43 please review

**Comment by somilyadav7** [comment]
@kunjgit pleasre review

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Make sure to add your game image in the  asset folder of the gamezone repo 
Also add your game entry in the main readme.md file of the gamezone for the format refer other entries !!

**Comment by somilyadav7** [comment]
> Make sure to add your game image in the asset folder of the gamezone repo Also add your game entry in the main readme.md file of the gamezone for the format refer other entries !!

Done

**Comment by somilyadav7** [comment]
@ishita-43 done the changes as requested

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @somilyadav7 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
