### PR TITLE
Timer added to Master Typing

### LINKED ISSUE #207: [Enhancement]: Adding a timer to master_typing
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement
This doesn't tell the user his/her progress in typing.

### Describe the solution you'd like

Solution steps
I want to add a timer (80-120sec) which gives a count of characters pressed, so that the user can compare.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by ishita80**
PR Description 📜
Timer now also gives you your typing speed (based only on correct keys).
Fixes #207

<hr>
 
Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added README.md in my folder 

<hr>

## Add your screenshots(Optional) 📸
ss

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @ishita80 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@ishita80 LGTM

**Comment by ishita80** [comment]
@Arun9739 Sorry Sir but I don't understand the meaning of the two labels.

**Comment by ishita80** [comment]
Merge Conflicts resolved.

**Comment by kunjgit** [comment]
Thank you  @ishita80 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
