### PR TITLE
Completed making Pumpkin Pursuit Game

### LINKED ISSUE #1939: [New game]: Pumpkin Pursuit
### 🎮 Game Request

Game logic and basic description
Welcome to "Pumpkin Pursuit," a thrilling memory game set in a spooky Halloween world. It's up to you to uncover pairs of matching pumpkins while enjoying enchanting sounds that enhance the Halloween experience. Sharpen your memory, embrace the challenge.

### Point down the features

Game points
-The player is given 60 seconds to match all the cards.
-The players moves are also counted.
-The player has to select all the matching pairs within 1minute to win the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #1939 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

https://github.com/kunjgit/GameZone/assets/112749383/7d7ce15d-8b8e-49d4-9420-9007990fdbf9

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @akhilender-bongirwar ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
you have to add proper game thumbnail !!!

**Comment by akhilender-bongirwar** [comment]
> you have to add proper game thumbnail !!!

Sure @kunjgit, will add it now. :)

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @akhilender-bongirwar , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Pull request merged**
