### PR TITLE
new game added

### LINKED ISSUE #3403: [New game]: DoraemonRun
### 🎮 Game Request

Doraemon Run is an adventurous game where players will be able to navigate through through top,left,right,bottom .Players must navigate Doraemon through obstacles like mazes while collecting cakes and avoiding traps. It offers engaging gameplay with intuitive controls and increasing difficulty levels. As Doraemon dashes through challenging mazes to devour delicious Dora cakes ,it will loose his score and health . It will track the high Score and Score and as soon as it health reaches 0 or it will crash to the boundary line , the game will end.

### Point down the features

 "Doraemon Run," players earn game points for every Dora cake Doraemon consumes during his adventurous run through the mazes. Each cake adds to the player's overall score, encouraging them to collect as many cakes as possible. Additionally, players may receive bonus points for collecting cakes in quick succession or for completing special challenges within the game. These points contribute to the player's overall score, allowing them to compete for high scores on the game's leaderboards.

Game points: Increases fro every dora cake - 10points
GamePoints decrease by crashing to the maze.
Health decreases by -1 everytime
And HealthScore : 0 (Game Ends)

It is very engaging and provide exciting user experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by SrijaVuppala295**
## PR Description 📜

DoraemonRun game successfully added
Fixes #3403

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2024-05-18 010337

https://github.com/kunjgit/GameZone/assets/140592148/020bc519-614b-4411-ac70-c5f3d9961695

--- 
<br>

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @SrijaVuppala295 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
@SrijaVuppala295 resolve merge conflicts !

**Comment by SrijaVuppala295** [comment]
@kunjgit , All checks have been passed sir, Resolved merge conflicts!!

**Comment by kunjgit** [comment]
Thank you  @SrijaVuppala295 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
