### PR TITLE
Added Bulls eye game

### LINKED ISSUE #1761: [New game]: Bulls eye game
### 🎮 Game Request

This is a basic archery game using SVG and animation. It allows the user to drag and release an arrow, simulating shooting at a target. The position and angle of the arrow are calculated based on the mouse movement, and the bow is animated accordingly. The code detects collisions between the arrow and the target using line segment intersection.

### Point down the features

It has a bow and arrow and a target
If the user misses the target then it shows its a "miss". 
if the user hits the board other than the center part of the target, it shows "hit".
If the user hits at the middle circle of the target then it's a bullseye.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by saikiranreddy201**
## PR Description 📜

I have added the bulls eye game and made the changes in the appropriate files.
I have tested the game and it's working completely fine.
I have added the instructions on how to play the game.

Fixes #1761 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>
<be>

Bulls_eye

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @saikiranreddy201 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @saikiranreddy201,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @saikiranreddy201 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @saikiranreddy201,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by saikiranreddy201** [comment]
Hey @kunjgit, This is not a closed issue, this one has been assigned to me!
Therefore I raised the PR, I still didn't understand why did you close it.

**Review by gurjeetsinghvirdee — COMMENTED** [review]
**Copied from here: https://github.com/Hypertext-Workaholics/bullseye-game
Live website: https://hypertext-workaholics.github.io/bullseye-game/**

**Pull request merged**
