### PR TITLE
Roshambo

### LINKED ISSUE #4540: [New game]: Roshambo
### 🎮 Game Request

The game is based on the classic game of rock paper and scissors.
In this,the user chooses one from the three options available and the computer does the same simultaneously. And thus, making the combinations, one of the both wins or either its a tie

### Point down the features

In this,the user chooses one from the three options available and the computer does the same simultaneously. And thus, making the combinations, one of the both wins or either its a tie
1. Rock defeats Scissor
2. Scissor defeats Paper
3. Paper defeats Rock

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by meetarora10**
## PR Description 📜
Based on the classic rock-paper-scissors game.
In this,the user chooses one from the three options available and the computer does the same simultaneously. And thus, making the combinations, one of the both wins or either its a tie

Rock defeats Scissor
Scissor defeats Paper
Paper defeats Rock

Fixes #4540 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot (471)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @meetarora10 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @meetarora10, You have reached your limit to contribute in GameZone with a score of 300. 
 We believe in giving equal opportunity to everyone so you will not be able to contribute to GameZone now onwards. 💗 
 Thank you for your valuable time and contribution in GameZone 🕹️! 

 Your merged pull requests:
- [#4376](https://github.com/kunjgit/GameZone/pull/4376) with labels: level2 score: (25)
- [#3961](https://github.com/kunjgit/GameZone/pull/3961) with labels: level2 score: (25)
- [#3866](https://github.com/kunjgit/GameZone/pull/3866) with labels: level1 score: (10)
- [#3827](https://github.com/kunjgit/GameZone/pull/3827) with labels: level2 score: (25)
- [#3811](https://github.com/kunjgit/GameZone/pull/3811) with labels: level2 score: (25)
- [#3775](https://github.com/kunjgit/GameZone/pull/3775) with labels: level3 score: (45)
- [#3695](https://github.com/kunjgit/GameZone/pull/3695) with labels: level2 score: (25)
- [#3603](https://github.com/kunjgit/GameZone/pull/3603) with labels: level3 score: (45)
- [#3529](https://github.com/kunjgit/GameZone/pull/3529) with labels: level2 score: (25)
- [#3373](https://github.com/kunjgit/GameZone/pull/3373) with labels: level2 score: (25)
- [#3333](https://github.com/kunjgit/GameZone/pull/3333) with labels: level2 score: (25)

**Comment by kunjgit** [comment]
Thank you  @meetarora10 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by meetarora10** [comment]
Thanku but it was good if you have told this when I created the issue.

**Pull request closed without merging**
