### PR TITLE
added tic tac toe

### LINKED ISSUE #18: [New game]: Tic Tac Toe
### 🎮 Game Request

I ll create the game skeleton of tic tac toe first and the logic for winning will be 3 X or 3 O diagonally or straight will win.This will be done in Html,css and Js

### Point down the features

This will be responsive that is can be played in any display size along with this there will be animation on winning.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by SimranLahrani842**
## PR Description 📜
Tic Tac Toe
Fixes #18 
I have added tic-tac-toe game where alternate chance is given to X and O.
Game can also be reset if required.
The chance of player each time and the winner is displayed.
Sound occurs on clicking the the box.

## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

## Add your screenshots(Optional) 📸
Screenshot (491)

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by SimranLahrani842** [comment]
Added all files and image in assets folder updates readme.md in main and resolved conflicts.
Kindly review my PR @kunjgit

**Comment by kunjgit** [comment]
Hey @SimranLahrani842 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by SimranLahrani842** [comment]
> Hey @SimranLahrani842 wave!
> 
> @kunjgit here, We have this annoucement to make loudspeaker!! During the time of PR don't alter main index file ! slightly_smiling_face In main Readme file just use * as a game number during the time we are merging we will add number !! eyes Make sure you join our [Discordjoystick](https://discord.gg/fgwk4XZfxG) if you haven't innocent Thank you heartpulse!

Ok Sir it was not mentioned anywhere so I wrote number.
Do I have to change number and write * now?
@kunjgit

**Comment by SimranLahrani842** [comment]
> Hey @SimranLahrani842 👋!
> 
> @kunjgit here, We have this annoucement to make 📢!! During the time of PR don't alter main index file ! 🙂 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 Thank you 💗!

added * instead of number..please review pr and merge it @kunjgit

**Comment by Arun9739** [comment]
@SimranLahrani842 Please resolve the branch conflicts

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 Please resolve the branch conflicts

Done sir kindly review and merge the PR... @Arun9739

**Comment by Arun9739** [comment]
@SimranLahrani842 LGTM

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 LGTM

@kunjgit please add the labels of level and gssoc and merge ..thanking you and  @Arun9739

**Comment by kunjgit** [comment]
Thank you  @SimranLahrani842 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
