### PR TITLE
Added Game "Hit_The_Mole"

### LINKED ISSUE #5124: [New game]:  Hit-the-mole
### 🎮 Game Request

Game logic and basic description
Test your reflexes and speed with our Mole-hitter game! In this fun and addictive game, moles pop up randomly from their holes, and it's your job to whack them before they disappear. The more moles you hit, the higher your score. But be quick – the moles get faster and more elusive as you progress through the levels.

### Point down the features

Game points
Hitting mole to gain points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Sourabh782**
## PR Description 📜

"Hit the Mole" game is a fun and engaging interactive game where players must quickly click on moles that randomly appear on the screen. The objective is to hit as many moles as possible within a set time limit. The game features simple yet appealing graphics, responsive controls, and keeps track of the player's score.

Fixes #5124 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in GameZone's README.md
- [X] I have added README.md in my Game folder 
- [ ] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.
- [X] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸

Hit_The_Mole

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Sourabh782 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — APPROVED** [review]

**Comment by kunjgit** [comment]
@Sourabh782 resolve merge confilicts

**Comment by Sourabh782** [comment]
@kunjgit Resolved conflicts

**Comment by Sourabh782** [comment]
@ishita-43 can u merge it?

**Comment by ishita-43** [comment]
@kunjgit will soon merge it

**Comment by kunjgit** [comment]
Thank you  @Sourabh782 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
