### PR TITLE
music add according to win or loose the game

### LINKED ISSUE #833: [Enhancement]: Add cool music into 15. Color Guessing Game
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement
i want to add music into no.15. Color Guessing Game 
it is not a problem but by the add music game is more attractive and its create more fun.

### Describe the solution you'd like

Solution steps
i want to add cool music in the game according to win and loose the game.

1. if user click on the any color its play click sound 
2. if user guess the wrong color then its play "oh no..." sound
3. if user guess the right color then its play win music.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by vidhimakani74**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #833
adding cool music into 15. Color Guessing Game.

- if user click on the any color its play click sound
- if user guess the wrong color then its play "oh no..." sound
- if user guess the right color then its play win music.

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @vidhimakani74 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by vidhimakani74** [comment]
> @vidhimakani74 Make an entry of your game into main README, add game screenshot

Working Video with music and all Screenshots are added in readme file

**Comment by Arun9739** [comment]
@vidhimakani74 LGTM

**Comment by kunjgit** [comment]
@vidhimakani74 You have to make sure that you are following proper guidelines !
create a PR again !

**Comment by kunjgit** [comment]
Thank you  @vidhimakani74 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
