### PR TITLE
[ADD]:  THE RAISING FIGHTING SPIRITS GAME 👾

### LINKED ISSUE #1076: [New game]:  THE RAISING FIGHTING SPIRITS 👾
### 🎮 Game Request

Game logic and basic description
- This game is a simple strategy card game where you fight against the Grim Reaper using a horde of spirits!
- Try to kill the Reaper faster to receive a better score!!! BUT watch out for the Reaper's next turn intended action!!!

### Point down the features

Game points
- You can stop/start the game sounds in the top right speaker icon.
-  Click/touch a soul to select it or use the buttons at the bottom right (next soul/previous soul) to navigate them.
- Look at the Reaper's next turn intention/action to create your strategy.
- Energy lets you know the amount of cards you can play per turn.
- Click and drag cards out/above your hand area to play them.
- End your turn and see the reaper action.
- During game events you can select one of the power up options.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## PR Description 📜
- This PR is about adding The Raising Fighting Spirits Game

## Fixes #1076 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Screenshots 📸

The_Raising_Fighting_Spirits

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @0xabdulkhalid ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@0xabdulkhalid Resolve the conflicts

**Comment by 0xabdulkhalid** [comment]
@Arun9739, Conflicts are resolved!

**Review by kunjgit — APPROVED** [review]

**Comment by 0xabdulkhalid** [comment]
@Arun9739, Conflicts are resolved!

**Comment by kunjgit** [comment]
Thank you  @0xabdulkhalid , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
