### PR TITLE
Adding new Game "Drum_And_Kit"

### LINKED ISSUE #185: Drum Kit Game
### 🎮 Game Request

Drum and Kit Game is a rhythm-based game where players simulate playing a virtual drum kit using input devices such as a keyboard or controller.
tech use:Html,css,javascript

### Point down the features

The game provides visual feedback in the form of on-screen prompts or notes that indicate when and which drum element to hit.
With increasing difficulty levels and varying music tracks, Drum and Kit Game offers an engaging and immersive experience for rhythm game enthusiasts.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Roshnijeewani3457**
## PR Description 📜

I have Added an new game called Drum_And_Kit Game that I have implemented using HTML,CSS and Javascript.I have Added
my game folder to the Games folder and added the game screenshot to the images folder in assests. I have also update the main Readme.md file
Fixes #185 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Roshnijeewani3457 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
you have to add image in main repo assets/images 
and also make sure you mark your entries in the main README file !!

**Comment by Roshnijeewani3457** [comment]
I have modified all the changes as above mentioned. Please reviewed my PR @kunjgit

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Roshnijeewani3457 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
