### PR TITLE
Haunting_Game Added

### PR DESCRIPTION
**Pull request by Kalivarapubindusree**
## PR Description 📜

#2395 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Haunting_Game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Kalivarapubindusree ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Kalivarapubindusree** [comment]
Now I removed all the images @kunjgit 
Can you please review this pr

**Comment by Kalivarapubindusree** [comment]
Can you please review this pr @kunjgit

**Review by gurjeetsinghvirdee — COMMENTED** [review]
First of all this is a Hunting game not Haunting Game & this is copied from here: **https://github.com/niiicolai/2d-hunting-game** 
Article Link: **https://betterprogramming.pub/create-a-simple-2d-hunting-game-with-javascript-and-html-1cb78e01a69e**
I asked you on last PR but you lied that you made this project 🫠
CC: @kunjgit @daccdacc

**Comment by kunjgit** [comment]
Thank you  @Kalivarapubindusree , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
