### PR TITLE
Added Hole and Mole Game

### LINKED ISSUE #4960: [New game]: Hole and mole game
### 🎮 Game Request

Game logic and basic description

This is a simple mole and hole a web based game built using html css js.
where you have to catch the mole, whenever you click on mole you will get points.

### Point down the features

Game points

This is a simple mole and hole a web based game built using html css js.
where you have to catch the mole, whenever you click on mole you will get points.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Maana-Ajmera**
## PR Description 📜
This is a simple mole and hole a web based game built using html css js.
where you have to catch the mole, whenever you click on mole you will get points.

Fixes #4960 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in GameZone's README.md
- [X] I have added README.md in my Game folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.
- [X] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Maana-Ajmera ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Maana-Ajmera** [comment]
@kunjgit @ishita-43 Please review my PR and merge it

**Review by ishita-43 — APPROVED** [review]
Seems good

**Comment by kunjgit** [comment]
Thank you  @Maana-Ajmera , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
