### PR TITLE
[GSSoC'23] Sketch Game Project Completed

### LINKED ISSUE #2415: [New game]: Etch-a-Sketch Game
### 🎮 Game Request

Game logic and basic description

- This game is a beginner friendly game.
- Also a beginner friendly project.
- Create so many images just hovering over the blocks of the grid or touch the blocks of the grid.
- Create as much large grid as you want.

### Point down the features

Game points

- Create emojis and different pictures
- Enjoy the game !

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## PR Description 📜

- This game is a beginner friendly game.
- This is a single player game.
- Also a beginner friendly project.
- Create so many images just hovering over the blocks of the grid or touch the blocks of the grid.
- Create as much large grid as you want.

Fixes #2415 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Avdhesh-Varshney ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Avdhesh-Varshney** [comment]
@kunjgit @Arun9739 sir, please review this pull request

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Resolve the conflicts @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
@gurjeetsinghvirdee @kunjgit @Arun9739 sir, conflicts resolved !

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Avdhesh-Varshney , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
