### PR TITLE
[New Game]:Life's_Mossaic

### LINKED ISSUE #4060: [New game]: Life’s Mosaic
### 🎮 Game Request

Game logic and basic description:
This basic logic forms the foundation of Life's Mosaic, allowing for the exploration of complex patterns and behaviors emerging from simple rules.The universe is an infinite, two-dimensional orthogonal grid of square cells.
Each cell can be in one of two states: ALIVE or DEAD.
Each cell interacts with its eight neighbors (horizontally, vertically, and diagonally adjacent cells).

Rules:
Underpopulation: Any live cell with fewer than two live neighbors dies.
Survival: Any live cell with two or three live neighbors lives on to the next generation.
Overpopulation: Any live cell with more than three live neighbors dies.
Reproduction: Any dead cell with exactly three live neighbors becomes a live cell.

### Point down the features

Controls: Play, Pause, Fast Forward, Slow Down, Clear, Random
Preset patterns (e.g., Glider, Gosper Glider Gun)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by PallaviGudupallavi**
## PR Description 📜
This PR is about a new game - 'Life's Mosaic'. In this game players create initial configurations and observe their evolution. This zero-player game is Turing complete and simulates complex patterns through simple rules on an infinite grid.

Fixes #4060 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @PallaviGudupallavi ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — CHANGES_REQUESTED** [review]
hi you also need to add your game entry into the main readme.md file of the gamezone repo refer other entries for the format

**Comment by ishita-43** [comment]
It is not showing in your pr files the readme. Md

**Comment by PallaviGudupallavi** [comment]
im unable to get the link to update in readme file...can you please tell me how do i get the path and add the path in readme file?

**Comment by ishita-43** [comment]
> im unable to get the link to update in readme file...can you please tell me how do i get the path and add the path in readme file?

Link would be same as other's you only need to add your game folder name inn the end. 

You can make these changes in your forked repo on your system and then push them in this pr

**Pull request closed without merging**
