### PR TITLE
added gradient background color to the website [GSSoC'23]

### LINKED ISSUE #602: [Bug]: The website has a very plane background which can be made interesting. [GSSoC'23]
### Give a brief about the bug ✍️

The website has a very plane background which can be made interesting. A better background. with some gradient in it will make it more fun and interesting.

Here is one sample : 
homepage for issue

We can add such gradients to give a more fun look to the website.

### What is the expected behavior? 🤔

A better background. with some gradient in it will make it more fun and interesting.

### Provide step by step information reproduce the bug 📄

I will design a new backgroung through figma and add it to the website

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by 1Shubham7**
## PR Description 📜

Added a background gradient color to the website to make it more fun interesting .

Closes #602

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [] I have added entries for my game in main README.md
- [] I have added README.md in my folder 
- [] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

gamezone background

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @1Shubham7 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @1Shubham7 !! can you please follow dark theme and have some good combination of gradient with other colours !!

**Comment by 1Shubham7** [comment]
ok @kunjgit , Let me add  a bit more darker theme.

**Review by 1Shubham7 — COMMENTED** [review]
Changed the gradient color as told by the maintainer.

**Comment by 1Shubham7** [comment]
@kunjgit  I changed the gradient to a bit more darker  and gaming related theme. Is it better? Shall I Show you more sample gradients?

**Comment by kunjgit** [comment]
We are sticking to the UI we have only if you are making changes then you have to make sure that it should go with original UI

**Comment by kunjgit** [comment]
Thank you  @1Shubham7 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
