### PR TITLE
[Enhancement]: Taash Game Ui changed

### LINKED ISSUE #4570: [Enhancement]: Taash Game Ui change
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

- In this game cannot upproach proper UI.
- I will make Redesign it.
- please assign me..

### Describe the solution you'd like

Screenshot from 2024-06-14 16-23-24

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by sivaprasath2004**
Hello @kunjgit and @ishita-43 ,
## PR Description 📜
[Enhancement]: Taash Game Ui changed
Fixes #4570

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

### Before

Screenshot from 2024-06-14 16-23-24

### After

[Screencast from 2024-06-17 18-01-47.webm](https://github.com/kunjgit/GameZone/assets/121082414/a5c062ec-ed46-404d-ac14-3b20dd25b09f)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @sivaprasath2004 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by sivaprasath2004** [comment]
Hello @ishita-43 , This is level 2 issue

**Comment by kunjgit** [comment]
Thank you  @sivaprasath2004 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
