### PR TITLE
Currency Converter

### LINKED ISSUE #3584: [New game]: Currency converter
### 🎮 Game Request

Game logic and basic description
I am planning to develop an educational and entertaining currency converter game. This game will serve as a fun and interactive tool for users to learn about the currencies of different countries. 

### Point down the features

Game points
The currency converter game will present users with various challenges and tasks related to currency conversion. Players will need to convert amounts from one currency to another, identify the correct currencies for different countries, and perhaps even engage in scenarios simulating international travel or trade.

Gameplay Examples

    Conversion Challenges: Players might be given an amount in one currency and asked to convert it to another currency within a time limit.
    Currency Identification: Users might be shown a list of countries and asked to match them with their correct currencies.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by kashisharora9462**
## PR Description 📜

Introducing a new, engaging, and educational game: Currency Conversion! This game is designed to be user-friendly, providing both fun and valuable learning experiences for players.

In this game, users can explore and understand currency exchange rates in an interactive and enjoyable way. The interface is designed to be intuitive and accessible, making it easy for players of all ages to participate and learn.
Fixes #3584 

 
## Mark the task you have completed ✅

- [x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x ] I have added screenshot for website preview in assets/images 
- [x ] I have added entries for my game in main README.md
- [x ] I have added README.md in my folder 
- [x ] I have specified the respective issue number for which I have requested the new game.

## Add your screenshots(Optional) 📸

Screenshot 2024-05-21 111559
Screenshot 2024-05-21 113737
Screenshot 2024-05-21 113720

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kashisharora9462** [comment]
changed!

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @kashisharora9462,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by kunjgit** [comment]
Thank you  @kashisharora9462 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Review by kashisharora9462 — COMMENTED** [review]
check if its done

**Comment by kunjgit** [comment]
Thank you  @kashisharora9462 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kashisharora9462** [comment]
I dont know what the error happened.I had successfully created the game added html,css and js file along with that i updated my readme.md file.I am not understanding what the conflict is and how to resolve as i am a begginner.
Can you please guide me what to do now please sir.

**Pull request closed without merging**
