### PR TITLE
Added Unword It ( reverse dumb-shard multiplayer game ) 

### LINKED ISSUE #4929: [New game]: Unword It ( reverse dumb-shard multiplayer game )
### 🎮 Game Request

is a digital twist on the classic game of charades. Players describe words in reverse order, challenging the opposing team to guess the original word.

## Gameplay:

- Teams take turns describing and guessing words
- Describing team sees the word in reverse
- Guessing team attempts to identify the word
- Points awarded for correct guesses or when time runs out
- Game continues for a set number of rounds or until a target score is reached

### Point down the features

- Reversed word display
- 30-second timer per round
- Two-team scoring system
- Reveal Letter" option (costs 1 point)
- Guess input and submission
- Alternating turns between teams
- Random word selection from a predefined list
- Simple, colorful user interface

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Shantnu-singh**
## PR Description 📜

Added Unword It ( reverse dumb-shard multiplayer game ) 
Fixes #4929

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>
## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Shantnu-singh ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Shantnu-singh** [comment]
hey @ishita-43 can you please review this and let me know of any changes.

**Review by ishita-43 — APPROVED** [review]
Good to go

**Comment by ishita-43** [comment]
Please resolve merge conflicts

**Comment by Shantnu-singh** [comment]
@ishita-43 done.

**Comment by kunjgit** [comment]
Thank you  @Shantnu-singh , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
