### PR TITLE
[New game]: Want to Add Space Dominator Game #4686

### LINKED ISSUE #4686: [New game]: Want to Add Space Dominator Game
### 🎮 Game Request

Game logic and basic description

in this user have some lives and have to kill all the enemies .

### Point down the features

Game points
the main character can shoot
throw bombs 

https://github.com/kunjgit/GameZone/assets/101548649/2c519b03-e2f8-4d32-9ec7-c7bd2d2ac11d

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by nishant0708**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #4686 

<hr>
 
## Mark the task you have completed ✅

- [Y ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [Y ] I have performed a self-review of my own code or work.
- [ Y] I have commented my code, particularly in hard-to-understand areas.
- [ Y] My changes generates no new warnings.
- [ Y] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ Y] I have added screenshot for website preview in assets/images 
- [Y ] I have added entries for my game in main README.md
- [Y ] I have added README.md in my folder 
- [Y ] I have added working video of the game in README.md (optional)
- [Y ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @nishant0708 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by nishant0708** [comment]
hey @ishita-43  @kunjgit Can you Review this Pr

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Please do the following changes 
add your game entry into main Readme.md file of the gamezone 
add your game image into asset folder of the gamezone follow contribution guidelines while naming the image

**Comment by nishant0708** [comment]
hey @ishita-43 @kunjgit please check it now it should be fine

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Review by ishita-43 — APPROVED** [review]
Ready to merge!!

**Pull request merged**
