### PR TITLE
Added Star Trek Trivia Game

### LINKED ISSUE #2413: [New game]: Star Trek Trivia
### 🎮 Game Request

A fun trivia game centered around the famous Star Trek franchise, which would include the following:

1. Multiple Difficulty Levels: Different difficulty levels to cater to various levels of Star Trek knowledge. 

2. Variety of Questions: A diverse range of questions covering different aspects of Star Trek, such as characters, aliens, technology, quotes, and memorable moments. This ensures that the quiz appeals to a wide audience and offers a mix of challenging and easier questions.

3. Time Constraints: A time limit to answer each question, increasing the pressure and making the game more exciting. 

4. Winning Criteria = 100 points 

### Point down the features

Game points:

On the basis of difficulty level:

- Easy =10 points
- Medium = 15 points
- Hard = 20 points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by tayyab-ilyas**
## PR Description 📜

A fun trivia game centered around the famous Star Trek franchise, which would include the following:

Multiple Difficulty Levels: Different difficulty levels to cater to various levels of Star Trek knowledge.

Variety of Questions: A diverse range of questions covering different aspects of Star Trek, such as characters, aliens, technology, quotes, and memorable moments. This ensures that the quiz appeals to a wide audience and offers a mix of challenging and easier questions.

Time Constraints: A 10 second time limit to answer each question, increasing the pressure and making the game more exciting.

Winning Criteria = 100 points

Fixes #2413

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @tayyab-ilyas ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @tayyab-ilyas,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @tayyab-ilyas,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Comment by tayyab-ilyas** [comment]
hey @gurjeetsinghvirdee ! can you check this out? also please don't forget to assign the Gssoc'23 label. Thanks!

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Can you re-add the screenshot in **`assets/images`** it's not working correctly

**Review by kunjgit — APPROVED** [review]

**Comment by tayyab-ilyas** [comment]
> Can you re-add the screenshot in **`assets/images`** it's not working correctly

Can you check now? working for me..

**Review by gurjeetsinghvirdee — APPROVED** [review]
Looks good

**Comment by kunjgit** [comment]
Thank you  @tayyab-ilyas , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by tayyab-ilyas** [comment]
hey @gurjeetsinghvirdee on the issue this was given the level 3 label

**Comment by gurjeetsinghvirdee** [comment]
> hey @gurjeetsinghvirdee on the issue this was given the level 3 label

That was automated by github action not given by any  human & labels should be given on the quality of PR

**Comment by tayyab-ilyas** [comment]
> > hey @gurjeetsinghvirdee on the issue this was given the level 3 label
> 
> That was automated by github action not given by any human & labels should be given on the quality of PR

cool.

**Pull request merged**
