### PR TITLE
Added Ninja Hattori game

### LINKED ISSUE #4833: [New game]: Ninja Hattori
### 🎮 Game Request

Game logic and basic description

A very popular cartoon ninja hattori is all here !
Dont let "kiyo" hurt ninja hattori

### Point down the features

Game points

- Save ninja hattori from kiyo till the destination to win
- Jump when kiyo comes your way and move ahead , 
- More the number of kiyo you defeat , more will be the points
- As soon as you come in contact with kiyo , game is over 

https://github.com/user-attachments/assets/352c2b6f-9bc9-42a3-8d1a-cbb56ba1ecb3

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Maana-Ajmera**
## PR Description 📜

Fixes #4833 

Game points

- Save ninja hattori from kiyo till the destination to win
- Jump when kiyo comes your way and move ahead , 
- More the number of kiyo you defeat , more will be the points
- As soon as you come in contact with kiyo , game is over 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

https://github.com/user-attachments/assets/352c2b6f-9bc9-42a3-8d1a-cbb56ba1ecb3

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Maana-Ajmera ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Maana-Ajmera** [comment]
@kunjgit added the game , please review and merge it

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Please update your pr and include following changes 
Add your game entry into the main Readme.md file of the repo  refer other entries for the format
Add your game image  in the asset folder of the repo follow naming convention mentioned in the contribution.md

**Comment by Maana-Ajmera** [comment]
@ishita-43 @kunjgit done the requested changes

**Comment by ishita-43** [comment]
conflict is arising in gamesdata.json try to resolve them

**Comment by Maana-Ajmera** [comment]
@ishita-43 resolved

**Comment by Maana-Ajmera** [comment]
@kunjgit , @ishita-43 I have resolved the conflicts

**Comment by Maana-Ajmera** [comment]
@kunjgit @ishita-43 I have resolved the conflicts, please review and please add labels, its been 1 week since i have created the pr

**Review by ishita-43 — APPROVED** [review]
Good to go!

**Comment by kunjgit** [comment]
Thank you  @Maana-Ajmera , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
