### PR TITLE
Anagram Checker Game #3510

### LINKED ISSUE #3510: [New game]: Anagram checker Game
### 🎮 Game Request

Game logic and basic description
The game generates two random words from a list of English words.
The game scrambles the letters of each word to create two anagrams.
The player is presented with the two anagrams and asked to unscramble them to form a valid English word pair.
If the player's guess is correct, they win the game.
If the player's guess is incorrect, they are given a hint about the possible word pair.
The player is given a certain number of attempts to guess the correct word pair. If they run out of attempts, they lose the game.

### Point down the features

Game points
The game involves generating two random words and scrambling their letters to create anagrams.
The player is asked to unscramble the anagrams to form a valid English word pair.
The game can be customized by changing the list of English words used to generate the anagrams.
The game can be implemented using a programming language such as Javascript.
The game can be used as a fun and educational way to teach players about anagrams and English vocabulary.
The game can be extended by adding additional features such as scorekeeping, time limits, or multiple rounds.
The game can be adapted for different age groups and skill levels by adjusting the length and difficulty of the words used to generate the anagrams.
The game can be played by a single player or in a multiplayer setting, where each player takes turns guessing the correct word pair.
The game can be integrated with a dictionary API or database to validate the player's guesses and provide hints.
The game can be made more challenging by increasing the number of anagrams or by adding a time limit for each guess.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Damini2004**
## PR Description 📜

Anagram Checker Game is game where two string is compared to check whether it is anagram or not.

Fixes #3510 #3667 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot 2024-05-21 020412

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Damini2004 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
@Damini2004 resolve the merge conflicts !

**Comment by kunjgit** [comment]
@Damini2004 still it's there

**Comment by Damini2004** [comment]
@kunjgit  Still conflicts is their ?

**Comment by kunjgit** [comment]
@Damini2004 resolve merge conflicts !

**Review by kunjgit — APPROVED** [review]

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Damini2004 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Damini2004** [comment]
You just have to copy paste the program proper then attach your file in that following program. The is available in the project then connect it properly.
If you didnt get then you can take help from mentor too.

@codewithishu

**Pull request merged**
