### PR TITLE
[Enhancement]: #2303 Website is now responsive

### PR DESCRIPTION
**Pull request by Tharun-nennavath**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes # <your_issue_number>

<hr> #2303 : This pull request resolves the issue of a non-responsive webpage and the visibility of overflow on the user interface. Upon being hired to address this problem, I have made the necessary changes to rectify the issue and ensure a seamless user experience.
 
## Mark the task you have completed ✅

- [ x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [[x]([url](url)) ] I have added screenshot for website preview in assets
ScreenShot1
/images 
- [ x] I have added README.md in my folder 
- [ x] I have specified the respective issue number for which I have requested the n
ScreenShot2
ew game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Tharun-nennavath ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by daccdacc** [comment]
Please make the following changes : 
- Show the changes that you were able to make. (like how it was before and what it is after you implemented changes)
- PR format improper.

**Comment by kunjgit** [comment]
Thank you  @Tharun-nennavath , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Tharun-nennavath** [comment]
Do i have to change it , and PR again

**Pull request closed without merging**
