### PR TITLE
Added WallSmash game

### LINKED ISSUE #1988: [New game]: Wall Smash
### 🎮 Game Request

You are provided with a set of 5 balls and several blocks labeled with numbers. Your task is to strike each block a number of times corresponding to the value displayed on it until the block dislodges. You have a limited number of attempts available, and your objective is to remove all the blocks.

### Point down the features

You are declared the winner if you pop all the blocks.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by saikiranreddy201**
## PR Description 📜

I have added the appropriate files for the WallSmash game and the game is ready to play!
Fixes #1988 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added a screenshot for website preview in assets/images 
- [x] I have added entries for my game in the main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @saikiranreddy201 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by saikiranreddy201** [comment]
Hey @kunjgit, you have merged my pr #1834 but forgot to add the gssoc labels to it, it still has pending labels to it. please add the gssoc label so that my pr counts 
**LINK:** https://github.com/kunjgit/GameZone/pull/1834

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
make sure you are adding README entry properly !!

**Review by kunjgit — APPROVED** [review]

**Comment by saikiranreddy201** [comment]
Dear @kunjgit please review my pr #1834 You have not added gssoc label there

**Comment by saikiranreddy201** [comment]
Hey @kunjgit I have resolved the conflicts new please merge this< also check the pr #1834, please add the labels 🙏

**Review by gurjeetsinghvirdee — COMMENTED** [review]
**Copied from here: https://github.com/bijection/wallsmash**
Live view: **https://wallsmash.com/**

**Comment by kunjgit** [comment]
Thank you  @saikiranreddy201 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
