### PR TITLE
mole

### PR DESCRIPTION
**Pull request by taneeshaa15**
gamezone

Updated readme:
review

Hi, @kunjgit ,
I hope you're doing well. I've addressed the game in issue #4339  and created a pull request for the same.
Could you please review the PR and let me know if any adjustments are needed?

Best regards,
Tanisha Garg

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @taneeshaa15 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @taneeshaa15,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by taneeshaa15** [comment]
@kunjgit Did the required changes, merge it now after reviewing.

**Comment by taneeshaa15** [comment]
@kunjgit review it.

**Comment by taneeshaa15** [comment]
@kunjgit Give your feedback.

**Comment by taneeshaa15** [comment]
@kunjgit There is no conflict now.

**Comment by taneeshaa15** [comment]
@kunjgit Merge it if found good.

**Comment by kunjgit** [comment]
Thank you  @taneeshaa15 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
