### PR TITLE
Bubble'z popper

### LINKED ISSUE #4212: [New game]: Bubble'z Popper
### 🎮 Game Request

Pop the Bubbles

A simple bubble-popping game made using HTML, CSS, and Javascript.
By moving the cursor onto the bubbles they blast.If you miss the 10 chances the game will end.

https://github.com/kunjgit/GameZone/assets/125206920/af0a669d-1e5e-40b5-bdd4-e32745c0a399

 

### Point down the features

-Points increase based on number of bubbles blasted.
-Sounds are added for good user experiences.
-Works on mobile too.the 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Chandu6702**
## PR Description 📜

I added a simple bubble-popping game using HTML, CSS, and Javascript.
By moving the cursor onto the bubbles they blast. If you miss the 10 chances the game will end.

Fixes #4212 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](ht
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x]  I have added entries for my game in main README.md
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot 2024-06-04 133640

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Chandu6702 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Chandu6702,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Chandu6702,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Chandu6702** [comment]
@kunjgit please review and merge this PR

**Comment by Chandu6702** [comment]
@kunjgit please review and merge this PR

**Comment by Chandu6702** [comment]
@kunjgit please review and merge this PR

**Comment by kunjgit** [comment]
Thank you  @Chandu6702 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
