### PR TITLE
#163 Frogger

### LINKED ISSUE #163: [New game]: Frogger
### 🎮 Game Request

Frogger is a simple yet challenging arcade game in which the player controls a frog that must cross a busy road and a river to reach its home. The game is played on a grid, and the frog can move left, right, up, and down. The player must avoid cars, trucks, and logs on the road. The player can earn points by crossing the road and river without being killed. The game ends when the player has successfully crossed the river.

### Point down the features

- the frog can move in any direction by avoiding all obstacles.
- The player can earn points by crossing the road and river without being killed.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Nilesh9106**
## PR Description 📜
Frogger is a classic arcade game where you control a frog as it tries to cross a busy road and a hazardous river to reach its home. The game is simple to play, but challenging to master. 
Fixes #163 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Frogger

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Nilesh9106 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@Nilesh9106 Plz add * in place of number in the main README file.

**Comment by Nilesh9106** [comment]
Hey, @Arun9739 I have made the changes that you have requested. Please Review this PR.

**Comment by Arun9739** [comment]
@Nilesh9106 LGTM

**Comment by kunjgit** [comment]
Thank you  @Nilesh9106 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
