### PR TITLE
Added Stickman Game

### LINKED ISSUE #2281: [New game]: Stickman Game
### 🎮 Game Request

Game logic and basic description
Goal of the game:

Get to the other end of the canvas or kill the enemy

Instructions:

Hold spacebar to throw sword further!
While the sword is flying you can throw knives with spacebar!
Arrow keys to move!

### Point down the features

Game points
As the player reach the other end of the canvas the next level will start or else the same level will repeat until the enemies got killed.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by uzmaansari23**
## PR Description 📜
Goal of the game:

Get to the other end of the canvas or kill the enemy

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes  #2281

Added a new Game stickman to resolve the created issue #2281
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot (71)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @uzmaansari23 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @uzmaansari23,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Comment by daccdacc** [comment]
Hey @uzmaansari23, can you implement the same changes in the stick hero game already existing on GameZone as it's more than 50% similar to that, and we don't accept duplicate games.

**Comment by uzmaansari23** [comment]
@daccdacc but my game is completely different then stick hero game .

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Yeah, your game is completely different because this game is not made by you either you can implement the changes on similar game mentioned by @daccdacc 
Copied from here: **https://github.com/INFOLITE-IN/Stickman**
Live View: **https://infolite-in.github.io/Stickman/**

**Comment by kunjgit** [comment]
Thank you  @uzmaansari23 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
