### PR TITLE
added Catch Him

### LINKED ISSUE #4715: [New game]: Catch him
### 🎮 Game Request

image

### Point down the features

,

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Khushi-Pushkar**
## PR Description 📜

Added Catch Him
Fixes #4715 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

please review and merge @kunjgit @ishita-43 
<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Khushi-Pushkar ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Khushi-Pushkar** [comment]
please review @ishita-43 and merge @kunjgit

**Comment by Khushi-Pushkar** [comment]
please review @ishita-43 and merge @kunjgit

**Comment by Khushi-Pushkar** [comment]
please review and merge @ishita-43 @kunjgit

**Comment by Khushi-Pushkar** [comment]
please review and merge @ishita-43 @kunjgit

**Review by ishita-43 — APPROVED** [review]
your pr review is completed and will soon be proceeded by merging

**Comment by kunjgit** [comment]
Thank you  @Khushi-Pushkar , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
