### PR TITLE
Added new game Solitaire

### LINKED ISSUE #2392: [New game]: Solitaire
### 🎮 Game Request

Solitaire is a popular single-player card game played with a standard deck. The objective is to arrange the cards in a specific manner, typically by suit and in ascending order. Players make moves by rearranging the cards on the tableau or foundation piles according to specific rules. The game requires strategic thinking and problem-solving skills to create sequences and free up cards. Solitaire is enjoyed by many as a challenging and relaxing pastime.

### Point down the features

It's a simple game just on completing it and thus changing the level and gives points on completing each level.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Deepanshu0703**
## PR Description 📜

Solitaire is a popular single-player card game played with a standard deck. The objective is to arrange the cards in a specific manner, typically by suit and in ascending order. Players make moves by rearranging the cards on the tableau or foundation piles according to specific rules. The game requires strategic thinking and problem-solving skills to create sequences and free up cards. Solitaire is enjoyed by many as a challenging and relaxing pastime.
Fixes #2392 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Deepanshu0703** [comment]
@kunjgit resolved conflicts

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Conflicts are still there @Deepanshu0703 please resolve it

**Review by kunjgit — APPROVED** [review]

**Comment by Deepanshu0703** [comment]
> Conflicts are still there @Deepanshu0703 please resolve it

Resolved

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Deepanshu0703 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
