### PR TITLE
New Game: Tinker_jump_master

### LINKED ISSUE #4853: [New game]: Tinker_jump_master
### 🎮 Game Request

One need to click left and right in order to make the Tinker to jump as high as possible.

### Point down the features

Game points

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by chakrabortydeep**
## PR Description 📜

Tinker Jump is game where the Tinker(Doodler) have to jump multiple platforms in order to reach high.
Fixes #4853

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @chakrabortydeep ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by chakrabortydeep** [comment]
//assign

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Add your game image in asset folder of the GameZone 
and resync your readme file with latest changes and then add your game entry in the file

**Comment by chakrabortydeep** [comment]
Done with the changes as suggested by you.

**Review by ishita-43 — APPROVED** [review]
Ready to merge!

**Comment by kunjgit** [comment]
Thank you  @chakrabortydeep , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
