### PR TITLE
Beat_a_mole

### LINKED ISSUE #3557: [New Game]: Beat_a_mole
### 🎮 Game Request
#3557
The Beat_a_Mole game is a classic arcade game implemented using HTML, CSS, and JavaScript. Players must hit moles that randomly pop up on the screen but if you hit the plant the game will be over. The game features a simple and intuitive user interface with responsive design elements.

### Point down the features

The player should hit the moles in order to get points but if the player hits the plant the game will be over.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by chakrabortydeep**
## PR Description 📜
The Beat_a_Mole game is a classic arcade game implemented using HTML, CSS, and JavaScript. Players must hit moles that randomly pop up on the screen but if you hit the plant the game will be over. The game features a simple and intuitive user interface with responsive design elements.

Fixes
 #3557 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Beat_a_mole

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @chakrabortydeep ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Update your pr files and include the following 
ADD MAIN readme.md file by  updating the entry in that file of your game
add your game image in the asset folder of the gamezone follow naming convention while doing  so

**Review by chakrabortydeep — COMMENTED** [review]
Done with the changes. Please review it now.

**Review by ishita-43 — COMMENTED** [review]
every thing is good but you need to see the readme file of this repo there you will find many games name you need to add your game name there refer other entries for the format and also add one image of your game in asset folder of the repo you will find this folder in the same hierarchy as the readmefile on the gamezone repo 
if you still find yourself confused see other pr and see how they made changes to the readme.md and asset folder

**Comment by chakrabortydeep** [comment]
Everything is updated as said by u.

**Review by ishita-43 — APPROVED** [review]
Seems good!!

**Comment by kunjgit** [comment]
Thank you  @chakrabortydeep , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
