### PR TITLE
new game added path finder puzzle

### LINKED ISSUE #3355: [New game]: Path Finder Puzzle
### 🎮 Game Request

🎮 Game Request: Path Finder Puzzle

Game Logic Description

Path Finder Puzzle is a grid-based game where players must find the shortest path from a start point to an end point. The game uses pathfinding algorithms like A* or Dijkstra's to teach and challenge players with increasing complexity.

1: Initialization:

The game board is a grid of cells.
Players can set the start and end points.
Obstacles can be placed on the grid to create barriers.

2: Player Interaction:

Players can click on cells to set the start point, end point, and obstacles.
A "Find Path" button initiates the pathfinding algorithm.

3: Pathfinding Algorithm:

The game uses pathfinding algorithms like A* or Dijkstra's to find the shortest path.
The algorithm visualizes the pathfinding process step by step.
4: Game End:

The game highlights the found path and displays the path length.
Players can reset the grid to try different configurations.

### Point down the features

Features of the Game

Interactive Grid:

Players can interact with the grid to set start and end points and place obstacles.

Algorithm Visualization:

Real-time visualization of the pathfinding algorithm.
Step-by-step animation showing how the algorithm explores the grid.

Difficulty Levels:

Multiple levels with varying grid sizes and obstacle densities.
Customizable grid for user-generated challenges.

Educational Aspect:

Explanation of the pathfinding algorithms used.
Option to switch between different algorithms to compare their performance.

Reset and Replay:

Button to reset the grid and start a new puzzle.
Option to save and share custom puzzles.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Harleen-786**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #3355 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2024-05-21 111651
Screenshot 2024-05-21 111717

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Harleen-786 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Harleen-786** [comment]
I am contributing on the behalf of GSSoC'24.

**Comment by kunjgit** [comment]
@Harleen-786 resolve merge conflicts !

**Comment by Harleen-786** [comment]
done please check

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Hey @Harleen-786,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Pull request merged**
