### PR TITLE
GhostBuster game is added

### LINKED ISSUE #1480: GhostBuster[New game]:
### 🎮 Game Request

Game logic and basic description The game follows the player's character as a recruit in the Ghostbusters, a team of parapsychologists who pursue and capture ghosts. The game features elements of typical third-person shooters, but instead of a traditional gun, each player is equipped with a Proton Pack, and other technological means of fighting and capturing ghosts

### Point down the features

The Ghost Busters Video Game is a 2009 action-adventure game based on the Ghostbusters media franchise. Terminal Reality developed the Windows, PlayStation 3, and Xbox 360 versions, while Red Fly Studio developed the PlayStation 2, PlayStation Portable, and Wii versions. The game was released after several delays in development and multiple publisher changes

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by shraddha761**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes  #1480 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @shraddha761 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @shraddha761,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by shraddha761** [comment]
@kunjgit please have a look

**Comment by kunjgit** [comment]
Hey @shraddha761 !!
Look at the documentation and tech stacks we are accepting !! 👀

**Comment by kunjgit** [comment]
Thank you  @shraddha761 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
