### PR TITLE
Add new Game Block Building 

### PR DESCRIPTION
**Pull request by bhaveshnegi**
## PR Description 📜
Issue no #3476

Block Building : Focuses on traditional tower-building gameplay without dynamic environments.

Precision and Timing: Emphasizes precision and timing in placing blocks to maintain stability and height.

Stability Challenge: Challenges players to carefully place each block to prevent the tower from collapsing.

Simplicity: Provides a straightforward gameplay experience without additional obstacles or power-ups.

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @bhaveshnegi ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @bhaveshnegi,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by bhaveshnegi — COMMENTED** [review]
Modify Readme

**Comment by kunjgit** [comment]
Thank you  @bhaveshnegi , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
