### PR TITLE
Added Super tetris game

### PR DESCRIPTION
**Pull request by pavitraag**
## PR Description 📜

Fixes # 5002

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in GameZone's README.md
- [X] I have added README.md in my Game folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.
- [X] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @pavitraag ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Please make following changes 
Add  your game entry in main readme. Md file of the gamezone repo
Add your game image in asset folder of the repo follow naming convention while naming the image

**Review by ishita-43 — APPROVED** [review]

**Comment by ishita-43** [comment]
> Please make following changes Add your game entry in main readme. Md file of the gamezone repo Add your game image in asset folder of the repo follow naming convention while naming the image

Ready to merge

**Comment by pavitraag** [comment]
@kunjgit can u please merge it

**Comment by pavitraag** [comment]
@kunjgit can u please merge this so that i can raise my next issue

**Comment by pavitraag** [comment]
@kunjgit please review my pr and merge it

**Comment by kunjgit** [comment]
Thank you  @pavitraag , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
