### PR TITLE
Toast Notification added

### LINKED ISSUE #3983: [New game]: Toast Notification
### 🎮 Game Request

Game logic and basic description : The toast notification game is a simple web-based game where clicking a button generates toast notifications with random messages and types. These notifications appear on the screen and disappear after a short duration.

### Point down the features

Game points : 
1. **Randomized Content**: Generates notifications with random messages and types (info, success, error) for variety.
2. **Auto-Removal**: Notifications disappear after 3 seconds, ensuring a clean UI.
3. **Dynamic Creation**: Clicking the button creates a new notification, enhancing interactivity.
4. **Reusable Functions**: Separate functions handle random message/type generation, making the code modular and easy to extend.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Vipullakum007**
## PR Description 📜
there only just index.html , script.js , style.css . html css for frontend  js for logic
The Toast Notification Game is a simple and interactive web-based game built using HTML, CSS, and JavaScript. Players can generate random toast notifications by clicking the "Show Notification" button. Each notification displays a random message with a specific type and disappears after a short duration.
Fixes #3983 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Toast_Notification

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Vipullakum007 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @Vipullakum007,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by kunjgit** [comment]
Thank you  @Vipullakum007 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Vipullakum007** [comment]
hey @kunjgit @ishita-43 , please check it i have added "Toast Notification game " i have already check there not exist but it says exist ,please review it.

**Pull request closed without merging**
