### PR TITLE
Resolved bug

### LINKED ISSUE #1713: [Bug]: Dice Showdown Game is not working!
### Give a brief about the bug ✍️

The Dice Showdown game added in the project is not working as it is supposed to be. 
I checked the link and found that it's just an image of the game but not the actual game.

Check the screenshot below:-
image

### What is the expected behavior? 🤔

Addition of working game the project will solve this issue!

### Provide step by step information reproduce the bug 📄

I would like to add the Dice game in the project, as the existing game does not works and links to an image, but not the game!

Can you please assign me this issue!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by sabhisharma-ise**
## PR Description 📜
Dice-Showdown-Game will now have an active working link, which was not previously linked properly.
I have re-named the image inside the assets folder, same as the folder name (which was earlier not same as the folder name)!
Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #1713 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have specified the respective issue number for which I have requested to solve the bug.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @sabhisharma-ise ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by sabhisharma-ise** [comment]
@kunjgit hey, can you please review this pr and merge it!
So, I can start working on my next issues for this project!

**Comment by kunjgit** [comment]
if you are renaming folder then you have to make sure you are changing it to everywhere it  is used 👀 !!

**Comment by kunjgit** [comment]
Thank you  @sabhisharma-ise , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
