### PR TITLE
Adding a new game: Guess the flag [gssoc23]

### LINKED ISSUE #2344: [New game]: Guess the game flag. [gssoc23]
### 🎮 Game Request

Game logic and basic description

## **Description 📃** 
- This program is designed to learn the flags of different countries
- So that everyone can identify the flag of different countries and boost your knowledge

### Point down the features

Game points
## **functionalities** 
- Press the start button to start the game
- Drag the flag of respective country and put into their box
- Finally, enjoy the grand congratulation of winning

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by thevirengarg**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
- This game is designed to learn the flags of different countries
- So that everyone can identify the flag of different countries and boost your knowledge
Fixes #2344 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

https://github.com/kunjgit/GameZone/assets/111726483/4f4e5ef3-f0a6-4d02-8483-b3be1b463440

<hr>

## Add your screenshots(Optional) 📸

Guess_the_flag

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @thevirengarg ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by thevirengarg** [comment]
@kunjgit Please review this PR

**Comment by daccdacc** [comment]
Hey @thevirengarg, the Game is already existing on GameZone. We don't accept duplicate games, you can do enhancement in already existing game.

**Comment by kunjgit** [comment]
Thank you  @thevirengarg , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
