### PR TITLE
Added ATLAS game

### LINKED ISSUE #4408: [New game]: Word Atlas
### 🎮 Game Request

World Atlas is an engaging educational game in which the user has to input a place by the last letter of the last shown place in 30 secs and no repetition of the place is required.

### Point down the features

1. Starting place is shown on the screen.
2. User has to input a new game using the last letter in 30 secs.
3. Verification checks are performed for the user input to be a place.
4. The game continues till the user fails to input the place in time.
5. Scores are maintained.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by abckhush**
## PR Description 📜
Added ATLAS game with Indian Cities Edition. 

Fixes #4408

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image
Screenshot 2024-06-12 023938
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Add your game entry in main readme.md file of gamezone refer other entries for format
ADD your images in asset folder of gamezone make sure to follow contribution guidelines while naming the images

**Review by ishita-43 — APPROVED** [review]
Good to go!

**Comment by abckhush** [comment]
Hi, could you pls merge this PR?

**Comment by kunjgit** [comment]
Thank you  @abckhush , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
