### PR TITLE
About us page For anagram checker game 

### LINKED ISSUE #4796: [Enhancement]:  Want to add an about us page for Anagram_Checker_Game and Anime_Clicker
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
I want to add an about us page for these games because this games may be tough to understand for some users 

### Describe the solution you'd like

Solution steps
Creatiing an about us .html file
intergrating it with main game file 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
## PR Description 📜

I have created an about us page for the anagram checker game 

Fixes #4796 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

https://github.com/user-attachments/assets/7d506f62-3b9c-4a2b-9fd8-081fba7a738c

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Ayushmaanagarwal1211 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Ayushmaanagarwal1211** [comment]
Hey @ishita-43 @kunjgit  Please review it and if any changes please let me know

**Review by ishita-43 — APPROVED** [review]
Good to go

**Comment by kunjgit** [comment]
Thank you  @Ayushmaanagarwal1211 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
