### PR TITLE
Floor Thirteen 

### LINKED ISSUE #2477: [New game]: Floor Thirteen
### 🎮 Game Request

Game logic and basic description
You just killed Mr. Johnson. There are multiple levels.

Screenshort:
image

### Point down the features

Demo Vedio:

https://github.com/kunjgit/GameZone/assets/98798977/5b56c91a-9911-442c-b0d4-05f481e1d54c

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Durgesh4993**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #2477
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

Demo Vedio:

https://github.com/kunjgit/GameZone/assets/98798977/5b56c91a-9911-442c-b0d4-05f481e1d54c

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Durgesh4993 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Durgesh4993,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Durgesh4993** [comment]
@kunjgit @gurjeetsinghvirdee Please check it out

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Durgesh4993,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Durgesh4993,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Durgesh4993** [comment]
@kunjgit Please verify it because i have alreay add an image to the assets/images directory and modify the main README.md file.

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Durgesh4993,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Code copied from: **https://github.com/js13kGames/floor-thirteen**
Live View: **https://js13kgames.com/games/floor-thirteen/index.html**

**Pull request closed without merging**
