### PR TITLE
Added event listeners for specific keyboard buttons and implemented the functionality to play music

### PR DESCRIPTION
**Pull request by shubhanshukaintura**
## PR Description 📜

The enhancement aims to improve the user experience of a web-based game by implementing keyboard event listeners for smooth music playback. Currently, users are required to interact with the mouse to trigger music playback, which can disrupt gameplay flow. By adding keyboard event listeners, users will be able to control music playback seamlessly using designated keyboard buttons, eliminating the need for mouse interaction. This enhancement enhances user convenience, contributes to a smoother gaming experience, and aligns with the goal of creating a more immersive gameplay environment.
Issue no. #3102
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot 2024-05-11 140140

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @shubhanshukaintura ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — APPROVED** [review]
LGTM!

**Comment by kunjgit** [comment]
Thank you  @shubhanshukaintura , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by shubhanshukaintura** [comment]
Thank you @kunjgit , looking forward for many more valuable contributions 👍

**Pull request merged**
