### PR TITLE
Dice Showdown Game Added to the Game folder of the repository.

### LINKED ISSUE #9: DICE SHOWDOWN GAME
### Game Description

The Dice Game is an exciting and engaging multiplayer game where two players compete to roll the highest number on their dice. It offers a thrilling experience that combines luck and strategy. The game is designed to entertain and challenge players of all ages.

### Game Logic

The game follows a simple set of rules:

1. Each player rolls a dice, which generates a random number between 1 and 6, ensuring a fair and unpredictable result.
2. The player with the higher number wins the game.
3. If both players roll the same number, the game ends in a tie.
The game provides an intuitive user interface with visually appealing dice images and a prominent heading that announces the winner or a tie. Players can easily continue playing by refreshing the page to generate new random numbers for the dice.

### Point down the features

1. **Multiplayer Gameplay**: The Dice Game allows two players to compete against each other in real-time. Players can take turns rolling the dice and experience the excitement of head-to-head gameplay.

2. **Randomized Dice Rolls:** The game utilizes a random number generator to simulate the roll of the dice. This ensures fairness and unpredictability in each round, adding an element of chance to the gameplay.

These features contribute to an engaging and interactive gaming experience

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Himanshu07-debug**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #9 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Himanshu07-debug ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @Himanshu07-debug 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by Durgesh4993** [comment]
@Himanshu07-debug Could you please send a demo vedio

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
@Himanshu07-debug Could you please add a button for refresh because it give the mose satisfaction to gamer not they refress all time

**Comment by Himanshu07-debug** [comment]
@Durgesh4993 Added Refresh Button.

**Review by Durgesh4993 — APPROVED** [review]
image
image

Game is properly working and no errors in code

**Comment by kunjgit** [comment]
Hey @Himanshu07-debug 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by Himanshu07-debug** [comment]
@kunjgit Sorry, But I do not Understood the game Number you wrote about. Is it the PR number or the Issue number. I will be happy if you will clear my doubt

**Comment by kunjgit** [comment]
Hey @Himanshu07-debug in our Repo's README add your game in the Game section and make sure you don't add number because we are adding games so number might conflict !!
Otherwise it looks great 🔥 !!
image

you have to add game here !!

**Review by kunjgit — CHANGES_REQUESTED** [review]
just add your game in main readme as I have mentioned in comment !! 😃

**Comment by Himanshu07-debug** [comment]
Dear @kunjgit,
I'm deeply grateful for your exceptional guidance and unwavering support throughout this contribution . Thank you for making my first GSSOC experience unforgettable.

**Comment by Himanshu07-debug** [comment]
@kunjgit ,
I hope that I had made the required steps. Is there still any problem in this PR???

**Comment by Himanshu07-debug** [comment]
@kunjgit ,
I hope that I had made the required steps. Is there still any problem in this PR???

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Himanshu07-debug , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
