### PR TITLE
[Bug]:Removing an extra screenshot in assets folder [gssoc23]

### LINKED ISSUE #2541: [Bug]:  Extra screenshot in assets folder [gssoc23]
### Give a brief about the bug ✍️

Description
Two different Screenshots of the game snake and ladder is there in assets folder. 

### What is the expected behavior? 🤔

Description
Delete one of the screenshot from the folder 

### Provide step by step information reproduce the bug 📄

Description
For each game there must be only one screenshot

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by thevirengarg**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
One of the snake and ladder game was removed, so through this PR I am removing screenshot of one of the snake and ladder game from assets folder 
Fixes #2541 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @thevirengarg ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by thevirengarg** [comment]
@kunjgit @Arun9739 @gurjeetsinghvirdee sir, please review this pull request

**Review by gurjeetsinghvirdee — COMMENTED** [review]
This is not a valid contribution towards the gssoc
I will accept this as just open source contribution that you removed extra images but it can't be considered as bug even I can't add level1 for this 
10 points for what just removing 2 images 

Over to you @kunjgit

**Comment by thevirengarg** [comment]
@gurjeetsinghvirdee There is a problem in Name convention of a game, I will fix it and put it under the same branch then you can give me atleast level 1 tag

**Comment by thevirengarg** [comment]
@gurjeetsinghvirdee Please review this pull request, I have added more commits to it

**Comment by kunjgit** [comment]
Thank you  @thevirengarg , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
