### PR TITLE
made tower_of_hanoi game

### PR DESCRIPTION
**Pull request by aasn0119**
## PR Description 📜
**Fixes # 51 (Tower-Of_Hanoi )**
Summary: 
This PR resolves issue #51, which involved creating a new game for Tower of Hanoi. The Tower of Hanoi game is now implemented using HTML, CSS, and JavaScript. The game allows players to move disks between towers following the rules of the puzzle. The PR also includes necessary styling and event handling for a smooth gaming experience.

Description:
This PR addresses issue #51, which involved the development of a new game for Tower of Hanoi. The game is now fully functional and interactive. Users can click on the towers to move disks, ensuring that larger disks are not placed on top of smaller ones.

The code follows best practices, adheres to proper indentation, and includes appropriate comments for clarity. The HTML structure is well-organized, the CSS styling enhances the visual appeal, and the JavaScript logic accurately handles the disk movements and win condition.

Overall, this PR successfully addresses issue #51, adding the Tower of Hanoi game as a new feature to the project. It provides an enjoyable gaming experience and serves as an engaging addition to the project's functionality.

<hr>
 
## Mark the task you have completed ✅

- ✅ I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- ✅ I have performed a self-review of my own code or work.
- ✅ I have commented my code, particularly in hard-to-understand areas.
- ✅ My changes generates no new warnings.
- ✅ I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- ✅ I have added screenshot for website preview in assets/images 
- ✅ I have added entries for my game in main README.md
- ✅ I have added README.md in my folder 
- ❌ I have added working video of the game in README.md (optional)
-  ✅ I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Tower_Of_Hanoi

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by aasn0119** [comment]
Is there any problem with the game??

**Comment by aasn0119** [comment]
@kunjgit, Is there any problem with the game ??

**Review by kunjgit — CHANGES_REQUESTED** [review]
add entries in main README file

**Comment by aasn0119** [comment]
> add entries in main README file

Done 🙂, Please review and tell me if there is any other problem.

**Review by kunjgit — CHANGES_REQUESTED** [review]
still you are missing on marking your game entry in README !!

**Comment by kunjgit** [comment]
do that change and create a PR again 😃 
everything in one time only !!

**Comment by kunjgit** [comment]
Thank you  @aasn0119 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
