### PR TITLE
Added a New Game Valorous_Rabbit

### LINKED ISSUE #231: [New game]: Valorous Rabbit
### 🎮 Game Request

Game logic and basic description
Valorous Rabbit is an adventurous game created using HTML, CSS, and JavaScript, where players take control of a brave rabbit on a mission to save its woodland friends from peril. Here's a description of how the game works:

HTML Structure:
The game interface is built using HTML elements. It typically includes a container div to hold the game elements, a canvas element for rendering the game graphics, score and life counters, and buttons for player interactions.

CSS Styling:
The game elements are styled using CSS to create an appealing visual design. The container div and canvas can be styled with appropriate dimensions and positioning to fit the game screen. The buttons, score, and life counters are styled to be easily readable and visually distinct.

JavaScript Functionality:

Initialization: When the game starts, JavaScript initializes the player's score and life counter to a default value and sets up event listeners to track player input.
Player Movement: JavaScript listens for keyboard inputs or button clicks to control the rabbit's movement. It updates the rabbit's position on the canvas accordingly.
Enemy Generation: JavaScript randomly generates enemies, obstacles, or challenges on the canvas to hinder the rabbit's progress. These may include predators, traps, or obstacles that the player must avoid.
Collision Detection: JavaScript detects collisions between the rabbit and enemies or obstacles. If a collision occurs, the player's life counter decreases, and appropriate feedback is provided.
Scoring: JavaScript tracks the player's score based on their progress and achievements within the game. For example, collecting power-ups or saving friends can increase the score.
Game Over: When the player's life counter reaches zero or the game objective is not achieved within a specified time limit, the game ends. The player's final score is displayed, and they may have the option to restart or quit the game.

### Point down the features

Game points
The player controls the rabbit using keyboard inputs or button clicks. The objective is to navigate the rabbit through various levels or stages, overcoming obstacles and enemies, and rescuing woodland friends along the way. The player must avoid colliding with enemies or traps to prevent their life counter from depleting. Collecting power-ups or bonuses can enhance the rabbit's abilities or provide extra points. The player's goal is to achieve the highest score and complete the game with the maximum number of rescued friends.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by uzmaansari23**
## PR Description 📜
Valorous Rabbit is an adventurous game created using HTML, CSS, and JavaScript, where players take control of a brave rabbit on a mission to save his life from a dangerous animal. The issue that I resolved is that I added a new game to the Website.

Fixes #231

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @uzmaansari23 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@uzmaansari23 you are not supposed to change the main index file.

**Comment by uzmaansari23** [comment]
@Arun9739  I didn't understand the changes you are asking for but I need to change main index file for adding the new game  sir.

**Comment by uzmaansari23** [comment]
@Arun9739 okay I'll commit the changes soon.😊

**Comment by uzmaansari23** [comment]
I've modified the changes please review it

**Comment by uzmaansari23** [comment]
Is it okay or should i generate a new pr?

**Comment by uzmaansari23** [comment]
I've made a new pr regarding the requested changes.

**Comment by kunjgit** [comment]
Thank you  @uzmaansari23 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
