### PR TITLE
Added a game "Harmony Mixer"

### LINKED ISSUE #4295: [New game]: Song Visualizer Game
### 🎮 Game Request

This Game allows users to upload a song file, visualize its frequency data, and manipulate specific frequencies at various points. Users can see a graphical representation of the sound's frequencies and interact with them to change the audio output.

Screenshot 2024-06-06 at 7 07 25 PM

### Point down the features

File Upload: Allow users to upload their song file.
Audio Context Setup: Create an audio context and set up the audio nodes for playback and manipulation.
Analyser Node: Use an AnalyserNode to visualize the audio frequencies.
Gain Nodes: Create multiple GainNode elements to control the gain (volume) at specific frequencies.
UI for Manipulation: Provide a user interface to manipulate the gain at various frequencies.
Update Audio: Apply the changes in real-time as users interact with the UI.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by sidharth2829**
## PR Description 📜

Added Game "Harmony Mixer"
Fixes #4295 

<hr>
 
## Mark the task you have completed ✅

- [ x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [x ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x ] I have added screenshot for website preview in assets/images 
- [ x] I have added entries for my game in main README.md
- [ x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2024-06-09 at 12 43 43 AM

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @sidharth2829 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @sidharth2829,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @sidharth2829,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @sidharth2829,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by sidharth2829** [comment]
@kunjgit , i can't understand what changes i am supposed to make. Please clarify.

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @sidharth2829,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by kunjgit** [comment]
Thank you  @sidharth2829 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @sidharth2829,
You need to make the following changes:
  - Please create a new folder inside the "Games" folder.
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Pull request closed without merging**
