### PR TITLE
Guess the celebrity using two pictures

### LINKED ISSUE #2568: [New game]: guess the movie star using two pictures
### 🎮 Game Request

# Game logic and basic description
Players receive two pictures related to the star and guess they have to guess their name.

### Point down the features

# Game points

- A successful guess increments the score by +1

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by amelia2802**
## PR Description 📜
Created a JavaScript game where players have to guess the correct celebrity based on the given images.
- Two images containing hints will be displayed on the screen.
- Players will also see four random options containing names of celebrities.
- Click on the option that you think matches the correct celebrity name.
- If your guess is correct, you will earn 5 points and proceed to the next level.
- If your guess is wrong, you can try again until you complete all the levels.
- Your final score will be displayed at the end of the game.

Fixes #2568 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Guess_The_Celeb

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @amelia2802 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @amelia2802,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @amelia2802,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @amelia2802,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @amelia2802,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Deepanshu0703** [comment]
Hey @amelia2802 add your folder link and game name in the main README.md

**Comment by amelia2802** [comment]
Hi @Deepanshu0703, Thank you for the insight but I believe I've added my game folder to the main README table, still the change request coming there. It would be great if you could review the PR and point me out what am I, lacking!

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM 🍁

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @amelia2802,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by kunjgit** [comment]
Thank you  @amelia2802 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
