### PR TITLE
Shrek Vs Wild game added

### LINKED ISSUE #3531: [New game]: " Shrek Vs Wild " game added
### 🎮 Game Request

This is the remake of classic Zombie apocalypse game with a twists of Shrek. In this game, Shrek is the main protagonist who fights against the Zombies and other Monsters . This game provides you an experience  of classical Zombie game with an interesting UI & Sound tracks. With Shrek , it will be fun ride to fight against the Monsters. Enjoy my game .

### Point down the features

1. By using the arrow keys , move the main character and defend him from the monsters.
2. By using the space key , you can shoot  or fight with the monsters.
3. Game Music intensifies your gaming experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by shuvadeepmondal**
## PR Description 📜

I have added a my game named Shrek Vs Wild , this is the remake of classic Zombie apocalypse game with a twists of Shrek. In this game, Shrek is the main protagonist who fights against the Zombies and other Monsters. This game offers a very user friendly interface, interesting music and game experience.
Fixes #3531 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @shuvadeepmondal ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @shuvadeepmondal,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by shuvadeepmondal** [comment]
Sir I created everything . It is changed . By mistake, i was tick wrong checkboxes

**Comment by shuvadeepmondal** [comment]
Sir I have completed my all tasks which are provided by GameZone. By mistake, I filled the wrong checkboxes

**Comment by shuvadeepmondal** [comment]
@kunjgit Sir please review once again

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @shuvadeepmondal,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by shuvadeepmondal** [comment]
I have done it once . It's showing on my Pc.

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @shuvadeepmondal,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @shuvadeepmondal,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by shuvadeepmondal** [comment]
Sir now modified the main README.md file and Photo added .

**Comment by shuvadeepmondal** [comment]
Sir please help me to resolve this problem . I have changed Readme.md file and added a photo

**Comment by kunjgit** [comment]
@shuvadeepmondal resolve the merge conflicts !

**Comment by shuvadeepmondal** [comment]
Okay Sir

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @shuvadeepmondal,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by shuvadeepmondal** [comment]
Sir I have resolved the merge conflicts . Now What to do Sir

**Comment by shuvadeepmondal** [comment]
Please Help me Sir

**Comment by shuvadeepmondal** [comment]
So should I send one another pr with updating the Readme and adding photo on main repo??
Please instruct me Sir.

**Comment by kunjgit** [comment]
@shuvadeepmondal still the merge conflicts are not resolved !

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @shuvadeepmondal,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by shuvadeepmondal** [comment]
Done it again @kunjgit Sir Please Merge

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @shuvadeepmondal , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
