### PR TITLE
brick and ball added

### LINKED ISSUE #3619: [New game]: Brick n Ball
### 🎮 Game Request

It is the classic game in which a ball destroys the bricks displayed in the game. And we have to save the ball when it comes down on the floor by moving the slider.

### Point down the features

-> It will record the game points according to bricks destroyed.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Yashgabani845**
## PR Description 📜

this is simple brick and ball game which   i had coded few months back  and i am very happy to contribute it
back to point :
this is brick and ball game code 
i have added game screeenshot,game folder, added in json file and changed README.md file
Fixes #3619 
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot (74)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Yashgabani845 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
@Yashgabani845 resolve merge conflicts !

**Comment by Yashgabani845** [comment]
@kunjgit  resolved

**Comment by Yashgabani845** [comment]
@kunjgit  checkout my PR i want to work on another isue of your repo that iassigned to me

**Comment by kunjgit** [comment]
Thank you  @Yashgabani845 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Yashgabani845** [comment]
@kunjgit  please add gssoc label otherwise my PR will not  be counted

**Pull request merged**
