### PR TITLE
Pop the bubbles

### LINKED ISSUE #4100: [New game]:  Pop the Bubbles
### 🎮 Game Request

Pop The Bubbles!" is a fast-paced, retro-style game where your reflexes and number recognition skills are put to the test. You have 60 seconds to pop as many bubbles as possible, focusing on bubbles with the current target number for bonus points. Perfect for players of all ages, it's easy to learn and endlessly fun!
image

### Point down the features

Your reflexes and number recognition skills are put to the test.
You have 60 seconds to pop as many bubbles as possible.
Each time you pop a bubble, a new target number appears. Focus on popping bubbles with the current target number for bonus points!
Easy to learn and perfect for players of all ages

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by samarsajad**
## PR Description 📜
Pop the Bubbles
## Description
"Pop The Bubbles!" is a fast-paced, retro-style game where your reflexes and number recognition skills are put to the test. You have 60 seconds to pop as many bubbles as possible, focusing on bubbles with the current target number for bonus points. Perfect for players of all ages, it's easy to learn and endlessly fun!

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @samarsajad ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by samarsajad** [comment]
Please review my pull request @kunjgit

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @samarsajad,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @samarsajad,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by samarsajad** [comment]
Please review my pull request @kunjgit

**Comment by samarsajad** [comment]
Hey, I made the changes you asked for, can you please review my pull request @kunjgit

**Comment by samarsajad** [comment]
Hey, I made the changes you asked for, can you please review my pull request. Also fixed the merge conflicts @kunjgit

**Comment by samarsajad** [comment]
Hey, can you please let me know if there is something else that I need to change @kunjgit

**Comment by samarsajad** [comment]
Hey I resolved the conflicts. can u please review it @kunjgit

**Review by ishita-43 — APPROVED** [review]
GOOD TO GO!!

**Comment by kunjgit** [comment]
Thank you  @samarsajad , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
