### PR TITLE
Addition of home icon to various games

### PR DESCRIPTION
**Pull request by KanchandeepK**
## PR Description 📜

As we click on one of the listed games we need to click on the arrow to get back to home .So, I have included the home icon to various games except few left as I am not able to load the games on my laptop.
Fixes # 1620

<hr>
 
## Mark the task you have completed ✅

Addition of home icon completed 

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 
Issue to be addressed
gameissue
After resolving issue 
home-icon

--- 
<br>

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @KanchandeepK ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @KanchandeepK,
Please make sure to link the relevant issue using the appropriate syntax, such as "#issueNumber" 👀. 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by kunjgit** [comment]
Thank you  @KanchandeepK , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by KanchandeepK** [comment]
@kunjgit Do I need to again create a pull request as I have mentioned the correct issue .

**Comment by 5h0ov** [comment]
@KanchandeepK  dont keep a space between the # and the issue number, otherwise it won't count.

**Comment by KanchandeepK** [comment]
@5h0ov is it required to add the screenshot in assets or is it fine.

**Pull request closed without merging**
