### PR TITLE
Add Pac-Man Doodle Game

### LINKED ISSUE #801: [New game]: PAC-MAN Doodle
### 🎮 Game Request

Pac-Man is a classic arcade game where players control a character named Pac-Man to navigate through a maze filled with dots and avoid ghost enemies. The objective is to eat all the dots in the maze while avoiding the ghosts. Power pellets are available to temporarily turn the tables, allowing Pac-Man to eat the ghosts. The game ends when all the dots are eaten, or when a ghost captures Pac-Man.

### Point down the features

- Classic gameplay inspired by the original Pac-Man arcade game.
- Use arrow keys or touch gestures to control Pac-Man's movement.
- Engaging maze layout with dots and power pellets.
- Colorful graphics and visually appealing game elements.
- Dynamic ghost AI that presents challenges and strategies.
- Score tracking to keep a record of the player's progress.
- Audio effects and background music for an immersive experience.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Poonam-13**
## PR Description 📜

Pac-Man is a classic arcade game where players control a character named Pac-Man to navigate through a maze filled with dots and avoid ghost enemies. The objective is to eat all the dots in the maze while avoiding the ghosts. Power pellets are available to temporarily turn the tables, allowing Pac-Man to eat the ghosts. The game ends when all the dots are eaten, or when a ghost captures Pac-Man.
Fixes #801 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots 📸
Pac - Man

## Add your working video 📸

https://github.com/kunjgit/GameZone/assets/103939318/cd5140a7-5346-4fdb-a65b-1603f9c72b02

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Poonam-13 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
mark you entry in main README file

**Comment by Poonam-13** [comment]
I've added. Now you can check it.

**Comment by kunjgit** [comment]
we are already having this game on GameZone !!

**Comment by kunjgit** [comment]
Thank you  @Poonam-13 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
