### PR TITLE
Snake game page's color theme is changed to enhance the page's beauty

### LINKED ISSUE #3366: [Enhancement]: Snake game page's design should be improved
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

I want to improve the design of the page : https://kunjgit.github.io/GameZone/Games/Snake_Game/

### Describe the solution you'd like

Solution steps

 

- [x] Change the theme color of the game
- [x]  Change the alignment of the elements in the page

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Tasnuva12**
## PR Description 📜

I have fixed the color theme of the page and changed the alignment of elements a little bit 
Fixes #3366

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Tasnuva12 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
@Tasnuva12 resolve the conflicts !

**Comment by Tasnuva12** [comment]
Hello  I changed the game's theme that's why it is showing conflict. should I not change the game's  css file?
image

**Comment by kunjgit** [comment]
@Tasnuva12 the issue is there is some changes after you and you are having changes on the same line that causes merge conflicts make sure you are learning it how to resolve that !

**Comment by kunjgit** [comment]
Hey @Tasnuva12,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by kunjgit** [comment]
Thank you  @Tasnuva12 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
