### PR TITLE
Target Mstery

### PR DESCRIPTION
**Pull request by Ks103**
## PR Description 📜

- this game is developed by html,css and js tech stacks and you can play it easily by moving your mouse to upward and hit the target!

- Players take turns throwing or shooting projectiles, such as darts, arrows, or bullets, towards the target. 
- The projectiles are designed to hit the board, ideally landing as close to the bullseye as possible.  
<br>

## **How to play? 🕹️**

- Drag the cursor upward so that you are able to hit the target.
- If you hit the target it gives you achievement note and if lose so you miss.
- Enjoy this game.
Fixes # 225

<hr>
 
## Mark the task you have completed ✅

- ✅ I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- ✅ I have performed a self-review of my own code or work.
- ✅ I have commented my code, particularly in hard-to-understand areas.
- ✅My changes generates no new warnings.
- ✅I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- ✅ I have added screenshot for website preview in assets/images 
- ✅ I have added entries for my game in main README.md
- ✅ I have added README.md in my folder 
- [x ] I have added working video of the game in README.md (optional)
- ✅I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2023-05-24 094634

--- 
<br>

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Ks103 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Ks103** [comment]
@kunjgit please verify and merge my pull request if there are any changes let me know.

**Review by Durgesh4993 — APPROVED** [review]
https://github.com/kunjgit/GameZone/assets/98798977/dcfa03c4-ce72-4889-a768-f050ced00184

**Comment by Durgesh4993** [comment]
Code has no errors and game is running smothly but i'll request to @Ks103 please add a screanshort on asset section

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Add a score card how much they scored

**Comment by Ks103** [comment]
I have added the ss , I request you to please approve my pr and merge it.

**Comment by kunjgit** [comment]
Hey @Ks103 Looks good just make sure during the time you make PR tag issue properly so ...
make sure you add your game entry on main README file and create PR again !!

**Comment by kunjgit** [comment]
Thank you  @Ks103 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
