### PR TITLE
fix: Made the newsletter section responsive on footer

### LINKED ISSUE #5068: [Bug]: The newsletter section is not responsive on footer
### Give a brief about the bug ✍️

Description

- The newsletter section is not responsive on footer

Screenshot 2024-08-02 140517

### What is the expected behavior? 🤔

Description

- The newsletter section should be responsive for good user-experience.

### Provide step by step information reproduce the bug 📄

Description

- I will use css media-queries & bootstrap classes in order to resolve this issue.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by vishanurag**
## PR Description 📜

Fixes #5068 

- Made the newsletter section of footer responsive in mobile-view.

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in GameZone's README.md
- [ ] I have added README.md in my Game folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.
- [ ] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2024-08-02 144856

_Please review & merge my pull-request under GSSoC'24_
--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @vishanurag ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by vishanurag** [comment]
@kunjgit @ishita-43 please review & merge my pull-request under GSSoC'24

**Review by ishita-43 — APPROVED** [review]

**Comment by vishanurag** [comment]
Can you please also add level1 label on this pr

**Comment by kunjgit** [comment]
Thank you  @vishanurag , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
