### PR TITLE
[New game ] : technical  mind game added

### LINKED ISSUE #3435: [New game]: Technical Mind game
### Game logic and basic description
it is similar to mind game which we usually play but there is one more enhancement 
we will use pictures of  diiferent technologies and frameworks we use in software development like node js , express,react,html,vite ,vue etc.

### basic look of this game will be :
Screenshot (56)

### Game points
each right guess has +5 point and each wrong guess has -1 point 
and each level has fix number of oves which user can play to clear current round and go to next round 

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Yashgabani845**
## PR Description 📜
 this game is similar to normal memory game but the new thing is that this game has images of diiferent web frameworks and languages rather than that typical animalos and birld pictures it is quite intereting for developers to play this game

Fixes #3435 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot (60)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Yashgabani845 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Yashgabani845,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Yashgabani845,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by Yashgabani845 — COMMENTED** [review]
it was added in newly created folder but i think issue was because of it was not named correctly i have edited it

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
@Yashgabani845 resolve the merge conflicts !

**Comment by Yashgabani845** [comment]
I have resolved all the conflicts

**Comment by kunjgit** [comment]
@Yashgabani845 you are still having merge conflicts in gamesData.json and README.md as well !

**Pull request merged**
