### PR TITLE
Virtual Pet Game added

### LINKED ISSUE #3555: [New game]: Virtual Pet Game
### 🎮 Game Request

Game logic and basic description:This is a one player virtual pet simulator I am coding without assistance. It will be using loops, event listeners, timers and animations.

### Point down the features

Game points:You have to make the pet survive.

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Nayanika1402**
## PR Description 📜

Fixes #3555 
 
## Mark the task you have completed ✅

- [ ✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅ ] I have performed a self-review of my own code or work.
- [ ✅ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✅ ] My changes generates no new warnings.
- [ ✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅ ] I have added screenshot for website preview in assets/images 
- [ ✅ ] I have added entries for my game in main README.md
- [ ✅ ] I have added README.md in my folder 
- [ ✅ ] I have specified the respective issue number for which I have requested the new game.

## Add your screenshots(Optional) 📸

Virtual_Pet_Game

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Nayanika1402 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
@Nayanika1402 resolve merge conflicts !

**Comment by Nayanika1402** [comment]
@kunjgit Resolved the conflicts

**Comment by kunjgit** [comment]
@Nayanika1402 resolve merge conflicts!

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Nayanika1402 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
