### PR TITLE
Classic 8 Ball Pool Game added

### LINKED ISSUE #352: 8 Ball pool
### 🎮 Game Request

Game logic and basic description:  An 8 ball pool game is a popular cue sport game played on a rectangular table with six pockets. The objective of the game is to use a cue stick to strike the white cue ball, aiming to pocket the colored balls (stripes or solids) and finally potting the black 8 ball to win.
The game typically involves two players taking turns. Each player is assigned a set of balls (stripes or solids) that they must pocket. The player who pockets all their designated balls first and legally pots the black 8 ball wins the game.

### Point down the features

Game points: sound effects, mose click movements , good background, good graphics

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by tanvigarg264**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
I have added a new game "Classic 8 Ball Pool Game
Fixes #352

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot (29)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @tanvigarg264 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
don't make changes in main index file and also make sure you mark your entries in main README

**Comment by tanvigarg264** [comment]
I have made the changes. plz review

**Comment by kunjgit** [comment]
it is still conflicting with main index create PR again by following proper guidelines

**Comment by kunjgit** [comment]
Thank you  @tanvigarg264 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by tanvigarg264** [comment]
Hey...should I make changes in index file or the game is added

**Pull request closed without merging**
