### PR TITLE
Added Etch a Sketch 2 

### LINKED ISSUE #4484: [New game]: Etch a Sketch 2
### 🎮 Game Request

Game logic and basic description:
Etch-a-Sketch is a delightful web-based drawing game that combines simplicity and creativity, inspired by the classic Etch-a-Sketch toy. This interactive game allows users to create vibrant patterns and drawings on a grid, offering various modes for different artistic expressions. The game's intuitive interface and dynamic functionality make it an engaging tool for users of all ages.

Game Logic:
The core of Etch-a-Sketch lies in its grid-based canvas. Users can dynamically adjust the grid size, with each cell of the grid serving as a pixel for drawing. The game features three main drawing modes: Monochromatic, Random Colors, and Darken. Each mode offers a unique way to interact with the grid and create distinct visual effects.

### Point down the features

Grid Creation:

Grid Size: Users can set the grid size by clicking the "Set Grid Size" button. The grid can be adjusted up to a maximum of 100x100 cells.
Cell Dimensions: The dimensions of each cell are dynamically calculated based on the grid size, ensuring the entire grid fits within a 600x600 pixel container.

Drawing Modes:

1: Monochromatic Mode: In this mode, hovering over grid cells colors them red. It is the simplest mode, ideal for straightforward and bold designs.
2: Random Colors Mode: This mode adds an element of surprise and vibrancy. Each cell changes to a randomly generated RGB color when hovered over, creating a colorful and dynamic drawing experience.
3: Darken Mode: This mode introduces a shading effect. Initially, all cells are black with 0% opacity. Hovering over a cell increases its opacity incrementally by 10%, gradually darkening the cell until it reaches full opacity.

Features:

1->Dynamic Grid Adjustment: Users can easily change the grid size to accommodate detailed or broad designs.
2->Multiple Drawing Modes: Three distinct modes provide versatility in drawing styles and effects.
3->Interactive Hover Effects: Real-time color changes and shading effects create an engaging and responsive drawing experience.
4->User-Friendly Interface: The game features a simple and intuitive interface with clearly labeled buttons and a clean design, making it accessible to all users.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by TexZ-GenZ**
## PR Description 📜

This Pull Request addresses issue by enhancing the existing Etch-a-Sketch game with new features and improvements. It introduces modes for random colors and gradual darkening, enriching the user experience beyond the traditional Etch-a-Sketch concept.

Fixes #4484 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Etch_a_Sketch_2

--- 
<br>

## Thank you so much for contributing to our repository 💗.

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @TexZ-GenZ ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Please enter your game in main readme,md file and refer other entries for format

**Comment by TexZ-GenZ** [comment]
Game added to main README . Please verify.

**Review by ishita-43 — APPROVED** [review]
good to go!!

**Comment by kunjgit** [comment]
Thank you  @TexZ-GenZ , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
