### PR TITLE
NEW GAME: HIT YOUR FRIEND

### LINKED ISSUE #3726: [New game]: HIT YOUR FRIEND
### 🎮 Game Request

There will be 2 players and 1 ball. Each player will alternatively get a chance to hit the other player with the ball with buildings being an obstacle. The one who hits the other first, wins!

### Point down the features

1. You may drag the ball more to increase its velocity.
2. The buildings shall serve as your obstacles.
3. You may reload the page to bring changes into the heights of the buildings!
4. Simple, easy to play, two players game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by 18Venus**
## PR Description 📜
I have added a new game: "Hit Your Friend". There will be 2 players and 1 ball. Each player will alternatively get a chance to hit the other player with the ball with buildings being an obstacle. The one who hits the other first, wins! 

You may drag the ball more to increase its velocity. The buildings shall serve as your obstacles. You may reload the page to bring changes into the heights of the buildings!

Fixes #3726

<hr>
 
## Mark the task you have completed ✅

- [x]  I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Once you open the game:
Hit-Your-Friend

Once a player wins:
Hit-Your-Friend-winner

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @18Venus ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @18Venus,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by 18Venus** [comment]
Have made the changes. Pls check. Thank you so much!

**Comment by kunjgit** [comment]
@18Venus resolve the merge conflicts !

**Comment by 18Venus** [comment]
Please check once. Thank you

**Comment by kunjgit** [comment]
@18Venus resolve the merge conflicts !

**Comment by kunjgit** [comment]
Thank you  @18Venus , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @18Venus,
You need to make the following changes:
  - Please create a new folder inside the "Games" folder.
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @18Venus , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
