### PR TITLE
Added Remember Color Game #622

### PR DESCRIPTION
**Pull request by NikhilCode12**
## PR Description 📜

Remember Color game is a game which helps you increase your mind thinking abilities, it tests your remembering skills. A color with a sound associated with it shows when the game starts, it will then continue to create a random sequence until the user hits the wrong color or the game is finally over, with better interest, game has a level counter so that the user keens to play the game forever.

Fixes # 622

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by NikhilCode12** [comment]
Thanks @kunjgit, it feels great contributing.

**Comment by Arun9739** [comment]
@NikhilCode12 plz make entry of your game in main README file.

**Comment by NikhilCode12** [comment]
Hey @Arun9739 , @kunjgit successfully made a PR to the pending #624 issue. It feels great contributing to the repo.

**Comment by Arun9739** [comment]
@NikhilCode12 Plz make entry of your game into main README.

**Comment by kunjgit** [comment]
please follow proper guidelines and make PR again

**Comment by kunjgit** [comment]
Thank you  @NikhilCode12 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
