### PR TITLE
[GSSOC23]: Add TicTacToe with AI

### LINKED ISSUE #1804: [New game]: Want to create a Tic-Tac-toe game with AI
### 🎮 Game Request

I want to add tictactoe game with AI mode and user mode both.
Rules for the game are same as normal TicTacToe

### Point down the features

It is made using React
Rules are same as normal TicTacToe
AI is made using minimax algorithm

### Select program in which you are contributing

GSSOC 23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by AyishikD**
## PR Description 📜
Created TicTacToe AI with Minimax algorithm and react
Fixes #1804 

Screenshot:
image

 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @AyishikD ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @AyishikD,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @AyishikD,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by AyishikD** [comment]
> Hello @AyishikD, You need to make the following changes:
> 
> * Please modify the main README.md file.
> * Please add an image to the assets/images directory.
> 
> Hoping that you will make those changes soon 🚀

Completed

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @AyishikD,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by AyishikD** [comment]
@kunjgit Both completed

**Comment by kunjgit** [comment]
we already have this game on GameZone make sure you come up with unique new idea !! 👀

**Comment by kunjgit** [comment]
Thank you  @AyishikD , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
