### PR TITLE
Added about paragraph (Enhancement)

### LINKED ISSUE #3293: [Enhancement]: Adding About Section for GameZone
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Adding an "About" section to your website is vital for informing users about the purpose and offerings of your platform. This section serves as a gateway for users to understand what your website is all about, who is behind it, and what they can expect to find. By providing a brief overview of your website's mission, vision, and objectives, users can quickly grasp its value proposition and relevance to their interests.
Including any unique features, services, or content that sets your website apart further entices users to explore and engage with your platform. Overall, the "About" section plays a crucial role in defining your website's identity and encouraging user interaction and participation.

### Describe the solution you'd like

1. Define the purpose.
2. Gather content.
3. Choose a format.
4. Select visuals.
5. Design layout.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by jency1**
## PR Description 📜

Added about paragraph for informing users about the purpose and offerings of the platform. This section serves as a gateway for users to understand what your website is all about.

Fixed #3293
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have specified the respective issue number for which I have requested the enhancement.

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @jency1 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by jency1** [comment]
Please add the level of the issue.

**Review by kunjgit — APPROVED** [review]
LGTM!

**Comment by kunjgit** [comment]
Thank you  @jency1 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by jency1** [comment]
@kunjgit  Please assign this PR to me.

As It is necessary to assign so that I can get this PR on leaderboard.
This PR is already merged and labels are also mentioned, so please assign this PR to me as soon as possible.

Thank you!

**Pull request merged**
