### PR TITLE
Number Guessing Game is added

### LINKED ISSUE #4788: [New game]: Number Guessing Game
### 🎮 Game Request

Game logic and basic description

https://github.com/kunjgit/GameZone/assets/138589633/f6340e64-d76a-47f2-b005-d8960546c31d

### Point down the features

Game points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Ishitamukherjee2004**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #4788 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

https://github.com/kunjgit/GameZone/assets/138589633/d1ba961a-be77-46cb-8f25-8fd7a60890ea

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Ishitamukherjee2004 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Ishitamukherjee2004** [comment]
@kunjgit @ishita-43 
please review the pr and merge it.

**Comment by Ishitamukherjee2004** [comment]
@kunjgit @ishita-43 Please review the pr and reply.................if you are not replying then why did you assign me the issue?? Why did you waste my time if you are not reviewing the pr

**Review by ishita-43 — COMMENTED** [review]
Sorry for late review 
You need to make these changes  in your PR 
Add your game entry into readme. Md file of the gamezone repo
Add your game image in  the assets folder of the repo follow naming convention for image

**Comment by Ishitamukherjee2004** [comment]
@ishita-43 I have updated it please check

**Comment by ishita-43** [comment]
> @ishita-43 I have updated it please check

Also add your game name in main readme.md file of the gamezone follow other entries for the format you will find this in same hierarchy as the assets folder there you need to update that file with your entry of game

**Comment by Ishitamukherjee2004** [comment]
@ishita-43 File is updated pls check

**Review by ishita-43 — APPROVED** [review]
Good to go

**Review by ishita-43 — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Ishitamukherjee2004 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
