### PR TITLE
[Enhancement]: Town_Rise_Game Redesign and Responsive fixed

### LINKED ISSUE #4634: [Enhancement]: `Town_Rise_Game` Redesign and Responsive
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

`Town_Rise_Game` game cannot proper ui and reponsive .
please assign me .

### Describe the solution you'd like

 
Screenshot from 2024-06-20 21-49-32

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by sivaprasath2004**
Hello @kunjgit  @ishita-43 ,
## PR Description 📜

[Enhancement]: Town_Rise_Game Redesign and Responsive fixed 

Fixes #4634 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

### Before
 
Screenshot from 2024-06-20 21-49-32

### After

Macbook-Air-127 0 0 1

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by sivaprasath2004** [comment]
Hello @ishita-43 , @kunjgit  please merge this branch

**Comment by sivaprasath2004** [comment]
Hello @ishita-43 , @kunjgit  please merge this branch

**Review by ishita-43 — APPROVED** [review]
Good to go!

**Comment by kunjgit** [comment]
Thank you  @sivaprasath2004 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
