### PR TITLE
Improved Tennis HUD and improved the CSS in Tennis

### LINKED ISSUE #3378: [Enhancement]: Tennis
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The score HUD for  the players is covering some part of the court, furthermore, the score below the court looks ugly.
image

### Describe the solution you'd like

I will do the following:

Remove the scores on top
Make the scores below, as standalone numbers, for better visual

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by VijaySamant4368**
## PR Description 📜

I improved the Heads Up DIsplay for the score system. I also commented some CSS code, which I think is serving no purpose. Please check the same.
Fixes #3378

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @VijaySamant4368 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by VijaySamant4368** [comment]
Please add the label for GSSoC 2024, and the level of the issue.
Thanks

**Review by kunjgit — APPROVED** [review]
LGTM!

**Comment by kunjgit** [comment]
Thank you  @VijaySamant4368 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
