### PR TITLE
New Game-Color_Blast

### LINKED ISSUE #3451: [New game]: Color Blast
### 🎮 Game Request

Game logic and basic description
Color Blast is an exciting web-based game created using HTML, CSS, and JavaScript. The game is set in a vibrant, fast-paced environment where the player controls an object that must navigate left and right by dodging and firing at incoming threats. The game emphasizes quick reflexes and strategic movement, providing an engaging experience for players of all ages.

### Point down the features

Game points
1.Implement lives in the game, means when you get hit you lose a live.
2.Can pause the game by clicking on the screen.
3.Have live score by which you can compete with your friends.
4.Require quick reflexes to dodge as well as fire bullets.
5.Very engaging and fun game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by AtharvaShinde253**
## PR Description 📜

New Game-Color_Blast
When you scroll the game it is provided with the rules of the game in which you have to fire as well as dodge bullets.
Implement lives in the game, means when you get hit you lose a live.
Can pause the game by clicking on the screen.
Have live score by which you can compete with your friends.
Fixes #3451

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Color_Blast

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @AtharvaShinde253 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @AtharvaShinde253,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by AtharvaShinde253** [comment]
> Hello @AtharvaShinde253, You need to make the following changes:
> 
> * Please modify the main README.md file.
> 
> Hoping that you will make those changes soon 🚀

I have updated the main readme should i raise another PR for the changes?

**Comment by kunjgit** [comment]
Thank you  @AtharvaShinde253 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @AtharvaShinde253,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Pull request merged**
