### PR TITLE
[GSSoC'23] Hunt Card Game Completed

### LINKED ISSUE #2741: [Enhancement]: Hunt Your Card Game
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

- Images are not shown properly
- Cards are not kept their right position and not aligned

https://github.com/kunjgit/GameZone/assets/114330097/4bceb2aa-3bb8-455a-a95a-f2a30c0df441

### Describe the solution you'd like

Solution steps

- Setting the links of the images.
- Adding a good ui for the users.
- Adding winning and losing sounds to make it more interactive.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## PR Description 📜
Enhancement in Hunt Card Game

Fixes #2741 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

https://github.com/kunjgit/GameZone/assets/114330097/00479ee9-11be-4208-818c-dff1d9afdc99

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Avdhesh-Varshney ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by gurjeetsinghvirdee — APPROVED** [review]
From next time if you make a PR like this adding spacing or some type of alignment fix leads to ban you from leaderboard before the ending of this program 🚨

**Comment by kunjgit** [comment]
Thank you  @Avdhesh-Varshney , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Avdhesh-Varshney** [comment]
> From next time if you make a PR like this adding spacing or some type of alignment fix leads to ban you from leaderboard before the ending of this program 🚨

@gurjeetsinghvirdee 
This game pictures are not shown earlier as i have already mentioned in the issue and also mentioned the alignment of the cards are not proper. 
And for spacing, i have just format the code in vs code to make it readable only. Next time, i will not formatting the code. 
So, please add level2 on this pr.
And requested to open a issue 2739.
Thanks for the remainder !

**Pull request merged**
