### PR TITLE
[Enhancement]: Whack a Mole : Game's start button's style should be modified and there should be a message after starting the game 

### LINKED ISSUE #4120: [Enhancement]: Whack a Mole : Game's start button's style should be modified and there should be a  message after starting the game
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

-I want to modify the button's style
-I want to add some messages so that user can understand when the game has been started and when it's over

### Describe the solution you'd like

- Go to the css file and change the button's style
- -Go to the js file and change the functionality of the page 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Tasnuva12**
## PR Description 📜

I have added game sound and some styling to the start button
Fixes #4120

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Tasnuva12** [comment]
hello, I have resolved all the conflicts. Will you please check my PR?

**Review by ishita-43 — APPROVED** [review]
Good to go!! ⚘

**Comment by Tasnuva12** [comment]
> Good to go!! ⚘

the issue for this pr was labelled level 2 , so doesn't that mean the pr should also be a level 2  task?

**Comment by ishita-43** [comment]
> > Good to go!! ⚘
> 
> the issue for this pr was labelled level 2 , so doesn't that mean the pr should also be a level 2 task?

The label on issues are assigned automatically based on the tag placed eg[Enhancement]
Later depending on the change made, and impact made labels are decided for small enhancement we place pr on label 1

**Comment by kunjgit** [comment]
Thank you  @Tasnuva12 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
