### PR TITLE
[New game]: Dot dash

### LINKED ISSUE #4553: [New game]:  Dot dash
### 🎮 Game Request

The game involves clicking on randomly appearing dots within a limited time to earn points. The speed of dot appearances increases as the player's score increases, making the game progressively challenging.

### Point down the features

Game points

fast-paced, 1-minute clicking game where players aim to catch as many dots as possible before time runs out, with the game's difficulty ramping up as they score higher.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
## PR Description 📜

Added a new game Dot_Dash

Fixes #4553

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @aditya-bhaumik ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by aditya-bhaumik** [comment]
@ishita-43 please review my pull request

**Comment by aditya-bhaumik** [comment]
@ishita-43 i have resolved the conflicts please review my pull request

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Place your game image in a asset folder of the gamezone repository and follow naming convention while naming your image

**Comment by aditya-bhaumik** [comment]
@ishita-43 i have added the image in the asset folder

**Comment by aditya-bhaumik** [comment]
@ishita-43 i have resolved the conflicts and added the image

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by aditya-bhaumik** [comment]
@kunjgit i have resolved the merge conflicts

**Pull request merged**
