### PR TITLE
Find The Number

### PR DESCRIPTION
**Pull request by AshishPandey04**
## PR Description 📜

I have added a new game Find The Number. I have also improve user experience by Allowing user to restart the game . Have written a Standard javascript code which is error free and gives user nice experince.
Fixes # <#4956>

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [ ✅] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅ ] I have added screenshot for website preview in assets/images 
- [✅ ] I have added entries for my game in main README.md
- [ ✅] I have added README.md in my folder 
- [✅ ] I have added working video of the game in README.md (optional)
- [✅ ] I have specified the respective issue number for which I have requested the new game.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @AshishPandey04 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by AshishPandey04** [comment]
@kunjgit please check the PR

**Comment by AshishPandey04** [comment]
check the pr pls

**Comment by kunjgit** [comment]
Thank you  @AshishPandey04 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
