### PR TITLE
Space_Invaders 

### LINKED ISSUE #1108: [New game]: space Invaders
### 🎮 Game Request

Game logic and basic description
In Space Invaders, the player controls a small spaceship that moves horizontally at the bottom of the screen. The objective is to shoot and destroy waves of descending alien invaders while avoiding their projectiles and barriers. The aliens move left and right, gradually descending towards the player's spaceship. If the aliens reach the bottom of the screen or the player's spaceship is hit by an enemy projectile, the game ends.

### Point down the features

Game points
Player-Controlled Spaceship
Shooting Mechanism
Alien Invaders

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Mannu292001**
## PR Description 📜

This PR is about Space Invaders Game
Fixes  #1108 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) `📸`

Space_Invaders

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Mannu292001 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Mannu292001,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Mannu292001,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Mannu292001,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Mannu292001,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Mannu292001,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by Mannu292001 — COMMENTED** [review]
I have made the changes in file plz and review it.

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Mannu292001,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Mannu292001,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Mannu292001,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Mannu292001,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by U-DAY-333** [comment]
Bro what is the change here he requesting you. Even i am facing the similar issue. All my checks are passed and  i updated main readme file also but still it is sjhowing me 1 change requested

**Comment by Mannu292001** [comment]
> Bro what is the change here he requesting you. Even i am facing the similar issue. All my checks are passed and i updated main readme file also but still it is sjhowing me 1 change requested

bro i will also not ale to understand how to change readme.md file and mentor are also not replying here

**Comment by daccdacc** [comment]
Hello @Mannu292001 @U-DAY-333, Sorry for some inconvenience caused.
You have to add entry of your game in main README.md file that is : [README file](https://github.com/kunjgit/GameZone/blob/main/README.md)

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Hey @Mannu292001 you are not reading documentation properly read it  properly and then make a PR

**Comment by kunjgit** [comment]
Thank you  @Mannu292001 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
