### PR TITLE
[New Game]Zombie_Shooter game added

### LINKED ISSUE #4681: [New game]:  Zombie Shooter game
### 🎮 Game Request

Game logic and basic description
A top-down shooter game where the player must survive waves of zombies.

### Point down the features

Game points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by sau-mili**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #4681

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Zombie_Shooter
Zombie_Shooter_canvas

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @sau-mili ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by sau-mili** [comment]
@ishita-43 @kunjgit please check

**Comment by nishant0708** [comment]
Hey @sau-mili I am facing trouble in forking this repo it is showing something like path invalid of some folder can you tell me how you forked this repo

**Comment by sau-mili** [comment]
> Hey @sau-mili I am facing trouble in forking this repo it is showing something like path invalid of some folder can you tell me how you forked this repo

you can talk about this in project channel in discord

**Comment by sau-mili** [comment]
@ishita-43 @kunjgit please check this pr

**Review by ishita-43 — APPROVED** [review]
good to go!!

**Comment by kunjgit** [comment]
Thank you  @sau-mili , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
