### PR TITLE
Insect Catch Game is Ready

### LINKED ISSUE #1580: [New game] [Insect Catch Game]:
### 🎮 Game Request

<h2>Game logic and basic description:</h2>

<li>This game is created with the help of html, css and javascript.</li>
<li>In this game first you can choose your favorite insect.The objective of the game is to catch as many insects as possible within a given time limit.</li>
<li>The insects come in various shapesand they move quickly and unpredictably across the screen.</li>
<li>The catchers must be quick and agile to track the insects' movements and snatch them out of the air.</li>

### Point down the features

<h2>Game points</h2>

<ol>
<li>change the insect type</li>
<li>show user points and time on screen</li>
<li>sound feature</li>
</ol>

### Select The Game Type

Single Player

### Pictures
1st
<br>
2nd

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by JadavShraddha**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes  #1580 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @JadavShraddha ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @JadavShraddha,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @JadavShraddha,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Comment by JadavShraddha** [comment]
I can't understand properly how to resolve this conflict. Please tell me what should I do.

**Pull request closed without merging**
