### PR TITLE
[New game]: Blink Beat #4770

### PR DESCRIPTION
**Pull request by Shantnu-singh**
## PR Description 📜
This pull request adds a new game named blink beat. you can experience the gameplay as it is live on the link provided in the readme.md

Fixes - Blink Beat #4770

<hr>
 
## Mark the task you have completed ✅

✅I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
✅I have performed a self-review of my own code or work.
✅ I have commented my code, particularly in hard-to-understand areas.
✅ My changes generates no new warnings.
✅I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
✅I have added screenshot for website preview in assets/images 
✅ I have added entries for my game in main README.md
✅I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
✅I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Shantnu-singh ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Shantnu-singh** [comment]
FInal Commit

**Comment by Shantnu-singh** [comment]
@kunjgit plz review this.

**Review by ishita-43 — CHANGES_REQUESTED** [review]
You need to make following changes:-
Add your game image in the asset folder of the gamezone follow naming convention mentioned in the contribution guidelines while doing so
Add your game entry into the main Readme.md file of the gamezone repo refer other entries for the  format
I hope you will make the desired changes soon

**Comment by Shantnu-singh** [comment]
Hey @ishita-43 can you review this and let me of any further changes .

**Review by ishita-43 — APPROVED** [review]
Seems good!

**Comment by kunjgit** [comment]
Thank you  @Shantnu-singh , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
