### PR TITLE
Add pagination in project list

### LINKED ISSUE #1498: [Enhancement]: Adding Pagination to GameZone Website
### Is your enhancement request related to a problem? Please describe.➕

Till now all the game projects are shown together, but it would be nice to add pagination to it.

### Describe the solution you'd like

I wish to add pagination with some number of games shown at a time. Please assign this to me!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by kartikjoshi267**
## PR Description 📜

This PR adds a pagination feature so as to view some projects only at a time and hiding other projects for the time being. Also, I have added `Next` and `Previous` buttons to go to next set of projects.
Fixes #1498 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @kartikjoshi267 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Really nice but @kartikjoshi267 can you reach out to us and take that with the theme that we are having on GameZone !!
it would be really nice to have but you need some designing changes 👀

**Comment by kartikjoshi267** [comment]
> Really nice but @kartikjoshi267 can you reach out to us and take that with the theme that we are having on GameZone !! it would be really nice to have but you need some designing changes 👀

Ok I will do the necessary changes.

**Comment by kartikjoshi267** [comment]
@kunjgit I have changed the design according to the theme of the website and also, changed the function calls to adapt to the new feature of dynamically updating the games/projects. Please review the changes and suggest any necessary changes.

**Comment by kunjgit** [comment]
Hey @kartikjoshi267 can you show us the updated design !! 👀

**Comment by kartikjoshi267** [comment]
> Hey @kartikjoshi267 can you show us the updated design !! 👀

I have designed it exactly the same way the Scroll to Top Button has been designed!
image

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
@kartikjoshi267 It's looking great 🔥

**Comment by kunjgit** [comment]
Thank you  @kartikjoshi267 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
