### PR TITLE
Anaconda game

### LINKED ISSUE #1738: [New game]:Anaconda  (a snake game )
### 🎮 Game Request

It is a anaconda the snake game , there are food in betwewn the path of anaconda and you anaconda eats it and its length increases accordingly.
It  is made using html, css and javascript .

the ui of the game is as shown below.

Screenshot 2023-06-20 200425

### Point down the features

it consist of a score bored , game over message and a background music

### Select program in which you are contributing

GSSoC23, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Adityamishra9719**
## PR Description 📜

I had added a game name Anaconda a  snake game .
It is made using HTML , CSS and JAVASCRIPT .
It is very easy to play as you only have to use up , down, left and right arrow to move snake for eating food and making high scores .
Fixes #1738 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Anaconda_Snake_game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Adityamishra9719 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Adityamishra9719,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Comment by Adityamishra9719** [comment]
Hi, @kunjgit  I have updated the main README.md file.

**Comment by kunjgit** [comment]
we have snake game already !! 👀

**Comment by kunjgit** [comment]
Thank you  @Adityamishra9719 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
