### PR TITLE
Added FAQ section 

### LINKED ISSUE #662: [Question]: Can I Add FAQ'S in GameZone using  bootstrap?
### Description
I have created an issue in the "Question or support request" because I am not sure whether we can add other features to the website GameZone,_if we can I would Like to create FAQ section using Bootstrap below are few questions examples:_

1. What is GameZone?
2. Is GameZone really free to play?
3. Can I submit my own game to GameZone?
4. Are there any multiplayer games available on GameZone?

@kunjgit,If you would like FAQs in GameZone  assign me this issue under GSSoC'23.

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Dimple-Choudhary**
## PR Description 📜

I have added a FAQ section with five questions and their respective answers. If you have any suggestions or if there is anything you would like me to modify, please kindly let me know. Thank you.
Fixes #662 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)

<hr>

## Add your screenshots(Optional) 📸

Screenshot (67)

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Dimple-Choudhary ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
for now we are not adding the section and you have to make sure that you follow the theme website is having !!

**Comment by kunjgit** [comment]
Thank you  @Dimple-Choudhary , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Dimple-Choudhary** [comment]
Can I still do changes?

**Pull request closed without merging**
