### PR TITLE
Country-Guesser Game changed

### LINKED ISSUE #2622: [Enhancement]: Background of Country Guesser Game
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement
Currently background of country guesser game is distracting for the player
Screenshot 2023-07-27 134508

### Describe the solution you'd like

Solution steps
I want to work on this issue and make background user friendly

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by akankshachanana1**
## PR Description 📜

I have changed background color as well as hover effect to make the game user friendly
Fixes #2622 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Earlier

https://github.com/kunjgit/GameZone/assets/127978268/e02d6e1c-b019-45c6-8dfa-18ac0ef9bbea

Now

https://github.com/kunjgit/GameZone/assets/127978268/54228ebb-2b25-40ba-890f-afde96e872e7

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @akankshachanana1 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Don't you think previous UI looks better

**Comment by akankshachanana1** [comment]
Actually that is a bright yellow color , which I think might distract user.

**Comment by kunjgit** [comment]
Thank you  @akankshachanana1 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
