### PR TITLE
Gem cruncher #4436

### PR DESCRIPTION
**Pull request by Aditijainnn**
## PR Description 📜

Added a game Gem_Cruncher
Fixes #  #4436

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Aditijainnn ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by ishita-43** [comment]
Your files of submodule are not visible make sure you added your game  in the games folder of the gamezone

**Comment by Aditijainnn** [comment]
> Your files of submodule are not visible make sure you added your game in the games folder of the gamezone

added files please merge my pr

**Comment by ishita-43** [comment]
> > Your files of submodule are not visible make sure you added your game in the games folder of the gamezone
> 
> added files please merge my pr

Files changes show more than 900 files I can't review them all at once 
You should remove unwanted fies and keep the desired one only and make sure you made your game entry in main readme file of the gamezone

**Review by ishita-43 — COMMENTED** [review]
Do you inttend to keep all these files

**Comment by kunjgit** [comment]
Thank you  @Aditijainnn , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
