### PR TITLE
Brain Card Game Added

### PR DESCRIPTION
**Pull request by CodeXsubham**
## PR Description 📜

Added Brain Card Game to Increase the ability to remember 🧠

Added #4023 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot 2024-06-01 145106

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @CodeXsubham ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @CodeXsubham,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by CodeXsubham** [comment]
Hey @kunjgit PA, 
I have already added the readme file plus asset directory , but I dont know what to modify in main readme.md file

**Comment by CodeXsubham** [comment]
@kunjgit Updated Main readme file please review it and merge it please

**Comment by CodeXsubham** [comment]
@kunjgit Hey PA, 
kindly Review it , I have added Readme file in the folder , Assets directory and but idk how to update the main readme file , Please merge as soon as possible so that I can work on next PR ,Thank You

**Comment by CodeXsubham** [comment]
@kunjgit hey PA ,
kindly  merge it , so that i can works on another PR

**Review by kunjgit — CHANGES_REQUESTED** [review]
@CodeXsubham make sure you are adding image and entry of your game in main readme!

**Comment by CodeXsubham** [comment]
@kunjgit how to add game in the main readme file ...idk how to

**Comment by kunjgit** [comment]
@CodeXsubham I would request you to have a look at merged pr under new game addition that can give you idea !
read documentation properly !

**Comment by kunjgit** [comment]
Thank you  @CodeXsubham , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Thank you  @CodeXsubham , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
