### PR TITLE
mole

### PR DESCRIPTION
**Pull request by taneeshaa15**
Game:
gamezone

Readme and image directory:
review

Hi, @kunjgit ,
I hope you're doing well. I've addressed the game in issue #4339  and created a pull request for the same.
Could you please review the PR and let me know if any adjustments are needed?

Best regards,
Tanisha Garg

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @taneeshaa15 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @taneeshaa15,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by taneeshaa15** [comment]
@ishita-43 @kunjgit 
Please check the updated files and kindly give your valuable feedback.

**Comment by taneeshaa15** [comment]
@ishita-43 @kunjgit Please assign me this issue before merging the file.

**Review by ishita-43 — CHANGES_REQUESTED** [review]
make sure enter your game in readme.md file of gamezone folder
for format refer other entries
I hope you will make changes soon.

**Comment by taneeshaa15** [comment]
@ishita-43 @kunjgit Did all the required changes, kindly review.

**Review by ishita-43 — COMMENTED** [review]
Go into GameZone repository there you will find various folders including Games Assets (you already did.  added images here) along with these you will find Readme.md there 
THIS file included entry of all the games created in this repository 
You simply need to add your game name there refer other entries to see what is the format to add that 
it would be like 
[Mole] (Here goeslink(same as others)/Mole)
I hope you will follow this .

**Comment by taneeshaa15** [comment]
@ishita @kunjgit Please review, all changes done.

**Review by ishita-43 — APPROVED** [review]
Ready to merge

**Comment by kunjgit** [comment]
Thank you  @taneeshaa15 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
