### PR TITLE
Added  Firedog Adventure Game

### LINKED ISSUE #2065: [New game]:  Adding Firedog Adventure Game
### 🎮 Game Request

Are you ready to test your skills and have a good laugh at the same time? Look no further than "Firedog Adventure"!

In this exciting game, you take on the role of a courageous firedog soaring through the skies, facing a swarm of mischievous flaming ravens determined to stop you. These fiery avian foes come in various sizes and vibrant colors, leaving behind dazzling trails of sparks as they soar. As you navigate the skies, your mission is to skillfully maneuver, avoiding collisions with the ravens and aiming to achieve the highest score possible. Be alert and agile, dipping, diving, and dodging your way through the relentless flock of ravens.

But beware! If one of those sneaky ravens manages to hit you, get ready for an explosive and hilarious animation that will undoubtedly bring a smile to your face. Get back up, shake off the ashes, and continue your Firedog Adventure!

### Point down the features

Features
-Smooth gameplay
-Comical animations
-Variety of ravens
-Soundtrack
-High scores
https://github-production-user-asset-6210df.s3.amazonaws.com/85815172/248575377-4f03f119-3e83-4ae9-99e5-9f3b972b9d79.mp4

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Nishitbaria**
## PR Description 📜

This pull request adds the exciting "Firedog Adventure" game to our project. Get ready for a thrilling experience that will test your skills and bring a smile to your face!
Fixes #2065 
## Features
- Play as a courageous firedog soaring through the skies.
- Encounter mischievous flaming ravens as your fiery avian foes.
- Ravens come in various sizes and vibrant colors with dazzling sparks trails.
- Skillfully maneuver to avoid collisions with the ravens.
- Aim to achieve the highest score possible.
- Enjoy explosive and hilarious animations when hit by a raven.
- Resume gameplay after getting hit and continue your Firedog Adventure.

## Screenshots (optional)
[Add relevant screenshots if available]

 
Informatician and 4 more pages - Personal - Microsoft​ Edge 27-06-2023 20_27_06

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Nishitbaria,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Nishitbaria,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Nishitbaria** [comment]
@kunjgit  I have added images in assests,updated MAIN Readme.md and added Firedog_Adventure in Games Folder

**Review by gurjeetsinghvirdee — COMMENTED** [review]
**Copied from here: https://github.com/JayeshYadav99/Endless-Running-Game---Beginner-Project/tree/main/FINAL**
Live link: https://jayeshyadav99.github.io/Endless-Running-Game---Beginner-Project/

**Comment by kunjgit** [comment]
Thank you  @Nishitbaria , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Nishitbaria** [comment]
@kunjgit @gurjeetsinghvirdee I am collaborator in that repositorry

**Comment by gurjeetsinghvirdee** [comment]
Why didn't you mentioned this before in description?

**Comment by Nishitbaria** [comment]
@kunjgit  What changes are remaining for me?

**Comment by kunjgit** [comment]
Thank you  @Nishitbaria , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
