### PR TITLE
Add background to paragraph

### LINKED ISSUE #2315: [Enhancement]: Make play & have fun text clearly visible
### Is your enhancement request related to a problem? Please describe.➕

Make play & have fun text clearly visible by adding background color white and text color to black

### Describe the solution you'd like

I will make the paragraph background white and it's text color black with some border radius like this: 

Screenshot from 2023-07-06 19-49-39

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by MisterMickey**
## PR Description 📜

Enhance UI of Game paragraph

Fixes #2315

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)

<hr>

## Add your screenshots(Optional) 📸

Screenshot from 2023-07-06 20-03-34

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @MisterMickey ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by daccdacc** [comment]
Hello @MisterMickey, Your changes aren't enough to label it under level2. 
Please make some more cool changes!!

**Comment by MisterMickey** [comment]
@daccdacc Made one more border change to make the boundary visible, check ss for the issue on changing theme

# Old

Screenshot from 2023-07-13 01-02-07
Screenshot from 2023-07-13 01-02-03


# New
Screenshot from 2023-07-13 01-14-12
Screenshot from 2023-07-13 01-14-08

**Comment by gurjeetsinghvirdee** [comment]
> Hello @MisterMickey, Your changes aren't enough to label it under level2. Please make some more cool changes!!

If level are not matching with PR quality then decrease it! Simple

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM 🌸

**Comment by kunjgit** [comment]
Thank you  @MisterMickey , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
