### PR TITLE
Added Sky Jumper Game 

### LINKED ISSUE #5058: [New game]:  Want to add sky jumper game
### 🎮 Game Request

Game logic and basic description
I want to add the sky jumper game 
Jump between moving platforms to stay in the game as long as possible. The goal is to survive and achieve the highest jump.

### Point down the features

Game points
in this game yor have to survive and do the highest jump as possible 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
## PR Description 📜

In this pr i have created the new game that is Sky Jumper 

Fixes #5058

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in GameZone's README.md
- [x] I have added README.md in my Game folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.
- [x] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸

image

https://github.com/user-attachments/assets/bdf1da30-880f-4394-ae02-deafd3798eaf

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Ayushmaanagarwal1211 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Please also add an image of your game in the assets folder of the gamezone repo.

**Comment by Ayushmaanagarwal1211** [comment]
@ishita-43  Done please check

**Review by ishita-43 — APPROVED** [review]
Approved

**Comment by kunjgit** [comment]
Thank you  @Ayushmaanagarwal1211 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
