### PR TITLE
Audio Wordle Game 

### LINKED ISSUE #4534: [New game]: Sound Wordle Game
### 🎮 Game Request

In this game, a tune will be played, and the user has to guess the name of the song in 5 guesses.

As stated before, the issue #4406 is the Word Shuffle Game. My game is different. It uses audio and is not an unscrambling of words, it is more of a guessing game. Like a wordle but using audio.

### Point down the features

1. The user will be given 5 chances.
2. The tune can be played as many times as the user wants.
3. If the letter is used in the word, it will become yellow.
4. If the letter is in the right place in the word, it will become green.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by abckhush**
## PR Description 📜

Fixes #4534

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @abckhush ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — COMMENTED** [review]
Ready to merge!!

**Review by ishita-43 — APPROVED** [review]

**Comment by abckhush** [comment]
Hi @kunjgit could you pls merge this?

**Comment by kunjgit** [comment]
Thank you  @abckhush , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
