### PR TITLE
Added Tiny Fishing game

### LINKED ISSUE #3652: [New game]: Added Tiny Fishing
## Game logic and basic description
It is a fun game to play for kids and children. This game gives you a very nice experience of fishing game , in this game you can catch the many fishes and level up of your equipment . there is a bonus section where you can get bonus prizes.

## Game points
1. you can your mouse or arrow keys for moving the fishing rod .
2. The music give you a very fun vibe .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Pujan-sarkar**
## PR Description 📜

I am adding the game Tiny Fishing and changed the required changes

Fixes #3652 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
tiny-fishing

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Pujan-sarkar ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Pujan-sarkar,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Pujan-sarkar,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Pujan-sarkar** [comment]
@kunjgit  please see the commit , the changes have already done but you are requesting it ...

**Comment by kunjgit** [comment]
@Pujan-sarkar resolve merge conflicts !

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Pujan-sarkar,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Pujan-sarkar,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Pujan-sarkar** [comment]
@kunjgit  sir i have done it again please merge it , all changes have done please .

**Comment by Pujan-sarkar** [comment]
sir @kunjgit  i have solve the conflicts please merge now

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Pujan-sarkar , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
