### PR TITLE
Added Morse_Code_Generator 

### LINKED ISSUE #4269: [New game]: Morse Code Generator
### 🎮 Game Request

Game logic and basic description
I want to generate the morse code for the given text

### Point down the features

Game points
1.Input the text given 
2.After clicking convert the given text changes to morse code
3.And there is a morse code output

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
## PR Description 📜
Added Morse_Code_Generator where the  input text can be converted into morse code and can be used for furture purpose 

Fixes #4269 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Morse_Code_Generator

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Saipradyumnagoud ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — APPROVED** [review]
Good work!! Approved 🚀.

**Comment by Saipradyumnagoud** [comment]
@ishita-43  can  you please merge it  soon so that i can start working on the another pull request

**Comment by ishita-43** [comment]
It will be soon merged by the Admin!! Till then explore the project or work on other projects of Gssoc'24

**Comment by Saipradyumnagoud** [comment]
> It will be soon merged by the Admin!! Till then explore the project or work on other projects of Gssoc'24

Yes Sure

**Comment by kunjgit** [comment]
Thank you  @Saipradyumnagoud , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
