### PR TITLE
Brought Simon Game in a single screen

### LINKED ISSUE #3126: Simon_Game_Challenge[Enhancement]:
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

It should be in only one page because the starting button is very small in it, so it is not visible.

### Describe the solution you'd like

add  height : 100vh;
increase Start button size

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by BagchiShreya**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below

The issue was that the game was not in a single screen and the player had to scroll down to get the play button. Fixed this issue by making required adjustments and brought the entire game in a single screen. Now there is no need to scroll.

Fixes #3126 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

simon

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @BagchiShreya ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — APPROVED** [review]
LGTM !

**Comment by kunjgit** [comment]
Thank you  @BagchiShreya , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by BagchiShreya** [comment]
> Thank you @BagchiShreya , for your valuable time and contribution in our GameZone 💗. It’s our GameZone, so Let’s build this GameZone altogether !!🤝 Hoping to see you soon with another PR again 😇 Wishing you all the best for your journey into Open Source🚀

Thank You

**Pull request merged**
