### PR TITLE
Completed making Whack a Mole game

### LINKED ISSUE #232: [New game]: Whack a Mole
### 🎮 Game Request

Game logic and basic description:
The game is absolutely fun. It consists of 9 holes where a mole will appear and change its position continously. The player must tap on the mole to get points. The twist is there also will be a insectivorous plant which also will be moving with the mole. The game ends when the player taps on the insectivorous plant.

### Point down the features

Game points:
The objective of the game is to score the highest by tapping on the mole correctly everytime and be causious of tapping on insectivorous plant since the game ends.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
## PR Description 📜
Completed Whack A Mole
Fixes #232 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Whack_A_Mole

--- 
<br>
## Add your video(Optional) 📸

https://github.com/kunjgit/GameZone/assets/112749383/ca161f5d-d044-48e4-b73e-53661d24839f

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @akhilender-bongirwar ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Review by Durgesh4993 — APPROVED** [review]

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @akhilender-bongirwar !! we are already having the game on GameZone !!
you can do enhancement in that 👀 !!

**Pull request closed without merging**
