### PR TITLE
Baseball Blitz added

### LINKED ISSUE #2359: [New game]: Baseball Blitz Game
### 🎮 Game Request

I want to add new baseball game using HTML, CSS, and JavaScript. This game aims to provide an immersive and enjoyable experience for players. 

### Point down the features

1. Baseball gameplay mechanics, including pitching, hitting, fielding, and baserunning. 
2. Introduce a multiplayer mode that allows players to compete against each other online.
3. Multiple difficulty levels to cater to players of different skill levels.
4. Track and display comprehensive game statistics and score.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by abhinav-m22**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
* Closes #2359 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2023-07-09 235520
<br></br>
Screenshot 2023-07-09 235547

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @abhinav-m22 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @abhinav-m22,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Comment by abhinav-m22** [comment]
@kunjgit @Arun9739 @daccdacc  Done
Please review and merge the PR!

**Comment by kunjgit** [comment]
Thank you  @abhinav-m22 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @abhinav-m22,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by abhinav-m22** [comment]
@daccdacc please add the labels
Thank you!

**Comment by abhinav-m22** [comment]
@kunjgit @daccdacc @Arun9739 
Please add the gssoc23 and the level label !

**Comment by abhinav-m22** [comment]
@gurjeetsinghvirdee Please add the labels

**Pull request merged**
