### PR TITLE
Added new rapid frenzy game

### LINKED ISSUE #3962: [New game]: Rapid Click Frenzy
### 🎮 Game Request

**Game Title: Rapid Click Frenzy**
Game Logic
In Rapid Click Frenzy, the player’s objective is to click a button as many times as possible within a given time limit. The game starts when the player clicks the "Start Game" button, which initializes the score to zero and sets the timer to the predefined duration (e.g., 10 seconds). As the game begins, the player clicks the "Click Me!" button repeatedly to increase their score. A timer counts down from the starting time, and once it reaches zero, the game ends. The player’s final score is then displayed, showing how many times they managed to click the button within the time limit.

### Point down the features

Features
Simple and Intuitive Gameplay

Easy-to-understand mechanics: click the button as fast as you can within the time limit.
Time-Limited Challenge

Players have a fixed amount of time (e.g., 10 seconds) to achieve the highest score possible by rapidly clicking a button.
Score Tracking

Real-time score display updates with each button click, showing the player’s current score.
Timer Display

A countdown timer visible on the screen, keeping the player aware of the remaining time.
Start and Restart Game

"Start Game" button to begin the game and reset all parameters (score and timer) for a fresh start.
Ability to restart the game after it ends by clicking the "Start Game" button again.
Game Over Screen

Upon the timer reaching zero, the game ends and a "Game Over" screen appears, displaying the player’s final score.
Responsive Design

The game adapts to different screen sizes and devices, ensuring a consistent experience on both desktop and mobile devices.

I am contributing Upne Gssoc24

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by NAVJOT-786**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Game Logic
In Rapid Click Frenzy, the player’s objective is to click a button as many times as possible within a given time limit. The game starts when the player clicks the "Start Game" button, which initializes the score to zero and sets the timer to the predefined duration (e.g., 10 seconds). As the game begins, the player clicks the "Click Me!" button repeatedly to increase their score. A timer counts down from the starting time, and once it reaches zero, the game ends. The player’s final score is then displayed, showing how many times they managed to click the button within the time limit.
Fixes #3962 

<hr>
 
## Mark the task you have completed ✅

- [ X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ X] I have performed a self-review of my own code or work.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [ X] My changes generates no new warnings.
- [X ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X ] I have added screenshot for website preview in assets/images 
- [ X] I have added entries for my game in main README.md
- [ X] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2024-05-31 at 1 00 22 PM

--- 
<br>
I am contributing upon Gssoc24
## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @NAVJOT-786 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by NAVJOT-786** [comment]
@kunjgit please check if anything else required

**Comment by NAVJOT-786** [comment]
@kunjgit pull request is not accepted yet is anything else required please tell?

**Comment by NAVJOT-786** [comment]
@kunjgit  please check i have solve the issue

**Comment by NAVJOT-786** [comment]
@kunjgit my pull request is not accepted yet is anything else required

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @NAVJOT-786 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
