### PR TITLE
Added DNA Sequencer game

### LINKED ISSUE #4891: [New game]: DNA Sequencer
### 🎮 Game Request

The DNA Sequencer Game challenges players to correctly arrange a randomized DNA sequence. Players can shuffle the sequence and use drag-and-drop functionality to reorder DNA bases (A, T, C, G) until they match the target sequence. The game includes a timer to add an element of urgency, requiring players to complete the task within the allotted time

### Point down the features

Game points
Objective: Arrange the DNA sequence correctly within the time limit.
Shuffle: Randomize the sequence for added difficulty.
Drag-and-Drop: Intuitively rearrange DNA bases using drag operations.
Timer: Countdown from 120 seconds to complete the game.
Feedback: Immediate indication of sequence accuracy

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by kosuri-indu**
## PR Description 📜

This PR adds a new interactive puzzle game, DNA Sequencer, to the project. The game challenges players to arrange DNA bases (A, T, C, G) in the correct order within a 120-second time limit.
Fixes #4891 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot 2024-07-19 210100

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @kosuri-indu ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kosuri-indu** [comment]
@kunjgit @ishita-43 
Please review this PR :)
Thank you

**Review by ishita-43 — APPROVED** [review]
Ready to merge!!

**Comment by kosuri-indu** [comment]
@kunjgit 
I have resolved the conflict, Could you review this PR?

**Comment by kosuri-indu** [comment]
@kunjgit Sir any update on this PR?

**Comment by kunjgit** [comment]
Thank you  @kosuri-indu , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
