### PR TITLE
Solved issue #3977- Forest Guardian Game

### LINKED ISSUE #3977: [New game]: Forest Guardian
### 🎮 Game Request

Game logic and basic description
 In this game, the player controls a guardian spirit that protects a magical forest. The player needs to navigate through the forest, collecting magical orbs and avoiding harmful creatures. The game will have multiple levels with increasing difficulty.

### Point down the features

Game points
Guardian Movement: Players control a guardian spirit using the left and right arrow keys to navigate through the forest.
Orb Collection: Players must collect magical orbs that appear at random positions to score points.
Avoiding Creatures: Harmful creatures appear and move through the forest, which the player must avoid to stay alive.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below

Forest Guardian is a simple browser-based game where players control a guardian spirit navigating through a magical forest, collecting orbs while avoiding harmful creatures.

Fixes # <your_issue_number>
Fixes #3977 
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Forest_guardian

https://github.com/kunjgit/GameZone/assets/142652964/e3ac3776-d6c6-45fc-bb37-ab62a8d51d64

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Aditi22Bansal ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Aditi22Bansal,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Aditi22Bansal** [comment]
@kunjgit 
Done

**Comment by Aditi22Bansal** [comment]
@kunjgit 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@kunjgit 
Kindly review and merge this 
So that I can add another PR
If any changes are required kindly tell
Thankyou

**Comment by Aditi22Bansal** [comment]
Resolved the conflicts 
Kindly merge
Thankyou

**Comment by Aditi22Bansal** [comment]
@kunjgit 
Kindly review

**Comment by Aditi22Bansal** [comment]
@kunjgit 
Kindly review and merge

**Comment by kunjgit** [comment]
Thank you  @Aditi22Bansal , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
