### PR TITLE
Enhancement of UI of Click the Circle game and adding some new features such as increasing time, button position .

### PR DESCRIPTION
**Pull request by Changingthegame**
## PR Description 📜

I have resolved the issue #4668.Kindly review it, I have enhanced the UI and also have made necessary changes such as fixing the position of start button and increasing time duration to 30 seconds.

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Change_1
Change_2

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Changingthegame ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Changingthegame** [comment]
Please mark labels gssoc in this issue #4668 .

**Comment by Changingthegame** [comment]
Hello @kunjgit, can you please  take action and merge  my pull request as I am very eager to contribute on another game in your repository. I tried to open an issue for that but it was automatically closed as I have an issue that is open till now. So, please do it as soon as possible.

**Comment by Changingthegame** [comment]
Hello @kunjgit , please merge my pull request as I have to contribute in more games in your repo but there is no response from last week.

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by kunjgit** [comment]
Thank you  @Changingthegame , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
