### PR TITLE
Added New game

### LINKED ISSUE #3113: [New game]: Simonsays2.0(enhanced UI and memes  sound effects)
### 🎮 Game Request

Simon Says Game Description The Simon Says Game is a classic memory game where players must repeat a sequence of colors in the same order as presented by the game. It's a fun way to challenge your memory skills and enjoy some nostalgic gameplay.

Installation: To play the Simon Says Game, simply clone this repository to your local machine or download the ZIP file. Then, open the index.html file in your web browser. Usage Once you've opened the game in your browser, click the "Start" button to begin. Simon will show a sequence of colors by lighting up the corresponding buttons. Pay close attention to the sequence! After Simon has finished, it's your turn to repeat the sequence by clicking the buttons in the same order. If you succeed, Simon will add another color to the sequence and the game continues. If you make a mistake, Simon will let you know and the game will restart.

Features: Classic Simon Says gameplay Colorful and engaging user interface Sound effects to enhance the gaming experience Contributing Contributions to the Simon Says Game are welcome! If you'd like to contribute, please follow these steps:

### Point down the features

**Each Correct Sequence**: You earn one point for every sequence that you correctly replicate.

**Increasing Difficulty:** Each round, the sequence becomes longer and more complex, increasing the difficulty and the potential to score more points as you progress

**High Score Tracking:** Some versions of the game may keep track of the high score, which is updated if the game that just ended had the largest sequence of correct matches since the game was turned  on.

Remember, the key to scoring high in Simon Says is a good memory and quick reflexes to match the sequences accurately as they get longer. Keep practicing, and you might just set a new high score! Good luck! 🌟

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by pandeyji711**
## PR Description 📜

I have added New Simonsays game (Simonsays2.0) . that include greater UI and Memes sound effect 
Fixes #3113 

<hr>

- [ X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ X] I have performed a self-review of my own code or work.
- [X ] My changes generates no new warnings.
- [ X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X ] I have added screenshot for website preview in assets/images 
- [X ] I have added entries for my game in main README.md
- [ X] I have added README.md in my folder 
- [X ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Simonsays2 0

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @pandeyji711 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Thank you  @pandeyji711 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by pandeyji711** [comment]
@kunjgit please review this

**Comment by kunjgit** [comment]
@pandeyji711  make sure you are having proper source code there you are right now having submodule and similar games are already there on GameZone !

**Comment by kunjgit** [comment]
Thank you  @pandeyji711 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by pandeyji711** [comment]
@kunjgit this is full source code and other simon say are not that good

**Pull request closed without merging**
