### PR TITLE
added grab the correct game

### LINKED ISSUE #4201: [New game]: Grab the carrot
### 🎮 Game Request

Game logic and basic description

it is basically a game like temple run where the character will be running and behind us there will be a monster chasing and we need jump the obstacle and other stuffs .

image

### Point down the features

Game points

This will be warded to the user according to the user highscore 

pls do assign the GSSOC Label 

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Aksshay88**
## PR Description 📜

I have included the Grab the carrot game where the user could use the play the character game where he could grab the carrots 
Fixes #4201 

<hr>
 

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you so much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Aksshay88 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Aksshay88,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Aksshay88** [comment]
@kunjgit Yeah sure will make it and we will add a nice readme.md with the images.Thanks for suggesting me .

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Aksshay88,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Aksshay88,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Aksshay88** [comment]
@kunjgit  I have changes the following changes asked to made .Thanks for suggesting me to do this one

**Comment by Aksshay88** [comment]
@kunjgit sure will change it

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Aksshay88,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Aksshay88,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Aksshay88,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Aksshay88,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Aksshay88,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by Aksshay88** [comment]
@kunjgit Still what changes should I need to make ?

**Comment by Aksshay88** [comment]
I have changed the Main README.md too .Pls do check with that

**Comment by Aksshay88** [comment]
image

have a look at it pls  

Any suggestion I would welcome that .
Thanks in advance .
Happy Hacking

**Comment by kunjgit** [comment]
Thank you  @Aksshay88 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
