### PR TITLE
Pokémon Style Game Added

### LINKED ISSUE #517: [New game]: Pokémon-Style Game
### 🎮 Game Request

- Wanted to create a **Pokémon-style game** 
- In this Pokémon-inspired game, players will explore a vast world filled with diverse monsters.
- We will fight the monsters with various fighting styles.

### Point down the features

- Exploration plays a crucial role in the game. Players will traverse diverse environments such as forests, mountains, caves, and cities, each containing unique monsters to encounter. 
- Using the keys on the keyboard we can move the player forward, backward right and left.
- There will be a specific area in which our player can move and once player steps on a particular location, the monster gets activated and the battle begins.
- There will be a life status bar, showing the current health and health will decrement upon the subsequent attacks.
 
It will look like as seen in the Pictures below.
Screenshot (154)
Screenshot (153)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Explorer003**
## PR Description 📜
**_### Pokémon Style Game_**

- Welcome to the enchanting world of Pokémon Style Game, an exciting adventure inspired by the beloved Pokémon series. Embark on a journey as a budding trainer, ready to explore diverse regions filled with captivating creatures.
- Exploration plays a crucial role in the game. Players will traverse diverse environments such as forests, mountains, caves, and cities, each containing unique monsters to encounter.
- Interesting Battles
- We will fight the monsters with various fighting styles
- Life status bar, showing the current health and health will decrement upon the subsequent attacks.
- Player can move by using various keys on keyboard

Fixes #517 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Pokemon_Style_Game
Screenshot (153)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Explorer003 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
don't use sub modules !! so we can review your code 👀 !!

**Comment by kunjgit** [comment]
Thank you  @Explorer003 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Explorer003** [comment]
Hey, @kunjgit  can you please tell me what basically are "Sub modules"?

**Pull request closed without merging**
