### PR TITLE
Add Triangle Back to Home Game

### LINKED ISSUE #2088: [New game]: Triangle: Back to Home
### 🎮 Game Request

This is a basic runner game. It is similar to mario like games but has improved graphics.

### Point down the features

The player has to pass the levels by overcoming the hurdles presented in their way.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by kartikjoshi267**
## PR Description 📜
Please review my PR!
Fixes #2088 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Triangle_Back_To_Home

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @kartikjoshi267 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Resolve conflicts @kartikjoshi267

**Comment by kartikjoshi267** [comment]
> Resolve conflicts @kartikjoshi267

Resolved!!

**Comment by kunjgit** [comment]
Thank you  @kartikjoshi267 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kartikjoshi267** [comment]
@daccdacc please add gssoc23 label

**Comment by kartikjoshi267** [comment]
@gurjeetsinghvirdee please add the labels for gssoc23!

**Comment by kartikjoshi267** [comment]
Please add appropriate labels for gssoc23! @gurjeetsinghvirdee @kunjgit @daccdacc

**Comment by gurjeetsinghvirdee** [comment]
> Please add appropriate labels for gssoc23! @gurjeetsinghvirdee @kunjgit @daccdacc

Not a mentor anymore & don't have access to the repo

**Comment by kartikjoshi267** [comment]
@daccdacc @kunjgit Please add `gssoc23` labels! I guess you forgot to add them!

**Pull request merged**
