### PR TITLE
thumbnail images for emoji_intruder and puzzel_winner

### PR DESCRIPTION
**Pull request by bhumika-1127**
@kunjgit issue #3641 has been rectified.

image

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @bhumika-1127 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by bhumika-1127** [comment]
@kunjgit are there any updates about this pull request.

**Review by kunjgit — APPROVED** [review]
LGTM!

**Comment by kunjgit** [comment]
Thank you  @bhumika-1127 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
