### PR TITLE
[New_Game] : Haunting_Game Added

### PR DESCRIPTION
**Pull request by Kalivarapubindusree**
## PR Description 📜

#2395 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Haunting_Game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Kalivarapubindusree ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Kalivarapubindusree** [comment]
Can you please review this pr @kunjgit

**Comment by Kalivarapubindusree** [comment]
Can you please review this pr @kunjgit @gurjeetsinghvirdee

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Remove **Chinese_Checkers.png & Tennis_Game.gif** from **assets/images** `dir`

**Comment by Kalivarapubindusree** [comment]
Can you please ignore the Chinese game image and tennis game image because I can't delete those images kindly ignore those two images and merge the remaining files @gurjeetsinghvirdee

**Comment by gurjeetsinghvirdee** [comment]
> Can you please ignore the Chinese game image and tennis game image because I can't delete those images kindly ignore those two images and merge the remaining files @gurjeetsinghvirdee

I have some doubts, Can you clear it please is this game owned by you
like this 2d game you made in just 4-5 days
I'm a MERN Stack dev, I can't make this in a week or a month even watching tutorial

**Comment by Kalivarapubindusree** [comment]
> > Can you please ignore the Chinese game image and tennis game image because I can't delete those images kindly ignore those two images and merge the remaining files @gurjeetsinghvirdee
> 
> I have some doubts, Can you clear it please is this game owned by you like this 2d game you made in just 4-5 days I'm a MERN Stack dev, I can't make this in a week or a month even watching tutorial

I made this game before of this contribution and I contributed some during this contribution @gurjeetsinghvirdee

**Review by kunjgit — APPROVED** [review]

**Comment by Kalivarapubindusree** [comment]
> > Can you please ignore the Chinese game image and tennis game image because I can't delete those images kindly ignore those two images and merge the remaining files @gurjeetsinghvirdee
> 
> I have some doubts, Can you clear it please is this game owned by you like this 2d game you made in just 4-5 days I'm a MERN Stack dev, I can't make this in a week or a month even watching tutorial

I have made this game before and some modifications are done that to  complete it fully  during this contribution @gurjeetsinghvirdee 
May I know is there anything wrong .
If it is kindly let me know sir.
Thanku

**Comment by Kalivarapubindusree** [comment]
I removed the images and made a new pr can you please review it https://github.com/kunjgit/GameZone/pull/2450
@kunjgit

**Comment by Kalivarapubindusree** [comment]
I made new pr after removing images @kunjgit 
https://github.com/kunjgit/GameZone/pull/2450

**Pull request closed without merging**
