### PR TITLE
Enhancement: All games recovered and 3D box game URL fixed

### LINKED ISSUE #4191: [Enhancement]: 3D box game not available
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement: The 3D box game should not appear at the dashboard, if it is not available.

https://github.com/kunjgit/GameZone/assets/126901961/32fda0e1-cbf0-4bd6-8489-7969d78c2cd8

### Describe the solution you'd like

finding out the game, check if available..
If not available, comment out the part making 3d box appear to dashboard

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by anisharma07**
## PR Description 📜

I fixed the games not showing up issue on the live gamezone website and also fixed url not found for 3d box game...

Fixes #4191

<hr>
 
## Tasks completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

fixed every line of game.json ... numbering was incorrect ... so i corrected it manually and there were some syntax error too...
image

--- 

https://github.com/kunjgit/GameZone/assets/126901961/52512d99-4850-49f2-8d42-94113a29c295

In index.js i corrected the no. of games from 418 to 417 the figure i got from finding length of game.json
image

all rest changes in index.js and script.js are due to my code formatter... you can ignore them they were only indentation changes... you can also check if there is any difference using difference checker website...

<br>
please mark the gssoc labels
## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @anisharma07 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by anisharma07** [comment]
@kunjgit  The games are not displaying on the live website ... this PR fixes the issue .... would be great if you merge it

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by kunjgit** [comment]
Thank you  @anisharma07 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
