### PR TITLE
Vinayak repeat

### LINKED ISSUE #3171: [Bug]: Guess_the_number take 2 guess with 1 input
### Give a brief about the bug ✍️

On giving one input it takes 2 as the same number which reduces the guess chance as guess chance is 10 but it make copy of 1 input and give it as 2 input provided

### What is the expected behavior? 🤔

It should take 1 input as 1 input only so the user can play it correctly

### Provide step by step information reproduce the bug 📄

Make changes in javascript code which makes it 2 times readable

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Vinayakkh**
## PR Description 📜

In Game when click on guess button it operate 2 times on a single integer which decrease the guess chance and 2 times same guess number is operate. I update js file as it runs a function 2 times when click on guess number.
Fixes #3171 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by kunjgit — APPROVED** [review]
LGTM!

**Comment by kunjgit** [comment]
@Vinayakkh please resolve the merge conflicts !

**Comment by Vinayakkh** [comment]
Resolved

**Comment by kunjgit** [comment]
Thank you  @Vinayakkh , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
