### PR TITLE
Added the game Yahtzee

### LINKED ISSUE #4276: [New game]: Yahtzee
### 🎮 Game Request
To add the game of Yahtzee. 
The game consists of thirteen rounds.
Each round begins with the rolling of five dice.
The player is allowed two more rolls within the round.   The player can choose certain dice to hold their values during a reroll.  

### Point down the features
Roll dice for scoring combinations, and get the highest total score.

Yahtzee5

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by pankhuri92**
## PR Description 📜

Fixes #4276

I have added the game of Yahtzee to the repository. The object of the game is to roll certain combinations of numbers with five dice. At each turn you throw dice trying to get a good combination of numbers; different combinations give different scores. 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots 📸
Screenshot 2024-06-08 000638

<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @pankhuri92 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by pankhuri92** [comment]
Kindly review my pr

**Comment by pankhuri92** [comment]
@kunjgit, kindly review my pr

**Comment by pankhuri92** [comment]
@ishita-43 @kunjgit could you please review

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by pankhuri92** [comment]
@kunjgit please merge the issue

**Comment by kunjgit** [comment]
Thank you  @pankhuri92 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by pankhuri92** [comment]
@kunjgit thank you for merging my pr. But it hasn't been assigned to me. Kindly assign it as well since its not reflecting on leaderboard.

**Pull request merged**
