### PR TITLE
Added Rock Paper Scissors Lizard Spock Game

### LINKED ISSUE #4932: [New game]: Rock, Paper, Scissors, Lizard, Spock game
### 🎮 Game Request

Rock, Paper, Scissors, Lizard, Spock is a game of chance that expands the traditional game of Rock, Paper, Scissors and was invented by Sam Kass and Karen Bryla. It was brought to fame after being used to settle a dispute about what to watch on TV between Sheldon and Raj in episode "The Lizard-Spock Expansion" in the famous show "The Big Bang Theory".

# Rules
1. Scissors cuts Paper
2. Paper covers Rock
3. Rock crushes Lizard
4. Lizard poisons Spock
5. Spock smashes Scissors
6. Scissors decapitates Lizard
7. Lizard eats Paper
8. Paper disproves Spock
9. Spock vaporizes Rock
10. (and as it always has) Rock crushes Scissors

Rules

### Point down the features

1. Five choices: Players can choose from Rock, Paper, Scissors, Lizard, or Spock.
2. Balanced gameplay: Each choice can beat two other choices and be beaten by two choices.
3. Reduced tie probability: The additional options decrease the likelihood of ties compared to the original game.
4. Strategic depth: The additional choices add more complexity and strategy to the game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Sam-Orion**
## PR Description 📜

Added the game Rock, Paper, Scissors, Lizard, Spock Game
Fixes  #4932

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
<hr>
ss1
<hr>
ss2
<hr>
ss3
<hr>
ss4

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Sam-Orion ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Sam-Orion** [comment]
@kunjgit @ishita-43 please add GSSOC label on the original issue, i.e., #4932

**Review by ishita-43 — APPROVED** [review]
Ready to merge

**Comment by kunjgit** [comment]
Thank you  @Sam-Orion , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
