### PR TITLE
Added Chicken cannon game

### LINKED ISSUE #2071: [New game]: Chicken cannon
### 🎮 Game Request

The chickens have discovered a new invention... the CANNON. So obviously they load their comrades in and try to DESTROY humanity! In the name of science. The instructions are simple just have to release the chicken at certain projectile motion
a 

### Point down the features

How to play ?
▫ Click to launch your chicken out of the cannon.
▫ Hold down to use your rocket. (Don't run out of fuel)
▫ DESTROY everything in your way.

image

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Bhuvanchand26**
## PR Description 📜

Added Chicken cannon game
Fixes #2071

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Bhuvanchand26 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Bhuvanchand26,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Bhuvanchand26,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by Bhuvanchand26** [comment]
Hey @kunjgit, can you please merge this PR , so that i can sync changes and try to work on other issues
THANK YOU

**Comment by daccdacc** [comment]
Hello, @Bhuvanchand26 You need to make an entry of your game into the main README.md file

**Review by kunjgit — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
Resolve conflicts @Bhuvanchand26

**Comment by Bhuvanchand26** [comment]
@gurjeetsinghvirdee , Resolved conflicts : )

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM 🌸

**Comment by kunjgit** [comment]
Thank you  @Bhuvanchand26 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
