### PR TITLE
Added Conqueror_Quest

### LINKED ISSUE #4963: [New game]: Adding a game Conqueror_Quest
### 🎮 Game Request

You play as main character and you have to choose properly to win this game

### Point down the features

health and xp items
spells and weapons

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by ayush-848**
## PR Description 📜
Added a new game Conquerer_Quest

Fixes #4963

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by ayush-848** [comment]
@ishita-43 please check

**Comment by ayush-848** [comment]
@ishita-43 This game do not have any images

**Comment by ayush-848** [comment]
@ishita-43 please check

**Review by ishita-43 — APPROVED** [review]
Good to go

**Comment by ayush-848** [comment]
@kunjgit please check it

**Comment by ayush-848** [comment]
@kunjgit I have resolved the conflicts, please check it now

**Comment by ayush-848** [comment]
@kunjgit I have resolved the conflicts, please check it now

**Comment by kunjgit** [comment]
Thank you  @ayush-848 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
