### PR TITLE
[New game]: Maze explorer game

### LINKED ISSUE #4758: [New game]: Maze explorer game
### 🎮 Game Request

"Maze Explorer" is a thrilling adventure game where players navigate through intricate mazes, collecting treasures while avoiding obstacles. The goal is to reach the exit before time runs out, exploring multiple levels of challenging puzzles and surprises along the way

### Point down the features

Dynamic Maze Generation: Each playthrough features randomly generated mazes, ensuring a fresh challenge every time.

Treasure Collection: Players must collect treasures scattered throughout the maze to earn points and bonuses.

Time Management: Navigate efficiently to reach the exit before the timer runs out, while avoiding traps and strategically using power-ups for extended gameplay.Game points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
## PR Description 📜

In Maze Explorer, you navigate through a randomly generated maze to reach the exit while avoiding obstacles and collecting items. The game is set in an ocean-themed environment, enhancing the visual experience. Your objective is to find the quickest path to the exit while accumulating points by collecting items.

Fixes #4758 

<hr>
 
## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Maze_Explorer

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @aditya-bhaumik ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by aditya-bhaumik** [comment]
@ishita-43 please review this pull request and merge it

**Review by ishita-43 — APPROVED** [review]
Good to go

**Comment by aditya-bhaumik** [comment]
@kunjgit please merge this pull request

**Comment by kunjgit** [comment]
Thank you  @aditya-bhaumik , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
