### PR TITLE
Update index.html

### LINKED ISSUE #3075: [Bug]: Add copyright label to footer section.
### Give a brief about the bug ✍️

Hello PA,
The footer section of website is missing the copyright label.

### What is the expected behavior? 🤔

We need to add a copyright notice to comply with legal requirements and protect our content.

### Provide step by step information reproduce the bug 📄

I will add a copyright notice similiar to below image of a random website.
329570271-374c7e13-140d-4ed3-9a97-8ce2095aa90a

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by dishathakurata**
## PR Description 📜

Added a copyright label in the footer
Fixes #3075 

<hr>
 
## Mark the task you have completed ✅

- [.] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [.] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [.] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [.] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Suggest any changes you want me to make
copyright

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @dishathakurata ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by dishathakurata** [comment]
Please assign this issue to me under GSSoC '24
Thank you in advance @kunjgit 💗

**Comment by kunjgit** [comment]
you are not having significant changes in this PR you can assign yourself an issue as shown in instructions make sure that you are having proper changes then only making PR !

**Comment by kunjgit** [comment]
Thank you  @dishathakurata , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
