### PR TITLE
pong

### LINKED ISSUE #640: [New game]: Pong
### 🎮 Game Request

Game logic and basic description
The game is designed to be played by two people on a ping pong table.

### Point down the features

Game points
The game has a counter which will track the points gained by the user. The user who will first score 5 points will be the winner. The paddles can be controlled on the same keyboard using the arrow keys and w-s keys.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by patnaikankit**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #640

In this commit, I have added the game of pong . Pong is a two-player game where each player controls a paddle to hit a ball back and forth. 

<hr>
 
## Mark the task you have completed ✅

- [ +] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ +] I have performed a self-review of my own code or work.
- [ +] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ +] I have added screenshot for website preview in assets/images 
- [ +] I have added entries for my game in main README.md
- [+ ] I have added README.md in my folder 
- [+] I have added my issue number

<hr>

## Add your screenshots(Optional) 📸
pong

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @patnaikankit ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
make sure you follow guidelines and create PR again

**Comment by kunjgit** [comment]
Thank you  @patnaikankit , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by patnaikankit** [comment]
@kunjgit I have made some changes to Pong but I would like to know what were the exact problems with my previous PR so that I can make this one perfect. Please let me know what are changes that you would like to see in this PR.

**Pull request closed without merging**
