### PR TITLE
Added Physics quiz game: #4092

### LINKED ISSUE #4092: [New game]: Physics quiz:
### 🎮 Game Request

The game will generate random physics questions, the player has to give as many correct answer as possible in 1 min.

### Point down the features

Game points:
To every correct ans 1 point is awarded.
After the completion of the game their points will be shown.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Anshika14528**
## PR Description 📜
Created a Physics Quiz Game in which you have to answer as many question as possible within 1 minute.
Fixes #4092

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2024-06-02 at 6 50 16 PM

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Anshika14528 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Anshika14528** [comment]
@kunjgit sir , Please review it.

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Game doesn't work properly!!
Make sure to try running it locally and making sure that the start button works and shows properly and it shows options to select correct answer.

I hope you will make desired changes soon!!

**Comment by Anshika14528** [comment]
@ishita-43 mam , i have made the required changes please review it now

**Review by ishita-43 — APPROVED** [review]
Thanks for implementing the changes.
Result is good and ready to merge!! ☺

**Comment by Anshika14528** [comment]
Thankyou mam

**Comment by kunjgit** [comment]
Thank you  @Anshika14528 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
