### PR TITLE
added Planet Savior game 👍

### LINKED ISSUE #2506: [New game]: Planet Savior
### 🎮 Game Request

This is a simple browser game built using HTML, CSS, and Vanilla JavaScript. The game involves shooting down asteroids to protect a planet.

## Features

- Player-Controlled Spaceship: The player controls a spaceship that is represented by a rotating image. The spaceship's orientation changes based on the mouse's position relative to the center of the canvas. The spaceship is used to shoot bullets at the incoming asteroids.

- Shooting Mechanism: When the player clicks on the canvas, the spaceship fires bullets in the direction of the click. The bullets move upward from the spaceship, trying to hit and destroy the incoming asteroids.

- Asteroids: Asteroids are represented by rotating images and move towards the planet in different directions. The player must destroy the asteroids by shooting them with bullets. Each destroyed asteroid increases the player's score.

- Explosions: When an asteroid is hit and destroyed, an explosion effect is shown at the asteroid's location. The explosion animation adds visual feedback to the player's successful shots.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by sabhisharma-ise**
## PR Description 📜

This is a simple browser game built using HTML, CSS, and Vanilla JavaScript. The game involves shooting down asteroids to protect a planet. Here's a beginner-friendly description of the game and its features:

Fixes #2506 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Planet_Savior

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @sabhisharma-ise ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by sabhisharma-ise** [comment]
@gurjeetsinghvirdee I've added the Game + fixed counting issue of games in the main README.md
Kindly have a review!

**Comment by sabhisharma-ise** [comment]
@gurjeetsinghvirdee check now!

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Code Copied from here: **https://github.com/MarcLopezAvila/planet-defense-game**
Live View: **https://marclopezavila.github.io/planet-defense-game/**

**Pull request closed without merging**
