### PR TITLE
Random Advice Generator

### LINKED ISSUE #3593: [New game]: Random Advice Generator
### 🎮 Game Request

This random advice generator generates a new and random advice each time the button is clicked.

### Point down the features

This uses a random advice generator api to generate a new and random advice which is the implemented using HTML,CSS and JavaScript.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by meetarora10**
## PR Description 📜
A completely responsive random advice generator app which will generate a new and random advice each time the visitor clicks on the button.
It uses a random advice api implemented using HTML,CSS,JavaScript.

Fixes #3593

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot (435)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @meetarora10 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
@meetarora10 resolve merge conflicts !

**Comment by meetarora10** [comment]
@kunjgit  I have made the changes.

**Comment by meetarora10** [comment]
@kunjgit please take a moment to review this PR

**Comment by kunjgit** [comment]
Thank you  @meetarora10 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @meetarora10,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by kunjgit** [comment]
Hey @meetarora10,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Pull request merged**
