### PR TITLE
Green Mahjong

### LINKED ISSUE #1501: [New game]:  Green-mahjong
### 🎮 Game Request

Mahjong game offers players the classic experience of matching identical pairs of tiles on a board. The starting page presents the shape of the board, and players can choose the difficulty level before beginning the game. Once the board is selected, the objective is to make matches by selecting two tiles at a time. Each time a pair of identical tiles is matched, the player's score increases by 2 points.

Game Logic:

1.Set up the board:

Create a grid or layout for the Mahjong board.
Populate the board with Mahjong tiles. Each tile should have a unique identifier and an associated image or symbol.
Randomly distribute the tiles across the board, ensuring that each tile is hidden from view initially.

2. Player interaction:

Allow the player to select two tiles at a time. When a tile is selected, it should become visible to the player.
If the two selected tiles match, remove them from the board. If they don't match, hide them again.
Keep track of the player's score, initially set to 0.

3. Matching logic:

Determine the matching criteria for tiles. Typically, Mahjong tiles can match if they have the same symbol or number.
Implement logic to check if the two selected tiles match according to the matching criteria.
If the tiles match, remove them from the board and increase the player's score by 2 points.
If the tiles don't match, hide them again, and the player's score remains unchanged.

4. Win condition:

Continuously check if all the tiles have been removed from the board.
If all the tiles are removed, the player has won the game. Display a victory message and the final score.

### Point down the features

1. Matched Pair: When the player successfully matches a pair of identical tiles, their score increases by 2 points. This encourages the player to make accurate and efficient matches.

2. Incorrect Match: If the player selects two tiles that don't match, their score remains unchanged. This emphasizes the importance of memory and concentration in the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by U-DAY-333**
## PR Description 📜

Adding new game : Green Mahjong
Fixes #1501

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot 2023-06-12 191735
Green Mahjong

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @U-DAY-333 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @U-DAY-333,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @U-DAY-333,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by U-DAY-333** [comment]
I have modified all the changes. @kunjgit please can you mention the additional changes that i need to change

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @U-DAY-333,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by U-DAY-333** [comment]
i have made the changes. @kunjgit review it

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @U-DAY-333,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Pull request merged**
