### PR TITLE
Tic tac toe

### LINKED ISSUE #4095: [Enhancement]: Tic Tac Toe Game
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement :
- A better version of exisiting Tic Tac Toe Game

### Describe the solution you'd like

Solution steps :
- You can preview it here : [Tic Tac Toe](https://oxoxgame.netlify.app/)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Apurv7777**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #4095 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Apurv7777 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Apurv7777** [comment]
### Please merge, if no changes are required . @kunjgit

**Comment by Apurv7777** [comment]
### Please merge, if no changes are required . @kunjgit

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Make sure to modify the main README.md file and add your game their.

**Comment by Apurv7777** [comment]
> Make sure to modify the main README.md file and add your game there.

As this is the update of the game, which is already added in README.md. Modification is not require, I guess. @ishita-43

**Review by ishita-43 — APPROVED** [review]
Good to go!! 🎊

**Comment by kunjgit** [comment]
Thank you  @Apurv7777 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
