### PR TITLE
Added sliding game

### LINKED ISSUE #4644: [New game]: Sliding Game
### 🎮 Game Request

* It's a 4x4 grid with 15 numbered tiles and one empty space.
* Players slide tiles into the empty space to reorder them numerically, ending with 1 in the top left and progressing to 15 in the bottom right.
* Swiping a tile checks if the empty space is adjacent. If so, the tiles swap positions.

### Point down the features

* Single-player tile puzzle game.
* Slide numbered tiles (1-15) to reorder them in sequence. 
* Empty space allows tile movement. 
* Goal: Reach order from 1 (top-left) to 15 (bottom-right). 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

Sliding_Game

### PR DESCRIPTION
**Pull request by muskan42**
## PR Description 📜

Added Sliding Puzzle Game

Fixes #4644 4644

<hr>
 
## Mark the task you have completed ✅

- [ x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x ] I have performed a self-review of my own code or work.
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ x ] My changes generates no new warnings.
- [ x ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ x ] I have added screenshot for website preview in assets/images 
- [ x ] I have added entries for my game in main README.md
- [ x ] I have added README.md in my folder 
- [ x ] I have specified the respective issue number for which I have requested the new game.

<hr>

Sliding_Game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @muskan42 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by muskan42** [comment]
@ishita-43 please review

**Review by ishita-43 — APPROVED** [review]
Approved

**Comment by TanviGandhotra** [comment]
@muskan42 i am not able to clone this repo will u help me as u were abled. dont you get this issue
image

**Comment by kunjgit** [comment]
Thank you  @muskan42 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
