### PR TITLE
Multiplayer-Chess

### LINKED ISSUE #3153: [New game]: CHESS
### 🎮 Game Request

Making the chess game 

### Point down the features

Game points

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Ashutosh-0506**
## PR Description 📜

I have created a new MULTIPLAYER CHESS game using WEB Sockets. This can be played on multiple devices and is not static as other frontend Chess games as it is a full stack Web dev project.
This uses major  Techstacks such as React,Tailwind CSS ,Sockets.io.
Fixes #3153

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Ashutosh-0506 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by ishita-43** [comment]
Resolve nerge conflicts or create new pr

**Comment by kunjgit** [comment]
Thank you  @Ashutosh-0506 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by ishita-43** [comment]
Closing thus or

**Pull request closed without merging**
