### PR TITLE
Added responsive NavBar in the Homepage. issue #3577

### LINKED ISSUE #3577: [Enhancement]: Adding Navbar to the Homepage for better user experience
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

I want to add Navbar with features like home, contact us, contributors,user manual, and feedback

### Describe the solution you'd like

Solution steps - for this task I will use HTML & CSS with its required properties to create a Navbar and will also add hover effect to make it more attractive.Please assign me this task @kun

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by HarshitGupta1511**
## PR Description 📜

Added responsive Navbar in the homepage for easy navigation and to make homepage much for systematic. Added a low color gradient background to navbar to make it more related to our website.
Fixes #3577 

<hr>
 
## Mark the task you have completed ✅

- [x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I have added screenshot for website preview in assets/images 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Before
Screenshot 2024-06-19 at 1 51 17 PM

After

Screenshot 2024-06-19 at 1 52 06 PM
Screenshot 2024-06-19 at 1 52 35 PM

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @HarshitGupta1511 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by HarshitGupta1511** [comment]
Please review and merge my PR @kunjgit @ishita-43

**Comment by ishita-43** [comment]
above after image is only applicable short screens or also for large ones?

**Comment by HarshitGupta1511** [comment]
It's for both

**Comment by HarshitGupta1511** [comment]
The added navbar is responsive and compatible with all screen sizes

**Review by ishita-43 — APPROVED** [review]
Ok!! Approved

**Comment by HarshitGupta1511** [comment]
@ishita-43 why it changed to level 1 from level 2? please label it with level 2

**Comment by ishita-43** [comment]
Enhancement tag cause to level the issue 
PR label is given only after review after seeing quality/impact and quantity of the pr,
and we thought the navbar can be enhanced more and more tailored to the home page style 
thats why its label is 1.

**Comment by kunjgit** [comment]
Thank you  @HarshitGupta1511 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
