### PR TITLE
Added Instructions in Simon game with screenshot in readme file (#69)

### PR DESCRIPTION
**Pull request by Yashika-Agrawal**
## PR Description 📜
I have added instructions of the Simon game with the objective of the game and also added screenshot of new UI to the readme fille. The instructions div is responsive to all screen sizes, in small screen size it is vertically stacked below the game.

Fixes # <#69>

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Yashika-Agrawal ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @Yashika-Agrawal 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Review by Durgesh4993 — APPROVED** [review]

**Comment by Durgesh4993** [comment]
@Yashika-Agrawal Could you please add a short video of game  in Readme of the game (As Admin said)

**Comment by Yashika-Agrawal** [comment]
> @Yashika-Agrawal Could you please add a short video of game in Readme of the game (As Admin said)
Hello @Durgesh4993 , Yea i can add a short video or gif of the Simon game , but as the readme file is update do I need to raise a separate PR for that?

**Comment by kunjgit** [comment]
Hey @Yashika-Agrawal 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by Yashika-Agrawal** [comment]
> @Yashika-Agrawal Could you please add a short video of game in Readme of the game (As Admin said)

Hey @Durgesh4993 , I have added gif in the readme file.

**Pull request merged**
