### PR TITLE
first contribution in gssoc

### PR DESCRIPTION
**Pull request by Khaleeq01**
I added Ping_Pong Game project made by using Html, Css and Javascript Issue Number is #79

I want to make smaller and easier version of this game. The main points for the game are -

There will be 2 rods at the top and bottom of the screen.
Both rods will be controlled with the same keys. In other words, they will move together.
When the game starts, an alert should be shown about the highest score and the player who scored it. If there is no such record, say 'this is your first time'.
If the score becomes highest, then store the name and max-score in local storage.
After every round, when one wins an alert will be displayed showing the winning player and his score
Point down the features
Every round should start when the 'Enter' key is pressed. ( You can use another key as well )
The rods will only move horizontally using the 'a' and 'd' keys. ( You can use other keys as well )
The losing rod will get the ball for the next match and the rods and ball will move to center.
The score will be counted from the start of every match.

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Khaleeq01 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @Khaleeq01 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by Durgesh4993** [comment]
@Khaleeq01 Please read guidlines which mentioned in Readme file and also provide issue number and Game details

**Comment by Khaleeq01** [comment]
@Durgesh4993 Should i provide the  Game details and issue number in comment section or create new Pull request. I write the game details in readme.md file

**Comment by Khaleeq01** [comment]
@Durgesh4993 and @kunjgit Please have a look i update the PR

**Comment by kunjgit** [comment]
Hey @Khaleeq01 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @Khaleeq01 !! still you are not adding image in assets and make your game entry in main README file !! 👀

**Comment by kunjgit** [comment]
Hey @Khaleeq01 follow proper guideline and make PR again

**Comment by kunjgit** [comment]
Thank you  @Khaleeq01 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Khaleeq01** [comment]
@kunjgit why are you closing this one will you tell me where i am wrong i did not understand

**Pull request closed without merging**
