### PR TITLE
Added Spiderman Game

### LINKED ISSUE #1865: [New game]: Spider Attack
### Game logic and basic description -
It's a spider game which I'm making using HTML, CSS & JavaScript.
It will contain Man with a Gun to shoot Spiders . 👍🏻 

### Point down the features

Game Includes Sounds, Gun, Spider, Man, Pop-Up and few more functionality.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
## Added Spider Game

I have added the **Spider Man** Game which developed using HTML, CSS, JavaScript also I have used sound and theme designs and I have used the key listeners for the optimize and smooth gameplay.
### Fixes #1865 

<hr>
 
## Mark for Completed tasks 💯 

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Screenshot -
Screenshot from 2023-06-23 02-30-33

## Video -

[Screencast from 23-06-23 02:31:41 AM IST.webm](https://github.com/kunjgit/GameZone/assets/121503426/edbab326-9a7d-45b0-af69-1904cbf3fa83)

---

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @SyedImtiyaz-1 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @SyedImtiyaz-1,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @SyedImtiyaz-1,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @SyedImtiyaz-1,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @SyedImtiyaz-1,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by SyedImtiyaz-1** [comment]
@kunjgit ,
I have fixed the  conflicts.

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @SyedImtiyaz-1,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by kunjgit** [comment]
make sure you are not doing the changes in the game data !!! 
create PR again by not altering any other info !!

**Comment by kunjgit** [comment]
Thank you  @SyedImtiyaz-1 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
