### PR TITLE
Dragon World Game

### LINKED ISSUE #3148: [New Game]: Dragon World Game
### 🎮 Game Request

In this game there will be a dragon that will jump over the obstacle let's say another dragon. It will be interesting and full of fun.

### Point down the features

Animation
Music
Full of Fun

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by VaibhavS0710**
## PR Description 📜

I have developed a new game using HTML, CSS, and JS
Fixes #3148 

<hr>
 
## Mark the task you have completed ✅

- [x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x ] I have added screenshot for website preview in assets/images 
- [x ] I have added entries for my game in main README.md
- [x ] I have added README.md in my folder 
- [x ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Dragon_Gamee

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @LordVaibhav ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by LordVaibhav** [comment]
Please @kunjgit  merge this PR.

**Comment by VaibhavS0710** [comment]
@kunjgit please merge this PR.

**Review by kunjgit — CHANGES_REQUESTED** [review]
@VaibhavS0710 you are not following proper guidelines make sure you are looking at documentation once again and folder readme template is for reference so that everyone can have look at base template and use it you should not add your details there !

**Comment by VaibhavS0710** [comment]
@kunjgit can you please guide me how I have to change. It will be very helpful for me as a beginner.

**Comment by VaibhavS0710** [comment]
@kunjgit please review the updated PR.

**Comment by VaibhavS0710** [comment]
@kunjgit please verify it if everything is alright

**Comment by kunjgit** [comment]
@VaibhavS0710 already the game is there on GameZone even graphics are same and we are not encouraging to adding same game again and again will recommend you to come up with some new ideas !

**Comment by kunjgit** [comment]
Thank you  @VaibhavS0710 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
