### PR TITLE
Added Otherworldly Odyssey game

### LINKED ISSUE #4809: [New game]: Otherworldly Odyssey
### 🎮 Game Request

It's an adventure role playing game where players will journey through a magical realm full of fantastic creatures, deadly challenges, and hidden surprises.

### Point down the features

1. This game would have an innovative XP system which would make it more engaging and fun to play.
2. A money system which can be used to buy various products.
3. A shop where the adventurers can buy elixirs to increase or recover their health or weapons ranging from a simple dagger to a legendary magic wand.
4. Player can earn money and farm XP by fighting various monsters to ultimately challenge the greatest threat this realm has ever faced an "Ancient Dragon".

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Sam-Orion**
## PR Description 📜

Added the game Otherworldly Odyssey where the player goes on an adventure to vanquish monsters from a kingdom.
Fixes #4809 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot (2)
Screenshot (3)
Screenshot (4)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Sam-Orion ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Sam-Orion** [comment]
@kunjgit and other reviewers, please add Gssoc label on the original issue i.e., #4809

**Review by ishita-43 — APPROVED** [review]
Good to go

**Comment by Sam-Orion** [comment]
@ishita-43 please add the labels

**Comment by Sam-Orion** [comment]
@kunjgit @ishita-43  please add the label, the PR has already been approved and is ready to merge.

**Comment by Sam-Orion** [comment]
@ishita-43 @kunjgit  Resolved conflicts,  you can merge now

**Comment by kunjgit** [comment]
Thank you  @Sam-Orion , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
