### PR TITLE
Added [New game]: Gobblet #3410

### LINKED ISSUE #3410: [New game]: Gobblet
### 🎮 Game Request

Gobblet is a strategic game where players place and stack pieces to form a line of five. The twist is that players can "gobble" their opponent's pieces by placing a larger piece over a smaller one, creating a dynamic and strategic game.
Gobblet Rule: Players can place their pieces on the board or stack them over their opponent's smaller pieces, effectively taking control of that spot.
Objective: The goal is to form a line of five pieces of your color in any direction (horizontally, vertically, or diagonally) to win the game.
You have different 4 sizes and 2 of each

### Point down the features

Game points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by dsyste20**
[New game]: Gobblet #3410
Add the finished game

## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below

Gobblet is a strategic game where players place and stack pieces to form a line of five. The twist is that players can "gobble" their opponent's pieces by placing a larger piece over a smaller one, creating a dynamic and strategic game.

Fixes #3410 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>
--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @dsyste20 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by dsyste20** [comment]
@ishita-43 can you please review this pr?

**Review by ishita-43 — APPROVED** [review]
Good to go !!

**Comment by kunjgit** [comment]
Thank you  @dsyste20 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
