### PR TITLE
Feat: Added Jigsaw Puzzle Game

### LINKED ISSUE #4676: [New game]: Adding the Jigsaw Puzzle Game
### 🎮 Game Request

**Game logic and basic description:**

I would like to request the addition of a classic jigsaw puzzle game to the site. This game will allow users to upload any image and transform it into a jigsaw puzzle with varying difficulty levels. Users can select from 12, 25, 50, 100, or 200 pieces to create a customized and engaging puzzle-solving experience.

### Point down the features

**Game points:**

- Image Upload: Users can upload their own images to create unique puzzles.
- Piece Selection: Choose from different puzzle sizes (12, 25, 50, 100, 200 pieces) for varying difficulty.
- Interactive Gameplay: Drag and drop pieces to solve the puzzle.
- User-Friendly Interface: Easy-to-use interface for a smooth and enjoyable user experience.
- Responsive Design: Fully responsive design to ensure compatibility across different devices.

This game will add a fun and interactive element to the site, appealing to users of all ages. It promotes problem-solving skills and provides a relaxing activity for users to enjoy.

**Screenshots:**

Screenshot (61)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by shreyash3087**
## PR Description 📜

This PR adds a new classic jigsaw puzzle game to the repository. The game allows users to upload any image and create a jigsaw puzzle with varying difficulty levels (12, 25, 50, 100, 200 pieces). The game is interactive, featuring drag-and-drop functionality for solving the puzzle. It also includes and a responsive design for compatibility across different devices.

Fixes #4676

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your video(Optional) 📸

https://github.com/kunjgit/GameZone/assets/72603662/cd30c976-d12a-465c-ab00-5b26dded4b20

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @shreyash3087 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by shreyash3087** [comment]
@ishita-43 Kindly Review

Thankyou

**Review by ishita-43 — CHANGES_REQUESTED** [review]
please also make your game entry into the readme.md file of the repo refer other entries for the format

**Comment by shreyash3087** [comment]
@ishita-43 Done

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by kunjgit** [comment]
Thank you  @shreyash3087 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
