### PR TITLE
[New Game] Drum kit added

### LINKED ISSUE #4876: [New game]: Drum kit
### 🎮 Game Request

Game logic and basic description : Introducing Drum Kit, a fun and interactive game where you can play different drums using your keyboard or by clicking on drum images. Each drum has its own unique sound. Tap the corresponding keys or click the drums to create awesome beats and enjoy making music!

### Point down the features

Game points :  does not have a point system but fun for user 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by shellygarg10**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #4876 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @shellygarg10 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — APPROVED** [review]
Approved

**Comment by shellygarg10** [comment]
hi @kunjgit @ishita-43  Is there anything else I need to do before it can be merged?

**Comment by ishita-43** [comment]
> hi @kunjgit @ishita-43 Is there anything else I need to do before it can be merged? Also in issue it is labelled as level 3 here it is labelled as level 2 !

You need to resolve the arising merge conflicts in readme.md file

**Comment by shellygarg10** [comment]
@ishita-43 I resolved the arising merge conflicts in readme.md file. I hope there is no issue anymore

**Comment by ishita-43** [comment]
> @ishita-43 I resolved the arising merge conflicts in readme.md file. I hope there is no issue anymore

Pr will soon be merged by the admin

**Comment by kunjgit** [comment]
Thank you  @shellygarg10 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
