### PR TITLE
Created new game, issue #3724

### LINKED ISSUE #3724: [New game]: Fruit Catch Game
### 🎮 Game Request

The player controls a basket at the bottom of the screen to catch fruits falling from the top. The game ends when the player misses 5 fruits. 
source

### Point down the features

- Levels and Difficulty: Increase the speed and frequency of falling fruits as the player's score increases.
-  Different Fruit Types: There will be different types of fruits.
- Friendly user interface

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by its-kritika**
## PR Description 📜
It is a fun game of fruit catching where a user controls basket to catch fruits. It has many features:
- **Multiple Fruit Types**: Catch various types of fruits such as apples, oranges, and more, each with their own unique appearance.
- **Scoring System**: Track your current score and lives.
- **Persistent Highest Score**: Highest score is saved locally in your browser.
- **Game Over Popup**: A popup appears with a restart button when the game is over.

Fixes #3724

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
**Game Start:**
Screenshot (403)

**Game Board:**
Screenshot (399)

**Game Over:**
Screenshot (402)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @its-kritika ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @its-kritika,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @its-kritika,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by its-kritika** [comment]
@kunjgit  I have made the necessary changes

**Comment by its-kritika** [comment]
@kunjgit I have made the necessary changes. Please review

**Comment by kunjgit** [comment]
Thank you  @its-kritika , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
