### PR TITLE
Fixed Multiple Semantic Errors-HTML5

### PR DESCRIPTION
**Pull request by NarendraKoya999**
## PR Description 📜
**I am working under GSSOC'23**
Fixes # <your_issue_number: #620> in `index.html`
##Issue No-1:
**Live Code:**
```
<html>
  <head></head>
  <body>
<main>
  <!--Nav Bar-->
  <ul>
  <li></li> ---> Multiple <li> tags here basis on Several Projects
  </ul>
<footer></footer>
</main>
</body>
  <script></script> --->Multiple <script> Tags Here
</html>
```
##Issue No-2:
**Live Code:**
```
<html>
<head></head>
<body>
<header>
    <nav></nav> --->Moved NAV BAR From <main> section to separate <header> section at top of the <body> section
</header>
<main>
  <section>
    <ul>
    <li></li> ---> Multiple <li> tags here basis on Several Projects
    </ul>
  </section>
</main>
<footer></footer> ---> Moved <footer> From <main> to separate <footer> section out of the <main> section

 <script></script> --->Multiple <script> Tags Here- Moved <script> Tag From outside of the <body> to the inside of 
                                     <body> section
</body>

</html>
```
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
**##Explaination about Issues:** 
**About `<script></script>` Tag:**
- Scripts can be placed in the <body>, or in the `<head>` section of an HTML page, or in both.
- For scripts that are critical to the page contents and should be loaded first such as **Analytics, API, or authentication-type of scripts**, it is recommended to place them in the head section of the HTML page.
- Other script tags should be placed at the bottom of the page before the closing` </body>` tag. These are scripts that you can afford to load after the web page is rendered like **jQuery or animations script** at the end.

About `<header>, <main>, <footer>`:
-In general, it is a good practice to place the `<header>` tag outside of the `<main>` tag, this is because the **header usually contains content that is shared across multiple pages, such as a logo, a navigation menu, and other elements that are not unique to a specific page, whereas the main content should be unique to each page.**
- In`<footer></footer> `section,Footer Element Better to use outside of the `<main> `content for **SEO Optimization and Page Loads.**
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @NarendraKoya999 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by NarendraKoya999** [comment]
I resolved Merge Conflicts and Please Check @kunjgit once

**Comment by kunjgit** [comment]
tag the issue you are working on and then make PR !!

**Comment by kunjgit** [comment]
Thank you  @NarendraKoya999 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
