### PR TITLE
restarts automatically and no scrolling up down pressing arrows:SNAKE

### LINKED ISSUE #328: [Enhancement]: after the game over alert in the snake game, make the game restart automatically
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement: I would like to have the game restart automatically once over instead of having the user to restart the webpage. Also i'd like to change the css a bit so that the entire game stays in a single frame and user wont need to scroll down to the bottom.
please assign this to me under GSSOC'23. Great project btw✌

### Describe the solution you'd like

Solution steps: in the script.js after the alert function we can add a restart function.

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Lakshyyaa**
## PR Description 📜

Fixes #328 

<hr>

game restarts when player loses, player wont have to manually reload the page everytime(snake game)
when arrow keys pressed, no scrolling up/down happens now as it used to(snake Game)

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Lakshyyaa ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@Lakshyyaa Plz add the screenshot of the section where you have changed.

**Comment by Lakshyyaa** [comment]
the entire game now fits in a single frame like so: 
image
so no scrollbar is showing and hence no scrolling movement on clicking arrows that were for the game

**Comment by Arun9739** [comment]
@Lakshyyaa LGTM

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Lakshyyaa , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
