### PR TITLE
Added Tower Of Hanoi game

### LINKED ISSUE #1411: [New game]: Tower Of Hanoi
### 🎮 Game Request

The Tower of Hanoi is a classic mathematical puzzle or game that consists of three rods and a set of disks of different sizes. The puzzle starts with all the disks stacked in ascending order of size on one rod, with the largest disk at the bottom and the smallest at the top. The objective is to transfer the entire stack of disks to another rod, while following certain rules.

The rules are as follows:

- Only one disk can be moved at a time.
- Each move consists of taking the top disk from one of the rods and placing it on top of the stack on another rod.
- A larger disk should never be placed on top of a smaller disk. In other words, at any point during the game, each rod should maintain the order of disk sizes with the largest disk at the bottom and the smallest at the top.

### Point down the features

- Problem-Solving: The Tower of Hanoi puzzle requires logical thinking, problem-solving skills, and careful planning. 
- Mathematical Application: The Tower of Hanoi puzzle has connections to various mathematical concepts, including number theory, combinatorics, and binary representation. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by AnkitaBarbora**
## PR Description 📜

I have added the HTML, CSS and JavaScript files for the game. I have also created a README according to the template given in the repository. 

Fixes #1411

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.
- [x] I have added working video of the game in README.md (optional)

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @AnkitaBarbora ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — APPROVED** [review]

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @AnkitaBarbora , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @AnkitaBarbora,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by AnkitaBarbora** [comment]
Okay Sir, thank you.

**Pull request merged**
