### PR TITLE
Astronaut_runner

### LINKED ISSUE #3331: [New game]: astronaut runner
### 🎮 Game Request

It is kind of like the mario game, the astronaut runs to an infinite distance avoiding the obstacles provided.

### Point down the features

features will include:
the creation of the player
gravity
player movements
level creation and much more

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by tanishkaa08**
## PR Description 📜

Created a new game called Astroaut runner.
Fixes #3331 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 

- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @tanishkaa08,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Review by kunjgit — CHANGES_REQUESTED** [review]
@tanishkaa08 in root assets/images don't add all assets you want in your game just screen shot of you game should be there !
if you need more images add it in your directory!

**Comment by kunjgit** [comment]
@tanishkaa08 resolve the merge conflicts !

**Comment by kunjgit** [comment]
Thank you  @tanishkaa08 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @tanishkaa08,
You need to make the following changes:
  - Please create a new folder inside the "Games" folder.
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by tanishkaa08** [comment]
please review it.

**Comment by tanishkaa08** [comment]
and if possible tell the issue and also how to solve it.

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @tanishkaa08 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
