### PR TITLE
Game uploaded , Readme added, SS uploaded

### PR DESCRIPTION
**Pull request by kushaljgec2025**
## PR Description 📜

Fixes #2912 

<hr>
 
## Mark the task you have completed ✅

- [ 1] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [1] I have performed a self-review of my own code or work.
- [ 1] I have commented my code, particularly in hard-to-understand areas.
- [ 1] My changes generates no new warnings.
- [ 1] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ 1] I have added screenshot for website preview in assets/images 
- [1 ] I have added entries for my game in main README.md
- [1 ] I have added README.md in my folder 
- [ 1] I have added working video of the game in README.md (optional)
- [ 1] I have specified the respective issue number for which I have requested the new game.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @kushaljgec2025 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @kushaljgec2025,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by kunjgit** [comment]
Thank you  @kushaljgec2025 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kushaljgec2025** [comment]
why it's closed

**Pull request closed without merging**
