### PR TITLE
Added Mathematics Escape Room Game

### LINKED ISSUE #4542: [New game]: Mathematics Escape Room
### 🎮 Game Request

Mathematics Escape Room is a game where the player solves math puzzles to progress through different rooms of an imaginary escape room.
Players navigate through different rooms by solving mathematical puzzles.
Each room presents a new challenge or puzzle related to a specific mathematical concept.

### Point down the features

Room Navigation:

Players navigate through different rooms by solving mathematical puzzles.
Each room presents a new challenge or puzzle related to a specific mathematical concept.

Progression System:

Players advance from one room to the next upon solving the puzzle correctly.
Each room's puzzle difficulty can increase progressively.

Feedback :

Immediate feedback on each puzzle attempt (correct or incorrect).

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by tanishaprasad**
## PR Description 📜

Added a new game 'Mathematics Escape Room'
Fixes #4542 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

MathematicsEscapeRoom

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @tanishaprasad ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by tanishaprasad** [comment]
@kunjgit Please review my pr so that i can work on another issue in your repository.

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Please do the following changes
add your game entry into the main readme.md file of the repo
refer other entries for the format

**Comment by tanishaprasad** [comment]
> Please do the following changes add your game entry into the main readme.md file of the repo refer other entries for the format

@ishita-43 I have done the required changes.

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by kunjgit** [comment]
Thank you  @tanishaprasad , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
