### PR TITLE
Added Hexsweep Game

### LINKED ISSUE #4768: [New game]: Hexsweep Game
### 🎮 Game Request

Game logic and basic description - Hex Sweep is a strategic puzzle game where players clear a hexagonal grid by identifying and marking mines based on numerical clues. It combines elements of logic and deduction, challenging players to carefully analyze the board and make precise moves to avoid triggering hidden mines.

### Point down the features

Game points - In Hex Sweep, players earn points by correctly identifying and marking all the mines on the grid without triggering any. Points are awarded based on the speed and accuracy of their moves, with bonus points for completing more challenging levels.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by ananyag309**
## PR Description 📜
Added Hexsweep Game
Fixes #4768 

<hr>
 
## Mark the task you have completed ✅

- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- ✅[ ] I have added screenshot for website preview in assets/images 
- [ ✅] I have added entries for my game in main README.md
- [✅ ] I have added README.md in my folder 
- [✅ ] I have added working video of the game in README.md (optional)
- [✅ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

https://github.com/kunjgit/GameZone/assets/145869907/a52beb46-c821-4dfc-8147-df43bdc6cd4d

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @ananyag309 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by ananyag309** [comment]
@ishita-43 ma'am please have a check and let me know if any changes are required.

**Review by ishita-43 — APPROVED** [review]
Ready to merge!!

**Comment by ananyag309** [comment]
@kunjgit sir please merge it

**Comment by kunjgit** [comment]
Thank you  @ananyag309 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by ananyag309** [comment]
@kunjgit sir i have resolved the conflicts

**Comment by kunjgit** [comment]
Thank you  @ananyag309 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
