### PR TITLE
Adding sudoku game.

### LINKED ISSUE #256: [New game]: sudoku
### 🎮 Game Request

Game logic and basic description:

Sudoku is a logic-based puzzle. It is a type of constraint satisfaction problem, where the solver is given a finite number of objects (the numerals 1-9) and a set of conditions stating how the objects must be placed in relation to one another. The puzzle consists of a 9×9 grid further divided into nine 3×3 sub-grids (also called boxes, blocks, regions, or sub-squares).

### Point down the features

Game points

The objective is to place the digits within the grid so that each column, row, and sub-grid contains all of the digits from 
1 to 9. Each puzzle is published with some of the boxes already filled in, and those constraints help define the problem's difficulty level.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by lakshmiprasannakusumanchi**
## PR Description 📜
I build a sudoku game using html,css,javascript with new features(provided with clear desciption in the newely added readme file) and I successfully added the new game( sudoku ) assigned to me.

Fixes #256

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

sudoku

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @lakshmiprasannakusumanchi ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
don't alter main index file

**Comment by lakshmiprasannakusumanchi** [comment]
@kunjgit I didn't understand the changes you are asking for but I need to change main index file for adding the new game know sir.

**Comment by lakshmiprasannakusumanchi** [comment]
@kunjgit I have updated main index file so please review it.

**Comment by lakshmiprasannakusumanchi** [comment]
@kunjgit Could you please check out my PR and merge it to the main branch.

**Comment by lakshmiprasannakusumanchi** [comment]
@kunjgit It's been a week since you are not merging my PR so please look into this I resolve of the problems.

**Comment by kunjgit** [comment]
It is still having conflict with main index file please make sure you follow guidelines and create PR again !!

**Comment by kunjgit** [comment]
Thank you  @lakshmiprasannakusumanchi , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
