### PR TITLE
Added Rocket_Ride

### LINKED ISSUE #4908: [New game]: Adding a new game Rocket_Ride
### 🎮 Game Request

This rocket game features a player-controlled spacecraft navigating through space, avoiding obstacles and collecting power-ups. The player uses arrow keys to move the rocket up and down, aiming to survive as long as possible while managing a fuel supply. The game increases in difficulty over time, with faster-moving obstacles and a gradually depleting fuel gauge, challenging players to achieve the highest score possible.

### Point down the features

1. Smooth, responsive rocket movement using arrow keys
2. Randomly generated obstacles with varying behaviors (static and moving)
3. Two types of power-ups: fuel replenishment and score boosts
4. Fuel management system that adds strategic depth
5. Progressive difficulty increase based on score
6. Parallax star background for a sense of motion
7. High score tracking using local storage
8. Start screen with instructions and game over screen with restart option
9. Frame-independent game logic for consistent gameplay across devices
10. Score and fuel display during gameplay

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by ayush-848**
## PR Description 📜

Added a new game

Fixes #4908

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @ayush-848 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — CHANGES_REQUESTED** [review]
please also add your game image in the asset folder of the gamezone follow naming convention while naming the image

**Comment by Maana-Ajmera** [comment]
@ishita-43 Please review my pr #4842

**Comment by ayush-848** [comment]
> please also add your game image in the asset folder of the gamezone follow naming convention while naming the image

i dont have any image
it is a text based rpg

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by ayush-848** [comment]
@kunjgit i have resolved the conflicts. Please merge it

**Comment by kunjgit** [comment]
Thank you  @ayush-848 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
