### PR TITLE
Fixed snake game

### LINKED ISSUE #3118: [Enhancement]: Snake Game not working.
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
The snake game is not working.You can hear the background music and instructions are given,but you cannot see the **SNAKE**

### Describe the solution you'd like

Solution steps
The snake must be visible in the game.Because ultimately it is the snake's game.

image

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by sakshii00**
Fixed the snake game and added the home button to the left top.

## PR Description 📜
I have fixed the snake game. The snake is visible now and game is working. I also aligned the home button to top left and made hiscore to HighScore.

Fixes #3118 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.

<hr>

## Add your screenshots(Optional) 📸
image

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @sakshii00 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — APPROVED** [review]
LGTM!

**Comment by kunjgit** [comment]
Thank you  @sakshii00 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @sakshii00,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by sakshii00** [comment]
Could you please assign this PR to me? @kunjgit

**Comment by sakshii00** [comment]
@kunjgit Sorry to trouble you again but please assign this PR to me. Thank you!

**Pull request merged**
