### PR TITLE
Created Doraemon Jump

### LINKED ISSUE #115: [New game]:  Create Doraemon Jump
### 🎮 Game Request

Game logic and basic description
Jump from cloud to cloud to ascend higher and higher. Collect power-ups like bamboocopter, doracakes, and anywhere door to help you reach new heights.

### Point down the features

Game points
- Avoid obstacles like Rats and Gians, which will knock you down if you make contact.
- Rack up points and try to beat your high score!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by amelia2802**
## PR Description 📜
The aim is to guide **Doraemon** up a never-ending series of **Dorayakis** without falling. The left side of the playing field wraps around to the right side. The entire game built with HTML,CSS and vanilla Javascript.
Fixes #115 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Doraemon Jump

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @amelia2802 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by Durgesh4993 — APPROVED** [review]
https://github.com/kunjgit/GameZone/assets/98798977/4d994483-3474-485d-84c9-d740829349d7

**Comment by Durgesh4993** [comment]
@amelia2802 Can you try to reduce errors,because as i shown in demo vedio. There are errors but overall your code is right.

**Comment by amelia2802** [comment]
Hi @Durgesh4993 , thank you for reviewing the codes. I've fixed the error and resolved the conflict. You can check it now.

**Comment by kunjgit** [comment]
Hey @amelia2802 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by amelia2802** [comment]
Hi @kunjgit and @Durgesh4993 , I've resolved the conflict as per the instruction. Can you review it now?

**Comment by Durgesh4993** [comment]
@amelia2802 Nice

**Review by kunjgit — APPROVED** [review]
Nice 🔥

**Comment by kunjgit** [comment]
Thank you  @amelia2802 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
