### PR TITLE
adding Guess That Pokemon

### LINKED ISSUE #4888: [New game]: Guess that Pokemon
## Game logic and basic description
A black outline of the pokemon will be displayed on the screen and the player has to guess which pokemon it is.
There will be options for guess, quit and hint.

## Game points
- If the player guesses the pokemon without using a hint they are rewarded 100 points.
- If the player guesses the pokemon after taking a hint they are rewarded 50 points.
- If the player incorrectly guesses the pokemon they get 0 points.
- If the player quits they get 0 points.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by aRUsh-codes**
## PR Description 📜
Added a new game called _"Guess That Pokemon"_
Fixes #4888 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
pokemon1

pokemon2

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @aRUsh-codes ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by aRUsh-codes** [comment]
Hi @kunjgit @ishita-43, please look into this and merge it.
Thank You!

**Review by ishita-43 — COMMENTED** [review]
Need to resolve merge conflicts arising in the readme.md fille

**Review by ishita-43 — APPROVED** [review]
Nicely completed  🎇
Approved

**Comment by kunjgit** [comment]
Thank you  @aRUsh-codes , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
