### PR TITLE
feat: add codeql workflow

### PR DESCRIPTION
**Pull request by harmeetsingh11**
### Related Issues or bug
This PR resolves issue: #1783  

### Files added
- `.github/workflows/codeql.yml`
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.

Please review this PR 
Thanks

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @harmeetsingh11 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @harmeetsingh11,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by kunjgit** [comment]
Thank you  @harmeetsingh11 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by harmeetsingh11** [comment]
@kunjgit please reopen issue #1783 so that I can make a new PR.

**Pull request closed without merging**
