### PR TITLE
Flying Ball Game added by Swastika

### PR DESCRIPTION
**Pull request by Swa-stika**
## PR Description 📜
Newly added a Game

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Swa-stika ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @Swa-stika,
Please make sure to link the relevant issue using the appropriate syntax, such as "#issueNumber" 👀. 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by kunjgit** [comment]
Thank you  @Swa-stika , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Swa-stika** [comment]
I have marked all the tasks that you are done with ✅.
I have linked the relevant issue using the appropriate syntax, such as "#issueNumber"

**Pull request closed without merging**
