### PR TITLE
Added "Rating and Feedback" in the Master Typing Game

### LINKED ISSUE #3380: [Enhancement]: Add "RATING / FEEDBACK" in the MASTER TYPING game when the game ends.
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
1.  The "Rating/Feedback" prompt is not displayed when the game ends , if it is displayed then it will add a professional and user-  friendly feature, making players feel their feedback is valued.
2.  Collects valuable player feedback for game improvement.
3.  Encourages continued player interaction and engagement with the game.

### Describe the solution you'd like

Solution steps
1.  I will add a "RATING/FEEDBACK" prompt structure when the game ends.
2.  I will add a logic to display the rating prompt, select a rating, and handle submission or cancellation.
3.  Allows players to rate the game from 1 to 5 stars. On submitting the rating it will show a thankyou message.
4.  Canceling the rating will hide the prompt without saving feedback.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by ShristiiSharma**
## PR Description 📜

Summary -

1. I have added a "RATING/FEEDBACK" prompt structure when the game ends.
2. I have added a logic to display the rating prompt, select a rating, and handle submission or cancellation.
3. Allows players to rate the game from 1 to 5 stars. On submitting the rating it will show a thankyou message.
4. Canceling the rating will hide the prompt without saving feedback.

Fixes #3380 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Screenshot of "Rating and Feedback Form" 📸

Rating Prompt

Feedback Form

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by kunjgit — APPROVED** [review]
LGTM!

**Comment by kunjgit** [comment]
@ShristiiSharma resolve the changes then you are good to go !

**Comment by ShristiiSharma** [comment]
@kunjgit I have resolved the conflicts. If any further changes are needed, please let me know.

**Comment by kunjgit** [comment]
Thank you  @ShristiiSharma , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
