### PR TITLE
Samurai Game Added

### LINKED ISSUE #497: [New game]: Samurai Game
### 🎮 Game Request

Game logic and basic description

This is a fighting game based on ninja samurai using JS.

### Point down the features

Game points

Single player game.
Improve reflexing power.
simple keyboard command

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by anandpiyush1521**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #497

This is a fighting game based on ninja samurai using JS.
Game points

- Single player game.
- Improve reflexing power.
- simple keyboard command

<hr>
 
## Mark the task you have completed ✅

✅ I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
✅ I have performed a self-review of my own code or work.
✅ I have commented my code, particularly in hard-to-understand areas.
✅ My changes generates no new warnings.
✅ I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
✅ I have added screenshot for website preview in assets/images 
✅ I have added entries for my game in main README.md
✅ I have added README.md in my folder 
✅ I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot (1629)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @anandpiyush1521 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
mark your entry in main README file of GameZone in games section !!

**Comment by anandpiyush1521** [comment]
done.

**Comment by kunjgit** [comment]
we are having exact same game on GameZone so if you want you can do some enhancement !!

**Comment by kunjgit** [comment]
Thank you  @anandpiyush1521 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
