### PR TITLE
[#151 issue] Added Fruit_Ninja

### LINKED ISSUE #151: [New game]: Fruit Ninja
### 🎮 Game Request

Fruit Ninja using HTML, CSS, and JavaScript. Fruit Ninja is an exciting and fast-paced game where players slice flying fruits while avoiding slicing bombs. The objective is to achieve a high score by slicing as many fruits as possible within a given time limit.

### Point down the features

Features 😊

Fruit Slicing: Allow players to slice flying fruits by using mouse clicks or touch events. Detect the slicing action and provide visual feedback, such as fruit splitting into halves.

Fruit Generation: Randomly generate fruits at different positions on the screen. Vary the size, type, and velocity of fruits to add challenge and excitement.

Score Tracking: Keep track of the player's score based on the number of fruits sliced correctly. Display the current score and highest achieved score on the game screen.

Bombs: Include bombs that appear along with the fruits. Slicing a bomb should result in a penalty or reduction of the player's score. Display warnings or indicators to help players avoid slicing bombs.

Sound Effects and Visual Feedback: Enhance the gaming experience with engaging sound effects for fruit slicing, combo achievements, and bomb explosions. Provide visual feedback through animations and effects to make the game more immersive.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by varunshankar07**
## PR Description 📜

This pull request introduces the implementation of the Fruit Ninja game, a fun and engaging interactive game for players of all ages. The purpose of this PR is to add this exciting game to our repository and make it available for users to enjoy.

Fixes #151 

<hr>
 
## Mark the task you have completed ✅

- [✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅] I have performed a self-review of my own code or work.
- [✅] I have commented my code, particularly in hard-to-understand areas.
- [✅] My changes generates no new warnings.
- [✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅ ] I have added screenshot for website preview in assets/images 
- [✅] I have added entries for my game in main README.md
- [✅] I have added README.md in my folder 
- [✅] I have added working video of the game in README.md (optional)
- [✅] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @varunshankar07 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by varunshankar07 — COMMENTED** [review]
Resolved Conflicts

**Review by kunjgit — APPROVED** [review]
🔥

**Comment by kunjgit** [comment]
Thank you  @varunshankar07 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by varunshankar07** [comment]
@kunjgit Hey!! I had something to say! when I open my game on GameZone Website, When The Main Page of My Website Loads Up The Logo And Katsuro Are Not Loading Up But When I Launch It Loacally It Runs Perfectly Remaining All Are Working Perfectly! Could You Look Into This!☺️

**Pull request merged**
