### PR TITLE
Added Hangman Game

### LINKED ISSUE #4945: [New game]: Hangman Game
### 🎮 Game Request

Game logic and basic description
In this game you have to guess the word and you have six chances if you choose  wrong word then man parts build one by one and after six chance the game end.

### Point down the features

Game have the category like fruits , animal etc on which you have to choose then guess the word from that category.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by yamini777**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #4945 
I have added Hangman Game in which you have to guess the word within six chances.
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Hangman_Game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @yamini777 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — APPROVED** [review]
good to go

**Comment by yamini777** [comment]
@kunjgit Kindly review and merge

**Comment by mohitgedar** [comment]
hey , do add this game to gamesData.json so that it is visible on the website also .Details about how to add is provided in contributors guideline

**Comment by yamini777** [comment]
@mohitgedar done with changes , kindly review

**Comment by mohitgedar** [comment]
Game added to gamesData.json Correctly , this PR is marked as Ready to merge , so it will be merged soon , wait for it.

**Comment by kunjgit** [comment]
Thank you  @yamini777 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
