### PR TITLE
Updated

### LINKED ISSUE #3893: [Documentation Bug]: Labyrinth game
### Describe the bug ✍️

very less information is given in the labyrinth's games about without any pictures or videos.

### Provide step by step information reproduce the bug 📄

I will enhance it and make it better.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by shruti110503**
## PR Description 📜
Updated the readme file of labyrinth game
Fixes #3893 

<hr>
 
## Mark the task you have completed ✅

- [ x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [x ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ x] I have added screenshot for website preview in assets/images 
- [x ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2024-05-30 141209

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @shruti110503 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
@shruti110503 specify the changes you have done as I can see you have added few new files !

**Comment by shruti110503** [comment]
@kunjgit 
Screenshot 2024-06-01 211838
As shown in the screenshot above i have updated the readme file of the labyrinth game

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @shruti110503 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
