### PR TITLE
New Game Virtual Playable Piano has been Added

### LINKED ISSUE #294: [New game]: Playable Piano Virtual
### 🎮 Game Request

Game logic and basic description
Recursive Arts Virtual Piano simulator is the ultimate online piano app that everyone can play. Enjoy the beautiful sound of a world-class Grand Piano. On desktop/laptop computers, you can play notes using your keyboard or mouse. 

### Point down the features

Game points
Tech Stack includes :
HTML,CSS,Java Script
Using piano tunes, we can build virtual piano for users. It helps to create their own tune and get lost in the music for some time.It brings peace out of it.
Screenshot 2023-05-23 at 12 48 11 PM

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by SnigdhaP2022**
## PR Description 📜
A Playable PIANO using HTML, CSS, and JavaScript. The user can play various tunes on this piano by clicking on the keys or using the keyboard keys. Users can also adjust the volume and show or hide shortcut keys on the piano.

Fixes #294

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

- [✅ ] I have performed a self-review of my own code or work.
- [ ✅] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅] I have added screenshot for website preview in assets/images 
- [ ✅] I have added entries for my game in main README.md
- [✅ ] I have added README.md in my folder 
- [✅ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Playable_Piano

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @SnigdhaP2022 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @SnigdhaP2022 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by SnigdhaP2022** [comment]
> Hey @SnigdhaP2022 👋!
> 
> @kunjgit here, We have this annoucement to make 📢!! During the time of PR don't alter main index file ! 🙂 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 Thank you 💗!

Do you want me to change the game number to * and commit the changes again?

**Review by kunjgit — CHANGES_REQUESTED** [review]
don't alter main index file

**Comment by kunjgit** [comment]
Hey @SnigdhaP2022 !!
We already have this game on GameZone if you want to do enhancement you have to make enhancement request !!
Thank you !

**Comment by kunjgit** [comment]
Thank you  @SnigdhaP2022 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
