### PR TITLE
added Snail Game 🐌

### LINKED ISSUE #2471: [New game]: Snail Game
### 🎮 Game Request

The Snail Game is a simple web-based board game designed for complete beginners to have fun and engage in a friendly competition. The game involves racing colorful snails to reach the finish line first. Each snail is represented by a specific color, and players take turns rolling a virtual die to advance their snails on the track. The first snail to cross the finish line wins the game.

## Features of the Game:

- Objective: The objective of the game is to race your snail to the finish line before your opponents do.

- Board Layout: The game board consists of multiple tracks, each corresponding to a different colored snail. Each track has 12 squares, and the snails start from the first square.

- Snails: There are six snails in total, each represented by a different color - red, blue, green, yellow, purple, and orange.

- Rolling the Die: To move your snail on the track, you click the "Roll Die" button. A virtual die is rolled, and a random color is displayed as the result.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by sabhisharma-ise**
## PR Description 📜

- The Snail Game is a simple web-based board game designed for complete beginners to have fun and engage in a friendly competition. 
- The game involves racing colorful snails to reach the finish line first. 
- Each snail is represented by a specific color, and players take turns rolling a virtual die to advance their snails on the track. 
- The first snail to cross the finish line wins the game.

Fixes #2471 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots 📸

Snail_Game

## Working Video 📽️

https://github.com/kunjgit/GameZone/assets/100849696/551f77da-b29a-40ba-96fb-c1418eaf6c7d

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @sabhisharma-ise ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by sabhisharma-ise** [comment]
@gurjeetsinghvirdee Can you review this PR!

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Make a new fiile for JS & CSS
Don't mix it in single file

**Comment by sabhisharma-ise** [comment]
@gurjeetsinghvirdee Can you check now!

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM 🌸

**Comment by kunjgit** [comment]
Thank you  @sabhisharma-ise , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
