### PR TITLE
Added Slider Puzzle Game

### LINKED ISSUE #990: [New game]: Slider puzzle
### 🎮 Game Request

Simple puzzle game in which we have to complete an image using different small pieces of it.

### Point down the features

Small pieces of a large image.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by sumitkr2000**
## PR Description 📜

Hey @kunjgit I have added the slider puzzle game to your website. Please review my pr and merge it. Thank you!

Fixes #990 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

242583734-871c02c1-6588-41a4-842b-9b8369c6404b

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @sumitkr2000 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @sumitkr2000,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @sumitkr2000,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by sumitkr2000** [comment]
@kunjgit The readme file is present but don't know why its now passing the test cases!!??

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @sumitkr2000 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by killingkillers** [comment]
Hello again Mr. @gurjeetsinghvirdee ,
I have a request kindly remove the labels because @sumitkr2000 copied the whole code from - https://github.com/ImKennyYip/slide-puzzle

You can check even the imgs and variables name are also same.

**Comment by gurjeetsinghvirdee** [comment]
Screenshot_2023-07-03-20-01-17-093_com discord-edit

Hope you understand & don't tag me again 
@killingkillers

**Comment by gurjeetsinghvirdee** [comment]
And I'm not a collaborator here

**Comment by killingkillers** [comment]
> And I'm not a collaborator here
LOL by the way you did great proud of you @gurjeetsinghvirdee . :+1:

**Pull request merged**
