### PR TITLE
Game brr

### LINKED ISSUE #1790: [New game]: Guess the cartoon name
### 🎮 Game Request

Prepare a collection of pictures and their corresponding correct answers.
Randomly select a picture from the collection.
Display the picture to the player.
Provide an input field or text box where the player can enter their guess.
Listen for the player's guess submission.
Compare the player's guess with the correct answer.
If the guess is correct, congratulate the player and move to the next picture.
If the guess is incorrect, the player can change the image.

### Point down the features

- Time limit to answer the guess
- Feature to change the picture
- LeaderBoard

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by shineishukla**
## PR Description 📜

Guess the Cartoon Name" is an interactive web application designed using HTML, CSS, and JavaScript. This engaging game challenges users to test their knowledge of popular cartoon names and allowing them to guess the correct answer.
Fixes #1790 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot (574)
Screenshot (575)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @shineishukla ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @shineishukla,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @shineishukla,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by shineishukla** [comment]
> Hello @shineishukla, You need to make the following changes:
> 
> * Please add a README.md file inside the newly created folder.
> * Please modify the main README.md file.
> * Please add an image to the assets/images directory.
> 
> Hoping that you will make those changes soon 🚀

Done with the changes. Please reiew.

**Comment by kunjgit** [comment]
follow proper guidelines and you have to create PR again !!

**Comment by kunjgit** [comment]
Thank you  @shineishukla , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
