### PR TITLE
Tetris

### LINKED ISSUE #1535: [New game]: Tetris Game
### 🎮 Game Request

A new tetromino piece is spawned at the top of the playfield.
The player can rotate and move the tetromino piece left and right.
The player can drop the tetromino piece by pressing the down arrow key.
When the tetromino piece touches the bottom of the playfield or another tetromino piece, it will be locked into place.
If a row of tetromino pieces is filled, it will be removed from the playfield and the player will score points.
The game ends when the playfield is filled with tetromino pieces.

### Point down the features

Different levels: The game can have different levels with different challenges, such as faster falling speed or more difficult tetromino pieces.
Power-ups: The player can collect power-ups that can help them clear rows or score more points.
Reflex and Concentration of user increases.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by chinmayjain08**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #1535 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @chinmayjain08 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @chinmayjain08,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by chinmayjain08** [comment]
Performing changes in main readme

**Comment by kunjgit** [comment]
Thank you  @chinmayjain08 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
we already have this game on GameZone you can do enhancement if you want !!

**Pull request closed without merging**
