### PR TITLE
Enhanced the game

### LINKED ISSUE #3116: [Enhancement]: Whack-a-Mole
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

It has a very simle UI.I can make it more attractive and add tiles from which the mole and piranha plants appear .So when you click on the plant the game is lost .

### Describe the solution you'd like

I can ad 9 tiles/buckets form which the mole and the piranha plant will peak .I can add an interactive UI which will enable users to enjoy it more.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by AtharvaShinde253**
## PR Description 📜

I have enhanced the game Whac-a-Mole and added a Mario theme to it.I made the UI more attractive adding different features to the game.
Fixes #3116
whac-a-mole

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @AtharvaShinde253 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
@AtharvaShinde253 resolve the merge conflicts in your fork !

**Comment by kunjgit** [comment]
Thank you  @AtharvaShinde253 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by AtharvaShinde253** [comment]
I have raised another PR which solved the merge conflicts.Please merge that PR #3208

**Pull request closed without merging**
