### PR TITLE
Added required files #1753

### LINKED ISSUE #1753: [New game]: Quiz game with Request
### 🎮 Game Request

Game logic and basic description
In this game the users will be asked multiple questions with options and must choose the correct one within 15 seconds. then, the user score will be shown based on correct answers only.

### Point down the features

Game points this would be the simple on the basis of multiple choice questions

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by manshasinghal**
#I have added 2 files and 1 folder in game folder files 
files added are - index.html,style.css, README.md 
folder is - js
i have added a screenshot in assets named quiz_game.png
fixes #1753

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @manshasinghal ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by manshasinghal** [comment]
Added required files

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @manshasinghal,
You need to make the following changes:
  - Please create a new folder inside the "Games" folder.
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by manshasinghal** [comment]
> Hello @manshasinghal, You need to make the following changes:
> 
> * Please create a new folder inside the "Games" folder.
> * Please add a README.md file inside the newly created folder.
> * Please modify the main README.md file.
> * Please add an image to the assets/images directory.
> 
> Hoping that you will make those changes soon 🚀

I have added a folder named Quiz_Game in Games as I mentione

**Comment by kunjgit** [comment]
follow proper guidelines and create PR again !!

**Comment by kunjgit** [comment]
Thank you  @manshasinghal , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
