### PR TITLE
[New Game] : Catch Craze

### LINKED ISSUE #4698: [New game]: Catch Craze
### 🎮 Game Request

In Catch Craze, you control a basket at the bottom of the screen, aiming to catch falling objects. The game gets progressively harder as you score more points, with objects falling faster and spawning more frequently. The goal is to score as many points as possible before the time runs out.

### Point down the features

Click the "Start Game" button to begin.
Move the basket to catch the falling objects.
Monitor the score and timer.
When the timer reaches zero, the game ends, showing your final score and a button to restart the game.

Controls: Use the left and right arrow keys to move the basket.
Scoring: Each object caught increases your score by 1.
Difficulty: Object speed and spawn rate increase every 5 points.
Timer: The game lasts for 60 seconds.
Game Over: When time runs out, the final score is displayed with an option to play again.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
## PR Description 📜

In Catch Craze, you control a basket at the bottom of the screen, aiming to catch falling objects. The game gets progressively harder as you score more points, with objects falling faster and spawning more frequently. The goal is to score as many points as possible before the time runs out.
Fixes #4698 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots

Catch_Craze

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by aditya-bhaumik** [comment]
@ishita-43 please review my last pull request please

**Comment by kunjgit** [comment]
Thank you @aditya-bhaumik ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by aditya-bhaumik** [comment]
@ishita-43 i have resolved the conflicts please review and merge my pull request please

**Comment by aditya-bhaumik** [comment]
@kunjgit i have resolved the conflicts can you please merge it

**Comment by kunjgit** [comment]
Thank you  @aditya-bhaumik , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
