### PR TITLE
Added Congratulations Animation in Tic Tac Toe game

### LINKED ISSUE #2314: [Enhancement]: Adding a Congratulations Animation in Tic Tac Toe game.
### Is your enhancement request related to a problem? Please describe.➕

Currently, the Tic Tac Toe game lacks a visual feedback mechanism to celebrate and congratulate the winning player. This enhancement aims to address this issue by incorporating a congratulations animation that triggers when a player successfully achieves a winning condition.

### Describe the solution you'd like

By making changes in the CSS and JS files.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Abhishek-Rajput-81**
## PR Description 📜

I have successfully enhanced the Tic Tac Toe game by adding a captivating Congratulations Animation that triggers when a player achieves victory by aligning three of their marks in a row, column, or diagonal. This addition elevates the gaming experience, providing a visually pleasing celebration to acknowledge the winning player's achievement.

### Fixes #2314

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

https://github.com/kunjgit/GameZone/assets/96196696/7fda377b-c5a5-42b8-b583-64eb9ca119da

<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Abhishek-Rajput-81 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Abhishek-Rajput-81** [comment]
@kunjgit @gurjeetsinghvirdee please review this pr

**Comment by Abhishek-Rajput-81** [comment]
@kunjgit @kunjgit

**Comment by Abhishek-Rajput-81** [comment]
@gurjeetsinghvirdee @kunjgit

**Comment by Abhishek-Rajput-81** [comment]
# I made these changes 
## **Before** 
image

## **After**
https://github.com/kunjgit/GameZone/assets/96196696/78f84907-74bc-4dfc-ada4-3f0035609dfa


### **@kunjgit plz review this pr and merge it so that I can raise more issues.**

**Comment by Abhishek-Rajput-81** [comment]
@gurjeetsinghvirdee @Arun9739 @kunjgit

**Comment by kunjgit** [comment]
it is already there on GameZone make sure you are coming up with unique idea !!

**Comment by kunjgit** [comment]
Thank you  @Abhishek-Rajput-81 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
