### PR TITLE
Added Wordmix Game

### LINKED ISSUE #4007: [New game]: Wordmix
### 🎮 Game Request

WordMix: Merge & Win is a captivating web-based game where players merge two given words to form a single word by alternating letters. This game not only challenges players' vocabulary skills but also tests their creativity in word manipulation, offering an immersive and enjoyable gaming experience.

### Point down the features

Presents players with a pair of words to merge.
Allows players to input their merged word.
Provides instant feedback on the correctness of the merged word.
Generates a new word pair for each game session.
Features a sleek and intuitive user interface for seamless gaming.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by manishh12**
## PR Description 📜

WordMix: Merge & Win is a captivating web-based game where players merge two given words to form a single word by alternating letters. This game not only challenges players' vocabulary skills but also tests their creativity in word manipulation, offering an immersive and enjoyable gaming experience.

Fixes #4007 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @manishh12 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by manishh12** [comment]
@kunjgit Kindly review this pr.

**Comment by manishh12** [comment]
@kunjgit Kindly review  this PR.

**Comment by manishh12** [comment]
@kunjgit Please merge this PR so that i can work on other issues.

**Comment by manishh12** [comment]
@kunjgit !!

**Comment by kunjgit** [comment]
Thank you  @manishh12 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
