### PR TITLE
Added Responsive Memory Game

### LINKED ISSUE #1874: [New game]:  A Responsive Memory Game
### 🎮 Game Request

A Responsive memory Game where the user is allowed to see the elements for a very short time, and then it is hidden for them to find the elements and match it

### Point down the features

Game points
Responsive
Fully functional
Memory Based
Entertaining

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by PoulavBhowmick03**
## PR Description 📜

Added the responsive memory game made using HTML CSS and Javascript

Fixes #1874 
Close #1874 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @PoulavBhowmick03 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by PoulavBhowmick03** [comment]
@kunjgit 
Please merge it

**Comment by PoulavBhowmick03** [comment]
@daccdacc Please merge this

**Comment by PoulavBhowmick03** [comment]
@kunjgit @daccdacc Please merge this

**Comment by kunjgit** [comment]
it is already there you can add new segment in it we can't accept this as new game !! 👀

**Comment by kunjgit** [comment]
Thank you  @PoulavBhowmick03 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
