### PR TITLE
Solved issue # 3742 - Added pixel painter game

### LINKED ISSUE #3742: [New game]: Pixel Painter
### 🎮 Game Request

Game logic and basic description
"Pixel Painter", a game where players use their mouse to paint pixels on a canvas to match a given pattern within a time limit.

### Point down the features

Game points
1. Multiple Levels and Increasing Difficulty
2. Hint System
3. Leaderboard

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Pixel Painter is an interactive web-based drawing application that allows users to create pixel art. It features a canvas for drawing, a color picker, an undo functionality, and a clear button. The interface includes smooth animations and an intuitive user experience.

Fixes # <your_issue_number>
Fixes #3742 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
pixel_painter

https://github.com/kunjgit/GameZone/assets/142652964/1cba9285-76d7-40b3-94d6-5b501f7de841

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Aditi22Bansal ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Aditi22Bansal** [comment]
@kunjgit 
Kindly review my PR and merge
Thankyou

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Aditi22Bansal,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Aditi22Bansal** [comment]
I have added @kunjgit 
image

**Comment by Aditi22Bansal** [comment]
@kunjgit 
Added 
Please review

**Comment by kunjgit** [comment]
@Aditi22Bansal resolve merge conflicts !

**Comment by Aditi22Bansal** [comment]
@kunjgit 
DONE 
KINDLY REVIEW AND MERGE

**Comment by kunjgit** [comment]
@Aditi22Bansal you are not having updated readme with latest change make sure you are doing that

**Comment by Aditi22Bansal** [comment]
@kunjgit 
Done 
Kindly check

**Comment by Aditi22Bansal** [comment]
@kunjgit 
Done

**Review by kunjgit — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
