### PR TITLE
Added 2D_Fighting_Game

### LINKED ISSUE #5016: [New game]: Add Two Player Fighting Game
### 🎮 Game Request

Game logic and basic description
This 2D game will replicate the real-world fighting experience of a samurai.

### Point down the features

Game points
This game have the features are:

1. Health
2. Katana Figurthing
3. A Moment of Triumph
4. The Best User Experience

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Vaibhav-kesarwani**
## PR Description 📜

Added 2D_Fighting_Game
Fixes #5016 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in GameZone's README.md
- [x] I have added README.md in my Game folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.
- [x] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸

Screenshot from 2024-07-29 16-26-46

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Vaibhav-kesarwani ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — APPROVED** [review]
Ready to merge

**Comment by Vaibhav-kesarwani** [comment]
@kunjgit Please review the PR and merge it

**Comment by Vaibhav-kesarwani** [comment]
@ishita-43 Please merge the PR

**Comment by ishita-43** [comment]
> @ishita-43 Please merge the PR

Merge will be done by the admin soon

**Comment by kunjgit** [comment]
Thank you  @Vaibhav-kesarwani , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
