### PR TITLE
[GSSoc`23] Wild Card Bonanza GAME Added

### LINKED ISSUE #717: [New game]: Wild Card Bonanza
### 🎮 Game Request

Game logic and basic description:

The game can be implemented using Html, CSS, and Javascript.

1. Player take turns. On each turn:
The player can either play a card from their hand that matches the color or number of the top card on the discard pile, or they can draw a card from the deck.
If the player plays a card, and it matches the number or color we move forward.
If the player cannot play a card, they must draw a card from the deck.
2. After the player's turn, it's the computer's turn. The computer will analyze its hand and play a card if there is a match with the top card on the discard pile. 
Continue alternating turns between the player and the computer until one of the players has no cards left in their hand.
At the end of the game, the one with no cards will be the winner.

### Point down the features

Game points
At the end of the game, the one with no cards will be the winner.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Sheetal-05**
## PR Description 📜

Wild Card Bonanza GAME Added
Fixes #717 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot (137)
<br>
<br>
Screenshot (138)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Sheetal-05 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@Sheetal-05 Mention * in place of a number in main README.

**Comment by Sheetal-05** [comment]
@Arun9739 Done

**Comment by kunjgit** [comment]
Thank you  @Sheetal-05 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
