### PR TITLE
Added the cursor property 

### PR DESCRIPTION
**Pull request by GauriBhandari**
## PR Description 📜

This pull request addresses two improvements in issue [#2384](https://chat.openai.com/c/link-to-issue) in the provided code snippet. Firstly, cursor property has been added to the label element, enabling it to change to a pointer shape when hovered over, indicating its interactive nature. Secondly, an anchor tag has been added to create an HTML link for the "github" text, directing users to the specified GitHub URL.

Changes Made:

Added anchor tag with the specified GitHub URL for the "github" text.
Included cursor: pointer; CSS property for the label element's inline style.

 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @GauriBhandari ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by GauriBhandari** [comment]
@kunjgit and @Arun9739 
I would appreciate it if you could kindly review my pull request. It adds the cursor property mentioned in #2384 issue. 
I would specifically like feedback on the code logic and readability. Any suggestions for improvement would be greatly appreciated.
Thank you in advance for taking the time to review my changes!

Best regards,
GauriBhandari

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Kindly Resolve Conflicts @GauriBhandari

**Comment by GauriBhandari** [comment]
Hi @gurjeetsinghvirdee , I have resolved the conflicts and made the necessary changes. Could you please review my changes?

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM 🌸

**Comment by GauriBhandari** [comment]
Thank you for reviewing my changes and providing the LGTM comment! I'm glad to hear that the pull request looks good. Could someone from the team (@kunjgit, @Arun9739, @gurjeetsinghvirdee ) please help with merging this? I'm eager to see these changes integrated into the main branch. Thanks in advance!

**Comment by kunjgit** [comment]
Thank you  @GauriBhandari , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by gurjeetsinghvirdee** [comment]
> Thank you for reviewing my changes and providing the LGTM comment! I'm glad to hear that the pull request looks good. Could someone from the team (@kunjgit, @Arun9739, @gurjeetsinghvirdee ) please help with merging this? I'm eager to see these changes integrated into the main branch. Thanks in advance!

It takes some time maybe 10-15 mins to reflect your changes after merging.

**Comment by GauriBhandari** [comment]
Thank you for merging my pull request! I appreciate the collaborative effort and the opportunity to contribute to this project. Looking forward to more contributions in the future!

**Comment by GauriBhandari** [comment]
@gurjeetsinghvirdee Thank you for merging my pull request! I'm thrilled to have contributed to this project. Could you please consider adding me to the contributors list?
And I am also not listed in the leaderboard of GSSOC'23 for this contribution. Could you please help.

**Pull request merged**
