### PR TITLE
Road fighter game is added

### LINKED ISSUE #2356: [New game]: Road fighter
### 🎮 Game Request

A 2 D Car Racing game made using HTMl , CSS & Javascript .

### Point down the features

player can control the movement of the car using Arrow keys from keyboard to move away from incoming cars and obstacles.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by shraddha761**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #2356 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @shraddha761 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by shraddha761** [comment]
@Arun9739 please review

**Comment by shraddha761** [comment]
@daccdacc Sry but I didn't understand where do I have to put * in readme

**Review by kunjgit — APPROVED** [review]

**Comment by daccdacc** [comment]
Hello @shraddha761, in the main README.md file where you are putting the entry of your game.

**Review by kunjgit — APPROVED** [review]

**Comment by shraddha761** [comment]
@daccdacc Can you review the PR. I have made the changes

**Comment by kunjgit** [comment]
Thank you  @shraddha761 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Game copied from here: **https://github.com/amoldalwai/RoadFighter**
Live view: **https://amoldalwai.github.io/RoadFighter/**

**Pull request merged**
