### PR TITLE
enhancement of escaperoom game

### LINKED ISSUE #4135: [Enhancement]: adding more puzzle question to escaperoom game
### Title:
Enhancement of Escape Room Game

### Description:
I want to add a new feature to the existing Escape Room Game. Currently, the game involves solving a series of puzzles to find a key and unlock the door. I would like to introduce a time limit for completing the game. Players will have a certain amount of time to solve all the puzzles and escape the room. If they fail to escape within the time limit, they lose the game.

### Proposed Changes:
1. Introduce a countdown timer at the beginning of the game.
2. Display the remaining time to the player throughout the game.
3. If the time runs out before all puzzles are solved, display a message indicating that the player has failed to escape.
4. Allow players to retry the game if they fail to escape within the time limit.

### Benefits:
1. Adds a sense of urgency and challenge to the game.
2. Increases replay value as players can try to beat their previous time.
3. Provides a clear win condition for the game.

### Additional Notes:
Players should have enough time to reasonably solve all the puzzles, so the time limit should be set accordingly.

### Describe the solution you'd like

**Design the User Interface:**

Determine where to display the countdown timer on the game screen.
Decide on the format for displaying the time remaining (e.g., minutes and seconds).
Implement the Countdown Timer:

**Add JavaScript code to initialize a countdown timer when the game starts.**
Update the timer display every second to show the remaining time.
Handle the case when the time runs out, triggering a game over scenario.
**Update the Game Logic:**

Integrate the countdown timer into the game logic to enforce the time limit.
Modify the win condition to include completing the game within the time limit.
Adjust the game over condition to include running out of time.

I am contrubuting upon gssoc24.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by NAVJOT-786**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #4135 
### Description:
I want to add a new feature to the existing Escape Room Game. I have added more puzzle question to the game that are required to unclock the door this make the game more interesting and reasonable 

<hr>
 
## Mark the task you have completed ✅

- [ X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ X] I have performed a self-review of my own code or work.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [ X] My changes generates no new warnings.
- [ X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ X] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2024-06-03 at 12 58 25 AM

--- 
<br>

## Thank you soo much for contributing to our repository 💗
I am contributing upon gssoc24

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @NAVJOT-786 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by NAVJOT-786** [comment]
@kunjgit please tell if anything else required

**Comment by NAVJOT-786** [comment]
@kunjgit my pull request is not accepted is anything else required?

**Comment by Harleen-786** [comment]
@kunjgit pull request is not accepted yet is anything else required?

**Comment by NAVJOT-786** [comment]
@kunjgit my pull request is not accepted yet is there any more changes i need to do?

**Comment by NAVJOT-786** [comment]
@kunjgit please verify and accept the pull request

**Comment by NAVJOT-786** [comment]
@kunjgit please verify the pull request

**Comment by NAVJOT-786** [comment]
@kunjgit it has been 7 days pull request is not accepted yet is any update required??

**Comment by NAVJOT-786** [comment]
@kunjgit kindly Review this PR and merge it .I am not able to take any other issue because of this .

**Comment by NAVJOT-786** [comment]
@ishita-43  kindly Review this PR and merge it .I am not able to take any other issue because of this .

**Comment by NAVJOT-786** [comment]
@kunjgit reminder!

**Comment by NAVJOT-786** [comment]
@kunjgit please check

**Comment by NAVJOT-786** [comment]
@kunjgit please review the pull request

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by kunjgit** [comment]
Thank you  @NAVJOT-786 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
