### PR TITLE
Add game dino Chrome version

### LINKED ISSUE #1700: [New game]: Dino game like chrome have
### 🎮 Game Request

Game logic and basic description

we need some pictures of dino , cactus and all, writing js for the functions

### Point down the features

Game points

- on space bar start the game
- up keyword dino will jump
- by touching cactus game will over
- score will update according to how many cactus crossed

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Swapnil-2503**
## PR Description 📜

Game added which is same as of chrome dino game
Fixes #1700 

<hr>
 
## Mark the task you have completed ✅

- [x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [ x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ x] I have added screenshot for website preview in assets/images 
- [x ] I have added entries for my game in main README.md
- [x ] I have added README.md in my folder 
- [x ] I have added working video of the game in README.md (optional)
- [ x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2023-06-20 142507

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Swapnil-2503 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Swapnil-2503** [comment]
@kunjgit please see this and merge pr

**Comment by kunjgit** [comment]
we already have this game on GameZone 👀 !!

**Comment by kunjgit** [comment]
Thank you  @Swapnil-2503 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Swapnil-2503** [comment]
@kunjgit please can you see again i know there is game dino runner allready but that is different as this game based on chromes dino game and also the visuals are different it's totally different

**Pull request closed without merging**
