### PR TITLE
Added Cross the river game

### LINKED ISSUE #4556: [New game]: Cross the river game
### 🎮 Game Request

Game logic and basic description
A farmer needs to cross a river with a wolf, a goat, and a cabbage. The boat can only carry the farmer and one of the other three items at a time. The challenge is to get all three items across the river without leaving the wolf alone with the goat (the wolf would eat the goat) or the goat alone with the cabbage (the goat would eat the cabbage).

### Point down the features

Game points
1. The boat can only carry the farmer and one other item at a time.
2. The farmer cannot leave the wolf alone with the goat.
3. The farmer cannot leave the goat alone with the cabbage.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by DiwareNamrata23**
## PR Description 📜

The farmer is the only one who can pilot the boat. The boat only carries two at a time. The goat can never be left alone with the cabbage, or it will devour it. The wolf also cannot be left alone with the goat, or it will eat it too. Can you cross them all?
Fixes #4556 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2024-06-16 at 11 52 36 AM
Cross_The_River

--- 
<br>

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @DiwareNamrata23 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by DiwareNamrata23** [comment]
@ishita-43 please do review my pr

**Review by ishita-43 — APPROVED** [review]
good to go!!

**Comment by kunjgit** [comment]
Thank you  @DiwareNamrata23 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
