### PR TITLE
Added Tennis Showdown

### LINKED ISSUE #2449: [New game]: Tennis Showdown
### 🎮 Game Request

I have developed a tennis game using HTML, CSS, and JavaScript and I would like to contribute it to the project. The game is designed to provide an interactive and enjoyable gaming experience for tennis enthusiasts.

### Point down the features

1. The game allows two players to control the tennis rackets using keyboard inputs or touch controls. The controls are intuitive, providing an easy and engaging experience.
2. The ball reacts to player hits, bounces off the walls and rackets accurately.
3. The game implements a scoring system similar to traditional tennis rules. It keeps track of each player's score, displays it on the screen, and determines the winner. 
4. The game is designed to be responsive on different devices.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by abhinav-m22**
## PR Description 📜

Added a tennis game using HTML, CSS, and JavaScript. The game is designed to provide an interactive and enjoyable gaming experience for tennis enthusiasts.

* Closes #2449 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @abhinav-m22 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @abhinav-m22,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Comment by abhinav-m22** [comment]
@kunjgit @daccdacc @Arun9739 
Made the required changes. Please merge the PR

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Resolve the conflicts @abhinav-m22

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @abhinav-m22,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @abhinav-m22,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @abhinav-m22,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Comment by abhinav-m22** [comment]
@gurjeetsinghvirdee Please check now!

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM

**Pull request merged**
