### PR TITLE
 Monster maker game added

### PR DESCRIPTION
**Pull request by Kalivarapubindusree**
## PR Description 📜

#787 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Monster_Maker

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Kalivarapubindusree ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Kalivarapubindusree** [comment]
Please Review at once! @kunjgit

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Kalivarapubindusree,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Kalivarapubindusree** [comment]
Already Added please check at once!

Monster maker game added by Kalivarapubindusree · Pull Request #906 · kunjgit_GameZone - Google Chrome 10-06-2023 10_55_09

**Comment by Kalivarapubindusree** [comment]
Please Review New Pull request #1077   @kunjgit

**Pull request closed without merging**
