### PR TITLE
feat: 3D Maze game using threeJs and MapGL

### LINKED ISSUE #2937: [New game]: Maze Game
### 🎮 Game Request

Game logic and basic description
In maze game a player should find a coorect path to make the target goes to the destination in single attempt

### Point down the features

Win or Lose in single attempt

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Gobinath-B**
## PR Description 📜

.  I developed a 3D Maze game using threeJs and MapGL .
. I built the game by 5 level and 5 different maps.
. I enhance the 3D experience by adding sound for movements.
. I write a clear README.md with game screenshots

Fixes #2937 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Gobinath-B ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Gobinath-B** [comment]
@kunjgit can you please review the code and merge it.

**Comment by kunjgit** [comment]
Sorry to inform but you are missing out on lot of things there in the documentation and how you have to take care of the structure please go through documentation once and again make PR

**Comment by kunjgit** [comment]
Thank you  @Gobinath-B , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
