### PR TITLE
Added Fish_Qrwal

### LINKED ISSUE #5118: [New game]: Fish Qrwal
### 🎮 Game Request

Game logic and basic description
The player must control the dangerous fish in this game in order to level up the boost.

### Point down the features

Game points
1. Health
2. Unique UI
3. Fish Health
4. Barriers

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Vaibhav-kesarwani**
## PR Description 📜

Added Fish_Qrwal
Fixes #5118 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in GameZone's README.md
- [x] I have added README.md in my Game folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.
- [x] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸

Fish_Qrwal

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Vaibhav-kesarwani ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Vaibhav-kesarwani** [comment]
@ishita-43 & @kunjgit Please review and merge the PR

**Comment by kunjgit** [comment]
Hey @Vaibhav-kesarwani, You have reached your limit to contribute in GameZone with a score of 180. 
 We believe in giving equal opportunity to everyone so you will not be able to contribute to GameZone now onwards. 💗 
 Thank you for your valuable time and contribution in GameZone 🕹️! 

 Your merged pull requests:
- [#5095](https://github.com/kunjgit/GameZone/pull/5095) with labels: level3 score: (45)
- [#5057](https://github.com/kunjgit/GameZone/pull/5057) with labels: level3 score: (45)
- [#5017](https://github.com/kunjgit/GameZone/pull/5017) with labels: level3 score: (45)
- [#4989](https://github.com/kunjgit/GameZone/pull/4989) with labels: level3 score: (45)

**Comment by kunjgit** [comment]
Thank you  @Vaibhav-kesarwani , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
