### PR TITLE
[GSSoC'23]: Dino game added

### LINKED ISSUE #1448: [New game]: Chrome Dinosaur Game
### 🎮 Game Request

Game logic and basic description
A dinosaur game, just like chrome dinosaur game that jumps when pressing spacebar and you have to avoid the obstacles by jumping.

### Point down the features

Game points
responsive
interactive

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by SoarinSkySagar**
## PR Description 📜

As said in the linked issue, I have added the Chrome Dino Game.
Fixes #1448 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @SoarinSkySagar ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by SoarinSkySagar** [comment]
@kunjgit @daccdacc @Arun9739 please review and merge this PR!
Issue: #1448 
PR: #1519

**Comment by kunjgit** [comment]
we already have this game in GameZone !! 👀

**Comment by kunjgit** [comment]
Thank you  @SoarinSkySagar , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by SoarinSkySagar** [comment]
@kunjgit no, I saw the game which you were talking about and it is a different game than this one, even though the names may be the same

**Pull request closed without merging**
