### PR TITLE
Adds game Angry Bird

### LINKED ISSUE #4744: [New game]: Angry Bird
### 🎮 Game Request

Modify Coins:

Allows users to change their current coin count to a specified amount.
Input the current number of coins, and the script sets the coin count to a high value (e.g., 999,999).
Unlock All Levels:

Unlocks all levels in the game, allowing access to play any level without needing to progress sequentially.
Ensures that all stages are available for immediate play.
Unlock All Birds:

Unlocks all bird characters, providing access to every bird in the game.
This feature lets users utilize any bird with unique abilities from the start.
User-Friendly Interface:

Simple HTML interface with buttons for each action.
Easy to use with prompts and alerts guiding the user through each modification process.

### Point down the features

Game points- Level 3

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by arunimaChintu**
## PR Description 📜

Modify Coins:

Allows users to change their current coin count to a specified amount.
Input the current number of coins, and the script sets the coin count to a high value (e.g., 999,999).
Unlock All Levels:

Unlocks all levels in the game, allowing access to play any level without needing to progress sequentially.
Ensures that all stages are available for immediate play.
Unlock All Birds:

Unlocks all bird characters, providing access to every bird in the game.
This feature lets users utilize any bird with unique abilities from the start.
User-Friendly Interface:

Simple HTML interface with buttons for each action.
Easy to use with prompts and alerts guiding the user through each modification process.

Fixes #4744 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @arunimaChintu ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Hi also add your game entry into the readme.md file of repo to make changes visible in the project!
I hope you will do needed changes soon!!

**Comment by arunimaChintu** [comment]
@ishita-43 yes sure

**Comment by arunimaChintu** [comment]
@ishita-43 Added README.md, please merge it now

**Comment by arunimaChintu** [comment]
@ishita-43 Please review it... READ.me is updated

**Review by ishita-43 — COMMENTED** [review]
you need to add your readme update in this pr only  as you had asset folder in this pr you dont need to create separate pr for that

**Comment by arunimaChintu** [comment]
@ishita-43 am closing this pr and creating an entirely new one...

**Comment by kunjgit** [comment]
Thank you  @arunimaChintu , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
