### PR TITLE
added Asteroids 3D Game 🌠

### LINKED ISSUE #2400: [New game]:  Asteroids 3D
### 🎮 Game Request

Implementing a 3D software renderer for rendering asteroids. 

### Point down the features

The game features a player-controlled spaceship that can move and shoot bullets. The goal of the game is to destroy the asteroids by shooting them with bullets. The asteroids move around the screen and can collide with the player's spaceship. The game also includes explosions and visual effects.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by sabhisharma-ise**
## PR Description 📜

The code provided is a JavaScript game that implements a 3D software renderer for rendering asteroids. The game features a player-controlled spaceship that can move and shoot bullets. The goal of the game is to destroy the asteroids by shooting them with bullets. The asteroids move around the screen and can collide with the player's spaceship. The game also includes explosions and visual effects.

Fixes #2400 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots 📸

Asteroids_3D

## Working Video 📽️

https://github.com/kunjgit/GameZone/assets/100849696/c1ef28c3-d6ab-4e2a-bcb2-20b07590372d

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @sabhisharma-ise ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by sabhisharma-ise** [comment]
@gurjeetsinghvirdee Can you review this PR!

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @sabhisharma-ise , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Code copied from **codepen**: **https://codepen.io/H2xDev/pen/rNQjaKj**

**Pull request merged**
