### PR TITLE
Added Score Counter and Practice Key Advisor

### LINKED ISSUE #3464: [Enhancement]: Master Typing Score Keeper
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The game does not provide the user with data on the number of keys that were correctly or incorrectly pressed. We can also give the user information about the key that was pressed incorrectly the most number of times at the end of game.

### Describe the solution you'd like

Solution steps
1. Changes in CSS and HTML to add new counters to keep track of the scores for correct and incorrect key presses.
2. Changes in JavaScript to update the counters and turn the keys red that were pressed incorrectly the most number of times at the end of the game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by KrishnaKalra**
## PR Description 📜

1. Added Counters to give user information about the correct Key Strokes.
2. Added Key advisor which will tell the user about the key which was pressed incorrectly most number of times and needs more practice at the end of the game.

Fixes #3464
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @KrishnaKalra ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — APPROVED** [review]
LGTM!

**Comment by kunjgit** [comment]
@KrishnaKalra resolve the merge conflicts !

**Comment by KrishnaKalra** [comment]
@kunjgit merge conflicts are now resolved.

**Comment by kunjgit** [comment]
Thank you  @KrishnaKalra , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
