### PR TITLE
Added Chess game with Computer

### LINKED ISSUE #4233: [New game]:  🎮 Chess Game with compute Request
### 🎮 Game Request

Description:
We propose the development of an AI-powered chess game that offers an engaging and challenging experience to players of all levels. The game will leverage advanced algorithms to provide intelligent gameplay while also offering a user-friendly interface for an immersive gaming experience.

Game Logic:
The AI chess game will follow standard chess rules, allowing players to enjoy the classic game in a digital format. The game will include features such as move validation, checkmate detection, and various difficulty levels to accommodate players from beginners to advanced.

### Point down the features

Intelligent AI Opponent: The game will feature an AI opponent with varying levels of difficulty, from beginner to grandmaster, to provide a challenging experience for players of all skill levels.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
## PR Description 📜

Embark on an exhilarating chess adventure with our AI-powered chess game! Whether you're a beginner seeking to learn or a seasoned player craving a challenge, our game offers an immersive experience tailored to your skill level. Battle against intelligent AI opponents ranging from novices to grandmasters, and hone your strategic skills with every move. With features like move validation, checkmate detection

Fixes #4233

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @thevijayshankersharma ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @thevijayshankersharma,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by thevijayshankersharma** [comment]
@kunjgit someone else got assigned this issue. Could please make sure that I will get assign the issue again

**Review by ishita-43 — APPROVED** [review]
Approved :>

**Comment by thevijayshankersharma** [comment]
@kunjgit now you can merge it.

**Comment by kunjgit** [comment]
Thank you  @thevijayshankersharma , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by thevijayshankersharma** [comment]
@kunjgit Could be it level 3 cause every body is getting level 3 and this took much time to complete too.

**Comment by ishita-43** [comment]
Hi there!
We assigned level 3 to the projects because of the new feature they brings to the project. Since we already have two other chess game in the repository we are putting this one in the level 2 category!!

**Pull request merged**
