### PR TITLE
Added Anime Clicker 

### LINKED ISSUE #2767: [New game]: Anime Clicker
## Game logic and basic description:
Frontend game developed using HTML, CSS, JavaScript. Player has to kill all the mosquitoes in a specific time

## Game points:
- There will different difficulty levels for playing the game
- Player will be given a mosquito net
- Player has to kill all the mosquitoes appearing on the screen consecutive order in specific time.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by sujanrupu**
## PR Description 📜

As a GSSOC '23 contributor I have added Anima Clicker game.
- Frontend game developed using HTML, CSS, JavaScript. Player has to kill all the mosquitoes in a specific time

Fixes #2767 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Anime_Clicker

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @sujanrupu ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Resolve conflicts @sujanrupu

**Comment by sujanrupu** [comment]
@gurjeetsinghvirdee I have resolved the conflicts, please review

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM 🍁

**Comment by kunjgit** [comment]
Thank you  @sujanrupu , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
