### PR TITLE
Added King_Sword_Runner

### LINKED ISSUE #5056: [New game]: Add King sword Runner
### 🎮 Game Request

Game logic and basic description
The 2D game which have the king player which have to reach the his castle after dfeating enemy

### Point down the features

Game points
1. Player Movement
2. Battle System
3. Graphics and UI
4. A Moment of Triumph
5. Health

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Vaibhav-kesarwani**
## PR Description 📜

Added King_Sword_Runner
Fixes #5056 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in GameZone's README.md
- [x] I have added README.md in my Game folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.
- [x] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸

Screenshot from 2024-07-29 16-35-03

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Vaibhav-kesarwani ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Vaibhav-kesarwani** [comment]
@ishita-43 Please review the PR and merge it

**Review by ishita-43 — APPROVED** [review]
Approved

**Comment by Vaibhav-kesarwani** [comment]
@kunjgit Please review and merge the PR

**Comment by Vaibhav-kesarwani** [comment]
@ishita-43 & @kunjgit Please review and merge the PR the PR is open 3 days ago

**Comment by ishita-43** [comment]
> @ishita-43 & @kunjgit Please review and merge the PR the PR is open 3 days ago

The pr would soon be merged by the admin

**Comment by Vaibhav-kesarwani** [comment]
@kunjgit Please merger the PR

**Comment by kunjgit** [comment]
Thank you  @Vaibhav-kesarwani , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
