### PR TITLE
Snake game

### LINKED ISSUE #149: Snake game:
### 🎮 Game Request

A Snake will be inside a box and will be moved on the basis of an arrow 
- top
- bottom 
- left
- right
If hit the wall then the game will be over if he will eat the "feed" then its length will  increases as well as score will also.

### Point down the features

Game points.
- it can be played on mobile as well as on laptop (Device Friendly)
- Smoothness of Game without any lag

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by iamsuyashpatel07**
## PR Description 📜

🎮 Game Request
A Snake will be inside a box and will be moved on the basis of an arrow

top
bottom
left
right
If hit the wall then the game will be over if he will eat the "feed" then its length will increases as well as score will also.
Point down the features
Game points.

it can be played on mobile as well as on laptop (Device Friendly)
The smoothness of Game without any lag

Fixes #149

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Snake_Game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @iamsuyashpatel07 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @iamsuyashpatel07 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by iamsuyashpatel07** [comment]
Hey @kunjgit ,

I read the updated readme file and according to that my pr and issues match. If you still feel that something is wrong then please let me know what is not matching.....

(P.S: Joined the discord channel I will love to have conversions with you there.)

**Comment by kunjgit** [comment]
Hey @iamsuyashpatel07 !! we are already having the Snake game on the site and it is conflicting with it !!
if you want to make changes you can have enhancement !! 
as someone who will come up with unique idea first then you can have enhancement in that you can clearly see that #59 is the first one to come with the idea !!
Looking forward to have your enhancement !!

**Comment by kunjgit** [comment]
Thank you  @iamsuyashpatel07 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
