### PR TITLE
Typing Speed test Game added

### LINKED ISSUE #262: [New game]: Typing Speed Test Game
### 🎮 Game Request

A typing speed game is a computer or online game designed to improve and test a player's typing skills and speed. These games are often interactive and engaging, offering a fun and challenging way to practice typing while aiming to achieve higher speeds and accuracy.

### Point down the features

The main objective of a typing speed game is to complete the given task within a specified time limit or to achieve the highest typing speed possible.
Typing speed games often provide feedback to players, such as displaying their words per minute (WPM) or accuracy percentage. This feedback allows players to track their improvement over time and encourages them to practice and refine their typing skills.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by code-gen21**
## PR Description 📜
- The Typing Speed Test is an interactive game that measures your typing speed and accuracy. It presents you with a series of random words, sentences, or paragraphs that you need to type as quickly and accurately as possible. The game keeps track of your typing speed in words per minute (WPM) and calculates your accuracy based on the number of correct keystrokes.

Fixes #262

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Typing_Speed_Test

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @code-gen21 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @code-gen21 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by code-gen21** [comment]
I have updated the README.md file. Please review it again.

**Comment by Arun9739** [comment]
@code-gen21 Remove the assests folder from your game's directory.  Put images in main asssets folder. Also resolve branch conflicts.

**Comment by Arun9739** [comment]
@code-gen21 resolve the branch conflicts

**Comment by kunjgit** [comment]
Thank you  @code-gen21 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
