### PR TITLE
Pop My Balloon Game Added

### LINKED ISSUE #3155: [New game]: Pop My Balloon
### 🎮 Game Request

Game logic and basic description:The basic concept of the game is that there will be a range of numbers from which players can choose a number. If the manage to guess the randomly chosen number, the balloon will pop and they lose. If they manage to avoid the lucky number, the range decreases such that their guess either becomes the new lower bound or new upper bound, and the balloon inflates just a little bit more.

### Point down the features

Game points:
Easy Level: The range starts off as 0-100 and players can guess any number within the range.
Harder Level: The range starts off as 0-84, and players can only guess numbers that are either from the lower bound (LB) to LB+12 or from the upper bound (UB) to UB-12.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Nayanika1402**
## PR Description 📜

As assigned me the task I have added a new game called Pop my Balloon.
Fixes #3155 
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅ ] I have performed a self-review of my own code or work.
- [ ✅ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✅ ] My changes generates no new warnings.
- [ ✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅ ] I have added screenshot for website preview in assets/images 
- [ ✅ ] I have added entries for my game in main README.md
- [ ✅ ] I have added README.md in my folder 
- [ ✅ ] I have specified the respective issue number for which I have requested the new game.

## Add your screenshots(Optional) 📸

Pop_My_Balloon

--- 

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Nayanika1402 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
@Nayanika1402 !
make sure you listing your game in main readme file in root !

**Comment by Nayanika1402** [comment]
Changes Added.Added the game in the Readme file.

**Comment by kunjgit** [comment]
Thank you  @Nayanika1402 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
