### PR TITLE
Added Escape Room game

### LINKED ISSUE #1820: [New game]: Escape Room
### 🎮 Game Request

This escape room game utilizes only CSS and HTML to create a visually appealing and interactive experience. The game consists of multiple stages, and as the user progresses through each level, the difficulty gradually increases. Each stage must be successfully completed in order to advance to the next level. The challenges become more challenging with each level, presenting a greater test for the player.

### Point down the features

The user is trapped inside a room and should search for keys and hints inside the room for escaping it and advancing into next room with much more difficulty.
This game consists of 10 levels in total and levels are much harder as you advance to another one.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by saikiranreddy201**
## PR Description 📜

I have added the Escape Room game with full functionality and have added the appropriate readme files
Fixes #1820 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added a screenshot for website preview in assets/images 
- [x] I have added entries for my game in the main README.md
- [x] I have added README.md to my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Escape_room

Screenshot 2023-06-22 151618

--- 
<br>

## Thank you so much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @saikiranreddy201 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @saikiranreddy201,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by saikiranreddy201** [comment]
Hey @kunjgit, I apologize but I have added the appropriate readme files, please do check

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @saikiranreddy201 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @saikiranreddy201,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by saikiranreddy201** [comment]
Dear @kunjgit please add gssoc'23 labels and remove the pending labels so that my pr counts, Thank you:)

**Comment by saikiranreddy201** [comment]
Hey @kunjgit, pleaseeeeee remove the gssoc labels, my pr doesn’t count if you don’t add gssoc labels it seems🙂

**Review by gurjeetsinghvirdee — COMMENTED** [review]
**Copied from here: https://github.com/takaneichinose/css-room-escape**

**Pull request merged**
