### PR TITLE
Adds Block Vault game 🕹️

### PR DESCRIPTION
**Pull request by SanskarSinghiit**
## PR Description 📜

This Pull Request addresses issue #5131. 

It introduces a new game titled Block Vault to the repository, with the following updates:
1. Implemented core game logic where players control a block that jumps over horizontally incoming obstacles.
2. Added speed increase mechanics for incoming obstacles.
3. Included a scoring system and game-over conditions.
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in GameZone's README.md
- [x] I have added README.md in my Game folder 
- [x] I have specified the respective issue number for which I have requested the new game.
- [x] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸

Block_Vault

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @SanskarSinghiit ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by SanskarSinghiit — COMMENTED** [review]
Reviewed all the file changes.

**Review by ishita-43 — APPROVED** [review]
Ready to merge

**Comment by kunjgit** [comment]
Thank you  @SanskarSinghiit , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by SanskarSinghiit** [comment]
Thankyou for merging my PR.

**Pull request merged**
