### PR TITLE
Flashlight Pointer Game Added

### LINKED ISSUE #2445: [New game]: Flashlight Pointer Game
### 🎮 Game Request

Flashlight Pointer Game

### Point down the features

Use your flashlight to find three rabbits hiding in the webpage somewhere out of sight. 
Find all the three rabbits to win the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Samriddhi15**
## PR Description 📜

Use your flashlight to find three rabbits hiding in the webpage somewhere out of sight. Find all the three rabbits to win the game.

Fixes #2445 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Flashlight_Pointer_Game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Samriddhi15 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Samriddhi15,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by Samriddhi15** [comment]
I already have Readme file inside the folder you can check @kunjgit

**Review by kunjgit — APPROVED** [review]

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM 🌸

**Comment by kunjgit** [comment]
Thank you  @Samriddhi15 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
