### PR TITLE
Added Moving Dice Game

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
##  Moving Dice Game | Issue Number : #108  

The **Moving Dice** game is a classic kids game that have sound of dice while shuffling and this is developed using HTML, **CSS, & JavaScript**.
The game starts with a single play button which make the game more clear and fun to the player because he/she going to direct step into the game, also have a count section to count the numbers of wins of the player in the correct order.

##Points -
- Press the "Play" button to start the game.
- The game will randomly choose a dice **Number** in the form of **Dice-Dots** and will play a sound. Repeat the dice to earn more points.
- If there is something issue with the device then it will pop-up "Please refresh the page."
- Press the "Play" button again or continue the game.

## Tasks
- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Screenshots 📸
Screenshot from 2023-05-21 00-42-36

Screenshot from 2023-05-21 00-42-17
--- 

## Video [🎥](https://emojipedia.org/movie-camera/)

[Screencast from 21-05-23 12:44:03 AM IST.webm](https://github.com/kunjgit/GameZone/assets/121503426/19a6befb-b9fc-4f1b-acbf-5828d4bb60f3)

## Thank you so much for giving us this opportunity to contribute in such a good repository 💗

### CODE REVIEW

**Review by kunjgit — CHANGES_REQUESTED** [review]
Just add your game entry in main Readme file with * as number !!
Other things are 🔥 !

**Comment by kunjgit** [comment]
Hey @SyedImtiyaz-1 !!
don't alter main index file and I was talking about readme file of GameZone
in this you have to add your game with number as *

image

**Comment by SyedImtiyaz-1** [comment]
Hello @kunjgit ,
The conflicts also resolved can you please review this.

**Comment by SyedImtiyaz-1** [comment]
Sir @kunjgit

**Review by kunjgit — CHANGES_REQUESTED** [review]
please don't alter main index file 👀

**Comment by SyedImtiyaz-1** [comment]
I think now it's solve ! @kunjgit

**Comment by SyedImtiyaz-1** [comment]
I think now it's solve ! @kunjgit

**Comment by SyedImtiyaz-1** [comment]
Conflicts also resolved

**Comment by kunjgit** [comment]
Hey @SyedImtiyaz-1 !!
Please follow proper guidelines and then create PR !! 👀

**Comment by kunjgit** [comment]
Thank you  @SyedImtiyaz-1 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
