### PR TITLE
BALL MOVEMENT IN A MAZE!

### PR DESCRIPTION
**Pull request by jshobhit11**
## PR Description 📜

INTRODUCTION - Tilting Maze is an exciting and challenging game that tests your dexterity and problem-solving skills.

OBJECTIVES -
The objective of a Tilting Maze game is to successfully navigate a ball or object through a maze by tilting the device to control its movement. The specific objectives can vary between different games, but they generally fall into the following categories:

Reach the Exit: The primary objective in many Tilting Maze games is to guide the ball from the starting point to the designated exit point of the maze. This requires carefully maneuvering through pathways, avoiding obstacles, and making strategic decisions to find the correct route.

Collect Items: Some Tilting Maze games introduce additional objectives where the player must collect specific items scattered throughout the maze. These items could be keys, gems, coins, or any other collectibles. The player needs to navigate the maze to find and gather all the required items before reaching the exit.

BEHIND LOGIC -
The logic behind a Tilting Maze game involves several key elements:
1. Accelerometer/Gyroscope Input
2. Physics Simulation
3. Maze Generation Algorithm
4. Collision Detection
5. Game Objectives and Rules

Fixes # <266>

<hr>
 
## Mark the task you have completed ✅

- [ x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x ] I have performed a self-review of my own code or work.
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ x ] My changes generates no new warnings.
- [ x ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ x ] I have added screenshot for website preview in assets/images 
- [ x ] I have added entries for my game in main README.md
- [ x  ] I have added README.md in my folder .
- [ x ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Link- [https://drive.google.com/file/d/1jvpdgXAcTwrsb7f7THUFXAiUcZ16MIDy/view?usp=sharing]

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @jshobhit11 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @jshobhit11 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Follow proper documentation and then raise a pull request you have to add image and also you have to make your game entry and also you have to make sure you tag issue  properly

**Comment by kunjgit** [comment]
Thank you  @jshobhit11 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by jshobhit11** [comment]
I have Updated the Proper Documentation and also mention Game Entry! 
Please review it again!

**Pull request closed without merging**
