### PR TITLE
[New Game]: Fruit Ninja

### LINKED ISSUE #2523: [New game]:  Fruit Ninja Game(Gssoc'23)
### 🎮 Game Request

This project is a clone of 90s classic Fruit Ninja Game. Made with JAVASCRIPT, HTML, and CSS.

### Point down the features

Start new game and you can only miss 3 fruits and also if you touch the bomb while cutting the fruits. After that, game will be over.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Bharatpathak08**
## PR Description 📜
I've added a new fruit ninja game which is the exact copy of 90's game

Fixes #2523 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>
--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Bharatpathak08 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Bharatpathak08** [comment]
@kunjgit I've done all these 3 tasks.

**Comment by Bharatpathak08** [comment]
> Hello @Bharatpathak08, You need to make the following changes:
> 
> * Please add a README.md file inside the newly created folder.
> * Please modify the main README.md file.
> * Please add an image to the assets/images directory.
> 
> Hoping that you will make those changes soon 🚀

Because of some mis-typing the checkboxes were not ticked. But I've done that also.

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Bharatpathak08,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Bharatpathak08,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Bharatpathak08,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Bharatpathak08** [comment]
@kunjgit could you check my PR now. I've added everything needed

**Comment by Bharatpathak08** [comment]
See
a
b
c

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Bharatpathak08,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by kunjgit** [comment]
Thank you  @Bharatpathak08 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Bharatpathak08** [comment]
@kunjgit  @Arun9739 could you check it once. Also see the screenshots shared here.

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Bharatpathak08,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Bharatpathak08** [comment]
I've added all these files 5 days ago. Check it out.

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Code copied from here: **https://code-projects.org/fruit-ninja-cutter-game-in-javascript-and-html5-with-source-code/**

**Pull request closed without merging**
