### PR TITLE
Animations Added

### LINKED ISSUE #3398: [Enhancement]: Adding Animations on Scrolling and Loading
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Adding animations on scrolling down.

### Describe the solution you'd like

Adding animations library and css animations

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by MHusain22**
## PR Description 📜
Added Animations in the heading, about and search bar.

Fixes #3398 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)

<hr>

## Add your screenshots(Optional) 📸

https://github.com/kunjgit/GameZone/assets/118285713/f776506b-10b2-4642-8f38-e72f50202a64

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @MHusain22 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
@MHusain22 resolve merge  conflicts !

**Comment by MHusain22** [comment]
@kunjgit Now it has no conflict with main branch and please add label of gssoc and level

**Comment by MHusain22** [comment]
@kunjgit Now there is no conflict with the base branch you can merge it. Please add the labels of gssoc and level 2 above and my name in Assignees.

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @MHusain22 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
