### PR TITLE
[New Game]: SONIC THE HEDGEHOG 

### LINKED ISSUE #748: [New game]: SONIC THE HEDGEHOG
### 🎮 Game Request

Game logic and basic description
- To play, simply hit left or right key to move Sonic around the screen. You can also jump by `up` key. 
- To dash, hit down key. Sonic will dash forward and destroy any obstacles in his path.

### Point down the features

Game points

-  Use your power-ups wisely. Power-ups can help you collect more rings, run faster, and jump higher.
-  Collect coins. Coins can be used to unlock new characters and stages.
-  Challenge your friends. See who can get the farthest in the game.
- As you play, you will collect rings, which can be used to purchase power-ups. 
- Power-ups can help you collect more rings, run faster, and jump higher. 
- You can also collect coins, which can be used to unlock new characters and stages.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## PR Description 📜
This PR is about adding the classical Sonic the hedgehog game!
Fixes #748 

<hr>

## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Sonic_The_Hedgehog

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @0xabdulkhalid ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@0xabdulkhalid LGTM

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @0xabdulkhalid , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
