### PR TITLE
Dhoombikerace

### LINKED ISSUE #2433: [New game]: Dhoom Bike race
### 🎮 Game Request

Game logic and basic description:
The objective of the game is usually to complete various levels or challenges by successfully executing Race, jumps, flips, and tricks while maintaining balance and control of the bike. And for each and every jump the score will increases.

### Point down the features

Game points:
- Bike Controls: Players can control the bike's speed, acceleration, braking, and direction using on-screen left, top , right , bottom keyboard inputs. T

- This allows them to navigate through the game's environment and perform jumps and tricks.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by vamshi726**
## PR Description 📜

The objective of the game is usually to complete various levels or challenges by successfully executing Race, jumps, flips, and tricks while maintaining balance and control of the bike.

Fixes #2433
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

##  screenshot of game 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @vamshi726 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @vamshi726,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @vamshi726,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @vamshi726,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by vamshi726** [comment]
Hi @kunjgit can please explain in detail what isstill missing in pull request

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
- Remove **`_config.yml`** 
- Add your game in **`README.md`** file of this repo
- Add Screenshot of your game in **`assets/images`** directory of this repo
- Rename extra **`.md`** from your **`README.md`** file

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @vamshi726,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @vamshi726,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Game Copied from here: **https://github.com/adnan-2000/Jumping-Bike-Game**
Live Website: **https://adnan-2000.github.io/Jumping-Bike-Game/**

**Comment by kunjgit** [comment]
Thank you  @vamshi726 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
