### PR TITLE
Added Slice storm game

### LINKED ISSUE #1933: [New game]: Slice Storm
### 🎮 Game Request

 - Slice Storm is a fun game where players have to smash boxes using their slicing skills. 
 - Slice through them with precision, avoiding obstacles, and aim for the highest scores.
 - The game is built using JavaScript, HTML, and CSS, making it accessible and playable on various desktop as well as touch 
    screen platforms.

### Point down the features

 - **Points**: Players are rewarded with points for every box they skillfully slice, with the score progressively growing for each successful cut.
 - **Power-ups**: Throughout the game, players may encounter unique boxes that grant advantageous power-ups, such as reducing the speed at which boxes appear.
 - **Obstacles**: Occasionally, challenging boxes will emerge, demanding multiple hits to be obliterated compared to regular boxes.
 - **High Scores**: The game diligently records the player's best score, enabling them to engage in self-competition and strive for personal excellence.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by VSatwika**
## PR Description 📜

Added Slice Storm game in which the player has to sice through boxes with precision, avoiding treacherous obstacles, and aim for the highest scores. 
Fixes #1933 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Slice_Storm

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @VSatwika ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VSatwika,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by VSatwika** [comment]
@kunjgit I have already added a ReadMe.md file inside the newly created game file.

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VSatwika,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by VSatwika** [comment]
@kunjgit I'm sorry but there is a ReadMe.md file in the newly created folder. I have created a ReadMe file inside the new game folder.

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @VSatwika , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by VSatwika** [comment]
@kunjgit Can labels for GSSoC'23 and level 3 added please? Thank You

**Pull request merged**
