### PR TITLE
[New game]: Color swap

### LINKED ISSUE #4656: [New game]: Color swap
### 🎮 Game Request

"Color Swap" is a simple yet addictive browser-based game developed using HTML, CSS, and JavaScript. The game revolves around the player controlling a character or object that must pass through obstacles matching its color. The color of the character changes randomly, requiring quick reflexes and strategic thinking.

### Point down the features

Simple Controls:

The player controls the character using the arrow keys or touch gestures on mobile devices.
The character moves left, right, up, or down to navigate through a series of color-coded obstacles.

Color Matching:

The character changes color periodically or when passing through special zones.
Players must guide the character through obstacles that match its current color to score points.

Increasing Difficulty:

As the game progresses, the speed and frequency of color changes increase.
More complex patterns and additional obstacles are introduced to challenge the player.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
## PR Description 📜

Added a new game color swap

**"Color Swap"** is a simple yet addictive browser-based game developed using HTML, CSS, and JavaScript. The game revolves around the player controlling a character or object that must pass through obstacles matching its color. The color of the character changes randomly, requiring quick reflexes and strategic thinking.

**Simple Controls:**

The player controls the character using the arrow keys or touch gestures on mobile devices.
The character moves left, right, up, or down to navigate through a series of color-coded obstacles.

**Color Matching:**

The character changes color periodically or when passing through special zones.
Players must guide the character through obstacles that match its current color to score points.

**Increasing Difficulty:**

As the game progresses, the speed and frequency of color changes increase.
More complex patterns and additional obstacles are introduced to challenge the player.

Fixes #4656 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @aditya-bhaumik ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by aditya-bhaumik** [comment]
@ishita-43 please review my pull request

**Comment by aditya-bhaumik** [comment]
@ishita-43 please review my pull request and add the gssoc labels

**Review by ishita-43 — APPROVED** [review]
Ready to merge!!

**Comment by kunjgit** [comment]
Thank you  @aditya-bhaumik , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
