### PR TITLE
Update README.md

### LINKED ISSUE #4421: [Documentation Bug]: Broken Links in README.md
### Describe the bug ✍️

The README.md file of the GameZone repository contains broken links. Several game names are listed as links, but they are not properly formatted or may be pointing to non-existent files or directories.

The broken links need to be fixed to ensure the smooth navigation and functionality of the documentation.

Step-by-step information to reproduce the bug 📄

1. Navigate to the README.md file of the GameZone repository.
2. Look for the list of games under the "Games" section.
3. Check each game name listed as a link.
4. Observe that several links are broken or improperly formatted.
Screenshot 2024-06-10 214320

### Provide step by step information reproduce the bug 📄

I plan to address this issue by:

Reviewing the README.md file to identify all broken links.
Correcting the formatting of broken links or removing them if necessary.
Ensuring that all game names listed as links are functional and properly formatted.
Testing the updated README.md file to ensure all links are working as expected.

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by GUNJESH843**
## PR Description 📜

This PR fixes broken links in the README.md file.

Fixes #4421 

- Fixed the broken links for Laser Darts and Emoji Slot Machine.

<hr>

## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)

<hr>

## Add your screenshots(Optional) 📸
Before:
Screenshot 2024-06-10 214320

After:
Screenshot 2024-06-10 215652

---

<br>

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @GUNJESH843 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by GUNJESH843** [comment]
hey, @ishita-43, this issue is a follow-up to your comment(https://github.com/kunjgit/GameZone/pull/4253#issuecomment-2156542043) on my previous PR,

Just had a small request, if you could label my PR as level2.

Thankyou

**Comment by ishita-43** [comment]
if you would add other changes in this pr we will add level otherwise this would remain level 1 
let me know you are gonna update this pr.

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by GUNJESH843** [comment]
> if you would add other changes in this pr we will add level otherwise this would remain level 1 
> let me know you are gonna update this pr.
> 

Could you clarify what other changes?

**Comment by kunjgit** [comment]
@GUNJESH843 resolve merge conflicts !

**Comment by GUNJESH843** [comment]
@kunjgit
hey,

I have resolved the merge conflicts.

**Comment by ishita-43** [comment]
> > if you would add other changes in this pr we will add level otherwise this would remain level 1
> > let me know you are gonna update this pr.
> 
> Could you clarify what other changes?

depends on you!

**Comment by kunjgit** [comment]
@GUNJESH843 resolve merge conflicts with latest changes after review is done then make sure there is no conflicts !

**Comment by GUNJESH843** [comment]
@kunjgit  please review the PR the conflict is resolved.

**Comment by kunjgit** [comment]
Thank you  @GUNJESH843 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
