### PR TITLE
Solved issue #3578- Adding word association game

### LINKED ISSUE #3578: [New game]: Adding Word Association Game
### 🎮 Game Request

Game logic and basic description

In this game, the player has to enter a word that begins with the last letter of the previously entered word. If the word is valid and follows the rules, the game continues. If not, an error message is displayed. It's a fun and challenging game that tests both vocabulary and quick thinking!

### Point down the features

Game points

Word Validation: The game checks whether the word entered by the player is valid according to predefined rules, such as being a real word and starting with the last letter of the previous word.

Real-time Feedback: The game provides immediate feedback to the player after each word entry, indicating whether it's valid or not.

Word Database: The game utilizes a word database or dictionary to verify the validity of entered words.

Hints: The game may provide hints or suggestions for valid words if a player is stuck, helping to keep the game moving and encouraging players to expand their vocabulary.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below

In this game, the player has to enter a word that begins with the last letter of the previously entered word. If the word is valid and follows the rules, the game continues. If not, an error message is displayed. It's a fun and challenging game that tests both vocabulary and quick thinking!

Fixes #3578 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2024-05-21 012648
Screenshot 2024-05-21 012708
Screenshot 2024-05-21 012846

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Aditi22Bansal ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Aditi22Bansal** [comment]
@kunjgit 
Kindly review the PR and approve
Thankyou

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Aditi22Bansal,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Aditi22Bansal** [comment]
Ok doing right now

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Aditi22Bansal,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Aditi22Bansal,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by Aditi22Bansal** [comment]
Done @kunjgit

**Comment by Aditi22Bansal** [comment]
@kunjgit 
Kindly review and merge

**Pull request closed without merging**
