### PR TITLE
Comprehensive Website Enhancements: Fix Game Loading, Pagination, Layout Issues, JSON Errors, Cursor Size, and Remove Redundant File

### LINKED ISSUE #4974: [Enhancement]: Comprehensive Website Enhancements: Fix Game Loading, Pagination, Layout Issues, JSON Errors, Cursor Size, and Remove Redundant File
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

- Users are unable to load games, impacting their experience and engagement.
- The pagination feature is not functioning, which makes it difficult for users to navigate through multiple games.
- The like button is overlapping with the game titles, making it difficult to read and interact with the content.
- Contributors are improperly modifying the gamesData.json file, adding trailing commas and removing the last curly brace, leading to errors.
- The manual cursor is excessively large, covering content and making it difficult for users to view and interact with elements like the like button.
- An unused index_old.html file is increasing the website’s load time, affecting performance.

### Describe the solution you'd like

- Improve game loading functionality to ensure all games are accessible to users. This enhancement will increase user satisfaction by providing a seamless and reliable gaming experience.
- Make pagination system working again to facilitate smooth navigation between games. This will improve the user experience by making it easier to browse and discover content.
- Redesign the like button layout to prevent it from overlapping with the game titles. This will enhance the visual layout and ensure that all interactive elements are clearly accessible and aesthetically pleasing.
- Update the contributors' guidelines to include clear instructions on proper JSON formatting.
- Adjust the size of the manual cursor to improve visibility and usability. This adjustment will ensure that the cursor does not obstruct important content, enhancing the overall user experience.
- Remove the unused index_old.html file to reduce load times and improve website performance. This will optimize the website’s efficiency and enhance the user experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by mohitgedar**
## PR Description 📜

Fixes #4974

- I have Improved game loading functionality to ensure all games are loading and accessible to users. This enhancement will increase user satisfaction by providing a seamless and reliable gaming experience.
- I have made changes so that pagination system is working again to facilitate smooth navigation between games. This will improve the user experience by making it easier to browse and discover content.
- I have Redesigned the like button layout to prevent it from overlapping with the game titles and also added hover effect to make it visually appealing. This will enhance the visual layout and ensure that all interactive elements are clearly accessible and aesthetically pleasing.
- I have also added hover effect to the Game Title , so that it get highlighted on mouse hover, indicating that it is a link to the code of the game
- I have Updated the contributors' guidelines to include clear instructions on proper JSON formatting, this time I used better markups to make it visually appealing and added some more points to counter new problems users are facing.
- I have reduced the size of the manual cursor to improve visibility and usability. This adjustment will ensure that the cursor does not obstruct important content, enhancing the overall user experience.
- I have Removed the unused index_old.html file to reduce load times and improve website performance. This will optimize the website’s efficiency and enhance the user experience. Screenshot of loadtime is also added for your reference 
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

### Before deletion of file load time is 42ms.
before deleting old_html file

### After deletion of file load time is 33ms.
after deleting old_html file

### Check game 24 , no overlapping and with hover effect  ( cursor not visible in SS )
GameZone - Brave 25-07-2024 12 08 04 PM
GameZone - Brave 25-07-2024 12 08 08 PM

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @mohitgedar ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by ishita-43** [comment]
Resolve merge conflicts of gamesdata. json

**Comment by mohitgedar** [comment]
@ishita-43  conflicts are resloved

**Review by ishita-43 — APPROVED** [review]
Seems good

**Comment by kunjgit** [comment]
Thank you  @mohitgedar , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
