### PR TITLE
Flapp Bird Added #22 Resolved

### LINKED ISSUE #22: [New game]: Single Player Flappy Bird Game
### 🎮 Game Request

Build a Single Player Flappy Bird Game where user will COntrol the flappy bird with a key and has to cross obstacles to gain points and score.

### Point down the features

It Will have Scoring and LeaderBoard Functionality.Once Deployed many people would be able to play and compete via Leaderboard

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by AbhishekPSingh07**
## PR Description 📜

Added The Flappy Bird Game
Fixes #22 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2023-05-21 at 8 20 51 AM

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by kunjgit — CHANGES_REQUESTED** [review]
make game playing area more bigger ! 
other things are working fine 🔥

**Comment by AbhishekPSingh07** [comment]
I Have Increased the play Area
Screenshot 2023-05-26 at 8 46 01 PM
Do You need me to increase it further

**Review by kunjgit — APPROVED** [review]
Looks good 🔥

**Comment by kunjgit** [comment]
Thank you  @AbhishekPSingh07 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
