### PR TITLE
removed redundancies

### LINKED ISSUE #5049: [Bug]: Fixing gamesData.json
### Give a brief about the bug ✍️

The games data.json file has a lot of error that isnt letting the game to be rendered locally and i would like to fix that as it would take a lot of time im raising an issue for this to get assigned to a level
image
image

### What is the expected behavior? 🤔

the games should render as it is rendering in the website locally too but there is supposed to be a bug in gamesData.json

### Provide step by step information reproduce the bug 📄

clone the repo
open assets folder
open the gamesData.json
and run the index.html with live server

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by abhay-sen**
Fixes #5049 

the website was not displaying any games when locally due to error in the json file i removed a lot of duplicates from the json and modified it to not provide errors and have distinct key values
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in GameZone's README.md
- [ ] I have added README.md in my Game folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.
- [ ] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸
before 
Screenshot 2024-07-31 174556

after 
Screenshot 2024-07-31 185053

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @abhay-sen ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by ishita-43** [comment]
Did your changes make sure only duplicate entries are removed of same game not different game of different people?!

**Comment by abhay-sen** [comment]
> Did your changes make sure only duplicate entries are removed of same game not different game of different people?! 

Yes ma'am I searched for the game urls and deleted the duplicates it took a lot of time but I made sure not to delete any game

**Review by ishita-43 — APPROVED** [review]
Approved

**Comment by ishita-43** [comment]
Please resolve merge conflicts

**Comment by abhay-sen** [comment]
@ishita-43 done

**Comment by kunjgit** [comment]
Thank you  @abhay-sen , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
