### PR TITLE
[GSSoC'23] Emoji Puzzle Game Completed 

### LINKED ISSUE #777: [New game]: Emoji Puzzle Game [GSSoC'23]
### 🎮 Game Request

Game logic and basic description

- Game is just a math riddle which creates some equations by using the emojis.
- Solve these equations and write the answer.
- This will update the score board according to the right and wrong answers.

### Point down the features

Game points

Points are given according to the wrong and right answer entered.
- (+1) for right answer
- (-1) for wrong answer

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## PR Description 📜

Title - Emoji Puzzle Game
Technology used - HTML, CSS, and JS
Fixes #777 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Emoji_Puzzle_Game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Avdhesh-Varshney ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Avdhesh-Varshney** [comment]
@kunjgit @raju-kumar21 @Arun9739 please review my pull request and merge it into the main branch

**Comment by Avdhesh-Varshney** [comment]
@kunjgit @Arun9739 @raju-kumar21 please review my pull request regarding a new game **Emoji Puzzle Game** and merge it into the main branch for successful contribution under GSSoC'23.

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Avdhesh-Varshney , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
