### PR TITLE
[Enhancement]: Addition of Chatbot

### LINKED ISSUE #4317: [Enhancement]: Addition of Chatbot
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Addition of Chatbot

### Describe the solution you'd like

Addition of Chatbot , to assist the user's.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Anjaliavv51**
issue #4317

## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #4317 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

WhatsApp Image 2024-06-07 at 19 16 54_b7362f02

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Anjaliavv51 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @Anjaliavv51, you can't open another pull request before completing the previous one 😀
You already have the following 1 open pull request(s):
#4319

**Comment by kunjgit** [comment]
Thank you  @Anjaliavv51 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Anjaliavv51** [comment]
@ishita-43 @kunjgit successfully added Chatbot

**Comment by Anjaliavv51** [comment]
@kunjgit @ishita-43 please preview the PR

**Comment by Anjaliavv51** [comment]
@kunjgit @ishita-43 please review the PR

**Pull request closed without merging**
