### PR TITLE
[GSSoC'23] Illusion Game Completed

### LINKED ISSUE #2512: [New game]: Illusion
### 🎮 Game Request

In this game, a rotating illusion pattern is displayed on the screen, and the player has to guess the direction of rotation. "C" for clockwise and "A" for counterclockwise. 

### Point down the features

Illusion Pattern Display:

The game displays a rotating illusion pattern on the screen.
The rotation direction of the pattern is randomized.

User Input and Scoring:

Users can input their guesses for the rotation direction using the "C" key for clockwise and the "A" key for counterclockwise.
The program checks if the user's guess matches the actual rotation direction and updates the score accordingly.
The score is displayed on the screen.

Game Loop and Timing:

The game runs in a loop, allowing continuous gameplay until the player quits.
The rotation direction changes every 2 seconds.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by dhruv1108git**
## PR Description 📜

Illusion game in Python using the Pygame library. In this game, a rotating illusion pattern is displayed on the screen, and the player has to guess the direction of rotation. t.
Fixes #2512

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @dhruv1108git ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by dhruv1108git** [comment]
@kunjgit @gurjeetsinghvirdee please review this PR.

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM

**Comment by dhruv1108git** [comment]
@kunjgit @gurjeetsinghvirdee conflicts resolved

**Comment by kunjgit** [comment]
Thank you  @dhruv1108git , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
