### PR TITLE
Add Retro_Dungeon_Puzzle game

### LINKED ISSUE #738: [New game]: Retro Dungeon Puzzle
### 🎮 Game Request

The Retro Dungeon Maze Puzzle game is a thrilling and immersive experience that transports players back to the enchanting world of classic video games. With its pixelated graphics and nostalgic atmosphere, this game captures the essence of retro gaming.

The Retro Dungeon Maze Puzzle game features a set of game logic that governs the mechanics and rules of the gameplay. Here's a high-level overview of the game logic:

>Maze Generation: The game generates random mazes with walls, corridors, and various obstacles using algorithms like depth-first search or recursive backtracking.

>Player Movement: The player can move in four directions (up, down, left, and right) using touch controls. The game ensures that the player stays within the boundaries of the maze and cannot move through walls.

>Objectives: The primary objective of the game is to find the exit of each maze and progress to the next level. To achieve this, the player may need to collect keys or other items scattered throughout the maze.

>Collisions and Interactions: The game checks for collisions between the player and the obstacle.

### Point down the features

Here are the features of the Retro Dungeon Maze Puzzle game:

> Randomly generated mazes with walls, corridors, and obstacles

> Player movement in four directions (up, down, left, and right)

> Objectives to find the exit of each maze and progress to the next level

> Collection of keys and other items scattered throughout the maze

> Collisions with enemies to avoid.

>Game over conditions for losing and victory conditions for winning

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by MisterMickey**
## PR Description 📜

Add Retro_Dungeon_Puzzle game

Fixes #738 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

Retro_Dungeon_Puzzle

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @MisterMickey ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Thank you  @MisterMickey , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by MisterMickey** [comment]
@kunjgit Why is this closed?

**Review by kunjgit — APPROVED** [review]

**Comment by MisterMickey** [comment]
@kunjgit Issues Resolved.

**Comment by kunjgit** [comment]
Thank you  @MisterMickey , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
