### PR TITLE
#348 Bird_game

### LINKED ISSUE #348: [New game]: The Bird Game !
### 🎮 Game Request

Game logic and basic description:
It's a simple game build on html and css only which will assign points based on the number pf birds aimed for shoot.

### Point down the features

Game points:
It increases as you shoot a bird.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Shr-reny**
## PR Description 📜

The game is made using html and css only and is a simple shooting game.  We simply need to aim the cursor on the flying bird and click in order to shoot. The number of birds you aimed at reflects your score.
Fixes #348

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](hxtps://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Bird_game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Shr-reny ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@Shr-reny Do the entry of your game into main README file.

**Comment by Shr-reny** [comment]
Yes @Arun9739  I've done it.

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hey !!
follow guidelines make your entry in main README and also add your image in assets/images

**Comment by Arun9739** [comment]
@Shr-reny Plz make a entry of your game into the main README file

**Comment by kunjgit** [comment]
Thank you  @Shr-reny , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
