### PR TITLE
Added Shadow Runner game

### LINKED ISSUE #5003: [New game]: Add Shadow Runner Game
### 🎮 Game Request

Shadow Runner is a simple browser-based game where the player must navigate through obstacles and collect power-ups to score points. The game area scrolls continuously, and the player must avoid obstacles while collecting power-ups to increase their score.

## Gameplay

- **Objective**: Avoid obstacles and collect power-ups to score points.
- **Scoring**:
  - Yellow Squares: -5 points
  - Green Triangles: +10 points
  - Red Balls: +15 points
  - Double points in darker areas

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by kosuri-indu**
## PR Description 📜

This PR adds, Shadow Runner which is a simple browser-based game where the player must navigate through obstacles and collect power-ups to score points. The game area scrolls continuously, and the player must avoid obstacles while collecting power-ups to increase their score.

### Gameplay

- **Objective**: Avoid obstacles and collect power-ups to score points.
- **Scoring**:
  - Yellow Squares: -5 points
  - Green Triangles: +10 points
  - Red Balls: +15 points
  - Double points in darker areas
 
Fixes #5003

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in GameZone's README.md
- [x] I have added README.md in my Game folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.
- [x] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your Video(Optional) 📸

https://github.com/user-attachments/assets/8e68ef7e-7ec1-4ab0-8334-26955da61c5f

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @kosuri-indu ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kosuri-indu** [comment]
@kunjgit @ishita-43
Please review this PR :)
Thank you

**Review by ishita-43 — APPROVED** [review]
Ready to merge

**Comment by kosuri-indu** [comment]
@kunjgit 
kindly review and merge this PR

**Comment by kosuri-indu** [comment]
@kunjgit 
resolved the merge conflicts sir

**Review by ishita-43 — APPROVED** [review]

**Pull request merged**
