### PR TITLE
penalty shoot out game

### LINKED ISSUE #4893: [New game]: Penalty Shootout Game
### Game logic and basic description

you have to goal in penalty shoot out 

### Point down the features

Game points

if goal is done point is awarded 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by ANKeshri**
## PR Description 📜

add a new game penalty shootout game 

Fixes #4893 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

   
Screenshot 2024-07-19 130833

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @ANKeshri ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by ANKeshri** [comment]
@kunjgit please review once and merge my pr

**Review by ishita-43 — APPROVED** [review]
Pr is approved

**Comment by ishita-43** [comment]
> @kunjgit @ishita-43 please review once and merge my pr

Will soon be merged by the admin

**Comment by ANKeshri** [comment]
@kunjgit solved the conflict please merge it

**Pull request merged**
