### PR TITLE
Adds Drummer Kit game 🥁

### LINKED ISSUE #5159: [New game]: Add Drummer Kit game 🥁
### 🎮 Game Request

Create a virtual drum kit game where players can hit drum pads to play beats and rhythms. Features include rhythm challenges, custom beats, and practice mode.

### Point down the features

- Virtual drum sounds (snare, bass drum, cymbals, etc.)
- Rhythm challenges and custom beat creation
- Practice mode and scoring system

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by SanskarSinghiit**
## PR Description 📜

Create a virtual drum kit game where players can hit drum pads to play beats and rhythms. 
Features include rhythm challenges, custom beats, and practice mode.

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in GameZone's README.md
- [x] I have added README.md in my Game folder 
- [x] I have specified the respective issue number for which I have requested the new game.
- [x] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @SanskarSinghiit ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by SanskarSinghiit** [comment]
@ishita-43 mam, please review this PR.

**Review by ishita-43 — APPROVED** [review]

**Comment by SanskarSinghiit** [comment]
Thank you

**Comment by kunjgit** [comment]
@SanskarSinghiit resolve merge conflicts !

**Comment by kunjgit** [comment]
Thank you  @SanskarSinghiit , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
