### PR TITLE
Added Belt_Black game

### LINKED ISSUE #5089: [New game]: I want to add a fighting game.
### 🎮 Game Request

Game logic and basic description

- There will be 2 players.
- Where player 1 will be the user and player 2 will be enemy.

### Point down the features

Game points

- Players have to fight with each other inorder to win.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by vishanurag**
## PR Description 📜
- Added Belt_Black game.

Fixes #5089 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in GameZone's README.md
- [x] I have added README.md in my Game folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.
- [x] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸
Screenshot 2024-08-05 231710

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @vishanurag ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by vishanurag** [comment]
@kunjgit @ishita-43 please review & merge my pull-request under GSSoC'24

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Please also add your game image in assets folder of the game zone follow naming convention for its name

**Comment by vishanurag** [comment]
@ishita-43 I have done the needful changes. Please check.

**Review by ishita-43 — APPROVED** [review]
Approved

**Comment by kunjgit** [comment]
Thank you  @vishanurag , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
