### PR TITLE
added Reverse memory game

### LINKED ISSUE #4122: [New game]: Reverse Memory Challenge
### 🎮 Game Request

Game logic and basic description

The game presents a grid of colored squares.
Clicking a square reveals a random color for a brief moment, then hides it again.
The twist is memorizing the sequence of colors in reverse order. With each successful recall, the sequence length increases, making it progressively harder.
Players lose if they enter the sequence incorrectly.

### Point down the features

Game points

Reverse Memory: Recall colors in reverse order, adding a unique challenge.
Level Up System: Sequence length increases for a growing challenge.
Simple Interface: Easy to learn with familiar grid and colors.
Customizable Difficulty (Optional): Adjust grid size or difficulty levels for personalization.
Feedback (Optional): Visual/audio cues for right/wrong answers for better engagement.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by MuraliDharan7**
## PR Description 📜

New game 'Reverse memory' is added. This will test our memory and also It will more fun as well.
Fixes #4122 

<hr>
 
## Mark the task you have completed ✅

- [ X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X ] I have performed a self-review of my own code or work.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] My changes generates no new warnings.
- [ X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X ] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [ X] I have added working video of the game in README.md (optional)
- [ X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

image

image

<br>

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @MuraliDharan7 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @MuraliDharan7,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @MuraliDharan7,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by ishita-43 — APPROVED** [review]
Looks great.. 🏆

**Comment by kunjgit** [comment]
Thank you  @MuraliDharan7 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
