### PR TITLE
[New game]: Simon Says game #2608

### LINKED ISSUE #2644: [New game]: Simon Game
### 🎮 Game Request

A RGB color guessing game.It has 2 levels easy and hard. In easy level you have 3 boxes and you have to guess from those 3 boxes but in hard level you have 6 boxes.

### Point down the features

It is a great game to play. It is basically a memory game and will benefit your memory a lot.

Tech Stack Used:
HTML5
CSS3
JAVASCRIPT

image

### Select program in which you are contributing

GSSoC23, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by misterraina**
### Simon Game - **Test Your Memory and Reflexes!**
Welcome to Simon, the classic memory and pattern recognition game! Challenge yourself and see how far you can go in this exciting and mind-boggling experience.

**How to Play:**
Simon will show you a sequence of colors, starting with just one. Your task is to repeat the pattern by clicking or pressing the corresponding color buttons. With each successful repetition, Simon will add one more color to the sequence, making it progressively challenging as you advance through the levels.

**Can You Remember the Sequence?**
Pay close attention to the order in which the colors are displayed, and be ready to recall and repeat them. Your memory and reflexes will be put to the test as the patterns become more intricate and demanding.

**Get Started Now:**
_Don't wait any longer! Test your memory and reflexes with Simon Game._

Thank You:

Fixes  #2644

<hr>
 

✅I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
✅ I have performed a self-review of my own code or work.
 ✅I have commented my code, particularly in hard-to-understand areas.
✅ My changes generate no new warnings.
 ✅I have followed the proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
 ✅I have added a screenshot for the website preview in assets/images.
 ✅I have added entries for my game in the main README.md.
 ✅I have added README.md in my folder.
 ✅I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot (127)
Screenshot (128)
Screenshot (126)

<br>

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @misterraina ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @misterraina,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by kunjgit** [comment]
Thank you  @misterraina , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by misterraina** [comment]
@kunjgit sir its #2608 and its an open issue also i commented there 'assign'

**Pull request closed without merging**
