### PR TITLE
Space invaders

### LINKED ISSUE #1108: [New game]: space Invaders
### 🎮 Game Request

Game logic and basic description
In Space Invaders, the player controls a small spaceship that moves horizontally at the bottom of the screen. The objective is to shoot and destroy waves of descending alien invaders while avoiding their projectiles and barriers. The aliens move left and right, gradually descending towards the player's spaceship. If the aliens reach the bottom of the screen or the player's spaceship is hit by an enemy projectile, the game ends.

### Point down the features

Game points
Player-Controlled Spaceship
Shooting Mechanism
Alien Invaders

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Mannu292001**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #1108  

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Space_Invaders

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Mannu292001 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Mannu292001,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by Mannu292001** [comment]
Can you help me understanding better in which file I need to change actually  I am not able to  understand which Readme.md file
need to change?

**Comment by daccdacc** [comment]
Hello @Mannu292001, You need to add you game entry in main [README](https://github.com/kunjgit/GameZone/blob/main/README.md) file.

**Comment by daccdacc** [comment]
Hello @Mannu292001, Your PR for this game is already there.
Make the required changes in PR #1242 
I am closing this PR as it is duplicate PR.
In case of any issue, you can reach out to us on [Discord](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment]
Thank you  @Mannu292001 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
