### PR TITLE
Fixed #4101 ( Guess_The_Number ) 

### LINKED ISSUE #4101: [Bug]: Three bugs in Guess The Number Game
### Description: There are three bugs in the game 
- Once you have completed the game and won, now if you keep pressing the guess button the no. of tries you used keeps increasing
- But if you lost the game and lost all lives, now if you keep pressing the guess game , the  ***Guessed numbers are:***  , keep adding more numbers
- third if you reset the game , the no of lives already used do not get updated for new game instead its the same of previous game , once you start , then it get updated

### Description : Expected Behavior
- once you complete the game the guess button , should not do anything 
- reset button should reset the game totally, not only internally but also on the display

### I have already fixed these bugs in my local repo and also well commented them :

- Manupulating Dom to update screen in reset  button so that the lives are reset properly
- Added two if's to the Play function to check if user has won or lost , so that pressing the Guess button don't run the game function

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by mohitgedar**
## PR Description 📜

Fixes #4101 

I have fixed the issue #4101 , in which I fixed three bugs of the game 

1. Once you have completed the game and won, now if you keep pressing the guess button the no. of tries you used keeps increasing
Guess The Number Game - bug1
2. But if you lost the game and lost all lives, now if you keep pressing the guess game , the ***Guessed numbers are:*** , keep adding more numbers
Guess The Number Game - Bug2
3. third if you reset the game , the no of lives already used do not get updated for new game instead its the same of previous game , once you start , then it get updated
Guess The Number Game - Bug3

### What I did 
- Manupulated Dom to update screen in reset button so that the lives are reset properly
- Added two if's to the Play function to check if user has won or lost , so that pressing the Guess button don't run the game's play function to the end.

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have specified the respective issue number for which I have requested the PR.
- [X] I have added screenshots of the bug in this Pull Request for reference

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @mohitgedar ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Hi there! the changes you made are not working properly!! ⚠ 
Make suitable and visible changes on the project instead . the changes on current pr hamper   other processes of the project.

**Comment by mohitgedar** [comment]
can you elaborate further , "the changes on current pr hamper other processes of the project." I don't know what to improve unless i know what is getting hampered . 
"Make suitable and visible changes on the project instead" . how do I make bug fixing visible ? 

please explain . I am not understanding your requested changes

**Comment by ishita-43** [comment]
Try running the project locally and make sure that it works fine even after making the changes without impacting the functionality eg i guess after changes the guess button is not working properly.

**Comment by mohitgedar** [comment]
@ishita-43  it's working well and good locally , also that bugs that I provided in PR with images , are fixed . it also don't have any conflict with main branch .

**Comment by mohitgedar** [comment]
https://github.com/kunjgit/GameZone/assets/29174711/a77308bc-58b4-47c7-8772-97bd2e8ddca8

here is a video of project working locally after changes , and bugs fixed

**Comment by ishita-43** [comment]
> working.project.after.changes.mp4 
> here is a video of project working locally after changes , and bugs fixed

You need to update your pr javascript file as your forked changes doesnt matches with the pr you created!!
Please match your pr code and the code in your forked repo which may be you are running.
I hope you will make desired changes soon!!

**Comment by mohitgedar** [comment]
everything is updated, my forked repo , my cloned repo , my pr , i don't see any difference , even fetched the newly merged pr's  , i had one other branch in my forked repo , in which i was working on another game , i deleted that to be sure that , that is not what you are talking about  , and if there is still some issue , lets me know 

my forked repo is 6 commits ahead , which are the commits of this pr , and when i go to the commit , i get a option to view pr , not to create a pr of push further code , as there was no changes in the code after the pr was created


mohitgedar_GameZone at secondary - Brave 09-06-2024 9 19 19 PM
mohitgedar_GameZone at secondary - Brave 09-06-2024 9 19 34 PM

**Comment by ishita-43** [comment]
ok send ss of your js file code

**Comment by mohitgedar** [comment]
main js - GameZone - Visual Studio Code 10-06-2024 8 24 30 AM
main js - GameZone - Visual Studio Code 10-06-2024 8 24 40 AM
main js - GameZone - Visual Studio Code 10-06-2024 8 24 50 AM

**Comment by mohitgedar** [comment]
@ishita-43  i have provided the screenshots of js file , do check it out , it's the same as the code of this pr

**Comment by ishita-43** [comment]
OK DID YOU TRIED RUNNING  THIS JS FILE WITH HTML AND CSS!!

**Comment by mohitgedar** [comment]
@ishita-43  @kunjgit I am closing this pull request , because the issues doesn't seem to be resolving , I don't understand the problem here, the code is working fine on my local machine with latest changes of main branch . there is nothing too much that i changed , i just added two if statements to stop the unnecessary functionality , and modified DOM once to show the latest changes on reset, nothing else was changed , but still there are changes requested , what am i supposed to change ? it's not like i modified too much that the files are not working anymore .

**Comment by kunjgit** [comment]
Thank you  @mohitgedar , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
