### PR TITLE
Added Sky Dodge

### LINKED ISSUE #2637: [New game]: Sky Dodge
### 🎮 Game Request

Game Description:
"Sky Dodge" is an exhilarating arcade-style game where you take control of a nimble flying object soaring through the sky. Your mission is to deftly navigate through the sky while avoiding the rain of falling blocks. Show off your piloting skills as you dodge and weave through the blocks to stay safe and achieve the highest score possible. Be cautious, as the challenge intensifies with each passing moment. How long can you last in the sky without a collision?

Game Logic:

- Player Control: The player controls a flying object using left and right arrow keys or A and D keys to move horizontally across the screen.

- Falling Blocks: Blocks of various shapes and sizes descend from the top of the screen towards the player's flying object at random intervals.

- Dodging Mechanism: The player must navigate the flying object left or right to avoid colliding with the falling blocks. Each successful dodge increases the player's score.

- Game Over: The game continues until the player's flying object collides with a falling block. Upon a collision, the game ends, and the player is presented with their score and whether they have beaten their previous high score.

- Play Again: After a game over, the player has the option to play again. If they choose to play again, the game resets, and a new round starts after a brief delay.

- Difficulty: Player can adjust the difficulty level during game.

### Point down the features

Game points

- Score and High Score: The game keeps track of the player's score, and it also records the highest score achieved as the player's "High Score." The High Score is stored in the browser's local storage to persist across sessions.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by tayyab-ilyas**
## PR Description 📜

Created and added new game Sky Dodge. Your mission is to deftly navigate through the sky while avoiding the rain of falling blocks. Show off your piloting skills as you dodge and weave through the blocks to stay safe and achieve the highest score possible. Be cautious, as the challenge intensifies with each passing moment. How long can you last in the sky without a collision?

Fixes #2637 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @tayyab-ilyas ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by tayyab-ilyas** [comment]
hey @gurjeetsinghvirdee ! can you check this out? please don't forget to give the gssoc'23 labe. Thanks :)

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Make a separate file for css & js don't mixup in one file

**Comment by tayyab-ilyas** [comment]
hey @gurjeetsinghvirdee I've fixed it, please review :)

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM 🍁

**Comment by kunjgit** [comment]
Thank you  @tayyab-ilyas , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
