### PR TITLE
Pig game added

### PR DESCRIPTION
**Pull request by PrateekPsingh**
## PR Description 📜

This pull request represents the successful addition of the Pig game to the games directory, ensuring strict adherence to the established code of contributing guidelines and code of conduct.

Fixes # <67>

<hr>
 
## Mark the task you have completed ✅

- [ ✔] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✔] I have performed a self-review of my own code or work.
- [✔ ] I have commented my code, particularly in hard-to-understand areas.
- [✔ ] My changes generates no new warnings.
- [ ✔] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✔] I have added screenshot for website preview in assets/images 
- [ ✔ ] I have added entries for my game in main README.md
- [ ✔ ] I have added README.md in my folder 
- [  ] I have added working video of the game in README.md (optional)
- [ ✔ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

p1

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @PrateekPsingh ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @PrateekPsingh 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @PrateekPsingh !! during the time you are making PR make sure you tag issue properly and also 
you need to add readme file to your game and make sure you have your entry on main README games section of GameZone !!
so follow proper guideline and create PR again !! 👀

**Comment by kunjgit** [comment]
Thank you  @PrateekPsingh , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by PrateekPsingh** [comment]
> Hey @PrateekPsingh !! during the time you are making PR make sure you tag issue properly and also you need to add readme file to your game and make sure you have your entry on main README games section of GameZone !! so follow proper guideline and create PR again !! eyes

I will create a new PR with all the changes as mentioned but is there any discrepancy in my game readme file as you have told me to add inspite of the fact that i have added it in the folder.

**Pull request closed without merging**
