### PR TITLE
Aqua sort

### LINKED ISSUE #4036: [New game]: AquaSort: A Water Sorting Puzzle
### 🎮 Game Request

Game Request:
Dive into the refreshing world of AquaSort, a water sorting puzzle adventure that challenges your strategic thinking and problem-solving skills. Inspired by the popular water sort puzzle game, AquaSort takes the concept to the next level with immersive gameplay and captivating challenges.

### Point down the features

Game Logic:
In AquaSort, players are presented with a series of test tubes filled with colorful water. The objective is to sort the water in each tube so that each tube contains only one color of water. To achieve this, players can transfer water between tubes, but there are rules to follow:

Players can only transfer water from one tube to another if the receiving tube is either empty or has the same color of water on top.
The last layer of water in a tube must match the color of the water being transferred.
As players progress through levels, they will encounter increasingly complex arrangements of test tubes and water colors, requiring careful planning and strategic thinking to solve.

image

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
## PR Description 📜

The Aquasort game has been implemented to provide players with a challenging water sorting puzzle experience.
Fixes #4036 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

image

<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @thevijayshankersharma ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @thevijayshankersharma,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by thevijayshankersharma** [comment]
@kunjgit Why is it showing add README.md even though its already there.

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @thevijayshankersharma,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by thevijayshankersharma** [comment]
@kunjgit Have a look here.

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @thevijayshankersharma , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
