### PR TITLE
Added Color_Blast_Game

### LINKED ISSUE #1681: [New game]: Color Blast
### 🎮 Game Request

In this game player have to move a white box from left to right and need to shoot down the boxes of color above.
He need to be procted its self from the colors droping from above and if he heat by color 3 times then game over.

### Point down the features

- it is a single player game.
- player can move its boxes from left to right using 'A' and "D" or left and right arrow key
- Shooting can be done using space button.

**ScreenShot**
image

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by lakhan06**
## PR Description 📜
In this game player have to move a white box from left to right and need to shoot down the boxes of color above.
He need to be procted its self from the colors droping from above and if he heat by color 3 times then game over.

- It is a single player game.
- Player can move its boxes from left to right using 'A' and "D" or left and right arrow key
- Shooting can be done using space button.

Fixes #1681 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

https://github.com/kunjgit/GameZone/assets/119161467/5505527e-d86c-4ba3-bd04-d6db8f50ade5

@kunjgit  I am writing to kindly request your attention and consideration in reviewing and accepting my pull request. I would greatly appreciate it if you could allocate some time to review the pull request and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly.
--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @lakhan06 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by lakhan06** [comment]
@kunjgit I am writing to kindly request your attention and consideration in reviewing and accepting my pull request. I would greatly appreciate it if you could allocate some time to review the pull request and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly.

**Comment by lakhan06** [comment]
@kunjgit I am writing to kindly request your attention and consideration in reviewing and accepting my pull request. I would greatly appreciate it if you could allocate some time to review the pull request and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly.

**Comment by kunjgit** [comment]
Thank you  @lakhan06 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
