### PR TITLE
Added Connect 4 Game

### LINKED ISSUE #4592: [New game]: Connect_4
### 🎮 Game Request

A strategy board game played by two players who take turns dropping colored discs from the top into a vertically suspended grid.
 

### Point down the features

The game ends as soon as a player successfully connects four of their discs in a row. The connection can be vertical, horizontal, or diagonal.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by ThisIsSahaj**
## PR Description 📜

A strategy board game played by two players who take turns dropping colored discs from the top into a vertically suspended grid.

Fixes #4592 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Connect_4

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @ThisIsSahaj ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @ThisIsSahaj, You have reached your limit to contribute in GameZone with a score of 180. 
 We believe in giving equal opportunity to everyone so you will not be able to contribute to GameZone now onwards. 💗 
 Thank you for your valuable time and contribution in GameZone 🕹️! 

 Your merged pull requests:
- [#4535](https://github.com/kunjgit/GameZone/pull/4535) with labels: level3 score: (45)
- [#4489](https://github.com/kunjgit/GameZone/pull/4489) with labels: level3 score: (45)
- [#4450](https://github.com/kunjgit/GameZone/pull/4450) with labels: level3 score: (45)
- [#4397](https://github.com/kunjgit/GameZone/pull/4397) with labels: level3 score: (45)

**Comment by kunjgit** [comment]
Thank you  @ThisIsSahaj , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by ThisIsSahaj** [comment]
> Hey @ThisIsSahaj, You have reached your limit to contribute in GameZone with a score of 180. We believe in giving equal opportunity to everyone so you will not be able to contribute to GameZone now onwards. 💗 Thank you for your valuable time and contribution in GameZone 🕹️!
> 
> Your merged pull requests:
> 
> * [#4535](https://github.com/kunjgit/GameZone/pull/4535) with labels: level3 score: (45)
> * [#4489](https://github.com/kunjgit/GameZone/pull/4489) with labels: level3 score: (45)
> * [#4450](https://github.com/kunjgit/GameZone/pull/4450) with labels: level3 score: (45)
> * [#4397](https://github.com/kunjgit/GameZone/pull/4397) with labels: level3 score: (45)

Why is that this user got to contribute so many times in the `GameZone` repository and I only get to contribute 4 times 
image

**Pull request closed without merging**
