### PR TITLE
Fruit Slicer

### LINKED ISSUE #4405: [New game]:  Fruit Slicer
### 🎮 Game Request

Fruit Slider is a fun and engaging puzzle game where players slide fruit pieces on a grid to align them in a specific order or pattern. The objective is to complete the puzzle in the fewest moves possible.

### Point down the features

- Players can slide fruit pieces horizontally or vertically into an adjacent empty slot.
-The goal is to rearrange the fruit pieces to match a given target pattern or order.
- Bonus points for completing levels quickly or with fewer moves.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by narayani9120**
## PR Description 📜
Fruit Slider is a fun and engaging puzzle game where players slide fruit pieces on a grid to align them in a specific order or pattern. The objective is to complete the puzzle in the fewest moves possible.
Fixes #4405

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

Screenshot 2024-06-12 213213

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @narayani9120 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Please images to the asset folder to the main GameZone folder!!

**Comment by narayani9120** [comment]
I have modified the changes, Can you check and merge my PR @kunjgit

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by kunjgit** [comment]
Thank you  @narayani9120 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
