### PR TITLE
[New Game] : Doodle_Jump

### LINKED ISSUE #251: [New game]: DOODLE JUMP
### 🎮 Game Request

Game logic and basic description
a character named "Doodler" who jumps on platforms to climb as high as possible while avoiding obstacles. The game's logic can be broken down into several key components:

Character and Platform Generation:

The game starts by generating the Doodler character at the bottom of the screen and a series of platforms above it.
Platforms can be generated randomly or using a predetermined pattern.
The position and spacing between platforms should allow the player to jump from one platform to another.
Player Input:

The player controls the Doodler's movement by tilting their device or using on-screen buttons.
The player's input determines the horizontal movement of the Doodler.
Jumping Mechanics:

The Doodler jumps automatically when standing on a platform.
The height and distance of the jump can be determined by the length of time the player holds the jump button or tilts their device.
Gravity and Falling:

The Doodler is affected by gravity, causing it to fall if it's not standing on a platform.
The falling speed can be constant or increase gradually as the player climbs higher.

### Point down the features

Game pointsScoring:

The player earns points as they climb higher.
Points can be awarded based on the distance climbed, platforms jumped on, or other achievements.
Power-Ups and Obstacles:

Power-ups can appear on platforms or floating in the air, providing temporary abilities or boosts.
Obstacles such as monsters, UFOs, or moving platforms can hinder the player's progress.
Colliding with obstacles usually results in game over, but power-ups may help the player overcome or destroy them.
Game Over:

The game ends when the Doodler falls off the bottom of the screen.
The player's score is recorded and displayed, allowing them to compare their performance with previous attempts.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by MohnishK7**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes  #251

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @MohnishK7 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by MohnishK7** [comment]
@kunjgit is the pull request correct?
can you please check it .

**Comment by kunjgit** [comment]
Hey @MohnishK7 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by MohnishK7** [comment]
@Arun9739 Ya here is the screenshot of a full web view.

image

**Comment by Arun9739** [comment]
@MohnishK7 Update your game's entry in main README file as per guidelines.

**Comment by MohnishK7** [comment]
@Arun9739 already updated

**Comment by Arun9739** [comment]
@MohnishK7 Don't give the direct number in main README. Just give a '*' in place of number, we will add the number. Also resolve branch conflicts.

**Comment by MohnishK7** [comment]
@Arun9739 sir, the above conflict was not present before.  #427 did the same thing as mine and got the successful merge. I have made the first issue regarding the doodle jump and as per the guidelines of gssoc . Could you look into this matter?
Thank you

**Comment by MohnishK7** [comment]
my pull request is first #321 and how come #427 pull request got merge first ?
how will i resolve this conflict?

**Comment by Arun9739** [comment]
@MohnishK7 Create separate branches for separate PR. Also only one PR for one issue. If you're facing conflict issue, please create new pr.

**Comment by kunjgit** [comment]
Hey @MohnishK7 !! we already have this game on GameZone !!
if you want you can do enhancement we can't have exact same again !!

**Comment by kunjgit** [comment]
Thank you  @MohnishK7 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
