### PR TITLE
Updated Rabbit Rush: Added new features and UI enhancement

### PR DESCRIPTION
**Pull request by Changingthegame**
## PR Description 📜

I have submitted a pull request to address the issue #3369 Enhancement: Rabbit Rush Game. I have tried my best to make the game better as I said to you.
Fixes # <3369>

<hr>
 
## Mark the task you have completed ✅

- [ x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [ x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [x ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ x
Gamezone1
Gamezone2
Gamezone3
] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Changingthegame ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Changingthegame** [comment]
Can you please tell me about the progress of  review of my PR.

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Changingthegame , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Changingthegame** [comment]
Hello @kunjgit , I have done necessary changes and pull request has been approved and merged. Can you plz close this issue as I am unable to get assigned and work on another issue in your project. Please do it as soon as possible...

**Pull request merged**
