### PR TITLE
Adding :  Color The Page Game

### LINKED ISSUE #3884: [New game]: Color The Page
### 🎮 Game Request

Game logic and basic description:
This a simple project where user can generate a random color for background, random gradient background and random button background .The heading also changes contrast on the basis of basis of background color. Background color also changes in case button background is button color is light.

### Point down the features

Game points:
User can have RGB value random color and can see how a color would look on background of the page and button. User can also have random gradient background color.

Screenshot 2024-05-30 124457

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by codewithganeshhh**
## PR Description 📜:
This a simple project where user can generate a random color for background, random gradient background and random button background .The heading also changes contrast on the basis of basis of background color. Background color also changes in case button background is button color is light. 
User can have rgb value random color and can see how  a color would look on background of the page and button. User can also have  random gradient background color.
 project is easy. The user only have to press the button and a random color would be generated

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #3884 

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅ ] I have added screenshot for website preview in assets/images 
- [✅ ] I have added entries for my game in main README.md
- [✅ ] I have added README.md in my folder 
- [✅ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2024-05-30 124457

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @codewithganeshhh ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @codewithganeshhh,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by kunjgit** [comment]
@codewithganeshhh you have deleted readmefile and not yet done changes !

**Comment by codewithganeshhh** [comment]
dear @kunjgit please check as soon as possible

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @codewithganeshhh , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
