### PR TITLE
Enhanced City_builder_game to a new level

### LINKED ISSUE #4665: [Enhancement]: City_Builder_Game needs complete renewal
## Game enhancement: City_Builder_Game
- Currently the game do nothing , you have fixed amount of credit  with which you just add some building , there is no start or end of the game , there is no win or lose

### Describe the solution you'd like

- I would like to enhance the game completely , building  should cost to create , and maintain , factories should produce money , 
- Add a pollution feature , where houses and factories create pollution and parks reduce the pollution
- Add a restart button to restart anytime you want 
- Final detailed result should be shown in the end which should also include the restart button
- CSS needs to be improved to make the game look better 
- Instructions should be added , how to play , what the game does  , what is its motive 
- Much more features can be added , as one starts working on it 

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by mohitgedar**
## PR Description 📜

Fixes #4665

- I have enhanced the game to a new level , previously it was not doing very much , you had fixed amount of credit with which you just add some building , there is no start or end of the game , there is no win or lose.

- After this enhancement the game have more features like factories produce pollution with time, they also produce money , parks reduce the pollution and cost money for maintaining them same is for houses , they generate pollution and need money for maintenance . 

- Also there are condition to win the game or lose the game , once the game end you can restart it , or if you want you can even restart in the middle of game.

- Also made the game responsive to different screen sizes.
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [X] I have added README.md in my folder 
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

### start of the game
City_Builder_Game
### completed the game
City Builder Game - Brave 22-06-2024 12 30 09 PM
### won the game
City Builder Game - Brave 22-06-2024 12 31 57 PM

--- 
<br>

### Note :- 
There was some trouble cloning the project , so I uploaded the files directly to forked repo , because of which ,you don't see what I changed and what I deleted , it shows that I deleted everything and rewrote everything.

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @mohitgedar ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by mohitgedar** [comment]
hello @ishita-43 , please review this PR

**Comment by mohitgedar** [comment]
hey @ishita-43 , now that your exams are complete , please review this PR.

**Review by ishita-43 — APPROVED** [review]
Good to go

**Comment by kunjgit** [comment]
Thank you  @mohitgedar , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
