### PR TITLE
Cube Smasher Game

### LINKED ISSUE #3670: [New game]: Smash Cubes
### 🎮 Game Request

The game starts by setting up the Three.js scene, including the camera, renderer, and lights. It also initializes important things like the level, score, and how many targets there are. 🚀 Colorful cubes spin around in the scene, giving it a lively feel. 🎨 Players can click on the screen, and the game will figure out if they've clicked on one of the cubes. When they do, the cube disappears in a big explosion of particles going everywhere. 💥 The game keeps track of how many cubes players have hit, updating their score and showing it on the screen. 📊 As players do well and move through levels, the game gets harder by making the cubes spin faster and adding more of them. 📈 After beating a level, players get encouraging messages and can choose to start again for more fun. 🏆✨

## Features:
- 🎮 Interactive 3D gameplay with clickable cubes.
- 🌈 Colorful spinning cubes for visual appeal.
- 💥 Explosive particle effects for click feedback.
- 📈 Progressive difficulty with multiple levels.
- 🎉 Victory message upon completing all levels.
- 🔄 Option to restart the game for endless fun.
- 🖥️ Responsive design for various screen sizes.
- 🎨 Stylish HUD for displaying score and level information.
- 🎵 Ambient lighting and spotlights for atmospheric effects.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by hiteshhhh007**
## PR Description 📜

I have added a new game called Cube Smasher. It has been done using HTML,CSS & JS (three.js has also been used)
Fixes #3670 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @hiteshhhh007 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @hiteshhhh007,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by kunjgit** [comment]
Thank you  @hiteshhhh007 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by hiteshhhh007** [comment]
please look into this! @kunjgit

**Pull request closed without merging**
