### PR TITLE
added gem cruncher

### PR DESCRIPTION
**Pull request by Aditijainnn**
Fixes # <your_issue_number>
#4436

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in GameZone's README.md
- [x] I have added README.md in my Game folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.
- [x] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸
353724741-315b6597-bdfd-403f-a708-ea46e9850e8f

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Aditijainnn ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Aditijainnn** [comment]
i have raised new pr and updated readme file also please check

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Add your game image in asset folder of the repo follow naming convention while naming that image

**Comment by Aditijainnn** [comment]
> Add your game image in asset folder of the repo follow naming convention while naming that image

done please merge my pr

**Review by ishita-43 — APPROVED** [review]
Ready to merge

**Comment by Aditijainnn** [comment]
please merge

**Comment by ishita-43** [comment]
> please merge

Merge will be proceeded by the admin soon!

**Comment by Aditijainnn** [comment]
ok

**Comment by ishita-43** [comment]
Please resolve merge conflicts

**Comment by Aditijainnn** [comment]
Done resolved them

**Comment by kunjgit** [comment]
Thank you  @Aditijainnn , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
