### PR TITLE
Shell Game Completed

### LINKED ISSUE #3282: [New game]: Shell Game
### 🎮 Game Request

Game logic and basic description: The Shell Game is a simple game where a ball is hidden under one of three bowls, which are then shuffled. The player must track the bowl containing the ball and guess its position after the shuffle. It's a fun and challenging game of observation and memory.

### Point down the features

Game points : 
Interactive Gameplay: Engage in a dynamic game where you need to follow the movement of the bowls and guess the correct position of the hidden ball.
Random Shuffling: Each game offers a unique challenge with a random shuffling mechanism ensuring a fresh experience every time.
User-Friendly Interface: Simple and intuitive controls with a clean design, making it easy for players of all ages to enjoy.

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Tamilkumaran17**
## PR Description 📜
<br>

new game completed.

Fixes #3282
 
## Mark the task you have completed ✅
<br>

- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅ ] I have performed a self-review of my own code or work.
- [ ✅ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✅ ] My changes generates no new warnings.
- [ ✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅ ] I have added screenshot for website preview in assets/images 
- [ ✅ ] I have added entries for my game in main README.md
- [ ✅ ] I have added README.md in my folder 
- [ ✅ ] I have specified the respective issue number for which I have requested the new game.

<hr>
--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Tamilkumaran17** [comment]
game added in README file!

**Comment by Tamilkumaran17** [comment]
any changes needed?

**Review by Tamilkumaran17 — COMMENTED** [review]
README updated

**Comment by kunjgit** [comment]
@Tamilkumaran17 resolve the conflicts !

**Comment by Tamilkumaran17** [comment]
Can you check now, i have resolved the conflicts!

**Comment by kunjgit** [comment]
@Tamilkumaran17 resolve conflicts as there are few games added after your PR you have to make sure you are adding your game at last
!

**Comment by Tamilkumaran17** [comment]
Now i set my game link at last. Can you check it now, if any other conflicts occur, i apologize to that and give me clear details about that for my reference!

**Review by kunjgit — APPROVED** [review]
LGTM!

**Comment by kunjgit** [comment]
@Tamilkumaran17 resolve the conflicts !

**Comment by kunjgit** [comment]
Thank you  @Tamilkumaran17 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
