### PR TITLE
Adds Random Choice Picker game 🕹️

### LINKED ISSUE #5143: [New game]: Random Choice Picker 🎲
### 🎮 Game Request

Introducing the Random Choice Picker!
Enter your choices into a textarea, hit ENTER, and let the game shuffle and reveal a random option.
Perfect for making quick decisions or adding a bit of fun!

image

### Point down the features

- **Interactive Textarea**: Input choices separated by commas.
- **Pick Button**: Randomly selects a choice when pressed.
- **Result Display**: Shows the selected choice.
- **Responsive Design**: Optimized for all devices.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by SanskarSinghiit**
## PR Description 📜

Fixes #5143 

This pull request introduces the Random Choice Picker game to the repository. The game allows users to input a list of choices and randomly selects one when a button is clicked. This addition enhances the repository with a new and engaging game option.

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in GameZone's README.md
- [x] I have added README.md in my Game folder 
- [x] I have specified the respective issue number for which I have requested the new game.
- [x] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @SanskarSinghiit ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — APPROVED** [review]
Ready to merge

**Comment by kunjgit** [comment]
@SanskarSinghiit resolve the merge conflicts !

**Comment by ishita-43** [comment]
> @SanskarSinghiit resolve the merge conflicts !

@kunjgit done!!

**Comment by kunjgit** [comment]
Thank you  @SanskarSinghiit , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by SanskarSinghiit** [comment]
Thank you.

**Pull request merged**
