### PR TITLE
Disney trivia

### LINKED ISSUE #4073: [New game]: Disney Trivia
### 🎮 Game Request

A fun and engaging trivia game about Disney movies, characters, and history.

### Point down the features

Features of this game will be as follows:

- Question Display: Shows a trivia question and multiple-choice answers.
- Next Button: Moves to the next question when clicked.
- Timer: Automatically moves to the next question when time runs out.
- Scoreboard: Tracks and displays the player's score at the end of the game or upon restarting.
- Restart Functionality: Allows players to restart the game from the beginning with a reset score.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by manmita**
## PR Description 📜
Added a new game disney trivia which is a fun quiz about disney movies, characters, etc.

Fixes #4073 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot from 2024-06-06 22-46-24

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @manmita ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by manmita** [comment]
@kunjgit please let me know what is pending

**Comment by manmita** [comment]
@ishita-43 please review this pr i have done everything as per the guidelines.

**Comment by kunjgit** [comment]
Thank you  @manmita , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
