### PR TITLE
[New game]: Screen Pet Game #3953

### LINKED ISSUE #3953: [New game]: Screen Pet Game
### 🎮 Game Request

Game logic and basic description

Screen Pet game is an event-based program, which means the functions it performs and the order in which it performs all functions is dependent on user input. In such programs, user input can take any form, such as keypresses and mouse clicks.

### Point down the features

Game points

Happy Face: When you will click on it with the mouse the screen pet will blush and it will look happy.

Cheeky Face: If you double-click it, then it will show its tongue to you.

Sad Face: If you ignore it then it will become sad and the point where you click then it will become happy again.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by nisargaa20**
## PR Description 📜

This PR fixes the issue related to the implementation of the Screen Pet game, which is an interactive, event-based program where a virtual pet responds to user interactions. The pet displays different emotions such as happiness, cheekiness, and sadness based on user interactions.

Fixes  #3953

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screen_Pet_Game_1
Screen_Pet_Game_2
Screen_Pet_Game_3
Screen_Pet_Game_4

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @nisargaa20 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @nisargaa20,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @nisargaa20,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by nisargaa20** [comment]
@kunjgit kindly check the changes

**Comment by kunjgit** [comment]
Thank you  @nisargaa20 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
