### PR TITLE
Resolved Dark mode issue

### LINKED ISSUE #4353: BUG 🐞: Dark mode gets turned off on refreshing the page
### Give a brief about the bug ✍️

Hey @kunjgit,
Here is the issue -
The dark mode preference does not persist across page refreshes.
Each time the page is refreshed, the mode resets to the default instead of maintaining the user-selected mode (dark or light).
I think it is due to the theme state is not being persisted when the page is refreshed.

**Screenshots**
- Before refreshing the page looks like(currently in light mode) :

image

- After refreshing the page :

image

### What is the expected behavior? 🤔

The selected dark or light mode should persist across page refreshes.
If a user selects dark mode, the page should remain in dark mode even after refreshing.

I hope I was able to explain the issue.
If so, Could you please assign this issue to me under GSSoC 24?

### Provide step by step information reproduce the bug 📄

**To Reproduce**
- Go to the website.
- Toggle the dark mode switch to change the theme.
- Refresh the page.
- Observe that the theme reverts to the default mode instead of retaining the selected mode.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by aslams2020**
hi @kunjgit,
closes #4353 

I have resolved the issue to persist the dark mode preference across page refreshes using localStorage.
The changes ensure that the user's selected mode (dark or light) is maintained even after the page is refreshed.

Please take a look and review it.
Also, please add the labels. 

## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @aslams2020 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by aslams2020** [comment]
Hey @kunjgit,
could you please take a look and review it.

**Review by ishita-43 — APPROVED** [review]
good to go!!

**Comment by kunjgit** [comment]
Thank you  @aslams2020 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
