### PR TITLE
New Game : Ganesh QR Maker

### LINKED ISSUE #4367: [New game]:  Ganesh QR Maker
### 🎮 Game Request

Game logic and basic description :
It was used Latest Technology
A simple web application which will generate a QR Code.

### Point down the features

QR CODE Generator

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by codewithganeshhh**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below: 

It was used Latest Technology
A simple web application which will generate a QR Code.

Fixes #4367 

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅] I have performed a self-review of my own code or work.
- [ ✅] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [ ✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅] I have added screenshot for website preview in assets/images 
- [ ✅] I have added entries for my game in main README.md
- [✅ ] I have added README.md in my folder 
- [ ✅] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
QR CODE Generator

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @codewithganeshhh ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @codewithganeshhh,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by codewithganeshhh** [comment]
All Resolve @kunjgit @Ishan-77 check this

**Comment by codewithganeshhh** [comment]
Dear @kunjgit Please check and merge

**Comment by codewithganeshhh** [comment]
dear @kunjgit please check asap

**Comment by codewithganeshhh** [comment]
@kunjgit @ishita-43 please review and merge

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @codewithganeshhh , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
