### PR TITLE
[New game]: Ninja-Run & Wall Crosser Completed

### PR DESCRIPTION
**Pull request by Durgesh4993**
https://github.com/kunjgit/GameZone/assets/98798977/df554522-9fd2-4af8-b995-f4743793276a

### CODE REVIEW

**Comment by Durgesh4993** [comment]
As you shown in a demo vedio this is properly working and i'll added eye image becaue old photo link was expired that why i'll downloaded the image Hope you like the my work

**Comment by Durgesh4993** [comment]
https://github.com/kunjgit/GameZone/assets/98798977/5a51e736-a974-48bb-83b8-38d4fe2dd420

**Comment by Durgesh4993** [comment]
Demo of Wall Croser also , Please check it out and if you need any changes please tell me i'll be change

**Comment by Durgesh4993** [comment]
#121 #122 Tast Completed

**Review by kunjgit — CHANGES_REQUESTED** [review]
Just don't alter index file ! 
also add your game entry in main readme file 
here ->
image

Other all things are fine 🔥

**Comment by Durgesh4993** [comment]
@kunjgit Now check i'll updated readme file

**Review by kunjgit — CHANGES_REQUESTED** [review]
please don't alter the main index file 👀

**Comment by kunjgit** [comment]
Hey @Durgesh4993 !!
Create PR again by following guidelines 👀

**Comment by kunjgit** [comment]
Thank you  @Durgesh4993 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
