### PR TITLE
Redesigned the paging style

### LINKED ISSUE #1719: [Bug]: Pagination styling is taking up quite a lot space
### Give a brief about the bug ✍️

Description:
image
image

This type of pagination styling is taking up a lot of space of the screen and also not looking that great and appealing to the eye.

### What is the expected behavior? 🤔

Screenshot 2023-06-20 162157
An example of what we can instead use. We can further add colors and styles according to GameZone's UI. This will look much better and presentable.

### Provide step by step information reproduce the bug 📄

By fixing the styling of the Paginng component, this can be achieved! And this will beautify the website further.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Akanksha-202**
## PR Description 📜

I was assigned to redesign the pagination style in order to let it consume less space of entire screen and also to make it responsive.
Fixes #1719 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have specified the respective issue number.

<hr>

## Add your screenshots(Optional) 📸

image

Video Preview
https://www.loom.com/share/7497ba96485d4958bf3ce04267ed39f0?sid=ae7a1641-9b90-4b78-afb5-b26756890d26

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Akanksha-202 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
you have to make changes and implement numbers !! 👀

**Comment by kunjgit** [comment]
Thank you  @Akanksha-202 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Akanksha-202** [comment]
> you have to make changes and implement numbers !! 👀
I'll do it with numbers, is everything else correct with this?
And do I have to create a new PR? since you closed this
@kunjgit

**Pull request closed without merging**
