### PR TITLE
Added Icy_tower_game

### PR DESCRIPTION
**Pull request by pavitraag**
## PR Description 📜
Fixes # 5041

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in GameZone's README.md
- [X] I have added README.md in my Game folder 
- [] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.
- [X] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @pavitraag ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Add your game image in asset folder of fthe gamezone repo

**Comment by pavitraag** [comment]
Done with changes @ishita-43

**Review by ishita-43 — APPROVED** [review]
Approved

**Comment by ishita-43** [comment]
Please resolve merge

**Comment by pavitraag** [comment]
@ishita-43 done

**Comment by kunjgit** [comment]
Thank you  @pavitraag , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
