### PR TITLE
Added the game of ATLAS

### LINKED ISSUE #1907: [New game]: ATLAS: Name the country
### 🎮 Game Request

Game logic and basic description
This is a classic game where players take turns naming countries based on specific rules. It puts the player's geographical skills to a test.

The rules are: 
- The game starts with a predefined word, "atlas". The first player begins by saying the name of a country that starts with the last letter of the word "atlas," which is the letter "s." 
- The second player then responds with the name of a country that starts with the last letter of the country the first player mentioned. 
- The game continues back and forth with players taking turns until a predetermined condition (of 2 passes or 3 incorrect attempts by the player) is met.

### Point down the features

Game points
- In this version of the game, players play against a computer. The player enters a country name, and the computer responds with a country that starts with the last letter of the player's country. The player's objective is to keep the game going by entering valid country names. 
- The game aims to test the players' knowledge of country names, improve their vocabulary, and challenge their ability to think quickly and make associations based on word patterns. 
- It can be an enjoyable and educational game for individuals who are interested in geography or simply want to have fun with wordplay.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by AnkitaBarbora**
## PR Description 📜

Added the game: ATLAS
Fixes #1907 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @AnkitaBarbora,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by AnkitaBarbora** [comment]
Oh okay sir

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @AnkitaBarbora , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by AnkitaBarbora** [comment]
Oh okay sir, I thought I could add it in this project because the game logic and gameplay was different. But no problem, I would love to continue contributing for this project 😄

**Pull request closed without merging**
