### PR TITLE
Falling Ball

### PR DESCRIPTION
**Pull request by khushimarothi**
## PR Description 📜

Added a falling ball game
#2574 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @khushimarothi ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @khushimarothi,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @khushimarothi,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by khushimarothi** [comment]
> Hello @khushimarothi, You need to make the following changes:
> 
> * Please add a README.md file inside the newly created folder.
> * Please modify the main README.md file.
> * Please add an image to the assets/images directory.
> 
> Hoping that you will make those changes soon 🚀

Please review I have made these changes

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @khushimarothi,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Comment by khushimarothi** [comment]
@kunjgit Please merge

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Resolve Conflicts @khushimarothi

**Comment by khushimarothi** [comment]
Check @gurjeetsinghvirdee

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM 🍁

**Comment by khushimarothi** [comment]
> LGTM 🍁

can you please update the level label in the issue to level 2 as well. I guess it is the bot who is assigning the label too

**Comment by gurjeetsinghvirdee** [comment]
> > LGTM 🍁
> 
> can you please update the level label in the issue to level 2 as well. I guess it is the bot who is assigning the label too

that doesn't matters, only PR labels will count

**Comment by kunjgit** [comment]
Thank you  @khushimarothi , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
