### PR TITLE
Added Fruity_Fortune

### LINKED ISSUE #4815: [New game]: Fruity Fortune
## Game logic and basic description
The Slot Machine Game is a simple and engaging web-based game where players spin three reels containing various fruit symbols. The objective is to match all three symbols to win a prize. Each spin costs $10, and a successful match rewards the player with $50. Players start with a balance of $100, and the game provides buttons to spin, reset the game, and view the rules.

## Game points
Starting Balance: $100
Cost per Spin: $10
Win Reward: $50 for matching all three symbols
Loss Penalty: $10 for not matching symbols

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by ayush-848**
## PR Description 📜
Fruity Fortune is a vibrant web-based slot machine game. Spin three reels of colorful fruit symbols, aiming to match all three for a $50 win. Start with $100, each spin costs $10.

Fixes #4815

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @ayush-848 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by ayush-848** [comment]
@ishita-43 please check

**Comment by ayush-848** [comment]
@ishita-43 @kunjgit please check it

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Hi there! you need to make following  changes 
Add your game entry in the main Readme.md file of the gamezone refer other entries there for the format 
Add your game image in the asset folder of the gamezone follow contribution guidelines while naming the image

**Comment by ayush-848** [comment]
> Hi there! you need to make following changes Add your game entry in the main Readme.md file of the gamezone refer other entries there for the format Add your game image in the asset folder of the gamezone follow contribution guidelines while naming the image

I have added the Readme file and My game do not contain any image

**Review by ishita-43 — COMMENTED** [review]
Your game entry in readme.md file still not visible

**Comment by ayush-848** [comment]
> Your game entry in readme.md file still not visible

@ishita-43 please check now

**Comment by ayush-848** [comment]
> Your game entry in readme.md file still not visible

@ishita-43 please check now. I have added it

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by kunjgit** [comment]
Thank you  @ayush-848 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
