### PR TITLE
Rock ,Paper & Scissor game

### PR DESCRIPTION
**Pull request by Tusharjoshi1703**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes # <your_issue_number> #11 

<hr>
 
## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
Screenshot (51)

- [x ] My changes generates no new warnings.

- [x ] I have added screenshot for website preview in assets/images 
- [x ] I have added entries for my game in main README.md
- [x ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Tusharjoshi1703 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
add your entry in main readme file and also add your image in assets/images

**Comment by kunjgit** [comment]
Hey @Tusharjoshi1703 make sure you check the demo and follow proper guideline you have told to make changes and you are not doing that !!

**Comment by kunjgit** [comment]
Thank you  @Tusharjoshi1703 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Tusharjoshi1703** [comment]
Sorry for the inconvenience as I'm having semester exams going on. I'll
complete the following by this weekend.
Thank you

**Comment by Tusharjoshi1703** [comment]
Please look after #11 I have completed the following requirements.
Thank you.

**Pull request closed without merging**
