### PR TITLE
Tower defense

### LINKED ISSUE #153: [New game]: Tower Defense
### 🎮 Game Request

A tower defense game is a popular genre of strategy game where the player's objective is to defend a specific location, typically referred to as a "base" or "castle," from waves of enemies. The game typically takes place on a grid-based map, and the player must strategically place defensive structures, known as towers, along the enemy's path to stop their advance.

### Point down the features

1. Tower Placement: Players can strategically place towers along enemy paths or designated areas to attack and eliminate enemies.

2. Enemy Waves: Waves of enemies spawn at regular intervals and move along predetermined paths towards the player's base. Each wave typically increases in difficulty.

3. Resource Management: Players earn resources or in-game currency by defeating enemies. They can use these resources to build or upgrade towers. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by tayyab-ilyas**
## PR Description 📜

A Plants vs Zombies type game where you battle waves of enemies by placing your defensive units and preventing them from reaching your home territory.

Player can Hover on the game grid with your mouse to place defenders, initially you get 300 elixir but placing a defender will consume 100 elixir. 

A players can re-fill your elixir by either hovering over the elixir points randomly displayed on the game grid or by eliminating an enemy, both defenders and enemies have 100 hit points however defenders can shoot projectiles but enemies can only do damage while colliding with a defender

Defeating 1 enemy gives 10 points and 50 points get you a win!

Fixes #153 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

tower_defense

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @tayyab-ilyas ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by tayyab-ilyas** [comment]
hey @kunjgit can you review this? thanks!

**Comment by Arun9739** [comment]
@tayyab-ilyas You are not supposed to change the main index file. Plz bring it back as original or create a new a PR.

**Comment by tayyab-ilyas** [comment]
Hi @Arun9739 I have made the changes, can you review it now? appreciate your response :)

**Comment by tayyab-ilyas** [comment]
hey @kunjgit I've resolved everything can this get merged now?

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Hey @tayyab-ilyas please don't alter main index file !!!!

**Review by kunjgit — CHANGES_REQUESTED** [review]
don't make any changes to main index file !!

**Comment by tayyab-ilyas** [comment]
@kunjgit I did change it initially but resolved it in further commits, it's not changed at all.

**Comment by tayyab-ilyas** [comment]
I've undone the edits in main index, can you review it ?@kunjgit

**Comment by Arun9739** [comment]
@tayyab-ilyas Plz resolve the branch conflicts

**Comment by tayyab-ilyas** [comment]
@Arun9739 @kunjgit I've done everything as asked however if other PRs get merged then README.md is again gonna have conflicts. Please give this a review and merge if possible, thanks!

**Comment by Arun9739** [comment]
@tayyab-ilyas Again there have been some conflicts, resolve it .

**Comment by tayyab-ilyas** [comment]
> @tayyab-ilyas Again there have been some conflicts, resolve it .

@Arun9739 again, I have resolved it but its due to new PRs being merged. I can't keep updating with every new PR

**Comment by kunjgit** [comment]
Thank you  @tayyab-ilyas , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
