### PR TITLE
Added Quiz game

### LINKED ISSUE #4961: [New game]: Quiz game with timer
### 🎮 Game Request

Game logic and basic description

A quiz game with a timer challenges players to answer questions within a limited time frame, adding an element of urgency and excitement. Players must quickly recall and select the correct answers before the timer runs out.

### Point down the features

Game points

Timed Questions: Each question has a countdown timer, adding urgency.
Score Tracking: Keeps track of the player's score based on correct answers and time taken.
Responsive Design: Compatible with various devices, ensuring a smooth experience on both desktop and mobile.
Review Answers: Allows players to review their answers after completing the quiz.
Customizable Timer: Players can set the timer duration according to their preference.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by heli0707**
## PR Description 📜
A quiz game with a timer challenges players to answer questions within a limited time frame, adding an element of urgency and excitement. Players must quickly recall and select the correct answers before the timer runs out.

Fixes #4961

https://github.com/user-attachments/assets/209ade0b-d1fb-4ee9-b2f3-bb4adbef8aee
<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Quiz_With_Timer

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @heli0707 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — APPROVED** [review]
Good to go

**Comment by ishita-43** [comment]
Please resolve merge conflicts

**Comment by heli0707** [comment]
> Please resolve merge conflicts

solved

**Comment by kunjgit** [comment]
Thank you  @heli0707 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
