### PR TITLE
[Color Blast Game] Added!

### LINKED ISSUE #2715: [New game]: Color Blast Game
### 🎮 Game Request

Game logic and basic description

I would like to introduce new game i.e Color Blast

### Point down the features

Game points

It includes features as Scores and Lives and needs to play accordingly. It has only one player capacity game

# View
Screenshot 2023-08-02 at 11 50 54 AM

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by SnigdhaP2022**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below

New game Color Blast has been added!
Fixes #2715 

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅ ] I have added screenshot for website preview in assets/images 
- [✅ ] I have added entries for my game in main README.md
- [✅ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ✅] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
# Begin
Screenshot 2023-08-02 at 12 17 08 PM

# End
Screenshot 2023-08-02 at 12 16 54 PM

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @SnigdhaP2022 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by SnigdhaP2022** [comment]
@kunjgit  @gurjeetsinghvirdee  Kindly, review this PR

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Copied from Codepen: **https://codepen.io/natewiley/pen/ExEoeZ**

**Comment by kunjgit** [comment]
Thank you  @SnigdhaP2022 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
