### PR TITLE
[GSSoC'23] Guess The Random Shape Game Ready

### LINKED ISSUE #1862: [New game]: Shape Guesser Game [GSSoC'23]
### 🎮 Game Request

Game logic and basic description

- Showing the dotted picture of the shape
- Showing different options
- Also Adding 3 lives for 3 wrong answers only, otherwise game will be over
- Current and high score will be shown on the screen

### Point down the features

Game points

- (+1) on chosen of correct answer
- 0 for the wrong answer
- Game will be over when 3 lives are exhausted !

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
- The player will tell the shape formed using dots.
- Options are given in the game.
- If player reaches to 10 points will win the game.
- If player looses all the 5 lifes will lose the game.

Fixes #1862 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Guess_The_Random_Shape

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Avdhesh-Varshney ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Avdhesh-Varshney** [comment]
@kunjgit please review this pull request and requested to merge it into the main branch for a valuable contribution under GSSoC'23 program

**Comment by Avdhesh-Varshney** [comment]
@kunjgit please review this pr. I have removed the conflicts and requested to merge it into the main branch for a successful contribution under GSSoC'23 program

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Avdhesh-Varshney , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Pull request merged**
