### PR TITLE
Added a new game Slide_Master_Puzzle

### PR DESCRIPTION
**Pull request by pani2004**
## PR Description 📜

I have added a new game with title Slide_Master_Puzzle . Issue #3432 

<hr>
 
## Mark the task you have completed ✅

- [x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [ x] My changes generates no new warnings.
- [ x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 

- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot (38)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @pani2004 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @pani2004,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by pani2004** [comment]
@kunjgit I have created a Readme.md file in the folder and can u please help me in how to update the main Readme.md file, what all things will i add there.

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @pani2004,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @pani2004,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @pani2004,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by pani2004** [comment]
@kunjgit What I have to do now?

**Comment by kunjgit** [comment]
@pani2004 resolve the conflicts !

**Comment by pani2004** [comment]
@kunjgit  Can u please help me in resolving the conflicts, in the provided SS what all things I have to remove? Screenshot (39)

**Comment by pani2004** [comment]
@kunjgit resolved the conflicts.

**Comment by kunjgit** [comment]
Thank you  @pani2004 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by pani2004** [comment]
@kunjgit Pls add appropriate labels!

**Pull request merged**
