### PR TITLE
Connection defender

### LINKED ISSUE #2279: [New game]: Connection Defender
### 🎮 Game Request

The game is to use the arrow keys to move the cursor and shoot the incoming arrows using the mouse on the connection which act as interruptions and prevent the wifi signal from getting disconnected for as long as possible.The cursor needs to be protected from the incoming arrows

### Point down the features

For every successful hit you will get 50 points

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Sreenija03**
## PR Description 📜
Connection defender game

Fixes #2279  

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅] I have performed a self-review of my own code or work.
- [ ✅] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [ ✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅ ] I have added screenshot for website preview in assets/images 
- [ ✅] I have added entries for my game in main README.md
- [ ✅] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [✅ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2023-07-05 at 9 06 23 PM

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Sreenija03 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Sreenija03,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Sreenija03,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Sreenija03,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Sreenija03** [comment]
@kunjgit I have made all the changes, Can you please check

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Sreenija03,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Comment by Arun9739** [comment]
@Sreenija03 I think you have not made an entry of your game into README

**Review by kunjgit — APPROVED** [review]

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Code Copied from: **https://github.com/js13kGames/connection-defender**
Live View: **https://codepen.io/BrianDGLS/pen/bxbveM**

**Game doesn't work with min.js file this file generated by browser in backend**

**Comment by kunjgit** [comment]
Thank you  @Sreenija03 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
