### PR TITLE
[New game]: Maze Game #46

### LINKED ISSUE #46: [New game]: Maze Game
### 🎮 Game Request

Game logic and basic description
The game logic revolves around a simple maze game where the player needs to navigate through a maze from a starting point to reach the end point.
1) Maze Generation:
- A maze is randomly generated using a grid-based system.
- The maze consists of walls and open paths that form a network of interconnected cells.
- The starting point is marked at a specific cell, and the end point is placed in another cell.
2) Player Movement:
- The player is represented as a character or object within the maze.
- The player can move in four directions: up, down, left, and right.
- The player uses input controls, such as arrow keys to navigate through the maze.
- The movement is constrained by the maze's walls, meaning the player cannot move through walls but can traverse through open paths.

### Point down the features

Game points

1. Difficulty levels can be implemented, altering the complexity of the maze generation.
2. Timer functionality can be included to track the time taken to complete the maze.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by rt-001**
# **Game_Name** 
MazeGame
---

<br>

## PR Description 📜

The Maze Game is a web-based game that challenges players to navigate through a maze using arrow keys or touch swipes. It features dynamically generated mazes of varying difficulty levels, visually rendered on a canvas using HTML5's Canvas API. With responsive design, customizable sprites, and clear instructions, players can enjoy a visually appealing and interactive maze-solving experience.
Fixes #46
<br>
## **functionalities 🎮**

 The game starts with first selecting the difficulty level. Then, the user should click on "Start" to start the game. After that, the user must finish the game. As the game ends, there will be a modal popup telling that the game has ended and also indicating how many steps it took.
<br>

## **How to play? 🕹️**

- Before starting the game, players need to select the desired difficulty level.
- To begin the game, the player must click on the "Start" button.
- Once the game starts, the player's objective is to navigate through the maze using arrow keys to reach the exit.
- At the end of the game, a modal popup appears, indicating that the game has ended.
- The modal popup also displays the number of steps the player took to complete the maze.

<br>
<hr>
 
## Mark the task you have completed ✅

- [✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅] I have performed a self-review of my own code or work.
- [✅] I have commented my code, particularly in hard-to-understand areas.
- [✅] My changes generates no new warnings.
- [✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅] I have added screenshot for website preview in assets/images 
- [✅] I have added entries for my game in main README.md
- [✅] I have added README.md in my folder 
- [✅] I have added working video of the game in README.md (optional)
- [✅] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2023-05-22 at 11 27 49 AM

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @rt-001 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @rt-001 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Review by Durgesh4993 — APPROVED** [review]
https://github.com/kunjgit/GameZone/assets/98798977/544594cb-2dfc-449f-827f-a48be2271b1d

No issues in code

**Comment by Durgesh4993** [comment]
@rt-001 Please add one screnshort in assets/images section

**Comment by rt-001** [comment]
@Durgesh4993  Yes doing it

**Review by kunjgit — CHANGES_REQUESTED** [review]
make sure you have README inside your game folder 
and make your game entry in main README file !!

**Review by kunjgit — CHANGES_REQUESTED** [review]
make sure you have README inside your game folder 
and make your game entry in main README file !!

**Review by kunjgit — CHANGES_REQUESTED** [review]
please make changes we have requested !!

**Comment by rt-001** [comment]
@kunjgit Done

**Review by kunjgit — CHANGES_REQUESTED** [review]
mark your entry in main README file !! 👀

**Comment by kunjgit** [comment]
Thank you  @rt-001 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
