### PR TITLE
Added Save_Doraemon Game

### LINKED ISSUE #1829: [New game]: Save Doraemon
### 🎮 Game Request

Game logic and basic description
A maze like structure will be incoming at Doraemon who is initially placed at a corner and using mouse controls the user has to press the buttons present on the screen to save Doraemon from colliding into those maze like structures.

### Point down the features

Game points
- Mouse Controls
- Score Leaderboard
- Lives to play

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by OMKAR-KALEPU**
## PR Description 📜

I've added a new game called Save_Doraemon
Fixes #1829 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Save_Doraemon

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @OMKAR-KALEPU ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @OMKAR-KALEPU,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @OMKAR-KALEPU,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by OMKAR-KALEPU** [comment]
I've already added an image to assets/images folder

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @OMKAR-KALEPU,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by kunjgit** [comment]
you have to add game thumbnail in assets/images !!!!!! 👀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @OMKAR-KALEPU,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @OMKAR-KALEPU , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @OMKAR-KALEPU,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Pull request merged**
