### PR TITLE
Added Light-Mode Theme

### PR DESCRIPTION
**Pull request by 1TusharSharma1**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes # <230>

This PR resolves issue #230. The focus of this modification was to enhance the application by introducing a light mode feature. I made changes to the JavaScript (JS), CSS, and HTML files to implement this functionality. Prior to this update, the application only supported a default dark theme. With the addition of the light mode, users now have the flexibility to switch between the dark and light themes based on their preference.

This enhancement aims to provide a more inclusive and personalized user experience. By offering a choice of themes, the application becomes more adaptable to different user preferences and environments. The light mode option adds versatility and improves readability, especially in well-lit environments or for users who prefer lighter interfaces.

I have thoroughly reviewed my code and ensured that it adheres to the project's contributing guidelines and code of conduct. I have also provided comments in areas that might require additional clarification.

Please note that no new warnings were generated as a result of these changes. Additionally, I followed the prescribed naming conventions outlined in the contributing guidelines.

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot (118)
Screenshot (117)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @1TusharSharma1 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by 1TusharSharma1** [comment]
> @1TusharSharma1 Plz add the screenshot for reference

Done!

**Comment by Arun9739** [comment]
@1TusharSharma1 LGTM

**Comment by kunjgit** [comment]
we are already having dark light mode feature make sure you do changes in that and you make enhancement if you want !!

**Comment by kunjgit** [comment]
Thank you  @1TusharSharma1 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by 1TusharSharma1** [comment]
> we are already having dark light mode feature make sure you do changes in that and you make enhancement if you want !!

But the one which I have made is better, 
Firstly, The toggle switch should never be on the left. 
And Secondly, There should not be any unnecessary text, The icon should be self explanatory.
But if you still think, The one which is merged is good, So I think it should be better if made the toggle on the left (should I raise an issue for it?).
But still give it a thought, Mine was a better option!

**Pull request closed without merging**
