### PR TITLE
Added Simon Says game

### LINKED ISSUE #4732: [New game]: Want to add Simon Says game
### 🎮 Game Request

In Simon Says, players watch as colored buttons light up and play sounds in a sequence. they need to remember and repeat this sequence by pressing the buttons in the same order. the game gets harder as it adds more steps making a mistake ends the game, showing the player's score and allowing them to try again. this game combines elements of memory, pattern recognition, and reflexes, making it both challenging and engaging.

### Point down the features

The Simon game project features color-based sequence memorization gameplay with user friendly interface, sound effects, adjustable difficulty levels, scoring, and feedback mechanisms.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Shravanikale**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #4732

i have added the Simon Says game,in which players watch as colored buttons light up and play sounds in a sequence. they need to remember and repeat this sequence by pressing the buttons in the same order. the game gets harder as it adds more steps making a mistake ends the game, showing the player's score and allowing them to try again. this game combines elements of memory, pattern recognition, and reflexes, making it both challenging and engaging.

<hr>
 
## Mark the task you have completed ✅

- [ x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x ] I have performed a self-review of my own code or work.
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ x ] My changes generates no new warnings.
- [x  ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ x ] I have added screenshot for website preview in assets/images 
- [ x ] I have added entries for my game in main README.md
- [ x  ] I have added README.md in my folder 
- [  ] I have added working video of the game in README.md (optional)
- [ x ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Shravanikale ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Hi there! you need to make following  changes 
Add your game entry in the main Readme.md file of the gamezone refer other entries there for the format 
Add your game image in the asset folder of the gamezone follow contribution guidelines while naming the image

**Comment by Shravanikale** [comment]
hey @ishita-43 !! i have added the game entry in the main Readme.md file and game image in the asset folder of the gamezone.

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Pull request merged**
