### PR TITLE
Slime Attack[GSSOC'23]

### LINKED ISSUE #2509: [New game]: Slime attack [GSSOC'23]
### 🎮 Game Request

Hello Sir,
I want to add a project of a game of Simple slime attack.

### Point down the features

Here it's a simple shooting game. Where the slime in spaceship is wandering in the screen very fast & we have to heat it with our gun.
Please assign me this issue under GSSOC'23.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by apu52**
## PR Description 📜

Hello Sir, 
Here is my project of Slime attack animation. Here I have made it using HTML,CSS .
Here I have made it a simple game. Here we have to attack a slime in a spaceship.
It's simply a shooting game
Fixes  #2509 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @apu52 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @apu52,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @apu52,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by apu52** [comment]
@kunjgit Sir I have made the README & asset changes following. Please take  a review & merge my PR

**Comment by sabhisharma-ise** [comment]
@apu52 Hello, instead of putting a star can you number the game in the main README.md file

**Comment by apu52** [comment]
image

Sir @sabhisharma-ise I have already marked it with sequential game no.

**Comment by sabhisharma-ise** [comment]
@apu52 okay, earlier it was star thatwhy I asked. Now it's okay!
(Don't call me sir, I'm also a contributor)

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @apu52 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
