### PR TITLE
pen pointer fight game wtr to #3889

### PR DESCRIPTION
**Pull request by bhumika-1127**
I have added a new game named "Pen Pointer Fight" wrt issue #3889. @kunjgit kindly review the pull request and incorporate the changes.

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @bhumika-1127 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @bhumika-1127,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @bhumika-1127,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by bhumika-1127** [comment]
@kunjgit I have update the readme.md. Kindly review and let me know.

**Comment by bhumika-1127** [comment]
@kunjgit Kindly review the PR. I have made the necessary changes and resolved the conflict.

**Comment by bhumika-1127** [comment]
@kunjgit Kindly review the PR.

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @bhumika-1127 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
