### PR TITLE
[GSSoC'23] Added Super Mario Run game

### PR DESCRIPTION
**Pull request by Vedansh-777**
## PR Description 📜

Embark on an epic platforming adventure as Tenacity, a courageous explorer on a mission to save the princess and restore peace to the Mushroom Kingdom. Run, jump, and overcome obstacles across multiple vibrant worlds filled with dangerous enemies and hidden secrets. Collect power-ups, defeat Bowser's minions, and face off against challenging bosses to rescue Princess Peach and bring harmony back to the land.

Fixes 
- #1823

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2023-06-22 at 1 39 17 PM

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Vedansh-777 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Vedansh-777,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Vedansh-777,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Vedansh-777,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Vedansh-777** [comment]
@kunjgit is there any other changes required ?

**Comment by Vedansh-777** [comment]
@kunjgit ?

**Comment by Vedansh-777** [comment]
> Hello @Vedansh-777, You need to make the following changes:
> 
> * Please modify the main README.md file.
> * Please add an image to the assets/images directory.
> 
> Hoping that you will make those changes soon 🚀

@kunjgit i have made necessary changes please verify.

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Vedansh-777 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Vedansh-777,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Vedansh-777** [comment]
@kunjgit please add labels in this PR ??

**Comment by Vedansh-777** [comment]
> Hello @Vedansh-777, You need to make the following changes:
> 
> * Please modify the main README.md file.
> * Please add an image to the assets/images directory.
> 
> Hoping that you will make those changes soon 🚀

@kunjgit please add labels in this???...Because it is not counting in leaderboard

**Comment by Vedansh-777** [comment]
@kunjgit @kunjgit @kunjgit @daccdacc please add labels in it ??????

**Pull request merged**
