### PR TITLE
New Game HangMan Created

### LINKED ISSUE #166: [New game]: Valorous Rabbit
### 🎮 Game Request

The Rabbit needs to run from the fox behind, collect carrots and avoid hurdles on the way.
image

### Point down the features

score will increase as the rabbit survives
high score will be updated accordingly.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by chinmayjain08**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below

Fixes #166 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots📸
image

image

image

<br>

## Add the working-video(Optional) 📹
https://github.com/kunjgit/GameZone/assets/92749015/67326ef9-4d42-4cf8-a6c3-3cda1cbd5434

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @chinmayjain08 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by chinmayjain08** [comment]
provided drive link of working video in readme file and also provided the video and screenshots in assets folder in my game folder HangMan

**Comment by kunjgit** [comment]
Hey @chinmayjain08 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by chinmayjain08** [comment]
Made changes to Readme in the PR #191 as per required. Now it's ready to merge 💯.

**Review by kunjgit — CHANGES_REQUESTED** [review]
Make sure you add your image in repo's assets folder 
rename your readme file to README.md
also make your entry on main README file !! 👀

**Comment by chinmayjain08** [comment]
Changes that were requested are done, there are no conflicts as well.

**Comment by chinmayjain08** [comment]
> 

Changes that were requested are done, there are no conflicts as well.

**Review by kunjgit — CHANGES_REQUESTED** [review]
add thumbnail in main repo assets/images !!
all other things are good 👀 !!

**Comment by kunjgit** [comment]
Thank you  @chinmayjain08 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
