### PR TITLE
Environmental Conservation Game is added

### PR DESCRIPTION
**Pull request by pallasivasai**
## PR Description 📜

 #4778 

 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Environmental Conservation Game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @pallasivasai ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @pallasivasai, You have reached your limit to contribute in GameZone with a score of 180. 
 We believe in giving equal opportunity to everyone so you will not be able to contribute to GameZone now onwards. 💗 
 Thank you for your valuable time and contribution in GameZone 🕹️! 

 Your merged pull requests:
- [#4716](https://github.com/kunjgit/GameZone/pull/4716) with labels: level3 score: (45)
- [#3586](https://github.com/kunjgit/GameZone/pull/3586) with labels: level3 score: (45)
- [#3499](https://github.com/kunjgit/GameZone/pull/3499) with labels: level3 score: (45)
- [#3376](https://github.com/kunjgit/GameZone/pull/3376) with labels: level3 score: (45)

**Comment by kunjgit** [comment]
Thank you  @pallasivasai , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by pallasivasai** [comment]
is this limit for overall?

**Pull request closed without merging**
