### PR TITLE
[ADDED]: Space Drifter

### LINKED ISSUE #1989: [New game]: Space Drifter
### 🎮 Game Request

# Game logic and basic description
A pretty darn difficult asteroid shooter game with realistic inertia and unconventional controls.

### Point down the features

# Game points
Hard to play but an interesting one.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Killer2OP**
## PR Description 📜

The Space Drifter game has been added
Fixes #1989 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Space_Drifter

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Killer2OP ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Killer2OP** [comment]
@kunjgit Please can you review my PR and kindly merge it.

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Killer2OP , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @Killer2OP,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by killingkillers** [comment]
@kunjgit , @gurjeetsinghvirdee ,
Remove the labels. 
This game is copied from : https://github.com/bence-toth/space-drifter
Check the link he copied each and every thing.

### Original JS Code by developer : 
Screenshot from 2023-07-03 12-39-44


@Killer2OP Code :

image

**Comment by gurjeetsinghvirdee** [comment]
I have a small request to you please don't tag me on every repo @killingkillers 
I'm already frustrated with other things

**Comment by gurjeetsinghvirdee** [comment]
Either I will leave this program

**Comment by killingkillers** [comment]
> I have a small request to you please don't tag me on every repo @killingkillers I'm already frustrated with other things

Okay, will remember next time.

**Comment by killingkillers** [comment]
> Either I will leave this program

Same, This program is nothing and I'm not going to participate and also not going to suggest anyone now.

**Comment by gurjeetsinghvirdee** [comment]
If someone want to frustrate then join this program 😕

**Pull request merged**
