### PR TITLE
[New Game] Pokemon Card Game

### LINKED ISSUE #2387: [New game]:  Pokemon card Game
### 🎮 Game Request

Game logic and basic description

This is a game which we used to play offline during our childhood. Now, I have come up making this as online game. It ressembles just as offline with same rules. But the give away is we can see our card in BIG Screen. Isn't it fun.

### Point down the features

Game points

Coming to the technical aspect, It can be built using simple HTML, CSS and JavaScript.
After, hitting live server button, we can see one participant cards on the screen. This project can be extended further.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by SnigdhaP2022**
## PR Description 📜
Added New Game Pokemon Card Game

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #2387 

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅ ] I have added screenshot for website preview in assets/images 
- [✅ ] I have added entries for my game in main README.md
- [✅ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [✅ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2023-07-19 at 8 01 36 PM

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @SnigdhaP2022,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by SnigdhaP2022** [comment]
@kunjgit  I have completed requested changes. Kindly, review the PR

**Comment by SnigdhaP2022** [comment]
> Hello @SnigdhaP2022, You need to make the following changes:
> 
> * Please add a README.md file inside the newly created folder.
> * Please modify the main README.md file.
> * Please add an image to the assets/images directory.
> 
> Hoping that you will make those changes soon 🚀

I have completed the changes. Kindly check files changes section.

**Comment by SnigdhaP2022** [comment]
@kunjgit I have completed the requested changes.Kindly,review the PR.

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Resolve conflicts

**Comment by SnigdhaP2022** [comment]
@gurjeetsinghvirdee  Conflicts were resolved. Kindly, review and merge this PR

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @SnigdhaP2022,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @SnigdhaP2022 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
