### PR TITLE
addedcountrygussergameimage

### LINKED ISSUE #2515: [Bug]: no image for country_Guesser_Game
### Give a brief about the bug ✍️

no image is there for country_Guesser_Game
Screenshot (428)

### What is the expected behavior? 🤔

we can add an image of the world.

### Provide step by step information reproduce the bug 📄

by img tag, we can add images and set the path correctly

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by khadar1020**
## PR Description 📜

i have added the countryguesser game image
Fixes #2515 

<hr>
 
## Mark the task you have completed ✅

- [] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot (430)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @khadar1020 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by khadar1020** [comment]
can you please review my pr @kunjgit

**Comment by khadar1020** [comment]
can you please review my pr @gurjeetsinghvirdee

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Bro it's better to add all projects that are missing from website because adding a img is not enough for level1 also

**Comment by khadar1020** [comment]
ok I will add to all projects @gurjeetsinghvirdee

**Comment by kunjgit** [comment]
Thank you  @khadar1020 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
