### PR TITLE
Added T-Rex Run

### LINKED ISSUE #249: [New game]: T-Rex Run
### 🎮 Game Request

The T-Rex Run project is a dinosaur-themed running game that gained popularity for its simplicity and addictive gameplay. Initially developed as an Easter egg for the Google Chrome browser's "No Internet" page, the game features a T-Rex character running endlessly through a desert landscape.

The objective of the game is to guide the T-Rex and help it avoid obstacles, such as cacti and birds, by jumping or ducking at the right time. The gameplay is straightforward and easy to understand, making it accessible to players of all ages and skill levels.

### Point down the features

In the T-Rex Run game, the point system is used to track and reward the player's progress and performance. The primary goal is to accumulate the highest score possible by successfully navigating the T-Rex through the obstacles.

The scoring in T-Rex Run is based on the distance covered. As the T-Rex runs through the desert, the player earns points for every meter or distance unit traveled. The score is constantly increasing as long as the T-Rex continues to move forward.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Arka2708**
## PR Description 📜
Added a New Game T-Rex Run. The T-Rex Run project is a dinosaur-themed running game that gained popularity for its simplicity and addictive gameplay. Initially developed as an Easter egg for the Google Chrome browser's "No Internet" page, the game features a T-Rex character running endlessly through a desert landscape.

The objective of the game is to guide the T-Rex and help it avoid obstacles, such as cacti and birds, by jumping or ducking at the right time. The gameplay is straightforward and easy to understand, making it accessible to players of all ages and skill levels.

Fixes #249 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Arka2708 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @Arka2708 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by Arka2708** [comment]
I didn't change index file, just showed what it can look like, also changed the readme file with '*' as stated.

**Comment by Arun9739** [comment]
@Arka2708 You are not supposed to change the main index file.

**Comment by Arka2708** [comment]
@Arun9739 I didn't change anything in the index.html file you can check it from the section 'files changed, there you can see the files I added and changed, the conflict is about the README.md file, which is because there are some changes added now in the README file which aren't there when I cloned the repo. I'll resolve it soon.

**Comment by Arka2708** [comment]
branch conflict resolved!

**Comment by Arka2708** [comment]
@kunjgit can you check this PR, please...

**Comment by Arun9739** [comment]
@Arka2708 Plz resolve branch conflicts

**Comment by Arka2708** [comment]
@Arun9739 The conflict is about the README.md file, which is because there are some changes added now in the README file which aren't there when I cloned the repo. Whenever you changed README.md there will be a branch conflict every time, so I request you🙏 whenever I'm resolving the conflict add the branch in that day, otherwise I've to resolve this branch conflict every day whenever a new thing is added.

**Comment by Arka2708** [comment]
conflicts resolved, Please merge the branch before adding new games

**Comment by Arka2708** [comment]
conflicts resolved, Please merge the branch before adding new games

**Comment by kunjgit** [comment]
Hey @Arka2708 !!
we already have this game you can do enhancement if you want 👀 !!

**Comment by kunjgit** [comment]
Thank you  @Arka2708 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
