### PR TITLE
New Game: 2048_win 

### LINKED ISSUE #4673: [New game]: Adding 2048_win
### 🎮 Game Request

Game logic and basic description
2048 is a simple game built using HTML, CSS, and JavaScript where the player matches the tiles with the same number and when the two tiles touch, they merge into one. Once the player gets 2048 in any square, they win.

### Point down the features

 Game points
- Tile Movement: Tiles can be moved by clicking arrow keys in the desired direction.
- Tile Generation: A new 2 digit tile will be generated after every move.
- Score Tracking: The score increases by the sum of total tiles merged in one click.
- Game Over Condition: Once the player gets 2048 in any square, they win and the game is over
- Difficulty level: The level increases with increasing tiles making it highly difficult for the person to achieve 2048.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by vidhiisaxena**
## PR Description 📜

2048 Win is a puzzle game where you merge numbers together to create larger numbers. The goal of the game is to reach the number 2048. The person who reaches 2048, wins the game.
Fixes #4673 

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅ ] I have added screenshot for website preview in assets/images 
- [✅ ] I have added entries for my game in main README.md
- [✅ ] I have added README.md in my folder 
- [✅ ] I have added working video of the game in README.md (optional)
- [ ✅] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @vidhiisaxena ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by vidhiisaxena** [comment]
Kindly merge my PR, the project manager asked me to create a pull request again.

**Review by ishita-43 — COMMENTED** [review]
do you intent to add only script.js to this folder ? and no other files

**Comment by vidhiisaxena** [comment]
yes, I've made a minor change in the game I added earlier to make it more interesting.

**Review by ishita-43 — APPROVED** [review]
good to go!!

**Comment by kunjgit** [comment]
Thank you  @vidhiisaxena , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by vidhiisaxena** [comment]
Respected Project Admin,
 My points in the leaderboard have not increased at all, kindly increase 45 points, you can decrease it from the previous account with which I made the initial PR (@VidhiSaxenaa).

**Comment by vidhiisaxena** [comment]
Greetings,
My PR has been merged and added to my count but the scores have not been
updated yet. Kindly add level 3 marks to my id with the username
vidhiisaxena. You can delete my score from the previous github id,
VidhiSaxenaa.
Kindly confirm once the scores have been updated.
Regards
Vidhi Saxena

**Comment by vidhiisaxena** [comment]
Kindly update my marks in the leaderboard.

**Comment by vidhiisaxena** [comment]
Greetings,
My PR has been merged and added to my PR count but the scores have not been
updated yet. Kindly add level 3 marks to my id with the username
vidhiisaxena, as it will affect my ranking. I've been constantly trying to
reach out to your team, it'll be great if you could sort this issue as soon
as possible.
Kindly confirm once the scores have been updated.
issue
Regards
Vidhi Saxena
github:- https://github.com/vidhiisaxena

**Comment by vidhiisaxena** [comment]
I will look into this and get back to you.

**Comment by vidhiisaxena** [comment]
Kindly update me as soon as possible. It's been more than 3 weeks, My
closed PR doesn't yet have a level assigned and no points have been added.
I'm attaching below my thread of conversation with @Antima Mishra
***@***.***> who approved my request. Kindly increase my
marks at the earliest.

**Comment by vidhiisaxena** [comment]
@ishita-43 The leaderboard is about to close now. Please update my marks asap.

**Comment by ishita-43** [comment]
> @ishita-43 The leaderboard is about to close now. Please update my marks asap.

Hi @vidhiisaxena you can raise such issues in gssoc discussion increasing points is not in ny hands gssoc officials may have the power to do so 
Describe Them about your both accounts and what issue you are facing by raising question or you can also create ticket on the discord server 

https://github.com/GSSoC24/Contributor/discussions/categories/q-a

**Comment by vidhiisaxena** [comment]
Kindly update score on this id.
@ishita-43

**Comment by ishita-43** [comment]
This pr  levels assigned to compensate the previous id pr

**Pull request merged**
