### PR TITLE
 Drawing App Game

### LINKED ISSUE #4528: [New game]: Drawing App Game
### 🎮 Game Request

Drawing App created with HTML, CSS, and JavaScript. This application will allow users to create drawings using various shapes and colors, offering a simple yet engaging drawing experience directly in the browser.
- Users select a tool and color, then interact with the canvas by clicking and dragging the mouse to draw.
- When a shape is selected, users click to define the shape's position and dimensions.
- The fill color option will fill shapes with the selected color, while the brush will allow for continuous freehand drawing.

### Point down the features

drawing app

This Drawing App will be a fun and creative addition to our collection of web-based games, offering users a simple yet powerful tool to create and share their artwork. 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by revanth1718**
## PR Description 📜
This is a simple and interactive drawing application built with HTML, CSS, and JavaScript. It allows users to draw shapes, use a brush tool, erase drawings, and save their creations as an image. The application offers a variety of features to make the drawing experience enjoyable and easy to use.
Fixes #4528 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Drawing_app

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @revanth1718 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by revanth1718** [comment]
@ishita-43 please review my pull request

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by kunjgit** [comment]
Thank you  @revanth1718 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
