### PR TITLE
Added Rock Paper Scissors 

### LINKED ISSUE #177: [New game]: Rock Paper Scissors
### 🎮 Game Request

Game logic and basic description
The game idea is simply based on the game of rock paper scissors.
It will have consequent rounds as the user progresses against the computer, they will get points 

### Point down the features

Game points
- Clean UI
- Easy to use and play

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by its-me-abhishek**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #177 
I have made Rock Paper Scissors game un=sing, HTML, CSS and Vanilla JS.

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 
Rock_Paper_Scissors
📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @its-me-abhishek ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@its-me-abhishek Remove the assests and images file from your folder. You need to add images to main assests file only. Also make entry of your game into main README file.

**Comment by its-me-abhishek** [comment]
I have made the required changes only the assets folder is there since it has the font file.

**Comment by its-me-abhishek** [comment]
Please merge the PR

**Comment by Arun9739** [comment]
@its-me-abhishek Mention * in plce of number, not any number in main README. Plz go though the guidelines.

**Comment by its-me-abhishek** [comment]
Done. Sorry for the inconvenience caused.

**Comment by Arun9739** [comment]
@its-me-abhishek Plz resolve the merge conflicts.

**Comment by its-me-abhishek** [comment]
Done

**Comment by Arun9739** [comment]
@its-me-abhishek LGTM

**Comment by kunjgit** [comment]
Thank you  @its-me-abhishek , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
