### PR TITLE
Added Four_In_Row

### LINKED ISSUE #4830: [New game]: Four in row
### 🎮 Game Request

**Four in a Row** is a two-player strategy game where players take turns dropping colored discs into a vertical grid. The objective is to connect four of their own discs in a row—either horizontally, vertically, or diagonally—before the opponent does.

### Point down the features

- **Two-Player Mode:** Designed for two players, either competitively or cooperatively.
- **Vertical Grid:** Features a vertical grid with slots where discs are dropped.
- **Disc Colors:** Players use different colored discs to differentiate between their moves.
- **Winning Condition:** The goal is to connect four discs in a row, either horizontally, vertically, or diagonally.
- **Turn-Based Play:** Players take turns dropping discs into the grid.
- **Game Over Detection:** The game ends when a player achieves four in a row or when the grid is full.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by heli0707**
## PR Description 📜
Four in a Row is a two-player strategy game where players take turns dropping colored discs into a vertical grid. The objective is to connect four of their own discs in a row—either horizontally, vertically, or diagonally—before the opponent does.

Fixes #4830 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

https://github.com/user-attachments/assets/0b312a6a-d45e-4617-b514-488ff371bc53

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @heli0707 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by heli0707** [comment]
@kunjgit  please review and merge it!

**Review by ishita-43 — CHANGES_REQUESTED** [review]
aLso add your game image in the asset folder of the repo follow naming convention mentioned in contribution guidelines while doing so

**Comment by heli0707** [comment]
@ishita-43 
done 
review it

**Review by ishita-43 — APPROVED** [review]
Good to go

**Comment by ishita-43** [comment]
Please resolve merge conflicts

**Comment by heli0707** [comment]
conflict resolved

**Comment by kunjgit** [comment]
Thank you  @heli0707 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
