### PR TITLE
Added new Interactive Quizzing Application

### LINKED ISSUE #270: [New game]: Beautiful UI and Responsive Quizzing Application
### 🎮 Game Request

The Simple Quiz Application is a web-based application built using JavaScript that allows users to take quizzes and test their knowledge on various topics. It provides an interactive and engaging way to assess and improve one's understanding of different subjects.

### Point down the features

1.) User-Friendly Interface: The application offers a clean and intuitive user interface, making it easy for users to navigate through the quiz and select their answers.

2.) Multiple Choice Questions: The quiz consists of multiple-choice questions, where users are presented with a question and a set of answer options. Users can choose the correct answer by clicking on the respective option.

3.) Score Tracking: As users progress through the quiz, the application keeps track of their score in real-time. The score is incremented when the user selects the correct answer and remains unchanged for incorrect answers.

4.) Restart and Retake: Users have the option to restart the quiz or retake it if they wish to improve their score or try different sets of questions.

5.) Responsive Design: The application is designed to be responsive and compatible with different screen sizes, allowing users to access and enjoy the quiz on various devices such as desktops, laptops, tablets, and smartphones.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by ann29-tdk**
## PR Description 📜

- The quizzing application is a JavaScript-based application that allows an admin user to manage questions by adding, updating, and deleting them.  Upon logging in, the admin user will be presented with a dashboard where they can perform various actions related to question management. The admin user can add new questions by providing a question statement and multiple answer options.

- They can also mark the correct answer(s) for each question. The admin user can select a question from the list to update its details. They can modify the question statement, answer options, and correct answer(s). The updated information will be saved in the system.

- The application will require a data storage mechanism to store the questions and their details. This has been achieved using localStorage .

Fixes #270

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

- Admin Screen

Admin Login
Admin Panel
Admin Question Addition

- Participant Screen

User Login
User Quiz
User Score

--- 
<br>

## Working Demo
[Working Demo Click Here](https://drive.google.com/file/d/1os8xHGIFx_KCvcnkWhL4JG4xsX6eE387/view?usp=share_link)

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Hey @ann29-tdk 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Review by kunjgit — CHANGES_REQUESTED** [review]
add screen shot in assets/image and also add game entry in main README file !!

**Comment by ann29-tdk** [comment]
> add screen shot in assets/image and also add game entry in main README file !!

I have added the game screenshot and updated readme file.

**Comment by ann29-tdk** [comment]
> add screen shot in assets/image and also add game entry in main README file !!

I have added the screenshot in images/assets folder and updated main README.md, please review it. Thank you

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @ann29-tdk , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
