### PR TITLE
Update README.md brick breaker

### LINKED ISSUE #2080: [Documentation Bug]: Brick breaker image not loading
### Describe the bug ✍️

Describe your bug here
I ll add the image in the brick breaker game so that it is easy to check in readme.md file.

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by SimranLahrani842**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #2080 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

solved this error:

ss1

now image is visible:

ss2

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @SimranLahrani842 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by SimranLahrani842** [comment]
> Thank you @SimranLahrani842 ,for creating the PR and contributing to our GameZone heartpulse Review team will review the PR and will reach out to you soon! innocent Make sure that you have marked all the tasks that you are done with ✅. Thank you for your patience! grinning

Add labels to my issue and merge the pr

**Comment by SimranLahrani842** [comment]
> Thank you @SimranLahrani842 ,for creating the PR and contributing to our GameZone heartpulse Review team will review the PR and will reach out to you soon! innocent Make sure that you have marked all the tasks that you are done with ✅. Thank you for your patience! grinning

Add labels to my issue and merge this pr.

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @SimranLahrani842 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
