### PR TITLE
Contributors Link fixed and Games Link added

### LINKED ISSUE #4818: [Enhancement]:  Fix Contributors Link and Add Games Link in Navbar
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The Contributors navigation link in the navbar is currently not working. Additionally, I would like to add a Games navigation link to the navbar, allowing users to jump directly to the games section. 

https://github.com/kunjgit/GameZone/assets/125213858/b944f1be-a143-4104-b6a2-f0a0b6415eca

@kunjgit Please assign me this task under GSSoC 2024. 
Thank you!

### Describe the solution you'd like

1. **Fix Contributors Link:** Check the href attribute of the Contributors link in the navbar and correct it to point to the appropriate section or page.
2. **Add Games Link:** Add a new navigation item in the navbar with the href attribute pointing to the Games section or page. Ensure it follows the same style and structure as the existing links.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by shreyasmunge**
## PR Description 📜

The contributors link in the Navbar was not working, and the games link was missing. I reviewed index.html to identify the issue, corrected the contributors link, and added a new link called "Games" in the navbar.
Fixes #4818 

<hr>
 
## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

https://github.com/user-attachments/assets/48e265d7-df12-4c87-8bbe-2c06fe57795b

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @shreyasmunge ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by mohitgedar** [comment]
hey,
This issue of contributors link not working along with others is already addressed in the PR #4802

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by shreyasmunge** [comment]
@kunjgit and @ishita-43 I have resolved the merge conflicts, Please have a look .

**Comment by mohitgedar** [comment]
hey, did you check how navbar responds for adding new element  ,for different screen sizes . you can check that by right click then  going to inspect and pressing ctrl+shift+M , and then draging the screen using || on RHS of screen to see response of the navbar.

According to me one extra element will cause overflow of elements in navbar for small screen size

**Comment by kunjgit** [comment]
Thank you  @shreyasmunge , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by shreyasmunge** [comment]
@ishita-43 Please add  Level  Label to this PR.

**Pull request merged**
