### PR TITLE
 ShroomKnight game added

### LINKED ISSUE #3913: [New game]: " ShroomKnight " game will be added
### 🎮 Game Request

"ShroomKnight" is an engaging web game where players control a fairy hero tasked with defending against invading spiders. The fairy combats the spiders by spawning mushrooms, which serve as automated defense units. These mushrooms shoot bullets at regular intervals, aiming to eliminate the approaching spiders before they reach the bottom of the screen.

- **Move the Fairy**: Use the arrow keys (Left, Right, Up, Down) to navigate the fairy across the canvas. Position the fairy strategically to avoid spiders and place mushrooms effectively.
- **Spawn Mushrooms**: Press the spacebar to spawn mushrooms at the fairy's current location. Each mushroom will automatically fire bullets upwards to destroy any spiders in their path.
- **Avoid Spider**s: The goal is to prevent spiders from reaching the bottom of the screen. If a spider gets past the defenses, it continues, but players should aim to stop as many as possible.

### Point down the features

1. Arrow Keys & ' W, A, S, D ' : Move the fairy in the respective direction.
2. Spacebar: Spawn a mushroom at the fairy's current position. The mushroom will fight against the spider by using their ability

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by shuvadeepmondal**
## PR Description 📜

I have added a my game named ShroomKnight , this is the remake of classic Spiders apocalypse game with a twists of A Fairy Hero. In this game, Fairy Hero, who spawns mushroom , is the main protagonist whose mushrooms fights against the Spiders 
Fixes #3913 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2024-06-02 152003

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @shuvadeepmondal ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by shuvadeepmondal** [comment]
@kunjgit Sir please Review and merge it

**Comment by shuvadeepmondal** [comment]
@kunjgit Sir Please Review it.

**Comment by shuvadeepmondal** [comment]
@kunjgit Sir Please help me .

**Comment by kunjgit** [comment]
Thank you  @shuvadeepmondal , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by shuvadeepmondal** [comment]
@kunjgit Sir can I make another pr?

**Pull request closed without merging**
