### PR TITLE
Adventure Game added 👍

### LINKED ISSUE #1956: [New game]: CSS Only Adventure Game
### 🎮 Game Request

This is a no-JS adventure game created using only CSS. The game is a simple text adventure, where the player can move around a grid of squares and interact with objects.
The game is controlled using the keyboard, and the player can move up, down, left, and right. The player can also interact with objects by clicking on them.

### Point down the features

The game is made up of a grid of squares, and the player can move around the grid using the keyboard.
It contains a few different objects, and the player can interact with objects by clicking on them.
It has a simple text-based interface, but it is still a fun and challenging experience.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by sabhisharma-ise**
## PR Description 📜

Added the Adventure Game!
Fixes #1956

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Adventure_Game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @sabhisharma-ise ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @sabhisharma-ise , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by sabhisharma-ise** [comment]
Hello, @kunjgit Can you remove the under-review tag please?
As this PR is already merged!

**Comment by sabhisharma-ise** [comment]
If you search for the games you're searching for, then you'll definitely find those games already there. But now what you're doing is specifically targeting my PRs only and searching for the games. 

And since, following the readme guidelines, if they mentioned that we cannot use the codebase of games already available on the internet/codepen, then I would definitely not use already available games. 

I request you to please add the GSSOC labels!

**Comment by gurjeetsinghvirdee** [comment]
> If you search for the games you're searching for, then you'll definitely find those games already there. But now what you're doing is specifically targeting my PRs only and searching for the games.
> 
> And since, following the readme guidelines, if they mentioned that we cannot use the codebase of games already available on the internet/codepen, then I would definitely not use already available games.
> 
> @gurjeetsinghvirdee I request you to please add the GSSOC labels!

Why they will mention in the repo when it already mentioned on the server rules that you can't do this thing

image

**Pull request merged**
