### PR TITLE
Improved UI of pagination 

### LINKED ISSUE #1819: [Bug]: Pagination UI
### Give a brief about the bug ✍️

pagination section is too close to the games. 

### What is the expected behavior? 🤔

it should have some gap between games and pagination

### Provide step by step information reproduce the bug 📄

I'll give margin top to pagination.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Naina047**
## PR Description 📜

I have added margin to top of pagination so as to maintain a gap between games and pagination. also i have added margin left and right to pagination section so as to make it more appealing.
Fixes #1819 

<hr>
 
## Mark the task you have completed ✅

- [ x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x ] I have performed a self-review of my own code or work.
- [ x ] My changes generates no new warnings.
- [ x ] I have specified the respective issue number for which I have requested the new game.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Naina047 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
you have to show us preview of it !!

**Comment by Naina047** [comment]
Screenshot 2023-06-24 124025

**Comment by kunjgit** [comment]
It is already done !!! 👀

**Comment by kunjgit** [comment]
Thank you  @Naina047 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
