### PR TITLE
Snakebites game added

### LINKED ISSUE #3549: [New game]: Snake Bites
### 🎮 Game Request

Overview:
Snake Bites is a modern twist on the classic Snake game, offering an engaging and challenging experience for players of all ages. Control the hungry snake as it slithers around the screen, eating food to grow longer while avoiding collisions with the walls and its own tail. With multiple difficulty levels, Snake Bites provides endless fun and tests your reflexes and strategic thinking.

Features:

Difficulty Levels:

Choose from three difficulty levels to match your skill and preference:
Easy (Speed: 5): A slower pace, perfect for beginners and those looking to relax.
Medium (Speed: 10): A moderate pace for experienced players seeking a challenge.
Hard (Speed: >15): A fast-paced, intense experience for experts who crave a real test of their reflexes.

Simple Controls:

Use the arrow keys or swipe gestures (on touch devices) to guide the snake in the desired direction.
Responsive controls ensure a smooth and enjoyable gameplay experience.

### Point down the features

Scoring System:

Earn points by eating food items that appear randomly on the screen.
Your score increases with each item consumed, and the snake grows longer, making the game progressively more challenging.
Track your current score and high score to compete with yourself and others.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by SrijaVuppala295**
## PR Description 📜
Added Snake Bites Game with intresting features ,adding sound effects, and adding level of the game so that snake can move slower or faster!!

Fixes #3549

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2024-05-22 160458

https://github.com/kunjgit/GameZone/assets/140592148/cb67f081-ba8e-4a47-86ea-35f84231e449

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @SrijaVuppala295,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by SrijaVuppala295** [comment]
@kunjgit , added README.md file.

**Comment by SrijaVuppala295** [comment]
@kunjgit Changes done!! Please review it and merge ..

**Review by kunjgit — CHANGES_REQUESTED** [review]
@SrijaVuppala295 make sure you are having latest version of main README check it out you are not synced with up to dated version yet @SrijaVuppala295 !

**Comment by SrijaVuppala295** [comment]
I have updated to the latest README.md file @kunjgit , please review and merge it.

**Review by kunjgit — CHANGES_REQUESTED** [review]
@SrijaVuppala295 you are not having up to dated make sure you are updating that !

**Comment by SrijaVuppala295** [comment]
@kunjgit , I have updated to the latest readme.md file sir , its showing 0 Conflicts also

**Comment by kunjgit** [comment]
@SrijaVuppala295 its not having numbering please have a look at it

**Comment by SrijaVuppala295** [comment]
> @SrijaVuppala295 its not having numbering please have a look at it
 @kunjgit , do you mean here.

Screenshot 2024-06-01 212053
  
### Please provide the file that need to be changed

**Comment by SrijaVuppala295** [comment]
@kunjgit ,please provide the file to be changed

**Review by kunjgit — CHANGES_REQUESTED** [review]
@SrijaVuppala295 you are not having latest README !

**Comment by SrijaVuppala295** [comment]
@ishita-43 , please review this , i have resolved merge conflicts.

**Comment by ishita-43** [comment]
Please follow the contribution guidelines while naming the game and respectively update the name in Readme.md file of the project!!

**Comment by SrijaVuppala295** [comment]
@ishita-43 ,please review it

**Review by ishita-43 — CHANGES_REQUESTED** [review]

**Comment by SrijaVuppala295** [comment]
@ishita-43 , if again the conflicts are not resolved, i will try to create a new PR , or say what should i change in that file

**Comment by kunjgit** [comment]
Thank you  @SrijaVuppala295 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
