### PR TITLE
added off the line game

### LINKED ISSUE #2282: [New game]: Adding a OFF THE LINE game
### 🎮 Game Request

Game logic and basic description
Gaol of the game:
Kill the enemy 

Instructions:
arrow keys are used to move the player
and z x are used to fight and kill the enemy on the rope on which they are standing

### Point down the features

Game points:
this is one time play game. 
points will degrade the ux of the game
but we can have multiplayer game in order to have an engagements 

screenshort
image

### Select program in which you are contributing
GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by rohanmittal1163**
## PR Description 📜

"Off the Line" is an exciting offline fighting game that combines speed, precision, and skill. It offers a thrilling experience where players take control of powerful characters and compete in a variety of levels. The goal is to kill your enemy as quickly as possible.

Fixes #2282 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
https://user-images.githubusercontent.com/97821844/251178223-017adc4c-64d3-4ed9-8252-fb9a8c1b37dd.png

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @rohanmittal1163 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @rohanmittal1163,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @rohanmittal1163,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Game Copied from: **https://github.com/jesusolmossanchez/off_the_line**
Live Link: **https://jesusolmossanchez.github.io/off_the_line/**

**Comment by kunjgit** [comment]
Thank you  @rohanmittal1163 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
