### PR TITLE
feat: Add timer change and modern type result popup

### LINKED ISSUE #3457: [Enhancement]: Time control for master Typing and little UI Changes
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement - Master Typing
The existing game master typing allows user to type for 1:00 min fixed time.. but if they want timer of their choice, that is not possible at the frontend...... so I want to include that feature, so game could become more engaging.

### Describe the solution you'd like

Solution steps:
1. use javascript and Html for time selection.
2. use better css for typing result popup

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by anisharma07**
## PR Description 📜

Now user can change the duration for which they want to type..
UI of typing result was also changed and a modern UI was added.
Fixes #3457

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 

<hr>

## Add your screenshots(Optional) 📸
image
image

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @anisharma07 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — APPROVED** [review]
LGTM!

**Comment by kunjgit** [comment]
@anisharma07 resolve the merge conflicts !

**Comment by anisharma07** [comment]
conflicts resolved ... now you can merge the pull request

**Comment by kunjgit** [comment]
@anisharma07 it's not yet resolved ! 
there might be possible someone has even made changes after you have resolved make sure you are resolving after latest changes !

**Comment by kunjgit** [comment]
Thank you  @anisharma07 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
