### PR TITLE
Painting Game Added

### PR DESCRIPTION
**Pull request by Kalivarapubindusree**
## PR Description 📜

#1042 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Drawing App JavaScript _ CodingNepal - Google Chrome 10-06-2023 13_23_28

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Kalivarapubindusree ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Kalivarapubindusree,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Kalivarapubindusree** [comment]
For this game their is no Images for this game please at once @kunjgit

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Kalivarapubindusree,
You need to make the following changes:
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by daccdacc** [comment]
Hello @Kalivarapubindusree, You will have to add one image in the assets/images directory which will be used as the thumbnail for your game on out GameZone website.

**Comment by daccdacc** [comment]
> Hello @Kalivarapubindusree, You will have to add one image in the assets/images directory which will be used as the thumbnail for your game on out GameZone website.

Also, the image that you have added in PR, if you will add the same image, then also it would work.

**Comment by Kalivarapubindusree** [comment]
Do I need to Do separate a another PR for only for the image r else I need to Do it along with the code files? @daccdacc

**Comment by daccdacc** [comment]
Hello @Kalivarapubindusree, just commit the image in the respective directory on your branch and you are done!🚀 
No need of new PR!

**Comment by daccdacc** [comment]
Hello @Kalivarapubindusree, Make sure all the modified files are within a single PR only.
Also add only 1 picture in assets/images directory for painting game.

Alternate Option : Close all the open PRs, create a new fresh PR having your game, entry in main README.md file and single picture in assets/images directory.

**Pull request closed without merging**
