### PR TITLE
Added 15 games in 1, issue no: #611

### LINKED ISSUE #611: [New game]: 15 games in one
### 🎮 Game Request

Game logic and basic description: Would help check the user their reflexes. Will be using HTML,JS,CSS

### Point down the features

Game points: Here user would perform the screen based guidelines, to play the game, will help them know their reflex speed. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Vraj1103**
## PR Description 📜
Added a name called 15 games in 1 with issue no mentioned below :
Fixes #611 [https://github.com/kunjgit/GameZone/issues/611](url) 

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅] I have performed a self-review of my own code or work.
- [ ✅ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✅ ] My changes generates no new warnings.
- [ ✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅ ] I have added screenshot for website preview in assets/images 
- [ ✅ ] I have added entries for my game in main README.md
- [  ✅] I have added README.md in my folder 
- [  ✅] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image
image
image
image
image
image
image
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Vraj1103 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Vraj1103** [comment]
@kunjgit kindly check and merge pr

**Review by kunjgit — CHANGES_REQUESTED** [review]
don't alter main index file also mark your entry in main README and you have to change the image that you are using and change it to your games !!

**Comment by Vraj1103** [comment]
@kunjgit mark your entry in main README means?

**Comment by kunjgit** [comment]
if you are not getting checkout the demo video we have on Discord and make PR again !!

**Comment by kunjgit** [comment]
Thank you  @Vraj1103 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
