### PR TITLE
[Gssoc`23] Cast and Catch Game

### LINKED ISSUE #694: [New game]: cast and catch
### 🎮 Game Request

Game logic and basic description

The game can be created using HTML CSS and JavaScript.

Description:
The Fishing Game is a simple and addictive game where the player tries to catch fish using a fishing hook. The player's goal is to catch as many fish as possible within a given time limit or until a certain score is reached. It tests the player's timing and reflexes as they try to hook the fish swimming in the pond.

Game Logic:

1. The game starts with a pond background image and a fishing hook positioned at the bottom center of the pond.
2. Fish of different sizes and types swim randomly in the pond.
3. The player can control the fishing hook using mouse clicks.
4. If the hook overlaps with the fish, the player scores points, and the caught fish is removed from the pond.
5. If the hook misses the fish, no points are scored.
6. The game continues for a certain duration.
7. The player's score is displayed on the screen during the game.
8. After the game ends, the player can restart the game to play again.

### Point down the features

Game points
If the hook overlaps with the fish, the player scores points and the caught fish is removed from the pond.
If the hook misses the fish, no points are scored.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Sheetal-05**
## PR Description 📜

Added Cast and Catch Game
Fixes #694 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
cast_and_catch
<br><br>
cast-and-catch

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Sheetal-05 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Please add image in assets/images

**Comment by kunjgit** [comment]
Thank you  @Sheetal-05 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Sheetal-05** [comment]
@kunjgit   I have added the image in the asset/ images.

**Pull request closed without merging**
