### PR TITLE
Added: Gravity Drops Game

### LINKED ISSUE #5097: [New game]: Gravity Drops
### 🎮 Game Request

Game logic and basic description
Gravity Drops is a fun and interactive game where players click on the canvas to add paint drops. The goal is to create unique patterns by manipulating gravity and the movement of the paint drops.

### Point down the features

Game points
- Click on the canvas to add paint drops.
- Change the color of the paint drops using the color picker.
- Increase or decrease gravity to control the movement of the drops.
- Clear the canvas without resetting the timer.
- Reset the canvas and timer to start fresh.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by kosuri-indu**
## PR Description 📜

Fixes #5097 
Gravity Drops is a fun and interactive game where players click on the canvas to add paint drops. The goal is to create unique patterns by manipulating gravity and the movement of the paint drops.

## **Functionalities 🎮**
- Click on the canvas to add paint drops.
- Change the color of the paint drops using the color picker.
- Increase or decrease gravity to control the movement of the drops.
- Clear the canvas without resetting the timer.
- Reset the canvas and timer to start fresh.

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in GameZone's README.md
- [x] I have added README.md in my Game 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

https://github.com/user-attachments/assets/b30c71dc-adc4-4228-b401-7df864bc2e76

Screenshot 2024-08-05 135112

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @kosuri-indu ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kosuri-indu** [comment]
@ishita-43 @kunjgit 
Please review this PR :)

**Review by ishita-43 — APPROVED** [review]
Approved

**Comment by kunjgit** [comment]
Thank you  @kosuri-indu , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
