### PR TITLE
imagetrivia flash game

### LINKED ISSUE #815: [New game]: Imagetrivia Flash game
### 🎮 Game Request

Game logic and basic description
It is web trivia game which consists of quizzes related to computer science and other fields made using HTML,CSS and Javascript.

### Point down the features

Game points

* Question Series
*  Options
*  Timer
*  Scorelist

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Shreya111111**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #815 

<hr>
 
## Mark the task you have completed ✅

- ✅ I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- ✅ I have performed a self-review of my own code or work.
- ✅ I have commented my code, particularly in hard-to-understand areas.
- ✅ My changes generates no new warnings.
- ✅I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- ✅ I have added screenshot for website preview in assets/images 
- ✅ I have added entries for my game in main README.md
- ✅ I have added README.md in my folder 
- ✅ I have added working video of the game in README.md (optional)
- ✅I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot 2023-06-04 194203
Screenshot 2023-06-04 194230

Screenshot 2023-06-04 194253
Screenshot 2023-06-04 194345

Screenshot 2023-06-04 194437

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Shreya111111 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@Shreya111111 Plz make entry of your game into main README file.

**Comment by Shreya111111** [comment]
@Arun9739  main readme as in the readme file of gamezone in that table right

**Comment by Shreya111111** [comment]
@Arun9739  and @kunjgit  here right....I have to make changes
Screenshot 2023-06-06 212539

**Comment by kunjgit** [comment]
Follow proper guidelines and create PR again !!

**Comment by kunjgit** [comment]
Thank you  @Shreya111111 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by shubhisingh184** [comment]
@kunjgit I want to contribute this project and I'll complete it within 3 days please assign it to me.

**Pull request closed without merging**
