### PR TITLE
Steam Punk Game Added

### LINKED ISSUE #3994: [New game]: Steam Punk
### 🎮 Game Request

Game logic and basic description
Steampunk is a game where the user fights off the aliens. 

### Point down the features

Game points
Points calculation 
Entrailing UI
Good Graphics

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Archiesachin**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #3994 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot (1056)

Screenshot (1058)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Archiesachin ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Archiesachin** [comment]
@kunjgit  @ishita-43  I have created the new PR with the same issue. This branch has no conflicts. So please merge it and add the gssoc and level labels. Thank You!

**Comment by ishita-43** [comment]
Your PR soon be merged by Admin. Till than you can explore other projects and work on issues.
Happy Contribution!!

**Comment by shruti110503** [comment]
@Archiesachin hey I just saw that your game is ready to merge in this repo. I have a pending PR for a game as well in this repo only. I need your help if you could please tell me how should I add my game in the main readme file.

**Comment by kunjgit** [comment]
Thank you  @Archiesachin , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
