### PR TITLE
Update style.css for home navigation

### PR DESCRIPTION
**Pull request by dharshini2022**
## PR Description 📜

Styles.css file for home page navigation in Master Typing game. Issue @3717. I have also made few enhancement in styles of the page

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Hey @dharshini2022, you can't open another pull request before completing the previous one 😀
You already have the following 1 open pull request(s):
#3838

**Comment by kunjgit** [comment]
Thank you @dharshini2022 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Thank you  @dharshini2022 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @dharshini2022,
Please make sure to link the relevant issue using the appropriate syntax, such as "#issueNumber" 👀. 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by dharshini2022** [comment]
> Hey @dharshini2022, you can't open another pull request before completing the previous one 😀 You already have the following 1 open pull request(s): #3838

Sorry, I didn't add the CSS file in the previous pull request. I request to check both the pull requests. Sorry for the inconvenience!

**Pull request closed without merging**
