### PR TITLE
Issue #423 3D-Box Game

### LINKED ISSUE #423: [New game]: 3D-Box
### 🎮 Game Request

There will be 2 types of 3d boxes of color red and green. Red is for danger and green will be our moving block. So we have to avoid all the red boxes and keep the green box on the platform and go as far as we can... It's an amazing game and will really be fun to make. It's gonna use HTML, CSS, JavaScript and Three.js Library.

Please assign this issue to me under the tag GSSoC'23 and I will try my best to close this issue and create a PR...

### Point down the features

The player can save his box by clicking left, right and can also use up and down arrow to move our box forward and backward respectively. The user can also use mouse to see the platform from the different angles so that he can get a 3D experience.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by AnmolChauhan123**
## PR Description 📜

There will be 2 types of 3d boxes of color red and green. Red is for danger and green will be our moving block. So we have to avoid all the red boxes and keep the green box on the platform and go as far as we can... It's an amazing game and will really be fun to make. It's gonna use HTML, CSS, JavaScript and Three.js Library.
Fixes #423

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @AnmolChauhan123 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@AnmolChauhan123 Make an entry of your game into main README file. Also make sure to change the name of present readme to 'README' as per guidelines.

**Comment by kunjgit** [comment]
follow proper guidelines and make PR again !!

**Comment by kunjgit** [comment]
Thank you  @AnmolChauhan123 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
