### PR TITLE
fixed the bugs of Main website

### LINKED ISSUE #4760: [Bug]: Main website not working properly
### Give a brief about the bug ✍️

Description: these bugs are based on latest clone of the project
- The scroller of the website don't work , it hangs anywhere , anytime .
- The Socials have duplicate entry.
- The page buttons of the contributors sections are not working properly.
- Images are placed at wrong places
- Main page is horizontally aligned , it should be vertically aligned
- Games don't load on the main website

### What is the expected behavior? 🤔

Description:
- The scroller should work smoothly. 
- Duplicate socials should be removed
- page buttons of the contributors section should work , so that one can see all contributors
- Images should be moved to right folder
- Main page should be vertically aligned

### Provide step by step information reproduce the bug 📄

Description:
You can see all these bugs by opening index.html in your browser from the latest clone of the repo .
 
- the bug for scroller needs to be addressed by analyzing the codebase
- duplicate socials can be removed from main html file directly
- bug regarding page button not working also needs to be searched for.
- Images that are placed in wrong folders can be moved to the right destination
- HTML structure and CSS need to be checked to make to page vertical
- games not loading , for this we need to check JS files .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by mohitgedar**
## PR Description 📜
I have removed the bugs of the main website , such as 
- scroller not working 
- games not shown
- contributors page buttons not working 
- duplicate socials 
- website being horizontal aligned.
- Made some structure change and added preview images for games that were not provided
- moved images from wrong folder to their suggested folder
- removed the CSS for the elements that were removed for bug fixing

Fixes #4760

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added video link for preview
- [X] I have specified the respective issue number.
- [x] I have described the updation very well in each commit as well as in my PR and Issue that I Created

<hr>

## Add your screenshots(Optional) 📸
Adding link to preview video as size was large and git don't allow more than 10mb

https://youtu.be/3efY6Wn_y40

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @mohitgedar ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by ishita-43** [comment]
Hi, resolve the conflicts of gamesData.json making sure no data is lost and your changes also preserved in there

**Comment by mohitgedar** [comment]
hey , I did not remove any of the games that were there before

I updated gameData.json to remove duplicate entries , and arrange them in order as some games had numbers upto 500 ,so I moved them to different keys so that when we add games in future we can just add them in the last of file.

I have not added the games that are not present in the list yet . I will add them in another PR , the main purpose of this PR is to modify least and make the website working again.

If you check the last lines of the files before change you will find duplicate entries ,some with same key , eg: 2133 onwards and 2004 onwards 
some games even have upto  3 duplicate entries.

**Comment by mohitgedar** [comment]
- Math Quiz -350
- Puzzle Game -333
- Shroom Knight -322
- Fidget Spinner -316

these are the positions where the games have been moves which you are creating a conflict

At present the gameData.json file is syntax wise incorrect and generate errors so trying to resolve conflicts with this file is not possible , we have to update the file alltogether , and as of your concern that if old games were removed , I can assure you that they were not . only duplicates were removed and correct images urls were provided, those games that didn't had images , images were added for them

**Comment by mohitgedar** [comment]
Hey I had to force-push because there was some trouble with the commit [124fb75](https://github.com/kunjgit/GameZone/pull/4761/commits/124fb755d94409246c8978eb55c7dbb803e8bfb5) , it had different changes for local repo and this PR

**Comment by mohitgedar** [comment]
conflict resolved by [194ee65](https://github.com/kunjgit/GameZone/pull/4761/commits/194ee65688ee51c0a4cfc12e78b7b30441fbc0ca)

**Comment by ishita-43** [comment]
> Hey I had to force-push because there was some trouble with the commit [124fb75](https://github.com/kunjgit/GameZone/pull/4761/commits/124fb755d94409246c8978eb55c7dbb803e8bfb5) , it had different changes for local repo and this PR

okay i am approving the pr , continue with your next issue

**Review by ishita-43 — APPROVED** [review]
APPROVED!!

**Comment by kunjgit** [comment]
Thank you  @mohitgedar , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
