### PR TITLE
Tic-Tac-Toe Game Added

### LINKED ISSUE #3873: [New game]: Tic-Tac-Toe
### 🎮 Game Request

1) Game Interface:

1. Design a 3x3 grid for the game board.
2. Provide clear visual indicators for player turns (e.g., 'X' and 'O').
3. Include a reset button to start a new game.

2) Game Mechanics:

1. Implement logic for two players to take turns.
2. Detect and handle invalid moves (e.g., selecting an already occupied cell).
3. Determine the game's outcome (win, lose) and display appropriate messages.

3) Player Interaction:

1. Enable players to click on the cells to make their moves.
2. Ensure the game updates in real-time with each move.

4) Code Quality:

1. Write clean, readable, and maintainable code.
2. Include comments and documentation where necessary.

### Point down the features

1. Design a 3x3 grid for the game board.
2. Provide clear visual indicators for player turns (e.g., 'X' and 'O').
3. Include a reset button to start a new game.
4. Detect and handle invalid moves (e.g., selecting an already occupied cell).
5. Determine the game's outcome (win, lose) and display appropriate messages.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by jency1**
## PR Description 📜

Fixes #3873 

Tic-Tac-Toe Game Added

## Features

- Interactive Game Board: Play on a 3x3 grid.
- Two-Player Mode: Play with a friend.
- Reset Game: Easily reset to a new game.
- New Game: Easily start a new game.
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

## Add your screenshots(Optional) 📸

Tic-Tac-Toe Game

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @jency1 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @jency1,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by kunjgit** [comment]
@jency1 resolve  merge conflicts !

**Comment by jency1** [comment]
> @jency1 resolve merge conflicts !

@kunjgit Please review and merge this PR.

I have solved the merge conflict issue.

**Comment by jency1** [comment]
@kunjgit Please review and merge this PR.

I have resolved the merge conflict issue.

**Comment by jency1** [comment]
@kunjgit Please review and merge this PR.

I have resolved the merge conflict issue.

**Comment by jency1** [comment]
@kunjgit Please review and merge this PR.

I have resolved the merge conflict issues.

**Comment by jency1** [comment]
@kunjgit Please review and merge this PR.

I have resolved the merge conflict issues.

**Comment by jency1** [comment]
@kunjgit   Thanks for merging the PR. 

Please assign this PR and issue to me, as this PR won't be counted if it is not assigned.

**Pull request merged**
