### PR TITLE
chore: update workflow to add label and pre-commit message & remove node_modules directory

### LINKED ISSUE #2597: [Documentation Bug]: update dependabot workflow and remove node_modules from codebase
### Describe the bug ✍️

- remove `node_modules` directory from `.github`
- update dependabot workflow: it should have a proper commit prefix according to conventions, such as `chore(deps)`. Additionally, it lacks a label, which could be helpful for someone looking at the PR, like `📦 dependencies`.

> Current One:

```yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
```

### Provide step by step information reproduce the bug 📄

image

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## PR Description 📜

- add appropriate label

```yml
labels:
      - 📦 dependencies
```

- add commit message

```yml
commit-message:
  prefix: 'chore(deps)'
```

## Fixes Issue

Closes #2597 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have specified the respective issue number for which I have requested the new game.

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Anmol-Baranwal ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM 🍁

**Comment by Anmol-Baranwal** [comment]
> Thank you @Anmol-Baranwal , for your valuable time and contribution in our GameZone 💗. It’s our GameZone, so Let’s build this GameZone altogether !!🤝 Hoping to see you soon with another PR again 😇 Wishing you all the best for your journey into Open Source🚀

Do you need a workflow that can analyse title of PRs and add labels accordingly based on keywords, like if there is `fix` in the title of the PR, then the workflow will add labels specified.
If you want this, let me know. I will make a proper issue. (This will need two files in which one will trigger other for analyzing)

**Comment by gurjeetsinghvirdee** [comment]
> > Thank you @Anmol-Baranwal , for your valuable time and contribution in our GameZone 💗. It’s our GameZone, so Let’s build this GameZone altogether !!🤝 Hoping to see you soon with another PR again 😇 Wishing you all the best for your journey into Open Source🚀
> 
> Do you need a workflow that can analyse title of PRs and add labels accordingly based on keywords, like if there is `fix` in the title of the PR, then the workflow will add labels specified. If you want this, let me know. I will make a proper issue. (This will need two files in which one will trigger other for analyzing)


Yeah go ahead bro either every issue assigns level3 & you can self assign issue by writing this `/assign`

**Comment by kunjgit** [comment]
Hey @gurjeetsinghvirdee ! , This issue is already assigned to @Anmol-Baranwal. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Pull request merged**
