### PR TITLE
Added Stacker Game

### LINKED ISSUE #1850: [New game]: Stacker.
### 🎮 Game Request

Stacker game uses just html and css, at every level a group of boxes moves on a 10x10 grid. whenever we want we can just click the button inside the box to stop and later the group of boxes is moved to the next level according to the number of boxes selected. This game's goal is to challenge the player to reach the top of the box.

### Point down the features

Have to catch the speed of the boxes which are moving and have to freeze them at our desired place. This game's goal is to challenge the speed of player's vision and skills to make to the top of the stack.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Bhuvanchand26**
## PR Description 📜

Added Stacker Game, Stacker game is made with just HTML and CSS.
Fixes #1850
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed the proper naming convention shown in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added a screenshot for website preview in assets/images 
- [x] I have added entries for my game in the main README.md
- [x] I have added README.md to my folder 
- [ ] I have added a working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Stacker_img

--- 
<br>

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Bhuvanchand26 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Bhuvanchand26,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Bhuvanchand26,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by kunjgit** [comment]
we already have this game with name Arcade game 👀 !!!

**Comment by kunjgit** [comment]
Thank you  @Bhuvanchand26 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Bhuvanchand26** [comment]
hey @kunjgit , I didn't find that game in this repo and there is no game named Arcade game and please re-check 
Thank you!

**Pull request closed without merging**
