### PR TITLE
Added The Cube game

### LINKED ISSUE #2598: [New game]: The Cube
### 🎮 Game Request

The Cube is a mind-bending puzzle game where players navigate through a series of interconnected, cubic rooms, each presenting unique challenges. To progress, participants must solve intricate puzzles, manipulate the environment, and uncover hidden clues. With its perplexing and immersive gameplay, The Cube tests players' logic, lateral thinking, and problem-solving abilities in an intense and unpredictable setting.

### Point down the features

"The Cube" is an intense time-based game where players face a series of challenges inside a mysterious cube. Each challenge must be completed within a strict time limit, adding a thrilling sense of urgency to the gameplay. The game tests players' wit, agility, and decision-making skills as they race against the clock to survive and progress through the enigmatic Cube's levels.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Deepanshu0703**
## PR Description 📜
The Cube is a mind-bending puzzle game where players navigate through a series of interconnected, cubic rooms, each presenting unique challenges. To progress, participants must solve intricate puzzles, manipulate the environment, and uncover hidden clues. With its perplexing and immersive gameplay, The Cube tests players' logic, lateral thinking, and problem-solving abilities in an intense and unpredictable setting.

Fixes #2598 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Deepanshu0703 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Deepanshu0703,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Deepanshu0703,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Deepanshu0703,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Deepanshu0703** [comment]
Hey @kunjgit I have already made these changes but still these problems occur

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Deepanshu0703,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Code copied from here: **https://github.com/bsehovac/the-cube**
Live View: **https://bsehovac.github.io/the-cube/**

**Comment by kunjgit** [comment]
Thank you  @Deepanshu0703 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
