### PR TITLE
[GSSoC'23] Picture Puzzle Game ✔️

### LINKED ISSUE #2813: [New game]: Picture Puzzle Game
### 🎮 Game Request

Game logic and basic description

- Showing a picture to you.
- Along side also showing a grid of puzzle through the parts of the picture.
- Solve that picture and join images by matching the complete image.

### Point down the features

Game points

- Timer will be available for you.
- How much time will you take to solve the challenge.
- This is just a time race and enjoy the game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## PR Description 📜
Title - Picture Puzzle Game
Fixes #2813 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

https://github.com/kunjgit/GameZone/assets/114330097/2de584af-b603-42bb-af9d-0b8212884164

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@gurjeetsinghvirdee @kunjgit sir, please review this pull request

**Comment by gurjeetsinghvirdee** [comment]
Bro you didn't get any padmashree if you get a rank in top 3 so don't make a copy paste PRs @Avdhesh-Varshney 
This thing project adding is not a part of open source contribution you are just wastin your time

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Copied: **https://code-projects.org/picture-puzzle-in-javascript-with-source-code/**

**Comment by kunjgit** [comment]
Thank you  @Avdhesh-Varshney , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
