### PR TITLE
Added ANGRY BIRD game...

### LINKED ISSUE #4744: [New game]: Angry Bird
### 🎮 Game Request

Modify Coins:

Allows users to change their current coin count to a specified amount.
Input the current number of coins, and the script sets the coin count to a high value (e.g., 999,999).
Unlock All Levels:

Unlocks all levels in the game, allowing access to play any level without needing to progress sequentially.
Ensures that all stages are available for immediate play.
Unlock All Birds:

Unlocks all bird characters, providing access to every bird in the game.
This feature lets users utilize any bird with unique abilities from the start.
User-Friendly Interface:

Simple HTML interface with buttons for each action.
Easy to use with prompts and alerts guiding the user through each modification process.

### Point down the features

Game points- Level 3

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by arunimaChintu**
## PR Description 📜
(I HAVE UPDATED BOTH THE READ.me files, it also includes all the assets and all the html,css,javascript and manifest files)
Modify Coins:

Allows users to change their current coin count to a specified amount.
Input the current number of coins, and the script sets the coin count to a high value (e.g., 999,999).
Unlock All Levels:

Unlocks all levels in the game, allowing access to play any level without needing to progress sequentially.
Ensures that all stages are available for immediate play.
Unlock All Birds:

Unlocks all bird characters, providing access to every bird in the game.
This feature lets users utilize any bird with unique abilities from the start.
User-Friendly Interface:

Simple HTML interface with buttons for each action.
Easy to use with prompts and alerts guiding the user through each modification process.

Fixes #4744 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @arunimaChintu ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by arunimaChintu** [comment]
@ishita-43 I have done all the necessary updates, ... closed the previous pr and recreated a new pr with all the files mentioned with updating both the read.me files and includes all the assets.

**Comment by arunimaChintu** [comment]
@ishita-43 Please review it now... nd @kunjgit Please merge it now

**Comment by arunimaChintu** [comment]
@ishita-43 Please merge this...

**Review by ishita-43 — APPROVED** [review]
good to merge!

**Comment by arunimaChintu** [comment]
@kunjgit Please merge this

**Comment by ishita-43** [comment]
> @kunjgit Please merge this

Resolve merge conflicts after that admin will merge the pr

**Comment by arunimaChintu** [comment]
@kunjgit Please merge this now... conflict resolved

**Comment by kunjgit** [comment]
Thank you  @arunimaChintu , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
