### PR TITLE
[New Game] : Added Bubble_Blast_Game

### LINKED ISSUE #78: [New game]: Bubble Blast: A Fun Bubble Shooter Game
### 🎮 Game Request

Bubble Blast is an exciting and addictive bubble shooter game built with JavaScript, HTML, and CSS. Shoot and match colorful bubbles to clear the board and earn points. Challenge yourself with increasingly difficult levels and strive for high scores.

### Point down the features

   - Engaging Gameplay: Enjoy hours of fun as you aim, shoot, and strategically match bubbles to create explosive combinations.
   - Power-Ups and Boosters: Utilize special power-ups and boosters to enhance your gameplay and overcome challenging situations.
   - Responsive and Intuitive Controls: Seamlessly control the shooter with easy-to-use mouse or touch inputs for precise aiming and shooting.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by md-rosh02**
## PR Description 📜

This pull request introduces the implementation of the Bubble Blast game, a fun and engaging interactive game for players of all ages. The purpose of this PR is to add this exciting game to our repository and make it available for users to enjoy.
Fixes #78

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅ ] I have added screenshot for website preview in assets/images 
- [✅ ] I have added entries for my game in main README.md
- [✅ ] I have added README.md in my folder 
- [ ✅] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @md-rosh02 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by md-rosh02 — COMMENTED** [review]
resolved conflicts

**Review by md-rosh02 — COMMENTED** [review]
conflicts

**Review by kunjgit — CHANGES_REQUESTED** [review]
don't alter anything in main README except your game entry

**Comment by md-rosh02** [comment]
@kunjgit plz check conflicts are resolved

**Comment by md-rosh02** [comment]
@kunjgit  plz check conflicts are resolved

**Comment by md-rosh02** [comment]
@kunjgit plz check conflicts are resolved🙏

**Comment by md-rosh02** [comment]
can you tell me what conflicts to resolve?

**Comment by md-rosh02** [comment]
@kunjgit bhai kya huva kab merge hoga ye reply to dediya karo yaar🙁🙁

**Comment by kunjgit** [comment]
Thank you  @md-rosh02 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by md-rosh02** [comment]
Thank you ❤

**Pull request merged**
