### PR TITLE
Balloon buster

### LINKED ISSUE #3607: [New game]: Balloon Buster
### 🎮 Game Request

Balloon Buster is a simple aiming and timing game where the player's objective is to pop as many balloons as possible within a given time limit. Balloons will appear randomly on the screen, and the player must click on them to pop them. Each popped balloon earns the player points, and the game keeps track of the player's highest score.

### Point down the features

1. **Popping Balloons**: The primary way to earn points in the game is by popping balloons. When a player clicks on a balloon, it pops, and the player earns one point. This encourages players to aim accurately and quickly click on balloons as they appear on the screen.

2. **Score Display**: The player's current score is displayed prominently on the screen. As the player pops balloons, the score increases accordingly. This provides immediate feedback to the player about their progress and performance in the game.

3. **High Score**: The game also tracks the player's highest score achieved in a single game session. This adds an element of challenge and motivation for players to try to surpass their previous best performance. The high score is updated whenever the player achieves a new high score during gameplay.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by manishh12**
## PR Description 📜

In this fun and addictive game, your objective is simple: pop as many balloons as you can before time runs out! Balloons will appear randomly on the screen, floating gently in the air. Your task is to aim carefully and click on each balloon to pop it. Each successful pop earns you points, so be quick and accurate!Keep an eye on the timer ticking down ⏰. You only have a limited amount of time to score as many points as possible. 
Fixes #3607 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @manishh12 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by manishh12** [comment]
@kunjgit Done. Kindly review it.

**Comment by manishh12** [comment]
@kunjgit  Waiting for your review.

**Comment by kunjgit** [comment]
Thank you  @manishh12 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @manishh12,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Pull request merged**
