### PR TITLE
Added turn on the light game

### LINKED ISSUE #4160: [New game]: Adding "Turn on the Light" Game
### 🎮 Game Request

"Turn on the Light" is a puzzle game where players are presented with a grid of lights, some of which are on and others off. The goal is to turn on all the lights by toggling them on or off. However, toggling one light affects the adjacent lights, either turning them on if they were off or turning them off if they were on. The challenge lies in figuring out the correct sequence of moves to achieve the goal.

### Point down the features

Grid Layout: The game will feature a grid layout, typically ranging from 4x4 to 8x8, with lights arranged in a pattern.
Toggle Mechanics: Players can interact with the lights by tapping or clicking on them to toggle their state.
Adjacent Interaction: Toggling a light affects the state of adjacent lights, creating a chain reaction that players must strategize around.
Multiple Levels: The game will offer multiple levels of increasing difficulty, with different grid sizes and configurations to challenge players.
Hints System: For players who get stuck, a hint system can provide clues or guidance on the next move without giving away the solution entirely.
Undo Functionality: Players can undo their moves to backtrack and try different strategies if they make a mistake.
Saves Progress: The game automatically saves the player's progress, allowing them to continue from where they left off.
Score and Achievement Tracking: Players can earn achievements based on their performance, such as completing levels within a certain number of moves or time limits.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
## PR Description 📜

The turn on the light game has been implemented providing the puzzle experience.

Fixes #4160

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @thevijayshankersharma ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — APPROVED** [review]
Good to go!! Everything works as expected 🎊

**Comment by thevijayshankersharma** [comment]
@kunjgit @ishita-43 Who will merge and when ??

**Comment by kunjgit** [comment]
Thank you  @thevijayshankersharma , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
