### PR TITLE
 Blast Zone #586

### LINKED ISSUE #586: [New game]: Blast Zone
### 🎮 Game Request

Game logic and basic description
The game is called Blast Zone. It is a simple 2D game where the player controls a rectangular shape and shoots bullets to destroy enemy shapes. 

1. The player controls the rectangular shape using the Left and Right arrow keys or the A and D keys to move horizontally.
2. The player can shoot bullets by pressing the Spacebar key.
3. Enemies, represented by other rectangular shapes, move horizontally across the screen.
4. The player's goal is to shoot and destroy the enemies before they reach the player's position.
5. If an enemy bullet collides with the player, the player loses a life. The player starts with a certain number of lives.
6. The game ends when the player loses all lives.
7. The player's score increases for each enemy destroyed.

### Point down the features

Game points

1. Game Objective: The objective of the game is to control a player character and destroy enemy units while avoiding their bullets. The player aims to achieve the highest score possible.

2. Controls: The player can use either the left and right arrow keys or the A and D keys to move the player character horizontally. The spacebar is used to shoot bullets.

3. Enemies and Bullets: The game features various enemy units that move horizontally across the screen and shoot bullets at the player. The player needs to dodge enemy bullets while strategically shooting them down.

4. Player Character: The player controls a character capable of shooting bullets to destroy enemies. The character can move left and right to avoid enemy attacks.

5. Score: The game keeps track of the player's score, which increases as the player destroys enemies. The score serves as a measure of the player's performance in the game.

6. Lives: The player starts the game with a certain number of lives (typically three). Each time the player is hit by an enemy bullet, they lose a life. If the player loses all their lives, the game is over.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by rt-001**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #586

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [ ✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅] I have added screenshot for website preview in assets/images 
- [✅ ] I have added entries for my game in main README.md
- [ ✅] I have added README.md in my folder 
- [ ✅] I have added working video of the game in README.md (optional)
- [ ✅] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Blast Zone

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @rt-001 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@rt-001 LGTM

**Review by kunjgit — CHANGES_REQUESTED** [review]
you have to add that image in main repo assets/images !!

**Comment by kunjgit** [comment]
Thank you  @rt-001 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
