### PR TITLE
2048_win

### LINKED ISSUE #3646: {New Game]: Adding  2048_win:
### 🎮 Game Request

Game logic and basic description
2048 is a simple game built using HTML, CSS, and JavaScript where the player matches the tiles with the same number and when the two tiles touch, they merge into one. Once the player gets 2048 in any square, they win. 
Screenshot 2024-05-22 171130

### Point down the features

Game points

- Tile Movement: Tiles can be moved by clicking arrow keys in the desired direction.
- Tile Generation: A new 2 digit tile will be generated after every move. 
- Score Tracking: The score increases by the sum of total tiles merged in one click.
- Game Over Condition: Once the player gets 2048 in any square, they win and the game is over
- Difficulty level: The level increases with increasing tiles making it highly difficult for the person to achieve 2048. 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by VidhiSaxenaa**
## PR Description 📜

2048 Win is a puzzle game where you merge numbers together to create larger numbers. The goal of the game is to reach the number 2048. The person who reaches 2048, wins the game. 
Fixes #3646 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅ ] I have performed a self-review of my own code or work.
- [ ✅ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✅ ] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅ ] I have added screenshot for website preview in assets/images 
- [ ✅  ] I have added entries for my game in main README.md
- [✅ ] I have added README.md in my folder 
- [ x ] I have added a working video of the game in README.md (optional)
- [ ✅ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @VidhiSaxenaa ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by VidhiSaxenaa** [comment]
I'm unable to add the link of the game to the github, can you please assist me with that? 
Thank you!

**Comment by kunjgit** [comment]
Thank you  @VidhiSaxenaa , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by VidhiSaxenaa** [comment]
I've self reviewd the code and it's error free. Please review it once and do let me know if something else is to be added. This is my first open source contribution so if I've made any error please excuse and guide me ahead. Thank you!

**Comment by kunjgit** [comment]
@VidhiSaxenaa resolve the merge conflicts !

**Comment by VidhiSaxenaa** [comment]
I've resolved the merge conflicts.

**Comment by kunjgit** [comment]
Thank you  @VidhiSaxenaa , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
@VidhiSaxenaa resolve the conflicts !

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @VidhiSaxenaa , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by VidhiSaxenaa** [comment]
Kindly assign this to me.

**Comment by ishita-43** [comment]
> Kindly assign this to me.

You want to assign this to your commented id if not change the id to your second account and then comment

**Comment by vidhiisaxena** [comment]
Kindly assign this to me.

**Pull request merged**
