### PR TITLE
Main

### LINKED ISSUE #222: [Bug]: eye is not displaying while hovering
### Give a brief about the bug ✍️

Description: when we hover on any game, the eye icon does not shows up and we just get the text message.

eye bug

### What is the expected behavior? 🤔

Description: should show the eye emoji on hovering

### Provide step by step information reproduce the bug 📄

none

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by soumargha**
## PR Description 📜
The issue was: there was no eye icon visible on hovering on the games. I have fixed that issue and have put the image in the assets folder. I downloaded an image and just replaced the link  and the issue has been fixed.
issue number: 

Fixes #222

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [x ] My changes generates no new warnings.
- [x ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x ] I have added screenshot for website preview in assets/images 

- [x ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @soumargha ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by soumargha — COMMENTED** [review]
issue solved

**Comment by soumargha** [comment]
issue solved

**Comment by kunjgit** [comment]
Hey @soumargha 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Hey @soumargha !! 
It is part of GameZone UI where we want when someone hover the game to play joystick would be there !!
and if you are not able to load that it is because of not having low connectivity it will happen it is not an issue !!
Thank you 💗 !!

**Comment by kunjgit** [comment]
Thank you  @soumargha , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
