### PR TITLE
Spirograph

### LINKED ISSUE #4522: [New game]: Spirograph
### 🎮 Game Request

A Spirograph is a geometric drawing tool that creates beautiful, spiraling structures.

Logic:

setting parameters like gear sizes and frequency values that define the shape of the structure.
calculating the X and Y coordinates involving trigonometric functions.
the t value is continuously incremented, causing the calculations to update the X and Y coordinates, resulting in an animation of the curve being drawn on the screen.

Screenshot 2024-06-07 193135

### Point down the features

1. Combine gears with various sizes to create unique designs.
2. Roll a smaller gear around a larger one, tracing stunning curves.
3. These patterns, called hypotrochoids/epitrochoids, hold mathematical beauty.
4. Explore endless patterns and designs.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by muskan42**
## PR Description 📜

A Spirograph is a geometric drawing tool that creates beautiful, spiraling structures.
Fixes #4522 
<hr>
 
## Mark the task you have completed ✅

- [x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [ x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ x] I have added screenshot for website preview in assets/images 
- [ x] I have added entries for my game in main README.md
- [ x] I have added README.md in my folder 
- [ x] I have specified the respective issue number for which I have requested the new game.

<hr>

Screenshot 2024-06-07 193135

--- 
<br>

## Thank you soo much for contributing to our repository 💗

@ishita-43 kindly review

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @muskan42 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Also add your game image in asset folder of gamezone repository is present in same hierarchy as readme.md

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by kunjgit** [comment]
Thank you  @muskan42 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
