### PR TITLE
Added Tic_Tac_Toe game

### PR DESCRIPTION
**Pull request by Meenal21i**
Added a new game Tic Tac Toe.

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Meenal21i ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by SimranLahrani842** [comment]
You have not mentioned your issue number and tic tac toe was already assigned me so after exams I completed it...what's your issue number?

**Comment by kunjgit** [comment]
Hey @Meenal21i 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by kunjgit** [comment]
Thank you  @Meenal21i , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
