### PR TITLE
New Game Added [Memory Card Flip]

### LINKED ISSUE #3437: [New game]: Memory Card Flip
### 🎮 Game Request

Game logic and basic description

# Memory Card Game

## Game Description
Memory card game is a classic matching game where players try to find pairs of identical cards by flipping over two cards at a time. The game is played with a deck of cards that have identical pairs, with the pairs being hidden face-down on a grid. The objective is to find all the matching pairs by remembering the locations of the cards.

### 1. Setup:
- Create a deck of cards with identical pairs. The number of cards depends on the size of the game board.
- Shuffle the deck and place the cards face-down on a grid, forming the game board.

### 2. Player's Turn:
- The player selects two cards by clicking or tapping on them to flip them over and reveal their faces.
- If the two revealed cards match, the player scores a point and the cards are removed from the game board.
- If the two revealed cards do not match, the cards are flipped back over, and the player's turn ends.

### 3. Scoring:
- Each time a player finds a matching pair, they score one point.
- The goal is to find all the matching pairs to accumulate the highest score.

### 4. Game End:
- The game ends when all the matching pairs have been found, and the player with the highest score wins.

### 5. Gameplay Mechanics:
- The player can only reveal two cards at a time.
- The player must remember the locations of the cards they have already revealed to find matching pairs.
- If the two revealed cards do not match, they are flipped back over, and the player's turn ends.
- The game can be designed with different grid sizes and card quantities to adjust the difficulty level.

### 6. Additional Features:
- Time limit: The game can be timed, and the player with the fastest time to find all the matching pairs wins.
- Leaderboard: The game can keep track of high scores and display a leaderboard for players to compete against each other.
- Difficulty levels: The game can offer different difficulty levels by adjusting the grid size and the number of cards.

This is a basic implementation of the memory card game. You can further enhance the game by adding sound effects, visual animations, and other interactive features to make the gameplay more engaging and enjoyable for the players.

### Point down the features

Game points

#### Time Limit:
- The game can be timed, and the player with the fastest time to find all the matching pairs wins.
- Game Points: 5 bonus points for the fastest time to find all matching pairs.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by VesperAkshay**
## PR Description 📜

This pull request addresses Issue 3437: Implement new memory card flip game by introducing a new memory card flip game to our application.

The game challenges players to test their memory by flipping over cards and trying to find all the matching pairs. The game board consists of a 4x4 grid of face-down cards, and players can click on any two cards to reveal their images. If the two revealed cards match, they will remain face-up. If the cards do not match, they will flip back over.

The objective is for players to uncover all the matching pairs in as few moves as possible, which requires remembering the positions and contents of the previously revealed cards.
Fixes #3437 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
tittle

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @VesperAkshay ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VesperAkshay,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VesperAkshay,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VesperAkshay,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VesperAkshay,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VesperAkshay,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VesperAkshay,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VesperAkshay,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VesperAkshay,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by VesperAkshay** [comment]
I have Done the requested changes but why it shows to change the readme file

**Comment by Yashgabani845** [comment]
bro  you have to add you game name and game link in main readme.md file which is located in main folder or which you can see in github

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VesperAkshay,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Comment by VesperAkshay** [comment]
> bro you have to add you game name and game link in main readme.md file which is located in main folder or which you can see in github

Thankyou For the Help

**Comment by kunjgit** [comment]
Thank you  @VesperAkshay , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
