### PR TITLE
math quiz wrt #4063

### PR DESCRIPTION
**Pull request by bhumika-1127**
## PR Description 📜
@kunjgit I had added Math Quiz wrt issue #4063. Kindly review the PR.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2024-06-01 221704

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @bhumika-1127 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @bhumika-1127,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @bhumika-1127,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by bhumika-1127** [comment]
@kunjgit I have already created a readme.md inside the new folder. Kindly re-review.

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @bhumika-1127,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Pull request merged**
