### PR TITLE
Mario game added

### LINKED ISSUE #93: [New game]: Mario game
### 🎮 Game Request

A Mario game will be created using JavaScript and the Kaboom.js library.

### Point down the features

Game points
The game will include features such as moving and jumping mechanics, enemy characters, collectible coins, power-ups, different levels, and a scoring system. 
The game assets, such as sprites for Mario, coins, blocks, and enemies, will be loaded from external image URLs. 
The game will be started with the initial level set to 0 and the score set to 0

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by KhushiTayal**
## PR Description 📜

The provided code is a JavaScript implementation of a basic Mario game using the Kaboom.js game framework. It includes features such as player movement, jumping, collecting coins, interacting with objects like bricks and enemies, navigating through pipes, and multiple game levels. The code sets up different scenes, handles collision detection, and displays the player's score. It provides a foundation for creating a simple platformer game reminiscent of the classic Mario games. 
Fixes #93 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by KhushiTayal** [comment]
@kunjgit please review this PR.

**Review by kunjgit — APPROVED** [review]
You will be able to see Mario on GameZone soon 🔥 !!
Make layout for the game and make sure your add the game you are specifying over here you have made two folders remove that and merge into one

**Comment by kunjgit** [comment]
Thank you  @KhushiTayal , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @KhushiTayal !! you have added two folders for the game and none of them is working you have just created the scripts for that !! we have to close the PR make sure you fix everything and then create a PR again !!

**Pull request merged**
