### PR TITLE
Added Catch the object game

### LINKED ISSUE #5033: [New game]: Want to add the game catch the objects
### 🎮 Game Request

Game logic and basic description
In this game you have to catch the object falling from the top 

### Point down the features

Game points
It consist of a circle object
you just need to catch that 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
## PR Description 📜

I have added the catch the object game 

Fixes #5033 

https://github.com/user-attachments/assets/60cc8e17-00cb-48e7-a531-2cf245a6dd44

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in GameZone's README.md
- [x] I have added README.md in my Game folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.
- [x] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Ayushmaanagarwal1211 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Ayushmaanagarwal1211** [comment]
@ishita-43  Please review it and merge it

**Comment by ishita-43** [comment]
Also add your game image in the pr follow naming convention for that mentioned in contribution. Md

**Comment by Ayushmaanagarwal1211** [comment]
@ishita-43  Done Please check

**Review by ishita-43 — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Ayushmaanagarwal1211 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
