### PR TITLE
Added memory game

### LINKED ISSUE #3515: [New game]: Flames
### 🎮 Game Request

The "FLAMES" game is a popular and lighthearted game often played to determine the compatibility or relationship status between two individuals.

### Point down the features

If a player correctly guesses the relationship status predicted by the FLAMES algorithm, they earn points.
Players who reach the correct guess within a limited time frame may earn additional points
Assign different point values based on the rarity or difficulty of the predicted relationship status.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
## PR Description 📜
Included memory game of
 A Basic 4x2 Memory Game. Which depicts your score of your memory retention and concentration power.
The goal is to find all matching pairs of cards by flipping them over two at a time.
Fixes #3515 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Saipradyumnagoud ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Saipradyumnagoud,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Saipradyumnagoud,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Saipradyumnagoud,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by Saipradyumnagoud** [comment]
can you please elaborate the problem i am not able to get it

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Saipradyumnagoud,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by Saipradyumnagoud** [comment]
there are two games

**Pull request closed without merging**
