### PR TITLE
Fix a bug in README.md of Adventure_Game

### LINKED ISSUE #3150: [Documentation Bug]: Adventure_Game
### Describe the bug ✍️

The image is not getting displayed in the README file, instead it is displaying code.
Here is the image of it:
image

### Provide step by step information reproduce the bug 📄

1. Go through the Adventure_Game README file.
2. Scroll down you can find the bug.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Bindusree1515**
## PR Description 📜

There was bug in the README.md file, where in the screenshot section there was code placed instead of screenshot, which i fixed.
Fixes #3150 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Bindusree1515 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Bindusree1515** [comment]
i solved https://github.com/kunjgit/GameZone/pull/3150 sir
could you please check and approve .

**Review by kunjgit — APPROVED** [review]
LGTM!

**Comment by kunjgit** [comment]
Thank you  @Bindusree1515 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Bindusree1515** [comment]
Thank you @kunjgit 💗

**Pull request merged**
