### PR TITLE
added chopsticks

### LINKED ISSUE #2697: [New game]: Chopsticks
### 🎮 Game Request

Game logic and basic description

Each player has one point on each hand and in each turn a player can attack or split. For attack: a player can add their points to another player's hand. For split: a player can redistribute their points among both hands. If the number of points on one hand reaches five or greater than five, the player loses a hand. The player loses the game if both hands are lost.

### Point down the features

Game points

A player can add points from one hand of theirs to their opponent's hand. A player can also re-distribute the points they have. A player cannot skip a turn

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by DyuthiVivek**
## PR Description 📜
added a new game chopsticks
Fixes #2697

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @DyuthiVivek ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @DyuthiVivek , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by DyuthiVivek** [comment]
@gurjeetsinghvirdee this is a new game, should it not be a level 3 pr?

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee this is a new game, should it not be a level 3 pr?

nope, level3 should be given according to the quality of the PR not by game that labels on issues was automated by github actions

**Comment by DyuthiVivek** [comment]
@gurjeetsinghvirdee thank you for the clarification

**Pull request merged**
