### PR TITLE
[NEW GAME]: "DANTE" ADDED 💡

### LINKED ISSUE #722: [New game]: DANTE (3D)
### 🎮 Game Request

Game logic and basic description
- The Game "Dante" is about a simulation orientated game
- The Dante's responsibility is to catch up all ghosts from the Hell

### Point down the features

Game points
- Catching the Ghosts & Hard level of ghost gains more points
- Catching new powers to attack ghosts

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## PR Description 📜
- This PR is about adding a new game called **"Dante"**, an real life simulation based game

Fixes #722

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
preview1

preview2

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @0xabdulkhalid ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
mark your game entry in main README file

**Comment by 0xabdulkhalid** [comment]
Done @kunjgit !

**Comment by 0xabdulkhalid** [comment]
Conflicts also have been resolved!

**Pull request closed without merging**
