### PR TITLE
[Enhancement]: Made Things Easier to Read in Light Mode & Fixed Game Preview Contrast Glitch

### LINKED ISSUE #2917: [Enhancement]: Making Things Easier to Read in Light Mode
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Website enhancement:

- I would like to change the selected areas in the website given below to make it easier to read the text i light mode. 
- I would also like to fix the game preview images getting a different contrast of colours when switched the light mode.

image

### Describe the solution you'd like

Solution steps

Edit the HTML and CSS and JS Files.

### Select program in which you are contributing

hacktoberfest

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by 5h0ov**
## PR Description 📜

I would like to change the selected areas in the website given below to make it easier to read the text i light mode.
I would also like to fix the game preview images getting a different contrast of colours when switched the light mode.

## Preview before fix:
image

## Preview Of Changes:
lightgz

Fixes #2917 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

See Above

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @5h0ov ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by 5h0ov** [comment]
@kunjgit  sir could you kindly review this PR under HackOctober '23

**Comment by kunjgit** [comment]
Hey @5h0ov you need to have significant enhancement to get it merged !
Try to do some more enhancement looking forward to have our next step :octocat:

**Comment by 5h0ov** [comment]
> Hey @5h0ov you need to have significant enhancement to get it merged ! Try to do some more enhancement looking forward to have our next step :octocat:

ok i will see what i can do :)

**Comment by 5h0ov** [comment]
> Hey @5h0ov you need to have significant enhancement to get it merged ! Try to do some more enhancement looking forward to have our next step :octocat:

could you suggest something to enhance in the website? 😥
or do i enhance the UI of a game as well?

**Comment by kunjgit** [comment]
Hey @5h0ov you can do one thing dark mode is too mess so that effect that we have on website you can remove that effect and improve the UI so it will look aesthetic and more attractive ! :octocat:

**Comment by 5h0ov** [comment]
> Hey @5h0ov you can do one thing dark mode is too mess so that effect that we have on website you can remove that effect and improve the UI so it will look aesthetic and more attractive ! :octocat:
you mean this effect sir?
image

**Comment by 5h0ov** [comment]
> Hey @5h0ov you can do one thing dark mode is too mess so that effect that we have on website you can remove that effect and improve the UI so it will look aesthetic and more attractive ! :octocat:

You mean this effect sir?:

image

or the floating white particles in background?

**Comment by 5h0ov** [comment]
@kunjgit Sir, I will try to solve the UI Issue later. For now i am closing this PR. Thanks !

**Comment by kunjgit** [comment]
Thank you  @5h0ov , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
