### PR TITLE
[GSSoC'23] Dots and Boxes Game Ready

### LINKED ISSUE #1646: [New game]: Dots and Boxes Game [GSSoC'23]
### 🎮 Game Request

Game logic and basic description

- Dots and Boxes is a classic pencil-and-paper game played on a grid of dots.
- Players take turns connecting two adjacent dots with a horizontal or vertical line to form a box.
- When a player completes a box, they put their initial inside it and get an extra turn. The player with the most boxes at the end wins.

### Point down the features

Game points

- The players who have the more boxes will win the game

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #1646 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Dots_and_Boxes_Game

## Demo Video
https://github.com/kunjgit/GameZone/assets/114330097/87688ed4-ec75-4f38-9059-b5e6f3d8ea1a

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Avdhesh-Varshney ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Avdhesh-Varshney** [comment]
@kunjgit This game has the automated functionality which player can play with the computer and enjoying the game with smooth UI and best experience

So, I requested to you that merge this game into the main branch of this repository for a valuable contribution under GSSoC'23 program

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Avdhesh-Varshney , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Pull request merged**
