### PR TITLE
Solved issue #3685- Space Explorer game

### LINKED ISSUE #3685: [New game]: Space Explorer
### 🎮 Game Request

Game logic and basic description
In this game, the player controls a spaceship that navigates through an asteroid field. The player must avoid asteroids and collect stars for points. 

### Point down the features

Game points
## Key Features

1. **Spaceship Control:**
   - Smooth left and right movement using arrow keys or 'A' and 'D' keys.
   - Responsive gameplay with collision detection.

2. **Asteroid Obstacles:**
   - Randomly spawning asteroids that fall downwards.
   - Players must avoid collisions to stay alive.

3. **Collectible Stars:**
   - Randomly appearing stars that fall downwards.
   - Collecting stars increases the player's score.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below

Space Explorer is a dynamic and visually appealing game where the player navigates a spaceship through an asteroid field, collecting stars and avoiding obstacles to score points.

Fixes # <your_issue_number>
Fixes #3685 
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Space_Explorer

https://github.com/kunjgit/GameZone/assets/142652964/e86a6b0f-c80b-476f-b4f6-7dade51a1610

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Aditi22Bansal ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Aditi22Bansal** [comment]
@kunjgit 
Kindly review the PR and merge
Thankyou

**Comment by kunjgit** [comment]
@Aditi22Bansal make sure you are having your README file updated to the latest and resolve the merge conflicts !

**Comment by Aditi22Bansal** [comment]
Done
Kindly review and merge
Thankyou

**Comment by Aditi22Bansal** [comment]
@kunjgit 
Please review and merge

**Review by kunjgit — APPROVED** [review]
LGTM!

**Comment by kunjgit** [comment]
Thank you  @Aditi22Bansal , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
