### PR TITLE
modified for correct rendering

### LINKED ISSUE #4868: [Bug]:  The thumbnail for the Brick Buster game isn't rendering correctly.
### Give a brief about the bug ✍️

Description
The thumbnail for the Brick Buster game is not rendering correctly, which is causing issues with its visibility and appeal. This improper rendering affects the overall presentation of the game, potentially impacting user engagement and interest. It's important to address this issue promptly to ensure that the thumbnail displays properly and attracts players effectively.

### What is the expected behavior? 🤔

Description
The expected behavior for the thumbnail of the Brick Buster game is that it should render clearly and correctly, displaying the intended image without any distortion, pixelation, or loading issues. The thumbnail should be visually appealing, adhere to the specified dimensions, and be fully visible across different devices and platforms, effectively attracting user interest and engagement.

Screenshot 2024-07-16 193337

### Provide step by step information reproduce the bug 📄

Description
Steps to Reproduce the Bug
1. Open the Platform: Launch the platform where Brick Buster is listed.
2. Navigate to Game Listing: Go to the section displaying the game.
3. Observe Thumbnail: Check for rendering issues (e.g., distortion or blank spaces).
4. Test on Different Devices: View the thumbnail on various devices and browsers.
5. Inspect Element: Right-click on the thumbnail and select "Inspect" to check the HTML/CSS.
6. Clear Cache: Clear your browser cache and reload the page.
7. Re-upload Thumbnail: Try re-uploading the thumbnail image.

Plan to Find the Bug's Solution
1. Review Image Specifications: Confirm the image format, dimensions, and size.
2. Check Server Logs: Look for errors related to image loading.
3. Test Different Images: Upload an alternative thumbnail to see if the issue persists.
4. Consult Documentation: Review platform guidelines for thumbnail rendering.
5. Engage Community Support: Ask for forums or support for similar issues.
6. Update Software: Ensure all related software is up to date.
7. Document Findings: Record any discoveries to identify patterns

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by sweta-singh28**
## PR Description 📜

Resolved the problem of incorrect thumbnail display for Brick Buster.
Fixes #4868

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot 2024-07-17 010536

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @sweta-singh28 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by ishita-43 — APPROVED** [review]
Good to go

**Comment by kunjgit** [comment]
Thank you  @sweta-singh28 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by sweta-singh28** [comment]
@kunjgit sir,  please assign this merged pr a proper level as it would allow me to gain points in the gssoc24 program.

**Comment by sweta-singh28** [comment]
@ishita-43

**Pull request merged**
