### PR TITLE
added a new game escape room (puzzle version)

### LINKED ISSUE #3357: [New game]: Escape room
### 🎮 Game Request

🎮 Game Request: Escape Room

Game Logic Description

Escape Room is a puzzle-solving game where players must solve a series of puzzles and find clues to escape from a locked room within a set time limit. The game challenges players' problem-solving and logical thinking skills with various types of puzzles, including riddles, code-breaking, and pattern recognition.

Initialization:

The game starts with an introductory screen explaining the rules and setting the story.
Players enter the escape room environment with interactive elements.

1: Player Interaction:

Players can click on different objects in the room to investigate and collect items.
Items can be used to solve puzzles and unlock new areas or clues.
A timer counts down the remaining time to escape.

2: Puzzle Solving:

The room contains multiple puzzles that must be solved in sequence.
Clues and items found in the room help to solve these puzzles.
Puzzles vary in type, including logic puzzles, pattern matching, and code-breaking.

3: Game End:

The game ends when the player successfully escapes the room or the timer runs out.
A summary screen shows the time taken and the puzzles solved.

### Point down the features

Features of the Game

1 : Interactive Environment:

Players can interact with various objects in the room.
Clues and items are hidden and require exploration to find.

2: Variety of Puzzles:

Different types of puzzles to solve, increasing in complexity.
Logical, pattern-based, and code-breaking puzzles.

3: Time Challenge:

Countdown timer to increase urgency and challenge.
Option to extend time with in-game actions or achievements.

4: Hint System:

Hints available for players who get stuck.
Limited hints to maintain the challenge.

5: Progress Tracking:

Progress is tracked, allowing players to see which puzzles have been solved.
Summary screen at the end showing performance and time taken.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by NAVJOT-786**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #3357 

I have added a new game called "Escape Room" to the GameZone website. This game involves solving a series of questions to unlock a door and escape the room. Each game session features randomly selected questions to ensure a unique experience every time.

<hr>

## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

![Escape Room Screenshot]
Screenshot 2024-05-17 at 1 23 29 PM
Screenshot 2024-05-17 at 1 23 35 PM
Screenshot 2024-05-17 at 1 24 00 PM

---

<br>

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @NAVJOT-786 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @NAVJOT-786,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Review by kunjgit — APPROVED** [review]
LGTM!

**Comment by kunjgit** [comment]
@NAVJOT-786 resolve the changes !

**Comment by NAVJOT-786** [comment]
@kunjgit My Pr is not yet accepted is anything else i have to do??

**Review by kunjgit — APPROVED** [review]
LGTM!

**Comment by kunjgit** [comment]
@NAVJOT-786 you are having merge conflicts in gamesData.json make sure you are resolving that !

**Comment by NAVJOT-786** [comment]
@kunjgit please check If any other chages required

**Comment by kunjgit** [comment]
@NAVJOT-786 it's not resolved yet !

**Comment by NAVJOT-786** [comment]
@kunjgit please check

**Pull request merged**
