### PR TITLE
Call Of Duty added

### LINKED ISSUE #4996: [New game]: Call Of Duty
### 🎮 Game Request

Call of Duty is a first-person shooter (FPS) game series where players experience various military scenarios, either through single-player campaigns or multiplayer modes. The game's logic involves players navigating through maps, completing objectives, and engaging in combat with enemies using a variety of weapons and tactics. The gameplay often includes a mix of shooting, stealth, and strategic elements, requiring players to make quick decisions and use their environment to their advantage.

### Point down the features

 players compete in teams or solo across different game types such as Team Deathmatch, Capture the Flag, and Battle Royale. Players can customize their loadouts with different weapons, attachments, and perks to suit their playstyle.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by arunimaChintu**
## PR Description 📜

Call of Duty is a first-person shooter (FPS) game series where players experience various military scenarios, either through single-player campaigns or multiplayer modes. The game's logic involves players navigating through maps, completing objectives, and engaging in combat with enemies using a variety of weapons and tactics. The gameplay often includes a mix of shooting, stealth, and strategic elements, requiring players to make quick decisions and use their environment to their advantage.

Fixes #4996 
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in GameZone's README.md
- [x] I have added README.md in my Game folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.
- [x] I have added my Game to gamesData.json file and it is loading properly on main website as intended.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @arunimaChintu ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by arunimaChintu** [comment]
@ishita-43 Please review it... @kunjgit Please merge this...

**Review by ishita-43 — APPROVED** [review]

**Comment by arunimaChintu** [comment]
@kunjgit Please merge this...

**Comment by kunjgit** [comment]
Thank you  @arunimaChintu , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
