### PR TITLE
Glass_and_ball

### LINKED ISSUE #2095: [New game]: Ball_and_Glass
### 🎮 Game Request

Welcome to the Ball and Glass Challenge! Your task is to guide a ball into a series of glasses by strategically positioning a stopper. The ball moves in a two-dimensional space, bouncing up and down and left and right. Your goal is to stop the ball at the right moment and position so that it falls into the glass.

### Point down the features

Game pointsEach successful glass entry earns you a certain number of points based on the level's difficulty.
If you miss a glass or fail to position the stopper correctly, you don't earn any points for that round.
Your total score is calculated by summing up the points from each successful glass entry.
You can aim for a high score and challenge yourself to beat your previous record.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by U-DAY-333**
## PR Description 📜

Added Ball and Glass Challenge! our task is to guide a ball into a series of glasses by strategically positioning a stopper. The ball moves in a two-dimensional space, bouncing up and down and left and right. Your goal is to stop the ball at the right moment and position so that it falls into the glass.

Fixes #2095
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Ball_and_glass

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @U-DAY-333 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Resolve conflicts @U-DAY-333

**Comment by daccdacc** [comment]
@U-DAY-333 Please checkout the link you have mentioned as well.

**Review by kunjgit — APPROVED** [review]

**Comment by U-DAY-333** [comment]
@daccdacc i have updated the link in readme file please review it

**Comment by kunjgit** [comment]
Thank you  @U-DAY-333 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @U-DAY-333,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Pull request merged**
