### PR TITLE
catch me if you can task

### PR DESCRIPTION
**Pull request by Khaleeq01**
I will be using mouse event for the assignment.
Create a box whose size changes dynamically according to viewport size. Now when you hover over the box, it should change its position randomly inside the viewport.
You can put box initially at any position inside the viewprt; just make sure that it does not move out of the viewport at any given time.

The box will look like this-https://ninjasfiles.s3.amazonaws.com/0000000000001861.png
Screenshot of final task-https://ninjasfiles.s3.amazonaws.com/0000000000001878.gif

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Khaleeq01 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @Khaleeq01 checkout the demo video we have on Discord and then create PR you are still missing out to entries

**Comment by kunjgit** [comment]
Thank you  @Khaleeq01 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Khaleeq01** [comment]
@kunjgit i tried many times but you did not merge my PR i did not know why you guys are making it complicated

**Pull request closed without merging**
