### PR TITLE
Drum kit project 

### LINKED ISSUE #651: [New game]: Drum Game
### 🎮 Game Request

A drum kit game using JavaScript is a game that allows the user to play a drum kit using their keyboard. The game is created using HTML, CSS, and JavaScript. 

### Point down the features

1. **A variety of drum sounds**: The drum kit should be able to produce a variety of drum sounds, such as snare drums, bass drums, cymbals, and toms.

2. **Customization:** The user should be able to customize the drum kit to their liking, such as choosing the different drum sounds and the layout of the kit.

3. **Easy to use:** The drum kit should be easy to use, even for beginners. The user should be able to start playing right away without having to learn a lot of complicated controls.
Responsive: The drum kit should be responsive to the user's input. The user should be able to play the drums smoothly and without any lag.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by shivamsisodia07**
## PR Description 📜

Drum kit project added
Fixes #651

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>
--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @shivamsisodia07 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@shivamsisodia07 Make an entry of your game into main README file.

**Comment by shivamsisodia07** [comment]
main readme updated

**Comment by kunjgit** [comment]
follow proper guidelines and then create PR !!

**Comment by kunjgit** [comment]
Thank you  @shivamsisodia07 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
