### PR TITLE
[Enhancement]: Alien_Invasion game doesn't work mismatch logic

### LINKED ISSUE #4731: [Enhancement]: `Alien_Invasion` game doesn't work mismatch logic
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

- `Alien_Invasion` project cannot drawable this is something issue for the mismatch logic.
- please see the below video..
- please assign me..

### Describe the solution you'd like

[Screencast from 2024-07-03 06-40-55.webm](https://github.com/kunjgit/GameZone/assets/121082414/a4694ce1-195a-41b2-80cb-b62bd9c34578)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by sivaprasath2004**
## PR Description 📜

[Enhancement]: Alien_Invasion game doesn't work mismatch logic

Fixes #4731 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

[Screencast from 2024-07-04 16-11-59.webm](https://github.com/kunjgit/GameZone/assets/121082414/1815d332-ac6f-43ed-953e-26395aaf88bc)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @sivaprasath2004 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by sivaprasath2004** [comment]
@kunjgit  i will finished...

**Review by ishita-43 — APPROVED** [review]
Approved!!

**Comment by kunjgit** [comment]
Thank you  @sivaprasath2004 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
