### PR TITLE
ADD GAME: UNRULY TOWER 🕹️

### LINKED ISSUE #604: [New game]: UNTRULY TOWER 🚀
### 🎮 Game Request

Game logic and basic description
- This game is about traversing the tower from bottom to top with left, right and spacebar(jump) keys
- It's quite addictive to play
- This games look will so much close to retro games

### Point down the features

Game points
- We can get points for passing every footstep

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## PR Description 📜
- This PR is related to adding a new game called "Unruly Tower", which is a single-player action based game
- Fixes #604 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Screenshot 📸

Screenshot 2023-05-30 at 20-16-18 CodePen - Unruly Tower

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @0xabdulkhalid ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
don't alter main index file !!!

**Comment by 0xabdulkhalid** [comment]
Done @kunjgit !

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @0xabdulkhalid , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by 0xabdulkhalid** [comment]
Hello @kunjgit, please make sure to add necessary labels like `gssoc23` & `level3`.

So that the `GSSOC`'s Backend can count this Contribution otherwise this PR will be skipped.

So please add those lables 🙌🏻

**Pull request merged**
