### PR TITLE
Maze Game #46

### LINKED ISSUE #46: [New game]: Maze Game
### 🎮 Game Request

Game logic and basic description
The game logic revolves around a simple maze game where the player needs to navigate through a maze from a starting point to reach the end point.
1) Maze Generation:
- A maze is randomly generated using a grid-based system.
- The maze consists of walls and open paths that form a network of interconnected cells.
- The starting point is marked at a specific cell, and the end point is placed in another cell.
2) Player Movement:
- The player is represented as a character or object within the maze.
- The player can move in four directions: up, down, left, and right.
- The player uses input controls, such as arrow keys to navigate through the maze.
- The movement is constrained by the maze's walls, meaning the player cannot move through walls but can traverse through open paths.

### Point down the features

Game points

1. Difficulty levels can be implemented, altering the complexity of the maze generation.
2. Timer functionality can be included to track the time taken to complete the maze.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by rt-001**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #46

<hr>
 
## Mark the task you have completed ✅

- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅] I have added screenshot for website preview in assets/images 
- [ ✅] I have added entries for my game in main README.md
- [✅ ] I have added README.md in my folder 
- [✅ ] I have added working video of the game in README.md (optional)
- [✅ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

MazeGame

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @rt-001 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by rt-001** [comment]
@kunjgit  created a new PR. I

**Review by kunjgit — CHANGES_REQUESTED** [review]
remove files that are not needed and also make sure you add game thumbnail in assets folder

**Comment by kunjgit** [comment]
Thank you  @rt-001 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
