### PR TITLE
Added Home Icon in Connect 4 game

### LINKED ISSUE #4014: [Enhancement]: Adding Home Icon in Connect 4 game
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement

I will add a Home Icon, adding it will improve the game's usability, making it more user friendly and accessible, which can lead to higher user satisfaction and retention.

### Describe the solution you'd like

Solution steps

Adding Home Icon at the top of the game, it will help players to navigate to the Home Page easily, increasing their convenience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by ShristiiSharma**
## PR Description 📜

Added a Home Icon, it will improve the game's usability, making it more user friendly and accessible, which can lead to higher user satisfaction and retention, also it will help players to navigate to the Home Page easily, increasing their convenience.

Fixes #4014

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Home Icon

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @ShristiiSharma ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by ShristiiSharma** [comment]
@kunjgit Please review my PR

**Comment by ShristiiSharma** [comment]
@kunjgit Please merge!

**Comment by ShristiiSharma** [comment]
@kunjgit Please merge, as I'm unable to raise another issue.

**Comment by kunjgit** [comment]
Thank you  @ShristiiSharma , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
