### PR TITLE
bulls and cows game added

### LINKED ISSUE #3184: [New game]: Bulls and Cows game could be added
### 🎮 Game Request

Game logic and basic description

One player, the Chooser, thinks of a four-letter word and the other player, the Guesser, tries to guess it.

At each turn the Guesser tries a four-letter word, and the Chooser says how close it is to the answer by giving:

The number of Bulls - letters correct in the right position.
The number of Cows - letters correct but in the wrong position.
The Guesser tries to guess the answer in the fewest number of turns.

If either word has repeated letters the rule is that each letter can only count towards the score once, and Bulls are counted before Cows.

can be done against computer

### Point down the features

Playing against computer is one of the features.

@kunjgit can you assign me this

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Ankitapanda25**
## PR Description 📜

This PR adds a new game to the website
Fixes #3184 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Ankitapanda25 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Ankitapanda25** [comment]
@kunjgit please do review my pr and provide a feedback

**Comment by kunjgit** [comment]
@Ankitapanda25 resolve the conflicts !

**Comment by Ankitapanda25** [comment]
@kunjgit done

**Comment by kunjgit** [comment]
@Ankitapanda25 it's still there !

**Comment by Ankitapanda25** [comment]
@kunjgit now?

**Review by kunjgit — CHANGES_REQUESTED** [review]
@Ankitapanda25 add your game image in root assets /images so that  we can land it on GameZone !

**Comment by Ankitapanda25** [comment]
@kunjgit done adding

**Comment by Ankitapanda25** [comment]
@kunjgit Please let me know if everything's right?

**Review by kunjgit — APPROVED** [review]
LGTM !

**Pull request merged**
