### PR TITLE
Mine_Sweeper Game

### LINKED ISSUE #3183: [New game]: Mine Sweeper by using pure css
### 🎮 Game Request

Game logic and basic description: It is implementation of the popular puzzle game Minesweeper. Built with [CSS and little bit of HTML]. We need to sweep through grid of tiles, avoiding hidden mines.
@kunjgit sir kindly assign me this project!!

### Point down the features

Game points
Tech Stack:HTML,CSS

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by neel815**
## PR Description 📜
Hi I have made this game called Minesweeper using HTML & CSS only it is very fun to play game as it refresh our old memories.
Fixes #3183 

<hr>
 
## Mark the task you have completed ✅

- [ * ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ * ] I have performed a self-review of my own code or work.
- [ * ] I have commented my code, particularly in hard-to-understand areas.
- [ * ] My changes generates no new warnings.
- [ * ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ * ] I have added screenshot for website preview in assets/images 
- [ * ] I have added entries for my game in main README.md
- [ * ] I have added README.md in my folder 
- [ * ] I have added working video of the game in README.md (optional)
- [ * ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @neel815 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
make sure you are adding your game in readme file !
@neel815 !

**Comment by neel815** [comment]
I have already added my github repo link which contains game kindly check it.

**Comment by kunjgit** [comment]
@neel815 in main readme file you have to add your game entry !

**Comment by ishita-43** [comment]
Please refer other merged Pr and see how they modified main README.MD file to add their game!!
and then add your game

**Comment by ishita-43** [comment]
> Please refer other merged Pr and see how they modified main README.MD file to add their game!! and then add your game

Just like your readme file this repo also has readme update that file you willl find that  where you find contribution guidelines and 
 game folder outside see that file and make changes there

**Pull request closed without merging**
