### PR TITLE
Update README.md

### LINKED ISSUE #4248: [Documentation Bug]: Broken Link in Documentation
### Describe the bug ✍️

To fix the broken link, I plan to update the URL to the correct one for the "Hit_the_hamster" game.
Screenshot 2024-06-05 194441

I am contributing to the GameZone program.

Code of Conduct: By submitting this issue, you agree to follow our CODE OF CONDUCT.

[✅] I follow the CONTRIBUTING GUIDELINE of this project.

### Provide step by step information reproduce the bug 📄

Step by step information to reproduce the bug:

Navigate to the documentation section of the GameZone repository.
Look for the link to the "Hit_the_hamster" game.
Click on the link and observe that it leads to a broken URL.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by GUNJESH843**
## PR Description 📜

This PR resolves the issue related to the broken link in the documentation. I have updated the link to the **[Hit_the_hamster](https://github.com/kunjgit/GameZone/tree/main/Games/Hit_the_hamster)** to ensure it directs to the correct location within the repository.

Fixes  #4248

<hr>
 
## Mark the task you have completed ✅

- [x] I have followed [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have followed proper naming convention as shown in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added a screenshot for website preview in assets/images.
- [x] I have added entries for my game in the main README.md.
- [x] I have added README.md in my folder.
- [x] I have added a working video of the game in README.md (optional).
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots (Optional) 📸
  
Before 

Screenshot 2024-06-05 194441

After

Screenshot 2024-06-05 194551

Thank you.
#*I AM A GSSoC Contributer*

--- 
<br>

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @GUNJESH843 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by ishita-43** [comment]
Hi @GUNJESH843 , there are other 3 error of same category .  Can you update them also !! if done properly ,update them and we  will give labels to your pr.

**Comment by GUNJESH843** [comment]
@ishita-43 sure I would love to work on the issues thanks for asking, I would start working on it ASAP! , I request you to accept this pull request until then. 

Thank you.

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by kunjgit** [comment]
Thank you  @GUNJESH843 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
