### PR TITLE
Movie Guessing Game

### PR DESCRIPTION
**Pull request by vishalkumarmahto**
## PR Description 📜

A new game added: Movie Guessing Game.  This is a pull request for the implementation of a new game name Movie Guessing Game. This is a game in which users guess the movie name by taking the hints from the emojis given. 
Fixes # <496>

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @vishalkumarmahto ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
mark your entries in main README file

**Comment by kunjgit** [comment]
here only you have to add the changes don't create new PR for the changes mark your entries in main README !!

**Comment by vishalkumarmahto** [comment]
Kindly review and merge it, as I have made the changes you requested for.

**Comment by kunjgit** [comment]
add your game entry and make one PR only for one issue 👀 !
we are closing this one come up one PR only

**Comment by kunjgit** [comment]
Thank you  @vishalkumarmahto , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
