### PR TITLE
Add features in Country Guesser Game

### LINKED ISSUE #1972: [Enhancement]: Add features in Country Guesser Game
### Feature Request
1. Add timer
2. Add start game button
3. Add new game button
4. When the game ends (time is up) ---> show a modal showing no of countries guessed and new game button
5. Also create separate css file

### Describe the solution you'd like

Done using Html css javascript

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by palakag29**
## PR Description 📜

- #1972 

Fixes #1972

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

### Before
[Screencast from 25-06-23 01:45:50 PM IST.webm](https://github.com/kunjgit/GameZone/assets/112793075/c898a8f4-9ccb-4f28-bd00-3f6350b68713)

### After
[Screencast from 25-06-23 01:53:18 PM IST.webm](https://github.com/kunjgit/GameZone/assets/112793075/458e0bc9-6711-432d-8db1-f2aa368684a4)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @palakag29 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by palakag29** [comment]
@kunjgit

**Comment by kunjgit** [comment]
follow proper guidelines and then create a PR !!

**Comment by kunjgit** [comment]
Thank you  @palakag29 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
