### PR TITLE
[GSSoC'23] Crossword Game Completed

### LINKED ISSUE #1572: [New game]: Crossword Game [GSSoC'23]
### 🎮 Game Request

Game logic and basic description

- Crossword puzzles are word games that involve filling a grid of squares with letters to form words.
- The grid consists of both horizontal and vertical lines, with intersecting words forming a complete puzzle.
- Clues or hints are provided for each word, ranging from straightforward definitions to more cryptic or tricky hints.
- Solving a crossword puzzle requires wordplay, general knowledge, and problem-solving skills.
- Crossword puzzles are popular in newspapers, magazines, and online platforms, providing an entertaining and challenging way to test vocabulary and knowledge.

### Point down the features

Game points

- Complete the whole game and will get a grand winning announcement

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## PR Description 📜

Title - Cross word Game
Tech used - HTML, CSS, and JS

Fixes #1572 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Crossword_Game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Avdhesh-Varshney ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Avdhesh-Varshney** [comment]
@kunjgit please review this pull request and requested to merge it into the main branch of thie repository for a successful contribution under GSSoC'23 program.

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Avdhesh-Varshney , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @Avdhesh-Varshney,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by Avdhesh-Varshney** [comment]
@kunjgit i have not worked on the closed issue. 
I am always first see the issue in one tab before creating the pull request.
I had not broken any guideline.

Kunj, I requested to add the levels on this pull request so that it will comes on the leaderboard and count as a contribution under GSSoC'23.

**Comment by Avdhesh-Varshney** [comment]
@kunjgit @gurjeetsinghvirdee please add labels on this pr

**Pull request merged**
