### PR TITLE
Added Bouncing ball Game

### PR DESCRIPTION
**Pull request by nandita27iitp**
## PR Description 📜
The 2D Bouncing Ball Game is a simple yet engaging web-based game developed using HTML, CSS, and JavaScript. It involves a ball that continuously bounces around within the boundaries of the game area, changing direction upon collision with the edges. This game provides a great example of basic game physics and interactive animation on the web.
HTML: The structure of the game is built using HTML, providing the canvas element where the game animations occur.
CSS: Styling is applied through CSS to ensure the game has a clean and visually appealing look. CSS is also used for animations that enhance the game's interactivity.
JavaScript: Core game logic is implemented in JavaScript, which includes ball movement, collision detection, speed adjustments, and game state management.
Fixes # 3885

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @nandita27iitp ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by nandita27iitp** [comment]
@kunjgit pls merge my PR

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @nandita27iitp , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
