### PR TITLE
Adding Taash Game

### LINKED ISSUE #4165: [New game]: Taash Game
### 🎮 Game Request

Game logic and basic description:
In Taash Game, the suits have no meaning. 
1. Number cards have a value equal to their number.
2. All the picture cards (Jacks, Queens, and Kings) are worth 10. 
3. Aces are worth 1.
4. The table keeps a record of total wins,loses and draws
5. Click on "Restart" Button to start a new game
6. Click on "Deal" Button to clear the field

### Point down the features

Patti Game

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by codewithganeshhh**
## PR Description 📜 :

In Taash Game, the suits have no meaning.

Number cards have a value equal to their number.
All the picture cards (Jacks, Queens, and Kings) are worth 10.
Aces are worth 1.
The table keeps a record of total wins,loses and draws
Click on "Restart" Button to start a new game
Click on "Deal" Button to clear the field

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #4165 

<hr>
 
## Mark the task you have completed ✅

- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅] I have added screenshot for website preview in assets/images 
- [✅ ] I have added entries for my game in main README.md
- [ ✅] I have added README.md in my folder 
- [✅] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Taash Game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @codewithganeshhh ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by codewithganeshhh** [comment]
Check  and Merge @kunjgit ASAP

**Comment by codewithganeshhh** [comment]
Check please i have more projects to add @kunjgit

**Comment by codewithganeshhh** [comment]
@ishita-43  check my PR

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Please add the proper link of your game to the main Readme.md for reference see other entries format there.

**Comment by codewithganeshhh** [comment]
Check again @ishita-43

**Review by ishita-43 — APPROVED** [review]
Great collaboration!! 🎊

**Comment by kunjgit** [comment]
Thank you  @codewithganeshhh , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
