### PR TITLE
Trex_Run Added

### LINKED ISSUE #2049: [New game]: T-rex Run
### 🎮 Game Request

Game logic and basic description
The game features a  Tyrannosaurus rex (T-Rex) character, which is controlled by the player. The T-Rex starts running automatically from the left side of the screen, and the objective is to help it avoid obstacles and survive for as long as possible.
The primary obstacle in the game is cacti, which are placed at varying heights along the ground. The player must time their jumps to make the T-Rex jump over these cacti. 

### Point down the features

Game points
The game's controls are straightforward and typically involve using the spacebar or up arrow key to make the T-Rex jump.
Timing is crucial to clear the obstacles successfully, as mistimed jumps or crouches will result in the T-Rex colliding with an obstacle and the game ending.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by akankshachanana1**
## PR Description 📜
The game features a Tyrannosaurus rex (T-Rex) character, which is controlled by the player. The T-Rex starts running automatically from the left side of the screen, and the objective is to help it avoid obstacles and survive for as long as possible.
The primary obstacle in the game is cacti, which are placed at varying heights along the ground. The player must time their jumps to make the T-Rex jump over these cacti.

Fixes #2049 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Trex_Run

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @akankshachanana1 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @akankshachanana1,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @akankshachanana1,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @akankshachanana1,
You need to make the following changes:
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — APPROVED** [review]

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Remove __.vscode__ folder from game

**Review by kunjgit — APPROVED** [review]

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM 🌸

**Comment by kunjgit** [comment]
Thank you  @akankshachanana1 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
