### PR TITLE
Added Guess_Num Game

### LINKED ISSUE #3682: [New game]: Guess the number
### 🎮 Game Request

Guess the Number" is a simple number guessing game where the player tries to guess a randomly generated number within a specified range. The player is informed whether their guess is too high or too low after each attempt. The game continues until the player guesses the correct number, at which point they are congratulated and informed of the number of attempts made. The player can then choose to play again or end the game.

### Point down the features

1. **Correct Guess**: 
   - When the player correctly guesses the number, they earn a certain number of points. This could be a fixed amount or based on factors such as the range of numbers or the number of attempts taken.

2. **Number of Attempts**:
   - Points could be awarded based on the number of attempts it takes for the player to guess the correct number. Fewer attempts could result in more points, incentivizing efficient guessing.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by manishh12**
## PR Description 📜

This project provides the functionality for the Guess the Number game. Players can input their guesses, and the game provides feedback on whether the guess is too high, too low, or correct. Players have a maximum of 10 attempts to guess the correct number, after which the game ends.
Fixes #3682 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @manishh12 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
@manishh12 resolve merge conflicts !

**Comment by manishh12** [comment]
> @manishh12 resolve merge conflicts !

@kunjgit Done. kindly review it again.

**Comment by manishh12** [comment]
> > @manishh12 resolve merge conflicts !
> 
> @kunjgit Done. kindly review it again.

@kunjgit Please review and merge this pr so that i can work on other issues.

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @manishh12 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
