### PR TITLE
Static_footer_fix

### PR DESCRIPTION
**Pull request by PVBharadwaj**
## PR Description 📜

Earlier the footer section used to be fixed/static on the website and appear on the screen right from the beginning.
When I fixed that issue, the footer text was not aligned to the centre. There are some (maybe) typos in the original code. The <ul> tags are not closed. So, I fixed them.
Fixes # <314>

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images
- [x] I have specified the respective issue number.

<hr>

## Add your screenshots(Optional) 📸
Before the fix
Screenshot

After the fix
Screenshot

--- 
<br>

### CODE REVIEW

**Comment by kunjgit** [comment]
Hey @PVBharadwaj 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 During the time of PR don't alter main index file ! 🙂 
 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Comment by PVBharadwaj** [comment]
> Hey @PVBharadwaj 👋!
> 
> @kunjgit here, We have this annoucement to make 📢!! During the time of PR don't alter main index file ! 🙂 In main Readme file just use * as a game number during the time we are merging we will add number !! 👀 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 Thank you 💗!

Ok. I am new to open source, I don't know that the main index file should not be altered. I will not repeat this for the next PR. Thank You

**Comment by Arun9739** [comment]
@PVBharadwaj please bring back the main index file to original state or else close this PR and create new one.

**Comment by PVBharadwaj** [comment]
Ok, I will close this PR and create a new one, but where can I make the required changes? Because the readme template is for new games. This PR is for website enhancement/bug fixes. Please let me know @Arun9739 .

**Comment by Arun9739** [comment]
@PVBharadwaj no changes in README. But you should not change main index file.

**Comment by PVBharadwaj** [comment]
In the main index file, the closing tag of the unordered list </ul> was not there (Please check line no. 264 in the main index.html file). So, the changes I am making in the styles.css page are not showing correct results. Can I add that line(</ul> in line no.264 in the main index.html file) to the main index file? Please let me know @Arun9739

**Comment by kunjgit** [comment]
Thank you  @PVBharadwaj , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
