### PR TITLE
enhanced black jack

### LINKED ISSUE #2221: [Enhancement]: Enchance blackjack game
### Is your enhancement request related to a problem? Please describe.➕

Center the game screen right now it is stuck at the top looking very bad.Some other small cosmetic changes

### Describe the solution you'd like

Will use HTML CSS and JS to achieve same

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by whiteknight16**
## PR Description 📜
Aligned the game screen properly and some cosmetic changes too
Fixes #2221 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @whiteknight16 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by whiteknight16** [comment]
@kunjgit

**Comment by kunjgit** [comment]
you need to make significant changes to get the enhancement done on the game !!

**Comment by kunjgit** [comment]
Thank you  @whiteknight16 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by daccdacc** [comment]
Hello @whiteknight16 , It's not having significant changes in it to be considered for level2, please add some more cool features 😇 !

**Comment by whiteknight16** [comment]
Ok 😃

**Pull request closed without merging**
