### PR TITLE
Fixed Readme Contribution game table

### LINKED ISSUE #4664: [Documentation Bug]: Fix README table with game folder links
### Describe the bug ✍️

Describe your bug here
### Tables with folder link to games is messed up by everyone. Check the screenshots attached.
<br><br>
## Screenshot1:
image
<br>
<br>
## Screenshot2:
image

### Provide step by step information reproduce the bug 📄

I want to organize the readme's table which contains folder link to the games.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### Provide step by step information reproduce the bug 📄

Description

Organizing readme's table with game folder links

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by vansh-codes**
## PR Description 📜
FIXED README TABLE WITH GAME FOLDER LINKS
Please review and let me know more changes needed.

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #4664 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @vansh-codes ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by vansh-codes** [comment]
@ishita-43 Its a readme fix pull request, and i guess that's why its telling to resolve conflicts.
Please review and let me know if any changes needed.

**Comment by kunjgit** [comment]
Thank you  @vansh-codes , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by vansh-codes** [comment]
@ishita-43 Hey Ishita! Please review my PR as it is a readme fix PR.

**Comment by ishita-43** [comment]
Please resolve merge conflicts after that it will get merged it may be arising due to deletion of entry or duplication of entry please make sure your file is in sync with the latest changes

**Comment by kunjgit** [comment]
Thank you  @vansh-codes , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
