### PR TITLE
Fixed the Footer

### LINKED ISSUE #2788: [Bug]: Fixing the footer
### Give a brief about the bug ✍️

Description

There is a gap between the waves and the footer and in that gap is the link to kunj's twitter and to the left of the gap some icons appear.

I would like to fix it under GSSoC'23!!

Preview:

image

### What is the expected behavior? 🤔

Description

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by 5h0ov**
## PR Description 📜
I have fixed the footer which was showing the socials in a gap between wave and the footer.

# Preview
image

Fixes #2788 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
See Above

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @5h0ov ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by gurjeetsinghvirdee** [comment]
Don't you think this gap created by you only & now removing the gap as bug in the sake of points this is not a open source contribution, you are just wasting your time doin this 
what you think you get from top 100 ranking 
- [X] Swags
- [X] Certificates 
- [] Internships I don't think so

**Comment by kunjgit** [comment]
Thank you  @5h0ov , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by 5h0ov** [comment]
> Don't you think this gap created by you only & now removing the gap as bug in the sake of points this is not a open source contribution, you are just wasting your time doin this 
> what you think you get from top 100 ranking 
> - [X] Swags
> - [X] Certificates 
> - [] Internships I don't think so 

but i dont remember making that gap? lemme check once

**Comment by 5h0ov** [comment]
> Don't you think this gap created by you only & now removing the gap as bug in the sake of points this is not a open source contribution, you are just wasting your time doin this what you think you get from top 100 ranking
> 
> * [x]  Swags
> * [x]  Certificates
> * [] Internships I don't think so

image

I removed those lines to fix the gap and those lines weren't add by me as shown in the picture! :(

**Comment by kunjgit** [comment]
Thank you  @5h0ov , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
