### PR TITLE
[Enhancement]: Would u like to add favicon to Touch-No-Fire Game?

### LINKED ISSUE #3973: [Enhancement]: Would u like to add favicon to Touch-No-Fire Game?
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
Would like to add favicon image to Touch-No-Fire-Game

### Describe the solution you'd like

Solution steps
image

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Anjaliavv51**
issue #3973

## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below

Updated the Logo of Touch-No-Fire-Game.

Fixes #3973 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@kunjgit please review the PR

**Comment by Anjaliavv51** [comment]
@kunjgit please review the PR

**Comment by Anjaliavv51** [comment]
@kunjgit

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Anjaliavv51 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
