### PR TITLE
Added Astray

### LINKED ISSUE #2081: [New game]: Astray
### 🎮 Game Request

Astray is a 3D Adventure Game in which you have to move the ball inside the Maze and get out of it to reach the destination and win the game.

### Point down the features

Visuals: The game is presented in a 3D graphical environment, allowing players to experience immersive gameplay.
Controls: The controls are designed to provide a responsive and intuitive way for players to maneuver the ball through the maze.
Obstacles and Challenges: The maze may contain obstacles such as walls, moving platforms, gaps, locked doors, and other puzzles that require the player to solve them to progress.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by linga66**
## PR Description 📜

Added Astray game
Fixes #2081 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Astray

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @linga66 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by gurjeetsinghvirdee** [comment]
Resolve the conflicst @linga66

**Comment by linga66** [comment]
> Resolve the conflicst @linga66 

I have made the changes @gurjeetsinghvirdee !

**Review by gurjeetsinghvirdee — COMMENTED** [review]
**Copied from here: https://github.com/wwwtyro/Astray
Live: https://wwwtyro.github.io/Astray/**

**Comment by kunjgit** [comment]
Thank you  @linga66 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
