### PR TITLE
8 Puzzle Game

### LINKED ISSUE #4223: [New game]: 8 PUZZLE
### 🎮 Game Request

Game logic and basic description
Game Request:
 8 Puzzle Game
 
Description

The 8 Puzzle Game is a classic sliding puzzle game developed in JavaScript. The game consists of a 3x3 grid with eight numbered tiles and one empty space. The objective is to arrange the tiles in numerical order by sliding them into the empty space.

Features:

2D Graphics: Simple and clean 2D interface.
Player Controls: Click or tap to move tiles into the empty space.
Randomized Start: Tiles start in a random order to ensure each game is unique.
Tile Sliding: Smooth sliding animations for tiles.
Move Counter: Tracks the number of moves made by the player.
Timer: Optional timer to track how long it takes to solve the puzzle.
Hint System: Provides hints or solutions if the player gets stuck.
Reset and Shuffle: Options to reset the puzzle or shuffle for a new challenge.
Sound Effects: Simple sound effects for tile movements.
Victory Screen: Celebratory message or animation upon solving the puzzle.

### Point down the features

Game points

Objective: Arrange the tiles in numerical order (1-8) with the empty space in the bottom-right corner.
Moves: Use the minimum number of moves to solve the puzzle.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by katarianikita2003**
\*Added 8 puzzle game*/

## PR Description 📜
gssoc'24 level 3

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #4223 
#4226 
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

game zone

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @katarianikita2003,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @katarianikita2003,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by katarianikita2003** [comment]
Heyy @kunjgit , I have added readme.md file

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @katarianikita2003,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.

Hoping that you will make those changes soon 🚀

**Comment by katarianikita2003** [comment]
I have modified main readme.md file

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @katarianikita2003,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by katarianikita2003** [comment]
Hello @kunjgit , please review my contribution

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @katarianikita2003,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by katarianikita2003** [comment]
Heyy @kunjgit , I added new game - Snake Game

**Comment by katarianikita2003** [comment]
Hey @kunjgit , Can you please review it?

**Comment by katarianikita2003** [comment]
> Hello @katarianikita2003, You need to make the following changes:
> 
> * Please add a README.md file inside the newly created folder.
> 
> Hoping that you will make those changes soon 🚀

I have already added readme.md file in newly created folder games/8_Puzzle

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @katarianikita2003,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by katarianikita2003** [comment]
Please consider 
[ce3367c](https://github.com/kunjgit/GameZone/pull/4243/commits/ce3367ce7c55991768446ddd9b849e4b12f103fb)
under new full request

**Comment by katarianikita2003** [comment]
Catch the Falling Objects Game is a browser-based game where players use a basket to catch objects falling from above. Move the basket using your mouse to catch the falling objects. Each caught object earns a point, while missed objects result in a loss of life. The goal is to score as high as possible before running out of lives.

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @katarianikita2003,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @katarianikita2003,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @katarianikita2003,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by kunjgit** [comment]
Thank you  @katarianikita2003 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @katarianikita2003,
You need to make the following changes:
  - Please create a new folder inside the "Games" folder.
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Pull request closed without merging**
