### PR TITLE
Mancala_Game 

### LINKED ISSUE #3136: [New game]: Mancala
### 🎮 Game Request

Game logic and basic descriptionMancala is a two-player board game that has been played for centuries across various cultures. The game typically consists of a wooden board with 12 small pits or cups, arranged in two rows, with a larger scoring pit at each end called the "mancala". Each player controls the six cups on their side of the board, and the goal is to collect the most stones or seeds in your mancala by the end of the game.

### Point down the features

Game points
Multiplayer modes
Engaging visuals and animations

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by manishh12**
## PR Description 📜

I have added a game called Mancala. This is a remake of the classic board game. This version features a user-friendly interface, strategic gameplay, and an engaging experience for players.
Fixes #3136 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @manishh12 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
@manishh12 add your game image in root director /assets so we can land your game on GameZone !

**Comment by manishh12** [comment]
@kunjgit i have done the changes as requested, kindly review it.

**Comment by kunjgit** [comment]
@manishh12 resolve the conflict !

**Comment by manishh12** [comment]
> @manishh12 resolve the conflict !

sorry for the inconvenience kindly check it now.

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @manishh12 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
