### PR TITLE
Added three games one is Fruit Cutting Game and second is MosquitoHitting and third NumberGuessingBySpeaking  .

### PR DESCRIPTION
**Pull request by ankit071105**
## PR Description 📜

# Mosquito-Whack
"Mosquito Whack" is an engaging and fast-paced game designed to test your reflexes and precision. The objective of the game is to swat as many mosquitoes as possible within a 30-second timeframe. Each successful hit awards points, while missing three mosquitoes results in game over. The game is complemented by lively background music and satisfying sound effects upon each successful hit, enhancing the overall gaming experience. 

# Fruit-Cutting
To enhance the fruit sliding game with background music and new cutting sound effects, we'll follow these steps:
Background Music Integration:
Choose or create a suitable background music track that complements the game's theme.
Implement the background music to play continuously during the game session.
Add controls for the player to mute or adjust the volume of the background music.
Cutting Sound Effects:
Select or create distinct sound effects for the fruit cutting action.
Ensure the sound effect is synchronized with the fruit cutting animation for a seamless experience.
Implement the sound effect to play each time a fruit is successfully cut by the player.

#  NumberGuessingBySpeaking 

The objective of the game is for the player to guess a randomly generated number within a specified range by speaking their guesses. The game provides feedback to help the player narrow down the correct number.
Example Scenario:
The game generates a random number between 1 and 100.
The player starts guessing by saying, "50."
The game responds with, "The number is higher."
The player then guesses, "75."
The game responds with, "The number is lower."
The player guesses, "63."
The game responds with, "Congratulations! You guessed the correct number."
The player is given the option to play again or choose a different difficulty level.
This game combines the fun of traditional number guessing games with modern speech recognition technology, providing an engaging and interactive experience for players.

<hr>
 
## Mark the task you have completed ✅
#4846  #4845 

## Add your screenshots(Optional) 📸

# Mosquito-Whack
https://github.com/user-attachments/assets/da9811c9-9c29-451b-b144-4ee5f24f34c3

# Fruit Cutting
https://github.com/user-attachments/assets/83042584-5ceb-42f5-bfd2-6012c1ba44b7

# NumberGuessingBySpeaking

Screenshot 2024-07-15 at 8 22 53 PM

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @ankit071105 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Thank you  @ankit071105 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by ankit071105** [comment]
#4847  Merged my PR . I request to merged my  pull request and add some interesting games for more fun by my PR

**Review by ishita-43 — COMMENTED** [review]
I recommend to make different pr for your different games in this way you only be helped by increasing number of points you can get from this repo . By adding more than one game in single pr i cant provide you a level higher than 3

**Comment by ankit071105** [comment]
> I recommend to make different pr for your different games in this way you only be helped by increasing number of points you can get from this repo . By adding more than one game in single pr i cant provide you a level higher than 3

I dont need a level higher than 3 if you wish you can give me  @ishita-43  you can give me lvl 2 also

**Comment by ankit071105** [comment]
Okay I am closing this pr onam regenerating a new pr for two games differently @ishita-43  thanks for helping me

**Comment by kunjgit** [comment]
Thank you  @ankit071105 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
