### PR TITLE
added all the required files

### PR DESCRIPTION
**Pull request by Babunshil**
## PR Description 📜

This is a web-based dice game created using HTML, CSS, and JavaScript. The objective of the game is to score as many points as possible by rolling two dice and accumulating points based on the number rolled. The game is designed to be played by two players, with each player taking turns to roll the dice. The game keeps track of the score, and the player with the highest score at the end of the game is declared the winner.
Fixes # <255>

<hr>
 
## Mark the task you have completed ✅

- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅ ] I have performed a self-review of my own code or work.
- [ ✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅  ] My changes generates no new warnings.
- [✅  ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅  ] I have added screenshot for website preview in assets/images 
- [✅  ] I have added entries for my game in main README.md
- [ ✅ ] I have added README.md in my folder 
- [ ✅ ] I have added working video of the game in README.md (optional)
- [✅  ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Dicee_Game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Babunshil ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Babunshil** [comment]
added the dicee game

**Comment by Arun9739** [comment]
@Babunshil add your game's entry into main README file. Also give a proper title to this PR.

**Comment by kunjgit** [comment]
Hey @Babunshil !!
we already have this game you can do enhancement

**Comment by kunjgit** [comment]
Thank you  @Babunshil , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
