### PR TITLE
[GSSoC'23] Cat Trap Game Completed

### LINKED ISSUE #2499: [New game]: Cat Trap Game
### 🎮 Game Request

Game logic and basic description

- This game is a single player game
- User will try entrap the cat inside a box
- If cat moves outside the box, user will lose the game

### Point down the features

Game points

- If user is able to entrap the cat inside the box and no move left for the cat, user will be the winner
- otherwise user loses the game

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## PR Description 📜
- This game is a beginner friendly game.
- This is a single player game.
- Entrap the cat and enjoy the game.

Fixes #2499 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Cat-Trap

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@kunjgit @Arun9739 @gurjeetsinghvirdee sir, please review this pull request

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Resolve Conflicts

**Comment by Avdhesh-Varshney** [comment]
@gurjeetsinghvirdee @kunjgit @Arun9739 sir, please again review my pull request

**Review by kunjgit — APPROVED** [review]

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Code copied from codepen: **https://codepen.io/mmede/full/gqwyMm**

**Comment by kunjgit** [comment]
Thank you  @Avdhesh-Varshney , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
