### PR TITLE
[New Game]:LifeMosaic

### LINKED ISSUE #4060: [New game]: Life’s Mosaic
### 🎮 Game Request

Game logic and basic description:
This basic logic forms the foundation of Life's Mosaic, allowing for the exploration of complex patterns and behaviors emerging from simple rules.The universe is an infinite, two-dimensional orthogonal grid of square cells.
Each cell can be in one of two states: ALIVE or DEAD.
Each cell interacts with its eight neighbors (horizontally, vertically, and diagonally adjacent cells).

Rules:
Underpopulation: Any live cell with fewer than two live neighbors dies.
Survival: Any live cell with two or three live neighbors lives on to the next generation.
Overpopulation: Any live cell with more than three live neighbors dies.
Reproduction: Any dead cell with exactly three live neighbors becomes a live cell.

### Point down the features

Controls: Play, Pause, Fast Forward, Slow Down, Clear, Random
Preset patterns (e.g., Glider, Gosper Glider Gun)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by PallaviGudupallavi**
## PR Description 📜
This PR is about a new game - 'Life's Mosaic'. In this game players create initial configurations and observe their evolution. This zero-player game is Turing complete and simulates complex patterns through simple rules on an infinite grid.

Fixes #4060 

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [ ✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅] I have added screenshot for website preview in assets/images 
- [✅ ] I have added entries for my game in main README.md
- [✅ ] I have added README.md in my folder 
- [x ] I have added working video of the game in README.md (optional)
- [ ✅] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @PallaviGudupallavi ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @PallaviGudupallavi,
You need to make the following changes:
  - Please create a new folder inside the "Games" folder.
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Please make sure add your game files and visible in your pr 
Also add your game image in asset folder and update main readme.md file

**Comment by kunjgit** [comment]
Thank you  @PallaviGudupallavi , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by PallaviGudupallavi** [comment]
@kunjgit in the previous PRs #4943 and #4152 i havent added the Readme.md file ..so i made a New PR #5060 ...Please review it...If any issues i can close all the PR's and raise a new one again.

**Comment by kunjgit** [comment]
Thank you  @PallaviGudupallavi , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
