### PR TITLE
Added Anagram-word-game

### LINKED ISSUE #4184: [New game]: Anagram Word Game
### 🎮 Game Request

Setup
    - Select a list of words (word bank).
    - Randomly pick a word from the word bank.
    - Scramble the letters of the chosen word to create a puzzle.

End Game
    - Once the player guesses the word correctly or chooses to give up, reveal the correct word.
    - Optionally, move to the next word or end the game.

### Point down the features

1. **Gameplay**:
    - Display the scrambled word to the player.
    - Allow the player to guess the original word.
    - Provide an input method for the player to submit their guess.
    - Check if the guess is correct:
        - If correct, notify the player of their success.
        - If incorrect, allow the player to guess again or provide a hint option.
        
2. **Scoring (Optional)**:
    - Track the number of attempts taken to guess the word.
    - Award points based on the number of attempts (fewer attempts yield more points).

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by manishh12**
## PR Description 📜

Anagram Word Game is an engaging web-based game where players are challenged to unscramble a given set of letters to form a correct word. This game is designed to test and enhance players' vocabulary and cognitive skills in a fun and interactive way, providing an enjoyable gaming experience for all ages.

Fixes #4184 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @manishh12 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by manishh12** [comment]
@kunjgit kindly Review this PR and merge it .I am not able to take any other issue because of this .

**Comment by manishh12** [comment]
@kunjgit Reminder !!

**Comment by kunjgit** [comment]
Thank you  @manishh12 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
