### PR TITLE
Added home button in whack a mole game

### LINKED ISSUE #4043: [Enhancement]: ADDING A HOME BUTTON IN WHACK A MOLE GAME
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
THERE SHOULD BE A HOME BUTTON IN WHACK A MOLE GAME

### Describe the solution you'd like

Solution steps
I WILL ADD A HOME BUTTON IN WHACK A MOLE GAME

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by TusharChamlikar**
## PR Description 📜

Fixes #4043 
Now the user can easily go to home page by just clicking on home button.
Screenshot 2024-06-01 135327

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @TusharChamlikar ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by TusharChamlikar** [comment]
plz merge my request

**Comment by TusharChamlikar** [comment]
plz merge my request @kunjgit sir.

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @TusharChamlikar , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
