### PR TITLE
Solved issue #4137- Quantum Maze

### LINKED ISSUE #4137: [New game]: Quantum Maze
### 🎮 Game Request

Game logic and basic description
"Quantum Maze" that involves navigating through a maze with quantum mechanics principles, including superposition and entanglement.

### Point down the features

Game points
Gameplay Features:

Quantum Walls: Walls that can exist in multiple states simultaneously. Players must collapse these walls by observing them to determine if they are passable.
Entangled Paths: Certain paths are entangled, meaning if you choose one path, the corresponding entangled path changes as well.
Superposition Gates: Gates that require the player to be in two places at once, achieved by splitting the player's state.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
## PR Description 📜

This game is a fun and challenging way to test your problem-solving skills by navigating through a maze with quantum mechanics-inspired rules.

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes # <your_issue_number>
Fixes #4137 
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Quantum_Maze
Quantum_Maze1

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Aditi22Bansal ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Aditi22Bansal** [comment]
@ishita-43 
@kunjgit 
Kindly review and merge the above PR

**Comment by kunjgit** [comment]
Hey @Aditi22Bansal, You have reached your limit to contribute in GameZone with a score of 250. 
 We believe in giving equal opportunity to everyone so you will not be able to contribute to GameZone now onwards. 💗 
 Thank you for your valuable time and contribution in GameZone 🕹️! 

 Your merged pull requests:
- [#4351](https://github.com/kunjgit/GameZone/pull/4351) with labels: level3 score: (45)
- [#3978](https://github.com/kunjgit/GameZone/pull/3978) with labels: level3 score: (45)
- [#3863](https://github.com/kunjgit/GameZone/pull/3863) with labels: level3 score: (45)
- [#3686](https://github.com/kunjgit/GameZone/pull/3686) with labels: level3 score: (45)
- [#3631](https://github.com/kunjgit/GameZone/pull/3631) with labels: level3 score: (45)
- [#3580](https://github.com/kunjgit/GameZone/pull/3580) with labels: level2 score: (25)

**Comment by kunjgit** [comment]
Thank you  @Aditi22Bansal , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
