### PR TITLE
Added Tower Block game

### LINKED ISSUE #4432: [New game]: Tower Block Game
### 🎮 Game Request

Game logic and basic description

In this game There blocks will be comming and you need to place one on another

### Point down the features

Game points
1)Blocks of same size comes You need to place
2)If we cant place correctly then the block breaks down 
3)You need to play the game with the space bar

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
## PR Description 📜

Added Tower Block Game 

Fixes #4432 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Tower_Block_Game

--- 
<br>

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Saipradyumnagoud ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by Saipradyumnagoud — COMMENTED** [review]
Solved The merge conflict also

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by Saipradyumnagoud** [comment]
> Good to go!!

its level 3 labeled

**Comment by ishita-43** [comment]
In beginning label are assigned automatically later we decide final label at the time of reviewing.We add label based on new feature added as we already have group of games with same functionality we labeled this pr as level 2.

**Comment by Saipradyumnagoud** [comment]
> pr as leve

but the game is different

**Comment by ishita-43** [comment]
> > pr as leve
> 
> but the game is different

Thats why we did not put this into plagiarism label

**Comment by Saipradyumnagoud** [comment]
> > > pr as leve
> > 
> > but the game is different
> 
> Thats why we did not put this into plagiarism label 

okayy done

**Comment by kunjgit** [comment]
Thank you  @Saipradyumnagoud , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
