### PR TITLE
New Game Steam punk

### LINKED ISSUE #3994: [New game]: Steam Punk
### 🎮 Game Request

Game logic and basic description
Steampunk is a game where the user fights off the aliens. 

### Point down the features

Game points
Points calculation 
Entrailing UI
Good Graphics

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Archiesachin**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #3994 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot (1044)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Archiesachin ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Archiesachin** [comment]
Hello @kunjgit please look into the PR.

**Comment by Archiesachin** [comment]
@kunjgit Please kindly review the PR since i don't have the option to resolve conflicts. Also don't forget to add the gssoc and level labels.

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Please follow contribution guidelines while naming images in asset folder.

**Comment by Archiesachin** [comment]
> Please follow contribution guidelines while naming images in asset folder.

I have named the thumbnail image as per the naming conventions (The image name is same as the folder name of my game)

**Comment by Archiesachin** [comment]
@ishita-43 @kunjgit please check the PR and merge it. I have followed all the naming conventions as well.

**Comment by ishita-43** [comment]
The name of images in assest folder should be same as name of the game!!

**Comment by Archiesachin** [comment]
> The name of images in assest folder should be same as name of the game!!



This image is not added by me... these image is due to the conflicts... I can't resolve them, only with write access can resolve the conflicts. 



Screenshot (1069)




I have added the image of my game in the assets folder same as my game name 



Screenshot (1070)

**Comment by Archiesachin** [comment]
@kunjgit  @ishita-43 can you please look into the changes that you requested. I have clarified the changes. Can you please merge the PR.

**Comment by Archiesachin** [comment]
@ishita-43 please review my PR

**Review by ishita-43 — APPROVED** [review]
Seems good!!

**Comment by kunjgit** [comment]
@Archiesachin resolve the merge conflicts !

**Comment by Archiesachin** [comment]
> @Archiesachin resolve the merge conflicts !
Screenshot_2024-06-11-16-16-12-44_40deb401b9ffe8e1df2f1cc5ba480b12



I don't have access to resolve the conflicts.

**Comment by kunjgit** [comment]
@Archiesachin resolve merge conflicts

**Comment by Archiesachin** [comment]
> @Archiesachin resolve merge conflicts

Give me access to resolve the conflicts. Only people with "write access" can resolve it. The resolve conflict button is disabled for me!

**Comment by ishita-43** [comment]
Hey do one thing close this pr and raise another on same issue with clear code make sure that this image doesnt show up there you can do so by again forking the repo and syncing the repo with latest changes !!

**Comment by Archiesachin** [comment]
> Hey do one thing close this pr and raise another on same issue with clear code make sure that this image doesnt show up there you can do so by again forking the repo and syncing the repo with latest changes !!

okayy

**Comment by kunjgit** [comment]
Thank you  @Archiesachin , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
