### PR TITLE
New game: Aero_Acrobat [gssoc23]

### LINKED ISSUE #1945: [New game]: Aero Acrobat [gssoc23]
### 🎮 Game Request

Game logic and basic description: "Aero Acrobat" is an exhilarating arcade-style game that challenges players to navigate a courageous boy through a breathtaking ascent into the sky. With the help of the spacebar and four arrow keys, players must guide the boy upwards, maneuvering through a maze of obstacles and platforms.

### Point down the features

Game points: The goal is simple: reach new heights and accumulate as many points as possible. Each successful ascent grants the player points, while collisions with obstacles result in penalties. With each passing level, the speed and difficulty increase, putting the player's skills to the test.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by thevirengarg**
## PR Description 📜
(NEW GAME)
Game logic and basic description: "Aero Acrobat" is an exhilarating arcade-style game that challenges players to navigate a courageous boy through a breathtaking ascent into the sky. With the help of the spacebar and four arrow keys, players must guide the boy upwards, maneuvering through a maze of obstacles and platforms. The goal is simple: reach new heights and accumulate as many points as possible. Each successful ascent grants the player points, while collisions with obstacles result in penalties. With each passing level, the speed and difficulty increase, putting the player's skills to the test.

Fixes #1945 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot (247)

https://github.com/kunjgit/GameZone/assets/111726483/e9fd5108-9d14-4ce9-9804-3667711f7023

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @thevirengarg ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @thevirengarg,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by thevirengarg** [comment]
@kunjgit I have already added README file in newly created folder of the game

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @thevirengarg , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Hey @thevirengarg,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by thevirengarg** [comment]
@kunjgit Please add the tag of gssoc23 and level3

**Comment by thevirengarg** [comment]
@Arun9739 @raju-kumar21 Please add the level tag and gssoc23 tag to this PR

**Pull request merged**
