### PR TITLE
8_puzzle

### PR DESCRIPTION
**Pull request by manikumarreddyu**
8_puzzle

Fixes : #4223 

I have fixed the issue #4223.
Added new game

<hr>
 
## Mark the task you have completed ✅

- [✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅] My changes generates no new warnings.
- [✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅] I have added screenshot for website preview in assets/images 
- [✅] I have added entries for my game in main README.md
- [✅] I have added README.md in my folder 

- [✅] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @manikumarreddyu ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @manikumarreddyu,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by manikumarreddyu** [comment]
i have created readme.md file in my folder..check it once

**Comment by manikumarreddyu** [comment]
In my opinion ,the bot which you hace created is not working fine..
it is my kind request to you that..make some edits to bot..

**Comment by manikumarreddyu** [comment]
Hey @kunjgit check it once

**Comment by manikumarreddyu** [comment]
hello @ishita-43  can you check it once

**Comment by manikumarreddyu** [comment]
hello @kunjgit  can you please check it once ..

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @manikumarreddyu,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by kunjgit** [comment]
Thank you  @manikumarreddyu , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @manikumarreddyu,
You need to make the following changes:
  - Please create a new folder inside the "Games" folder.
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Pull request closed without merging**
