### PR TITLE
new game : dinosaur memory game added

### LINKED ISSUE #3244: [New game]: . Dinosaur Memory Game
### 🎮 Game Request

Dinosaur Memory Game is a classic memory game with a twist! Players will be presented with a grid of facedown cards featuring dinosaurs related images. Clicking on a card will reveal the image. The objective is to find matching pairs by flipping over two cards at a time.

### Point down the features

 - If the cards match, the player scores a point and a fun dinosaur sound effect plays. 
 - If the cards don't match, they are flipped back over, and the player tries again.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by shellygarg10**
## PR Description 📜
Dinosaur Memory Game is a classic memory game with a twist! Players will be presented with a grid of facedown cards featuring dinosaurs related images. Clicking on a card will reveal the image. The objective is to find matching pairs by flipping over two cards at a time.
Fixes #3244

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2024-05-13 194114

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @shellygarg10 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by shellygarg10** [comment]
Hi @kunjgit , Just checking in to see if you have a chance to review my pull request. The pull request seems to have passed all checks. Is there anything else I need to do before it can be merged?

**Comment by kunjgit** [comment]
@shellygarg10 make sure you are adding your game in main readme file !

**Comment by shellygarg10** [comment]
@kunjgit i have updated the readme file please check

**Review by kunjgit — CHANGES_REQUESTED** [review]
@shellygarg10 add image in assets !

**Comment by shellygarg10** [comment]
@kunjgit updated the assets as well

**Comment by kunjgit** [comment]
@shellygarg10 in root of repository there is readme file that keeps track of all the games there on GameZone there you have to add that entry !
please try to read documentation properly !

**Comment by shellygarg10** [comment]
hi @kunjgit ! I've carefully reviewed the README file and resolved any conflicts with the base branch. The updated version should merge cleanly. Please take a look at the changes and let me know if you have any questions. This is my first time contributing to an open-source project, so I'm sorry for not being able to do it as required initially but I appreciate your patience!

**Review by kunjgit — APPROVED** [review]
LGTM!

**Comment by kunjgit** [comment]
Thank you  @shellygarg10 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by shellygarg10** [comment]
@kunjgit @ishita-43 my leaderboard points for this PR has been removed , what is the issue ?

**Pull request merged**
