### PR TITLE
Random Colour Generator

### LINKED ISSUE #3352: [New game]: Colour_Generator
### 🎮 Game Request

This new innovative game named as Colour_Generator, aimed to be generate a new version of colours at every time. I am developed this code using html, css, javascript. So , coming to the point , firstly open the web and it shows you some random versions of colours , and colour naming codes are also available near that certain colour , what there mentioned . These colours are changed after every refreshing process. So , the advantage of this game is to gain best version of colours which are useful for build some certain web pages, mainly in css applications. So this is the main motive of this game , and logic is mentioned as above. Thank You!!!

### Point down the features

This game points  are 10 out of 10 , because it is not a joy game , it is most required game for developers
Screenshot 2024-05-16 211529
Look this.... you may got a general idea about this project

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Yashgabani845**
## PR Description 📜

Randoom colour generator added
html,css,js and readme file added 
it is very simple project it generate random colours and their 6 digit hexdadecimal code ad print it 

Fixes #3352 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot (230)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Yashgabani845 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
@Yashgabani845 resolve merge conflicts

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Yashgabani845 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by sanjay-kv** [comment]
@kunjgit  I need access to your repo , i have communicated via email multiple times.

**Comment by Yashgabani845** [comment]
@sanjay-kv 
sir i think @ishita-43 can help you on this 
becuase she can change labels of PR and she is mentor of this repo .
i realises these cotributions are not matching level of other full stack project repos after working on them 
i'm also regretting about these contribution i also wasted my time on repetetive teak rather than upgrading my skills and dive and contribute in MERN and full stack web project
i would be happy to limit these points and maintain quality of program
thank you for this guidelines

**Comment by Yashgabani845** [comment]
@sanjay-kv also he is repling on discord frequntly so you can connect with him there too

**Pull request merged**
