### PR TITLE
[NEW GAME]: Cat Play added

### LINKED ISSUE #737: [New game]:  Cat play
### 🎮 Game Request

An instrument play application on which you can play various music instruments using keyboard keys.
Screenshot 2023-06-02 211515
Live Demo(https://iiitian-cat.netlify.app/)

### Point down the features

Using this app you can play cowbell, tabla, bongo, cymbal, piano and marimba using keyboard keys.
For example, you can play piano using the number keys from 1 to 0.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Ayush2966**
#737 issue under which new game cat play has been added
Fixes #737

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Screenshot 2023-06-02 211515

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Ayush2966 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@Ayush2966 Make entry of your game into main README file.

**Comment by Ayush2966** [comment]
> @Ayush2966 Make entry of your game into main README file.

@Arun9739 I have made some changes, please check

**Comment by Ayush2966** [comment]
> @Ayush2966 You have not yet made the entry into main README file.

Please check,I have done the required changes

**Comment by kunjgit** [comment]
Thank you  @Ayush2966 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
