### PR TITLE
Added Progress Bar to Scroll To Top & Minor Changes

### LINKED ISSUE #2357: [Enhancement]: Adding a circle of progress to Scroll To Top Button & Minor Fixes
### Is your enhancement request related to a problem? Please describe.➕

# Website enhancement

- I would like to add a circular progress bar wrapping the scroll to top button. I would also animate it so that when the user hovers over the button it enlarges.
- I would also like to make the Next/Back buttons take the user to the top of the webpage on clicking.
- I will look for other minor fixes while i work on this

# Short Preview of The Progress Bar Concept:
scrollbutton

### Describe the solution you'd like

Solution steps
 Stated Above

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by 5h0ov**
## PR Description 📜
- Added a progress bar to the Scroll To Top Button(For reference see attached GIFs below)
- Made it so that when user clicks Next and Previous buttons it takes them to the top of the website again smoothly.
- Made the search input field wider for easier accesibility.
- Added separate css and js files for the scroll to top button

Fixes #2357 

<hr>
 
# Add your screenshots(Optional) 📸

## Scroll To Top Button:
scrollgz

## Next & Previous:
next

## Search Input Field:
searchcont

<hr>
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @5h0ov ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by 5h0ov** [comment]
i have fixed the conflicts could you kindly review the PR @gurjeetsinghvirdee

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM 🌸

**Comment by kunjgit** [comment]
Thank you  @5h0ov , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by 5h0ov** [comment]
@gurjeetsinghvirdee  sir could you kindly tell me the exact reason in detail why will this pr become invalid? it would help me clarify better what isnt allowed then.

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee sir could you kindly tell me the exact reason in detail why will this pr become invalid? it would help me clarify better what isnt allowed then.
> 
> A scroll up button is a feature in many projects

if you make same PR again & again that would be spammy but if you change the code it would be acceptable like you can change the design of the button according to their Project UI so it will be a valid PR

**Comment by 5h0ov** [comment]
> > @gurjeetsinghvirdee sir could you kindly tell me the exact reason in detail why will this pr become invalid? it would help me clarify better what isnt allowed then.
> > A scroll up button is a feature in many projects
> 
> if you make same PR again & again that would be spammy or duplicate that thing also mentioned in server rules you can check that, but if you change the code it would be acceptable like you can change the design of the button according to their Project UI so it will be a valid PR

i will keep it in mind for next time then

**Comment by 5h0ov** [comment]
thanks 😀

**Pull request merged**
