### PR TITLE
Issue 738

### LINKED ISSUE #738: [New game]: Retro Dungeon Puzzle
### 🎮 Game Request

The Retro Dungeon Maze Puzzle game is a thrilling and immersive experience that transports players back to the enchanting world of classic video games. With its pixelated graphics and nostalgic atmosphere, this game captures the essence of retro gaming.

The Retro Dungeon Maze Puzzle game features a set of game logic that governs the mechanics and rules of the gameplay. Here's a high-level overview of the game logic:

>Maze Generation: The game generates random mazes with walls, corridors, and various obstacles using algorithms like depth-first search or recursive backtracking.

>Player Movement: The player can move in four directions (up, down, left, and right) using touch controls. The game ensures that the player stays within the boundaries of the maze and cannot move through walls.

>Objectives: The primary objective of the game is to find the exit of each maze and progress to the next level. To achieve this, the player may need to collect keys or other items scattered throughout the maze.

>Collisions and Interactions: The game checks for collisions between the player and the obstacle.

### Point down the features

Here are the features of the Retro Dungeon Maze Puzzle game:

> Randomly generated mazes with walls, corridors, and obstacles

> Player movement in four directions (up, down, left, and right)

> Objectives to find the exit of each maze and progress to the next level

> Collection of keys and other items scattered throughout the maze

> Collisions with enemies to avoid.

>Game over conditions for losing and victory conditions for winning

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by MisterMickey**
## PR Description 📜

This PR adds a new game Retro_Dungeon_Puzzle.
Fixes #738 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed the proper naming convention shown in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added a screenshot for website preview in assets/images 
- [x] I have added entries for my game in the main README.md
- [x] I have added README.md to my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @MisterMickey ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@MisterMickey Add screenshot of your game. Also add * in place of a number in main README file.

**Comment by MisterMickey** [comment]
@Arun9739 Done!

**Comment by MisterMickey** [comment]
Screenshot from 2023-06-04 22-20-06
Screenshot from 2023-06-04 22-20-09

Screenshot from 2023-06-04 22-20-11
Screenshot from 2023-06-04 22-20-14
Screenshot from 2023-06-04 22-20-21
de02-1abd-41fc-8f8a-050de87608ea)

**Comment by Arun9739** [comment]
@MisterMickey LGTM

**Comment by kunjgit** [comment]
you have to make changes of one game only in a PR it is having other folder as well so remove that and create PR again !!! 👀

**Comment by kunjgit** [comment]
Thank you  @MisterMickey , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
