### PR TITLE
Add Bow Arrow Game

### LINKED ISSUE #223: [New game]: BOW-AND-ARROW GAME
### 🎮 Game Request

This is a BOW-AND ARROW GAME made using HTML , CSS and JAVASCRIPT.

**Objective is to shoot monsters and save birds.**
1.Move the man with "arrow keys".
2.Shoot arrow with "space bar".

### Point down the features

**Can Shoot in both the directions(L/R).**

  +1 for hitting monster.

  -5 if monster reaches birds.

Game Over if score<0.

Monsters speed increases each level.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Roshnijeewani3457**
## PR Description 📜
I have Added an new game called Bow_Arrow Game that I have implemented using HTML,CSS and Javascript.I have Added
my game folder to the Games folder and added the game screenshot to the images folder in assests. I have also update the main Readme.md file.
Fixes #223 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Roshnijeewani3457 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
don't add your all images in main repo assets 
just add one good screenshot of game !!

**Comment by Roshnijeewani3457** [comment]
@kunjgit Please review my PR again . I have made the above changes as mentioned.

**Review by kunjgit — APPROVED** [review]

**Review by kunjgit — CHANGES_REQUESTED** [review]
add your game entry in main README properly

**Review by kunjgit — CHANGES_REQUESTED** [review]
add your game entry in main README properly

**Comment by Roshnijeewani3457** [comment]
@kunjgit please review my PR again .I have resolved above problem mentioned

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Hey @Roshnijeewani3457,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by kunjgit** [comment]
Thank you  @Roshnijeewani3457 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by kunjgit** [comment]
Thank you  @Roshnijeewani3457 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
