### PR TITLE
added new game

### LINKED ISSUE #189: [New game]:  Menja
### 🎮 Game Request

Game logic and basic description
This game is similar to fruit ninja game , where instead of fruits it will be cubes and mouse will be acting as a knife to split the cubes into smaller cubes , and this will continue till you will be cutting those cubes , and after game finishes it will show you the highest score and the current score . 

### Point down the features

Game points
Number of cubes smashed 
Two modes to play the game ( Normal game and casual mode )
in casual mode game will not end , in normal game there will be scores 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by SALONI-AGGARWAL0304**
I have added new game , Menja

## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #189

<hr>
 
## Mark the task you have completed ✅

- [ x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.

- [x ] My changes generates no new warnings.
- [ x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ x] I have added screenshot for website preview in assets/images 
- [x ] I have added README.md in my folder 
- [x ] I have specified the respective issue number for which I have requested the new game.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @SALONI-AGGARWAL0304 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hey !
Just make sure the image you are adding in asset would be used as thumbnail of your game on GameZone so make sure you add some catchy image !
Don't alter main index file and add your game entry with * number in README games section 👀

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Hey @SALONI-AGGARWAL0304 just make sure you don't alter other parts of main README just add your game entry in that and then your PR is ready to merge please make that changes 👀

**Review by kunjgit — CHANGES_REQUESTED** [review]
make the changes mentioned in comment

**Comment by SALONI-AGGARWAL0304** [comment]
made changes

**Comment by kunjgit** [comment]
you are not resolving the conflicts please create new PR and follow proper guideline !! 
we will merge once you will create new PR

**Pull request closed without merging**
