### PR TITLE
Update README.md

### LINKED ISSUE #757: [Documentation Bug]: same game
### Describe the bug ✍️

Describe your bug here
Games 66 ie tower block and 74 ie stack game are same only the name is different ..
Both need to form a tower with the help of blocks.

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by SimranLahrani842**
## PR Description 📜

Duplicate games in readme.md
Fixes #757 

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @SimranLahrani842 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@SimranLahrani842 LGTM

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 LGTM

Resolved merge conflicts please merge my PR.

**Comment by kunjgit** [comment]
we have to keep both on the GameZone 👀 !!!

**Comment by kunjgit** [comment]
Thank you  @SimranLahrani842 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
