### PR TITLE
New Game Contra-Shooter Added

### LINKED ISSUE #3505: [New game]: Contra
### 🎮 Game Request

Game logic and basic description

# Contra

## Overview

Contra is a classic side-scrolling action game developed and published by Konami in 1987. It is known for its challenging gameplay, intense action, and iconic run-and-gun mechanics.

## Gameplay

In Contra, players take on the role of either Bill Rizer or Lance Bean, highly skilled commandos tasked with infiltrating and defeating an alien invasion force known as the Red Falcon Organization. The game features fast-paced, run-and-gun gameplay where players must navigate through a series of side-scrolling levels, eliminating enemies and obstacles while avoiding hazards and powerful bosses.

The game's signature feature is the ability to execute a "Spread Shot", a devastating weapon that fires multiple projectiles in a wide arc, allowing players to mow down hordes of enemies with ease. Players can also collect various power-ups and weapon upgrades throughout the game to enhance their firepower and survivability.

## Legacy

Contra is considered a landmark in the run-and-gun genre and has had a lasting impact on video game history. It has spawned numerous sequels and spin-offs, and its influence can be seen in many modern action-packed games. The game's iconic status and challenging gameplay have made it a beloved classic for generations of gamers.

### Point down the features

Game points

## Key Features

- **Intense Action**: Contra is renowned for its lightning-fast and relentless action, with waves of enemies, challenging boss battles, and intricate level designs that test the player's reflexes and skill.

- **Iconic Weapons**: The "Spread Shot" is the game's most iconic weapon, allowing players to unleash a barrage of bullets and clear the screen of foes.

- **Co-op Gameplay**: Contra supports two-player co-op, allowing players to team up and tackle the alien threat together.

- **Challenging Difficulty**: Contra is known for its high level of difficulty, requiring players to master the game's mechanics and patterns to progress through the levels.

- **Memorable Soundtrack**: The game's driving, synth-heavy soundtrack, composed by Hidenori Maezawa and Takashi Yoshioka, is a cherished part of Contra's legacy.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by VesperAkshay**
## PR Description 📜

# Add New Game - Contra

## Description

I would like to propose adding the classic video game Contra to our project. Contra is an iconic run-and-gun action game that was first released by Konami in 1987. It has since become a beloved title in the gaming community.

The key features of the Contra implementation would be:

- Recreate the classic 2D side-scrolling gameplay where the player controls a commando who must fight their way through levels filled with enemies and obstacles.
- Implement the iconic Contra "Spread Shot" weapon that allows the player to shoot diagonally in addition to left/right.
- Include the famous "Konami code" cheat that grants the player 30 extra lives when entered.
- Faithfully recreate the level design, enemy patterns, and boss fights from the original arcade and NES versions of the game.
- Add support for 1 or 2 player cooperative gameplay.
- Ensure high-quality sound effects and chip-tune style music to match the retro aesthetic.

Adding Contra to our game library would be an excellent way to expand the selection of classic arcade-style titles available to our users. It is a true gaming classic that many players will enjoy revisiting or experiencing for the first time.

Please let me know if you have any other questions or need additional information. I'm excited about the prospect of bringing Contra to our platform!

Fixes #3505 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @VesperAkshay ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VesperAkshay,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VesperAkshay,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by VesperAkshay** [comment]
Please help me and tell where is the Error 
Main README.md is also updated and Image is also added in the directory

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VesperAkshay,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VesperAkshay,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @VesperAkshay,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by kunjgit** [comment]
@VesperAkshay resolve the conflicts !

**Comment by kunjgit** [comment]
Thank you  @VesperAkshay , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
