### PR TITLE
Added a licenses section and a MIT licenses badge 

### LINKED ISSUE #2402: [Documentation Bug]: Adding a small Licenses section to the readme and a MIT Licenses badge
### Describe the bug ✍️

The readme file of the repo should have a Licenses section to make it more professional.

### Provide step by step information reproduce the bug 📄

I can add a licenses section and a MIT License Badge to the readme

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by 1Shubham7**
## PR Description 📜

Added the Licenses section and MIT License badge to the readme.md

Fixes #2402 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @1Shubham7 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Can you re-check again, we are not using MIT License in this repo

**Comment by 1Shubham7** [comment]
sure @gurjeetsinghvirdee

**Comment by 1Shubham7** [comment]
@gurjeetsinghvirdee . Really sorry for the mistake, I corrected the License to Apache-2.0 License

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM 🌸

**Comment by 1Shubham7** [comment]
Thank you @gurjeetsinghvirdee

**Comment by kunjgit** [comment]
Thank you  @1Shubham7 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
