### PR TITLE
[New game]: Touch-No-Fire-Fame

### LINKED ISSUE #3727: [New game]: Touch-No-Fire-Fame
### 🎮 Game Request

Game logic and basic description
Game Rules!
* Eat the food to gain score
* Do not touch the fire
* The fire multiplies once with even scores
* If you stay idle, the fire won't do anything
* Do not touch the moving fire
* Please play using arrow keys

## Screenshot Section

image

## Demo Video Section

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/154777864/a88f676a-69c8-4cc9-b6e6-98e5fca1aa59

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Anjaliavv51**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #3727

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have added working video of the game in README.md (optional)
- [X] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

## Demo Video Section

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/154777864/a88f676a-69c8-4cc9-b6e6-98e5fca1aa59

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Anjaliavv51 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Anjaliavv51,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Anjaliavv51,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Anjaliavv51** [comment]
> Hello @Anjaliavv51, You need to make the following changes:
> 
> * Please add a README.md file inside the newly created folder.
> * Please modify the main README.md file.
> * Please add an image to the assets/images directory.
> 
> Hoping that you will make those changes soon 🚀

image

Readme.md file is already added please check

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Anjaliavv51,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Anjaliavv51,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Anjaliavv51,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by Anjaliavv51** [comment]
@kunjgit please check once

**Comment by Anjaliavv51** [comment]
image

Please check it is added

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Anjaliavv51,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by Anjaliavv51** [comment]
> Hello @Anjaliavv51, You need to make the following changes:
> 
> * Please add a README.md file inside the newly created folder.
> 
> Hoping that you will make those changes soon 🚀

it is added please check

**Comment by kunjgit** [comment]
@Anjaliavv51 resolve the merge conflicts !

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Anjaliavv51,
You need to make the following changes:
  - Please add a README.md file inside the newly created folder.

Hoping that you will make those changes soon 🚀

**Comment by Anjaliavv51** [comment]
@kunjgit please check it is added , conflicts are resolved

**Comment by Anjaliavv51** [comment]
> Hello @Anjaliavv51, You need to make the following changes:
> 
> * Please add a README.md file inside the newly created folder.
> 
> Hoping that you will make those changes soon 🚀

image

@kunjgit please check once

**Comment by manishh12** [comment]
> > Hello @Anjaliavv51, You need to make the following changes:
> > 
> > * Please add a README.md file inside the newly created folder.
> > 
> > Hoping that you will make those changes soon 🚀
> 
> image
> 
> @kunjgit please check once



@Anjaliavv51 Try renaming `Readme.md` to `README.md`.
image

**Comment by Anjaliavv51** [comment]
@kunjgit it is renamed

**Comment by Anjaliavv51** [comment]
@kunjgit please review the game.

**Comment by kunjgit** [comment]
@Anjaliavv51 resolve the merge conflicts !

**Comment by Anjaliavv51** [comment]
@kunjgit please review the game.Conflicts are resolved!

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Anjaliavv51 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by codewithishu** [comment]
@Anjaliavv51 I am also getting the same problem as I have already added readme.md to my file and all the conflicts are resolved instead he is asking to update REAdmE.md and assets.
How did you resolve help me out

**Pull request merged**
