### PR TITLE
Added Catch him game

### PR DESCRIPTION
**Pull request by Khushi-Pushkar**
Added #4715 
Kindly review and merge

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Khushi-Pushkar ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by nishant0708** [comment]
Hey @Khushi-Pushkar I am facing trouble in forking this repo it is showing something like path invalid of some folder can you tell me how you forked this repo

**Comment by Khushi-Pushkar** [comment]
Hey @nishant0708 . I was unable to clone the forked repository, so I made changes directly in the forked repository itself

**Comment by nishant0708** [comment]
Damm okk @Khushi-Pushkar thanks for helping

**Comment by Khushi-Pushkar** [comment]
@kunjgit pls review and merge

**Comment by Khushi-Pushkar** [comment]
@kunjgit pls review and merge

**Comment by Khushi-Pushkar** [comment]
@kunjgit pls review and merge

**Comment by Khushi-Pushkar** [comment]
@kunjgit @ishita-43 Kindly Review and merge

**Review by ishita-43 — CHANGES_REQUESTED** [review]
Please make the following changes 
add your game entry into main readme.md file follow other entries for the format 
add your game image into the asset folder of the gamezone follow contribution guidelines while naming the image

**Comment by kunjgit** [comment]
Thank you  @Khushi-Pushkar , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
