### PR TITLE
'Whack a Mole' Game Boxes Design Enhancement

### PR DESCRIPTION
**Pull request by iamRabia-N**
## PR Description 📜
This PR contains the updated code for 'Whack a Mole' game boxes design enhancement. This PR is the result of following issue:
'Whack a Mole' Game Boxes Design Enhancement #2334 
<hr>
 
## Mark the task you have completed ✅
- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
gamezone (2)

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @iamRabia-N ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by iamRabia-N** [comment]
@kunjgit Kindly review this PR.

**Comment by daccdacc** [comment]
Hey @iamRabia-N , Please make some more changes to get it the label of level2.

Looking for some cool changes from your side.

**Comment by iamRabia-N** [comment]
Hi @daccdacc 
Kindly review this updated design of the game. Share your review on this design. If this design is approved, I'll publish this design code in pull request.
**Screenshots**

gamezone (3)

Button design when it is hovered
gamezone (2)

Design while playing game
gamezone (1)

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
> Hi @daccdacc Kindly review this updated design of the game. Share your review on this design. If this design is approved, I'll publish this design code in pull request. **Screenshots**
> 
> gamezone (3)
> 
> Button design when it is hovered gamezone (2)
> 
> Design while playing game gamezone (1)

Yeah, it looks good.

**Comment by gurjeetsinghvirdee** [comment]
Yeah, it looks good. @iamRabia-N

**Comment by iamRabia-N** [comment]
@daccdacc @gurjeetsinghvirdee This design's code is in the latest commit with id "4166f3ee6a64e62e6e35c01f941c0bd3184cb927". Kindly review it. If you face any trouble, do let me know.

**Review by gurjeetsinghvirdee — APPROVED** [review]
Looks Good

**Comment by iamRabia-N** [comment]
@gurjeetsinghvirdee 

> Looks Good

Kindly merge it.

**Comment by kunjgit** [comment]
Thank you  @iamRabia-N , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
