### PR TITLE
Added required files #1753

### LINKED ISSUE #1753: [New game]: Quiz game with Request
### 🎮 Game Request

Game logic and basic description
In this game the users will be asked multiple questions with options and must choose the correct one within 15 seconds. then, the user score will be shown based on correct answers only.

### Point down the features

Game points this would be the simple on the basis of multiple choice questions

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by manshasinghal**
Added html,css and js files for my Quiz Game and a screenshot of my game
fixes #1753

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @manshasinghal ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by manshasinghal** [comment]
Add the required files

**Comment by kunjgit** [comment]
Hey @manshasinghal,
 You can't work on a closed issue 👀! 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by kunjgit** [comment]
Thank you  @manshasinghal , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
