### PR TITLE
Navigation bar is missing on the site. After adding the Navigation ba…

### LINKED ISSUE #194: Enhance Header: Improve Website Design and Navigation for Better User Experience
I would like to Enhance it's navbar for better UX, kindly assign me this issue.

### PR DESCRIPTION
**Pull request by testdib**
…r to the site it will make website look more attractive and make easy to use by the users as it will help in the direct navigation of the different section of the website and improved webdesign.

## PR Description 📜
Look upon the website and discover that navigation bar is missing so added the navigation bar.
Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #194  <your_issue_number>

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @testdib ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Arun9739** [comment]
@testdib Plz add the screenshot of the section where you have changed, also resolve the branch conflicts.

**Comment by testdib** [comment]
Screenshot 2023-05-31 122558

**Comment by kunjgit** [comment]
we are not accepting that navigation bar changes for now and make sure if you are working on some issue you make changes to that only !!
for now we are closing your PR

**Comment by kunjgit** [comment]
Thank you  @testdib , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
