### PR TITLE
New Game : Hit Or Miss 🏏

### LINKED ISSUE #3732: [New game]: Hit or Miss Cricket  🏏
### 🎮 Game Request

"Hit or Miss Cricket 🏏" is an interactive web game where players test their luck by predicting the outcome of each cricket ball—Six, Four, Single, Double, or Triple. Points are awarded for correct guesses, and the game continues until an incorrect guess is made. It's a simple yet engaging way to enjoy cricket and see how lucky you are with your predictions.

### Point down the features

 > Five buttons representing possible outcomes (Six, Four, Single, Double, Triple).
 > Display area for showing the result of the guess.
 > Scoreboard to keep track of the player's points.
 > Restart button to reset the game and start over.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by namandude**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #3732
 Hit or Miss 🏏 is an interactive web game where players test their luck by predicting cricket ball outcomes—Six, Four, Single, Double, or Triple. Points are awarded for correct guesses, and the game continues until an incorrect guess is made.

Features:

Interactive Buttons: Five options to guess the ball's outcome.
Immediate Feedback: Displays whether the guess was correct and shows the actual result.
Score Tracking: Updates and displays the player's points in real-time.
Restart Option: Allows players to reset the game after an incorrect guess.
Visual Effects: A glowing screen effect for correct guesses, enhancing excitement.
Objective:
Accumulate as many points as possible by correctly guessing the outcomes of consecutive balls. Enjoy the thrill of cricket with a fun and simple prediction challenge.
 

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for website preview in assets/images 
- [X] I have added entries for my game in main README.md
- [X] I have added README.md in my folder 
- [X] I have specified the respective issue number for which I have requested the new game.

WhatsApp Image 2024-05-31 at 00 15 28_3803599e

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @namandude ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @namandude,
You need to make the following changes:
  - Please create a new folder inside the "Games" folder.
  - Please add a README.md file inside the newly created folder.
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by namandude** [comment]
@kunjgit  Please review it asap
Thank You!1

**Comment by namandude** [comment]
Hey please check i have made the changes

**Comment by namandude** [comment]
Please its been 2 weeks please do check it asap

**Comment by namandude** [comment]
@kunjgit Please check it please

**Comment by namandude** [comment]
@kunjgit Please review it

**Comment by namandude** [comment]
Hey Kunjgit/Gamezone Please review my pr

**Comment by ishita-43** [comment]
Resolve merge conflicts arising in README.md

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by kunjgit** [comment]
Thank you  @namandude , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
