### PR TITLE
Minesweeper

### LINKED ISSUE #100: [New game]: Minesweeper
### 🎮 Game Request

Game logic and basic description
The board is divided into cells, with mines randomly distributed. To win, you need to open all the cells. The number on a cell shows the number of mines adjacent to it. Using this information, you can determine cells that are safe, and cells that contain mines. Cells suspected of being mines can be marked with a flag using the right mouse button.

### Point down the features

Game points 
It will show the remaining mines you need to escape the mines

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Naishadha-satya**
## PR Description 📜
added a new game Minesweeper
Fixes #100 

<hr>
 
## Mark the task you have completed ✅

- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [ ✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅] I have added screenshot for website preview in assets/images 
- [✅ ] I have added entries for my game in main README.md
- [ ✅] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ✅] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗
Minesweeper

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Naishadha-satya ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by raju-kumar21 — APPROVED** [review]

**Comment by kunjgit** [comment]
Hey @Naishadha-satya 👋!
 
  @kunjgit here, 
 We have this annoucement to make 📢!! 
 We have updated our README 🚀 
 Make sure you follow proper guideline to raise your next issues !! 
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG) if you haven't 😇 
  Thank you 💗!

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hey !!
Look at the documentation and add your game thumbnail in assets folder of repo !!
also make your entry in main readme file games section with game number *

**Comment by Naishadha-satya** [comment]
Hi i've completed adding Minesweeper game in README file and thumbnail in assets folder

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Naishadha-satya , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
