### PR TITLE
The labyrinth of death

### LINKED ISSUE #2304: [New game]: The labyrinth of death
### 🎮 Game Request

Game logic and basic description
You are Isaac Newton and you are searching for it in the underworld. Defeat Hades and claim it!

Use WASD to move, Space for the sword (if you collected it) and Shift to switch to boomerang boomerang (once you collect it) and WASD to control it.

Screenshort:
image

### Point down the features

Demo Vedio:

https://github.com/kunjgit/GameZone/assets/98798977/11278da1-3488-4d63-90a2-0da1853d1b3a

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Durgesh4993**
## PR Description 📜

You are Isaac Newton and you are searching for it in the underworld. Defeat Hades and claim it!

Use WASD to move, Space for the sword (if you collected it) and Shift to switch to boomerang boomerang (once you collect it) and WASD to control it.

Fixes #2304
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
image

Demo Vedio:

https://github.com/kunjgit/GameZone/assets/98798977/11278da1-3488-4d63-90a2-0da1853d1b3a

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Durgesh4993 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Durgesh4993** [comment]
@kunjgit Please review and merge it

**Comment by Durgesh4993** [comment]
@kunjgit Please check it out i have resolved the conflict

**Review by kunjgit — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Durgesh4993 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
