### PR TITLE
Added Rocket_Shooter Game

### LINKED ISSUE #4812: [New game]:  I want to add a Rocket Shooter game.
####  _Game logic and basic description_

- There will be some enemy rockets who will try to attack.
- Our mission will to shoot those enemy rockets to win the game. 

####  _Game points_

- Enemy rockets will try to attack on our rocket.
- Our mission is to shoot enemy rockets to win the game.
- I am a GSSOC'24 contributer.
- Please assign this issue to me under gssoc labels.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by vishanurag**
## PR Description 📜

I have added my Rocket_Shooter game that I have developed using HTML, CSS, Bootstrap & JavaScript.
Fixes #4812 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Screenshot 2024-07-11 184121

### _Please review & add GSSOC'24 labels in this pull-request._

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @vishanurag ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by vishanurag** [comment]
OK @kunjgit . Thank You 🙏

**Comment by vishanurag** [comment]
@ishita-43 Mam please review my pull-request and please merge it under GSSoC'24 labels.

**Comment by kunjgit** [comment]
Thank you  @vishanurag , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by vishanurag** [comment]
@kunjgit , @ishita-43 please review and merge my pull-request under GSSoC'24.

**Comment by vishanurag** [comment]
Now, i have resolved merge conflicts
@kunjgit , @ishita-43 Please review & merge my pr under GSSoC'24.

**Comment by vishanurag** [comment]
@ishita-43 please review my pull-request and kindly merge under GSSoC'24

**Review by ishita-43 — APPROVED** [review]
Good to go

**Comment by vishanurag** [comment]
@ishita-43 I have resolved merge conflicts. Can you please check and let me know is everything is fine with my PR 🙏.

**Comment by kunjgit** [comment]
Thank you  @vishanurag , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
