### PR TITLE
Dinoffline

### LINKED ISSUE #2441: [New game]: Dinoffline
### 🎮 Game Request

Game logic and basic description
This is a 3D remake of the famous Chrome Dino Game. Run as far as possible or race with one of your friends, but be careful not to bumb into any obsticles!

The game inculdes:
-Day-Night Cycles
-Co-op Multiplayer

### Point down the features

ScreenSort:
image

Demo Vedio:

https://github.com/kunjgit/GameZone/assets/98798977/5b1e0ff0-9509-4382-a348-599a29015162

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Durgesh4993**
## PR Description 📜
This is a 3D remake of the famous Chrome Dino Game. Run as far as possible or race with one of your friends, but be careful not to bumb into any obsticles!

Fixes #2441
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

Demo Vedio:

https://github.com/kunjgit/GameZone/assets/98798977/5b1e0ff0-9509-4382-a348-599a29015162

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Durgesh4993 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Durgesh4993** [comment]
@kunjgit Please review and merge it

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Make a new file for Script & CSS part don't mix it

**Review by kunjgit — APPROVED** [review]

**Comment by Durgesh4993** [comment]
@gurjeetsinghvirdee As per your instruction i have seprated style & Script file from index file. if any other change you want please suggest

**Comment by Durgesh4993** [comment]
@kunjgit @gurjeetsinghvirdee  Please merge it if everything is fine

**Comment by Durgesh4993** [comment]
@kunjgit Now check, i have resolved the conflict

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by kunjgit** [comment]
Thank you  @Durgesh4993 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
