### PR TITLE
[New game]: Want to Add New Game Five Nights At Freddy #4784

### LINKED ISSUE #4784: [New game]: Want to Add New Game Five Nights At Freddy
### 🎮 Game Request

Game logic and basic description
In this Game We are Locked in One room and There are 5 Killers which can move freely around house and are looking for us we spy on them using cameras and when we look any killer by camera he cant move . Our Aim is to Survive

### Point down the features

Game points
To Survive 

image

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by nishant0708**
## PR Description 📜

Added Five Nights At Freddy
Fixes #4784 

<hr>
 
## Mark the task you have completed ✅

- [x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [x ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ x] I have added screenshot for website preview in assets/images 
- [x ] I have added entries for my game in main README.md
- [x ] I have added README.md in my folder 
- [x ] I have added working video of the game in README.md (optional)
- [ x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

Five_Nights_at_Freddys

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @nishant0708 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by nishant0708** [comment]
hey @kunjgit @ishita-43 please review this pr

**Comment by nishant0708** [comment]
Hey @ishita-43 @kunjgit please review this pr

**Comment by ishita-43** [comment]
Hi there your pr seems to contain large amount of files i will not be able to review them please make sure your pr contains only your game folder and related asset and readme files Please update your pr

**Comment by nishant0708** [comment]
hey @ishita-43  it only include game files and updated readme file and updated image assets actually it is using engines thats why it seems big but i thinks its not.

**Review by ishita-43 — APPROVED** [review]
Astonishing work!! 🌟

**Comment by kunjgit** [comment]
Thank you  @nishant0708 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
