### PR TITLE
Added a button.

### LINKED ISSUE #3137: [Enhancement]: Vault master game need a proper instruction of how to play. and a better background.
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement: I think we can improve this game by adding some instructions of how to play and adding a appealing background. please assign this task to me, I will make this game exceptional.

### Describe the solution you'd like

Solution steps

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Nehayp21242929**
I have added a button for showing how to play-instruction.

## PR Description 📜

Added a button for showing how to play-instruction using swal function from sweetalert.

https://github.com/kunjgit/GameZone/assets/167680713/e880bbbc-00b3-45a9-b3aa-d1c93d8608af

Fixes #3137

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @Nehayp21242929 ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by Nehayp21242929** [comment]
I have added a button in the Wault master game.
And please label a level for this issue.
Thank you for giving a chance for the contribution.^^

**Review by ishita-43 — APPROVED** [review]
Good to go!!

**Comment by kunjgit** [comment]
Thank you  @Nehayp21242929 , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
