### PR TITLE
added new game reversi ai

### LINKED ISSUE #2319: [New game]: Add AI reversi
### 🎮 Game Request

Game logic and basic description
The game starts with an 8x8 board with two initial black and two initial white pieces placed in the center.
Players take turns placing their colored pieces on the board. A move is valid if it results in the flipping of at least one opponent's piece in a straight line (horizontally, vertically, or diagonally).
some of the features are :
-to flip the token
-cascading effects
-the corners and edges of the board have special strategic significance in Othello

### Point down the features

Game points
The game is a single-player experience in which an AI assumes the role of your opponent.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by RitiChandak**
## PR Description 📜

The main goal in the game of Othello is to dominate the board by having the highest number of your colored disks on it when the game reaches its conclusion. The game ends when either no more legal moves can be made or when the entire board becomes filled with disks. In the end, the player who possesses the majority of disks on the board is proclaimed the winner. also named as reversi

THIS GAME IS PLAYED AGAINST AI
Fixes #2319 

<hr>
 
## Mark the task you have completed ✅

- [ ✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [  ✅ ] I have performed a self-review of my own code or work.
- [ ✅ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✅ ] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅] I have added screenshot for website preview in assets/images 
- [✅ ] I have added entries for my game in main README.md
- [✅ ] I have added README.md in my folder 
- [✅ ] I have added working video of the game in README.md (optional)
- [✅ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @RitiChandak ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Review by kunjgit — APPROVED** [review]

**Comment by RitiChandak** [comment]
I sincerely apologize for forgetting to make the necessary changes

**Comment by daccdacc** [comment]
The game already exists on GameZone!
And we don't accept duplicate games, you can do enhancement in the already existing game.

**Comment by kunjgit** [comment]
Thank you  @RitiChandak , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by RitiChandak** [comment]
@daccdacc  so i have to add this code to the existing game ?

**Pull request closed without merging**
