### PR TITLE
[NEW GAME]: Hit Your Friend

### PR DESCRIPTION
**Pull request by 18Venus**
## PR Description 📜

I have added a new game "Hit Your Friend". This is a two-player game where both players try to hit each other with a ball. Both get to play alternatively. The player who hits first wins.

You may reload if you wish to the change building heights.

<hr>
 
## Mark the task you have completed ✅

- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [ ✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅] I have added screenshot for website preview in assets/images 
- [✅ ] I have added entries for my game in main README.md
- [✅ ] I have added README.md in my folder 

<hr>

## Add your screenshots(Optional) 📸
Opening UI:
Hit-Your-Friend

If a player wins: 
Hit-Your-Friend-winner

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @18Venus ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by kunjgit** [comment]
Hey @18Venus,
Please make sure to link the relevant issue using the appropriate syntax, such as "#issueNumber" 👀. 
 Follow the proper guideline and make a new PR again 😀. 
 Happy Hacking 💗

**Comment by kunjgit** [comment]
Thank you  @18Venus , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by 18Venus** [comment]
Hey @kunjgit, can you please let me know how to add the issue number? It's a new game and I have not addressed any issue. I am sorry for the confusion but can you please let me know do I have to create an issue like adding a new game and then create a pull request out of it?

Thank you!

**Pull request closed without merging**
