### PR TITLE
Adding Bomb Throw Game

### LINKED ISSUE #3564: [New game]:  Bomb Throw Game
### 🎮 Game Request

Game logic and basic description:

- You have 10 Second to Align the distance and the angle and it will automatically throw the bomb.
- It was a single player game

### Point down the features

Game points:

- You have 10 Second to Align the distance and the angle and it will automatically throw the bomb.

- It was a single player game

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by codewithganeshhh**
## PR Description 📜

Fixes #3564 

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅] I have added screenshot for website preview in assets/images 
- [ ✅] I have added entries for my game in main README.md
- [ ✅] I have added README.md in my folder 
- [✅ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Bomb Throw Game

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by codewithganeshhh** [comment]
Hey @kunjgit  I resolve the problem . Please check and add ASAP.

**Comment by kunjgit** [comment]
@codewithganeshhh still not resovled !

**Comment by codewithganeshhh** [comment]
resolve Task @kunjgit

**Comment by kunjgit** [comment]
Thank you  @codewithganeshhh , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
