### PR TITLE
[GSSoC'23] Music Guess Game Completed 

### LINKED ISSUE #1509: [New game]: Music Guessing Game [GSSoC'23]
### 🎮 Game Request

Game logic and basic description

- This game can be played by more than 2 members.
- In this game, a song tune will play which is of around 10 seconds.
- After listening this tune, four options are visible having the name of songs.
- Out of four options, one option having the name of that song and pressed on that option.
- In this way, scoreboard will update.

### Point down the features

Game points

- If correct option is pressed, score will increase by 1
- Otherwise, decrease by 1
- And the one who reaches the score 10 will win the game

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## PR Description 📜

Title - Music Guess Game
Technology used - HTML, CSS and JS

Fixes #1509 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [x] I have added entries for my game in main README.md
- [x] I have added README.md in my folder 
- [x] I have added working video of the game in README.md (optional)
- [x] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸

https://github.com/kunjgit/GameZone/assets/114330097/cfb182b7-f129-4ac1-8a72-0c88573e61c7

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Avdhesh-Varshney,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by Avdhesh-Varshney** [comment]
@kunjgit  I have added all the changes please review my pull request and merge it into the main branch for a successful contribution under GSSoC'23

**Review by kunjgit — APPROVED** [review]

**Review by kunjgit — CHANGES_REQUESTED** [review]
Hello @Avdhesh-Varshney,
You need to make the following changes:
  - Please modify the main README.md file.
  - Please add an image to the assets/images directory.

Hoping that you will make those changes soon 🚀

**Comment by kunjgit** [comment]
Thank you  @Avdhesh-Varshney , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Comment by Avdhesh-Varshney** [comment]
@kunjgit please add the labels to this pull request. This pull request is not comes on the leaderboard.
Please add the labels as soon as possible.

**Comment by Avdhesh-Varshney** [comment]
@kunjgit please add labels. This pr is not comes on the leaderboard.

**Comment by Avdhesh-Varshney** [comment]
@kunjgit this pr have merged 2 weeks but still you have not addes labels on this pr. So, that's why this pr is not shown on the leaderboard.
I requested to add label on this pr to come on the leaderboard.

**Comment by Avdhesh-Varshney** [comment]
@kunjgit @gurjeetsinghvirdee please add labels on this pr

**Pull request merged**
