### PR TITLE
Addition of home icon to games

### LINKED ISSUE #1620: [Enhancement]: Addition of home icon to the games page
### Is your enhancement request related to a problem? Please describe.➕
There could be some functionalities which could be improved in the games .

###Functionalities like: 
As for now ,whenever we choose a game we are directed to that game .But we need to use the arrow on the top to direct back to the homepage of the website.
gameissue

### Describe the solution you'd like

Solution steps: Addition of home icon to the games  pages so that by hovering over the home icon we should be directed back to the home page .

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by KanchandeepK**
## PR Description 📜

Fixes #1620

###Changes: 
-As when we click on a game to go back to the homepage ,I have added the home icon .
-By hovering over the home icon we land back to homepage.
-Some games couldn't be loaded in my server so I was not able to make the change.
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for website preview in assets/images 
- [ ] I have added entries for my game in main README.md
- [ ] I have added README.md in my folder 
- [ ] I have added working video of the game in README.md (optional)
- [ ] I have specified the respective issue number for which I have requested the new game.

<hr>

## Add your screenshots(Optional) 📸
Without addition of home icon on games
gameissue

After resolving the issue
Screenshot 2023-06-30 152238
@kunjgit Please review my PR.

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @KanchandeepK ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by gurjeetsinghvirdee** [comment]
How can I check this my system lagging so much 😔@KanchandeepK

**Comment by KanchandeepK** [comment]
@gurjeetsinghvirdee I will try to figure it out .It was working fine in mine.

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee I will try to figure it out .It was working fine in mine.

Not working on my system i3 11th gen 😕

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM

**Comment by kunjgit** [comment]
Thank you  @KanchandeepK , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request merged**
