### PR TITLE
Update README.md

### LINKED ISSUE #2844: README UPDATE[Documentation Bug]:
### Describe the bug ✍️

THERE ARE A LOT OF GRAMMATICAL ERRORS IN THE README.

### Provide step by step information reproduce the bug 📄

SPELLINGS OF WORDS LIKE "CONSTRUCTIVE" ARE WRONG AS WELL AS THERE ARE A LOT OF GRAMMATICAL ERRORS IN THE FRAMING AND PUNCTUATION OF THE STATEMENTS.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

### PR DESCRIPTION
**Pull request by abhisar-yadav**
corrected all typing errors

## PR Description 📜

corrected all the grammatical errors

Fixes #2844

- [x] I follow [CONTRIBUTING GUIDELINE]
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE]
- [x] I have specified the respective issue number for which I have requested the new game.

### CODE REVIEW

**Comment by kunjgit** [comment]
Thank you @abhisar-yadav ,for creating the PR and contributing to our GameZone 💗 
 Review team will review the PR and will reach out to you soon! 😇 
 Make sure that you have marked all the tasks that you are done with ✅. 
 Thank you for your patience! 😀

**Comment by abhisar-yadav** [comment]
I have solved the issue kindly review my PR

**Comment by abhisar-yadav** [comment]
kindly review my PR

**Comment by abhisar-yadav** [comment]
kindly merge my pr
@

**Comment by kunjgit** [comment]
Thank you  @abhisar-yadav , for your valuable time and contribution in our GameZone 💗. 
 It’s our GameZone, so Let’s build this GameZone altogether !!🤝
  Hoping to see you soon with another PR again 😇 
 Wishing you all the best for your journey into Open Source🚀

**Pull request closed without merging**
